### ISSUE TITLE
How to make font size of mermaid larger?

### ISSUE THREAD

**Issue by huangwb8** [knsv/mermaid#1017]
Recently I use mermaid in markdown to create flowchart. However,I found that if the flowchart is big, the font size of mermaid flowchart is too small.Here is and example:

[a big flowchart example](https://picture.hwb0307.top/images/2019/10/20/7QvYVvZ7Jh1QFXlq.jpg)

So, my problem is : 
Are there any methods to make the text in the boxes larger? Global setting is more appreciate.
Thanks!

**Comment by Dunning-Kruger** [comment]
Hey, have you checked out the [styling docs](https://mermaidjs.github.io/#/flowchart?id=styling-and-classes)? You could apply a class to all your nodes (or not) and style them using CSS.

**Comment by huangwb8** [comment]
Thanks! Actually I had no idea about CSS, but I tried some code in your [styling docs](https://mermaidjs.github.io/#/flowchart?id=styling-and-classes)
```
graph TD
start[<font size=6>附一电子报销流程]-->a1[<font size=6>1.发票检验]
a1-->b1[<font size=6>发票税号正确]
b1--<font size=6>是-->c1[<font size=6>发票下方盖公司有效印章]
c1-->d1[<font size=6>发票背面填写项目]
d1-->e1[<font size=6>项目名称]
d1-->e2[<font size=6>项目负责人签名]
d1-->e3[<font size=6>报销人签名]
d1-->e4[<font size=6>审核人签名]
start-->a2[<font size=6>2.填写报销单]
a2-->b2[<font size=6>项目负责人审核通过]
b2-->c3[<font size=6>打印报销单]
start-->a3[<font size=6>3.获取入库单]
a3-->a3b1[<font size=6>锐竞平台下单]
a3b1-->a3c1[<font size=6>...]
a3c1-->a3d1[<font size=6>在结算页面打印入库单]
b1--<font size=6>否-->c2[<font size=6>发票退回发票源更正]
c2-->a1
classDef className fill:#f9f,stroke:#333,stroke-width:4px
class start,a1,a2,a3 className;
```
I found `classDef` work well, but I still did not find out the font size method in `classDef`. Instead, I use `<font size=n>` in every node to solve the problem~

**Comment by Dunning-Kruger** [comment]
Don't forget to mark the issue as closed if it has been resolved. Thank you!
