### ISSUE TITLE
Error in "Basic Syntax" wiki page

### ISSUE THREAD

**Issue by vijay40** [knsv/mermaid#113]
In Basic Syntax Wiki page, last section specifying that semicolons are optional, the declaration of graph is rendered as Graph instead of graph syntax. There should be graph syntax of the rendered graph to allow others to understand how white spaces can be included between vertices and semicolons are optional.

The last lines below which graph syntax should be shown are 
**"Below is the new declaration of the graph which is also valid along with the old declaration of the graph as described in the graph example on the home wiki page."**
I think that below this there should be graph syntax followed by the rendered graph itself.

**Comment by knsv** [comment]
Thanks! I will look at that unless you want to look at it yourself. The markdown file is in the gh-pages branch.

**Comment by vijay40** [comment]
I will fix that and submit the pull request.
