### ISSUE TITLE
Subgraph syntax bug?

### ISSUE THREAD

**Issue by caryfitzhugh** [knsv/mermaid#120]
I'm trying to incorporate mermaid graphs into a blog posting.

I can do simple (non-subgraph) graphs just fine.

I try to do a subgraph and the parser gets confused
![hle6j06](https://cloud.githubusercontent.com/assets/445848/6176603/328e8bd8-b2ce-11e4-80ff-df8d33224624.jpg)

I can *see* it working on this page: http://knsv.github.io/mermaid/flowchart.html#subgraphs

And even copying the code for the subgraph from that page's view-source into my page - fails.

http://hivewing.github.io/2015/02/12/Testing-Mermaid.html

I have checked, and the example page's script src is the same as the one in my blog.

What else substantive could be different?  

Same JS sources (at least the mermaid source).  Same graph definition... ?

Any help is appreciated!

**Comment by sujeetpillai** [comment]
I'm having the same issue. I'm assuming you solved it. How did you manage it?

**Comment by knsv** [comment]
What version are you on?

The subgraphs was introduced after the initial release.

That might your issue. I hope this helps.

/Knut  

--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by TobyAbel** [comment]
I get a 404 from your hivewing page, but I've experienced this problem just not when ending a subgraph with a semicolon. Removing the semicolon causes it to render perfectly.

**Comment by TobyAbel** [comment]
(apart from having the horrible black background as described in #121 rather than the nice yellow one here[http://knsv.github.io/mermaid/flowchart.html#subgraphs])

**Comment by sujeetpillai** [comment]
it was a version issue. Upgrading fixed it.
