### ISSUE TITLE
subgraph background is black in rendered flowchart PNG via CLI

### ISSUE THREAD

**Issue by trumbitta** [knsv/mermaid#121]
subgraph background is black in rendered flowchart PNG via CLI, thus its title can't be seen and arrows almost get lost (dark grey on black)

Is there a way to style the subgraph?

**Comment by knsv** [comment]
Yes there is an option, (--css), to add a css file to the graph rendering. The class that styles the subgraph has is .cluser. An example below:

```css
.cluster { fill:#f5f5f5;}
```

There should probably be a better default value then black ... :)

**Comment by trumbitta** [comment]
Nice, thank you!

I was using 0.3.3, and now after having updated to 0.3.5 the option is there :D

**Comment by knsv** [comment]
You are welcome! Closing this one.Let me know if you run into anything else.

**Comment by mistic100** [comment]
Black should be definitely changed by something else. Currently it looks like a bug.

Is there a list of the classes that can be used ?

**Comment by knsv** [comment]
You can look at the css file sin the list folder. Maybe the cli should use mermaid.css per default if no css is set.
/Knut
--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
