### ISSUE TITLE
Add a css file, mermaid.css, with default styling

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#122]
For easier styling and integration on a website a default css file should be included in the distribution.

**Comment by velvia** [comment]
+1.

perhaps related to this:  if you use subgroups with the command-line CLI tool, the .png generated will show a black box for each subgroup with the text being invisible.  I believe this must be related to the lack of a default mermaid.css (or do you want a separate issue filed?)
Alternatively a way to specify a .css file to the CLI tool would be great.

**Comment by knsv** [comment]
@fardog do you think that the cli tool could use the css file dist/mermaid.css as stylesheet when no other stylesheet has been set?

**Comment by knsv** [comment]
Closing this issue as of release 0.4.0. Changes to the cli tool should in new issue
