### ISSUE TITLE
Add syntax for double headed arrows

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#123]
This can make diagrams less cluttered.

The obvious syntax: <--> wont work is it will be interpreted as an odd tag by the browser.

Maybe:

```
*-->
```

Am open for suggestions and better ideas.

**Comment by davidmarkclements** [comment]
Switch the arrows around?
```
a >--< b
```
Although that might still cause problems, not sure would need to be explored and cross browser tested. 

Bit of a leap, but the duality of the plus-minus could be considered "two way", 

```
a -±> b
```
That's easy on a mac keyboard (top left under esc), Win and Linux users would need to use key combos by default

The third option is to simply render co-dependent entities with a single two way arrow,

```
a --> b
b --> a
```

As far as I can see the meaning is the same, but the visual is improved. 
You could always add an option to render arrows separately in the event of
an unforeseen use case.

**Comment by agladysh** [comment]
`a ->> b`?

Anyway, I'd like to see this feature too

**Comment by knsv** [comment]
We should support this. I would happily add contributions in this area.
The ->> syntax is a little to close a regular arrow I think.

The >--< option is intuitive in one way but odd in another way. My favorite, but strong opionions are appreviated.

The third option is the obvious one and if nothing else, this has to work. Regardless of any shorter syntax agreed upon:
```
a --> b
b --> a
```

**Comment by agladysh** [comment]
How should one force two separate arrows (i.e. the current behavior) when using two entries? This is sometimes needed for readability.

**Comment by CyborgMaster** [comment]
I like either `>--<` or `*-->`

**Comment by yieme** [comment]
I like `*-->` or maybe even `--*` for both ways

**Comment by zegal-cn** [comment]
*-*

**Comment by zegal-cn** [comment]
`*-*`

**Comment by AXGKl** [comment]
When at this one I would highly appreciate to be able to just reverse the direction of single headed arrow as well. 

Rationale: In a TD diag the arrangement on the screen heavily depends on entities left or right. And so I'm often in the conflict of having either a good arrangement or the right arrow direction. 

Should I open a new one for this? Since I think it can be done within the work for this one...

**Comment by yxliang01** [comment]
Would be appreciated if this can be implemented soon since it has been 3 years.

**Comment by KoalaBear84** [comment]
I just wanted a line with on both sides an arrow, looks like it is not possible

**Comment by snowyu** [comment]
Use the unicode Char(LONG LEFT RIGHT ARROW):  “⟷”  to be more intuitive.

**Comment by CyborgMaster** [comment]
@snowyu, the main argument against a unicode character is Mermaid's inspiration by Markdown.  One of the main advantages is the ability for developers to easily type these files with a standard text editor.  That becomes much more difficult if the characters used are not found on a standard keyboard.   

I still advocate for a syntax using normal ASCII characters.  Possibly `*-->`.

**Comment by snowyu** [comment]
I have been using markdown too.  You can `copy-paste` in the graphic env easily.

Even in the terminal env, for instance, in the Vim text-editor you could enter insert mode and press `Ctrl + V` + `U` and then the code-point number as a 4-digit hexadecimal number (pad with zeros if necessary). So you would type `Ctrl + V` + `U` `2` `7` `f` `7`. 

I think this is not a conflict with the using ASCII characters. It could be supported both way.
But It seems to find a proper ASCII characters hardly. So the unicode way could be supported first.

**Comment by FDiskas** [comment]
Simple `<-->`

**Comment by davidmarkclements** [comment]
Read the very first comment.

**Comment by knsv** [comment]
This one is implemented with the syntax <-->

**Comment by KoalaBear84** [comment]
But it does not work? Any guidance? (Or is the live editor not updated)
https://mermaidjs.github.io/mermaid-live-editor/

**Comment by phuongnd08** [comment]
@knsv As of 8.2.6, double headed arrow is still not rendered. It is accepted by the processor though.

This
```
      graph TD
      A[Christmas] <-->|Get money| B(Go shopping)
      B --> C{Let me thinksssssx<br/>sssssssssssssssssssuuu<br />tttsssssssssssssssssssssss}
      C -->|One| D[Laptop]
      C -->|Two| E[iPhone]
      C -->|Three| F[Car]
```

get rendered to this
![image](https://user-images.githubusercontent.com/184037/64087799-ca8c5c80-cd68-11e9-9b37-10a339a543a2.png)

**Comment by yieme** [comment]
@knsv thank you for the double arrow support. This is awesome! I've been able to confirm what @phuongnd08 is seeing with the mermaid live editor.

It also looks like the live editor is using version, 8.2.6, as: `https://mermaidjs.github.io/mermaid-live-editor/src.95fd6b94.js` contains: `module.exports={name:"mermaid-live-editor",version:"0.2.0",` ... `,mermaid:"^8.2.6",
`...

**Comment by heavysixer** [comment]
I just pulled master and built it from source and was unable to get the double arrows to render correctly. I see that there are specs (which pass) but when trying it in an editor the double arrow is ignored though no error occurs. Just and FYI.

**Comment by tamvm** [comment]
@phuongnd08 you can "hack" double headed arrows with classDiagram as this example: https://mermaid-js.github.io/mermaid/#/?id=class-diagram-experimental

**Comment by qchenevier** [comment]
@heavysixer @yieme @phuongnd08 I could get the double arrow using the `flowchart` type diagram instead of the default `graph` one.

Just begin your graph definition with `flowchart` instead of `graph`.

Example [here in the live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IFRCXG4gICAgYzE8LS0-YTJcbiAgICBzdWJncmFwaCBvbmVcbiAgICBhMTwtLT5hMlxuICAgIGVuZFxuICAgIHN1YmdyYXBoIHR3b1xuICAgIGIxLS0-YjJcbiAgICBlbmRcbiAgICBzdWJncmFwaCB0aHJlZVxuICAgIGMxLS0-YzJcbiAgICBlbmRcbiAgICBvbmUgLS0-IHR3b1xuICAgIHRocmVlIC0tPiB0d29cbiAgICB0d28gLS0-IGMyIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

![](https://mermaid.ink/svg/eyJjb2RlIjoiZmxvd2NoYXJ0IFRCXG4gICAgYzE8LS0-YTJcbiAgICBzdWJncmFwaCBvbmVcbiAgICBhMTwtLT5hMlxuICAgIGVuZFxuICAgIHN1YmdyYXBoIHR3b1xuICAgIGIxLS0-YjJcbiAgICBlbmRcbiAgICBzdWJncmFwaCB0aHJlZVxuICAgIGMxLS0-YzJcbiAgICBlbmRcbiAgICBvbmUgLS0-IHR3b1xuICAgIHRocmVlIC0tPiB0d29cbiAgICB0d28gLS0-IGMyIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**Comment by davesatt** [comment]
I see that double arrows were added to flowcharts, but sequence diagrams are the place I most want double arrows. For things such as bidirectional media in SIP Call Flows.
![sip_calling_fig1](https://user-images.githubusercontent.com/84872079/119714058-665cd680-be30-11eb-9211-ef754021af2f.gif)

**Comment by nagashi** [comment]
How does one have an arrow point to the left if it's at all possible?

**Comment by vallamost** [comment]
Why is this closed? It still doesn't work on here - https://mermaid-js.github.io

**Comment by Justin-Garey** [comment]
Can you point to where in the code the syntax for sequence diagrams is parsed? I think syntax with A->>B could be extended to A->*B for arrow in "all" (both) directions.

**Comment by tulisachin** [comment]
Still no Solution to the both sided arrow?

**Comment by Jinwook94** [comment]
Please add both side arrows in sequence diagrams. Thanks.

**Comment by Justin-Garey** [comment]
For anyone looking at this in the future, the bidirectional arrows were added today in https://github.com/mermaid-js/mermaid/pull/5209.
