### ISSUE TITLE
Gantt - suitable xAxis for longer project

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#125]
>In the example I posted above, I have from 2015-01-22 to 2015-07-15. I would like the axis labels to have ticks every week and the label to be the Monday of each week. 03/09, 03/16, 03/23, etc.

>I realize that would be ~25 week ticks in this case which seems like a lot but the only good way I can tell to show that "sprint 3 starts on the week of 03/23" for example.

**Comment by knsv** [comment]
@nickwynja I have boosted the range for which week ticks are applied. This is in the master branch now but not release. Try it out and see how it works.

**Comment by nickwynja** [comment]
This is looking better for me. Thanks!

I figured out the custom formatting you have in `axisFormatter` and used the following to get the axis labels the format that we work in:

```
 // Monday a week
    ["%-m/%-d", function (d) {
        return d.getDay() == 1;
    }],
```
That outputs this and makes it easy to say "Sprint 3 starts on 5/11" as my managers typically ask:

![screen shot 2015-03-05 at 1 19 13 pm](https://cloud.githubusercontent.com/assets/1012017/6511351/41a566b0-c33a-11e4-8317-4b40097d4219.png)

**Comment by knsv** [comment]
Good! Will keep it as it is then.

**Comment by knsv** [comment]
I am closing issues and see this one as closed. Let me know if you feel differently!
