### ISSUE TITLE
Possibility to set the width of the generated flowchart

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#129]
By adding a flowchartConfiguration with the with it should b possible to set the with to 100% or a specific with like 970px

If the configuration is omitted the actual width should be used.

**Comment by knsv** [comment]
A fix for this has been released in version 0.5.0

**Comment by trienism** [comment]
Has anyone verified this issue has been resolved? I'm struggling to get the flow diagram to resize based on width argument and I could certainly be doing something wrong.  However, I simply modified 

_/test/web.html_

```
    <script>
        var config = {
            mermaid:{
                startOnLoad:true,
                htmlLabels:true,
                callback:function(id){
                    console.log(id,' rendered');
                },
                flowChart:{width:'50%'}
            }
        };
        mermaid.initialize(config);
    </script>
```
And did not seem to notice any of the charts resize.

**Comment by pnewell** [comment]
I am having trouble with this as well. If I want to set the max width for the nodes, where and how do I do it exactly?

**Comment by knsv** [comment]
Sorry for the late reply for this. Summer is great! :-)

@pnewell, this issue refers to the width of the whole chart and not the nodes.

@trienism, I see the issue. Currently it will decrease the width if it is to wide. But will ignore your setting. If you surround you mermaid div with another div with width:50% set in the css you should get the effect you desire.

Will fix this though for next release.
