### ISSUE TITLE
Using the library for iOS development

### ISSUE THREAD

**Issue by Ali1** [knsv/mermaid#130]
Hi

Has anyone successfully been able to use this library on an iOS app? Any ideas on how to go about doing this?

Thanks

**Comment by knsv** [comment]
Hello,

Maybe if you make the app as an html5 app. I don’t see any obvious reasons why would not work. No way to know for sure without trying though :)  

--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Ali1** [comment]
Thanks. No, I'm wanting an actual app. I'm thinking the best way would be to get a server to generate the an svg and send it back. But could I keep this open for a bit longer just to see if anyone else has any ideas :)

**Comment by knsv** [comment]
@Ali1 did you find a way in the end? I am closing this issue now. Let me know if you want me top re-open it.
