### ISSUE TITLE
tags ending in a "v" don't render

### ISSUE THREAD

**Issue by thomaxxl** [knsv/mermaid#132]
Hi,
can you tell me how I can use node descriptions ending in a "v" please?
graph TD;
    A[blav]-->B;
    A-->C;
    B-->D;
    C-->D;

doesn't work

**Comment by knsv** [comment]
Hi Thomas!

I recognize this issue and luckily it has been fixed. So to answer your question I would say that an upgrade to version 0.4.0 is the way to go. 

I would also recommend looking at the readability changes done to the syntax:
http://knsv.github.io/mermaid/flowchart.html

```
graph TD
A[blav] --> B
A --> C
B -- text on link --> D
C --> D
```

Good luck!

**Comment by knsv** [comment]
I am closing this one. Let me know if it still is an issue.
