### ISSUE TITLE
Some examples not displayed on Firefox 36.0.1

### ISSUE THREAD

**Issue by pembeci** [knsv/mermaid#138]
On Firefox 36.0, only the first or first few examples are rendered. Others return just the text definition. Chrome works fine, so it shouldn't be a network or setup problem on my part. Firefox console shows the following security error, may be it is related:

> "Registering new lang" flowchart.html:197:20
> SecurityError: The operation is insecure. mermaid.full.js:30994:0

Here is an screenshot:
![mermaid_flowchart_html](https://cloud.githubusercontent.com/assets/2614837/6631890/157378aa-c936-11e4-8777-d85af49253aa.png)

**Comment by knsv** [comment]
Thanks for pointing this out. I believe it is the same root cause as issue #128. Firefox can not copy a style and then stops the executions. This is resolved but not yet released but will be a part next release.

**Comment by knsv** [comment]
I think in this case it has to do with css files fetched from another origin that are accessible to mermaid.

**Comment by pembeci** [comment]
That may be it. Thanks for the fast response and this very useful library. Another question, if you don't mind. dagre-d3 says it will not be maintained any more. How will this effect mermaid?

**Comment by knsv** [comment]
Good question... we could move the d3 usage and svg rendering out of dagre-d3 into mermaid but keep using dagre. Less risk of browser impact in dagre. Pull requests are still beeing accepted though so the community can fix critical issues.
