### ISSUE TITLE
IE Support issue

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#142]
Online demo: http://mdp.tylingsoft.com/  Please scroll to the bottom and you will see the flowchart and sequence diagram.

Tested on Windows 8.1 64 bit, IE 11. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/733544/6765148/8c6268b6-d00e-11e4-8fd6-9d3935ee6114.png)

Yes I found this issue https://github.com/knsv/mermaid/issues/99 I think I might be able to fix the flowchart issue.

But there is also issue with the sequence diagram. You can see that the two vertical lines are too long.

**Comment by knsv** [comment]
Thanks, will take a look!

**Comment by tylerlong** [comment]
I confirm that flowchart issue could be solved by:

```javascript
var mermaid_config = {
  htmlLables: false
};
```

**Comment by tylerlong** [comment]
I have found the root cause to the sequence diagram vertical line too long issue. It is caused by this line:

https://github.com/knsv/mermaid/blob/a38a156d3b26c21b715dbe9a9f47e3ff27edb9e4/src/diagrams/sequenceDiagram/svgDraw.js#L78

 ```
.attr("y2", 2000)
```

2000 is a hard coded large value.

**Comment by tylerlong** [comment]
A workaround for the sequence diagram issue is:

```javascript
$('line[y2="2000"]').each(function(){
  $(this).attr('y2', $(this).closest('svg').attr('height'));
});
```

**Comment by knsv** [comment]
Thanks!. Did you manage to fix the styling for the flowcharts? If so I can add that to the default styling mermaid.css

**Comment by tylerlong** [comment]
No, I didn't change the style of flowcharts. I fixed it by:

```javascript
var mermaid_config = {
  htmlLabels: false
};
```

**Comment by knsv** [comment]
@tylerlong do you think I can close this one? I am going through the issues and compiling them to a roadmap.

**Comment by tylerlong** [comment]
Yes, you can close it.  But please don't ignore the following content:

I have found the root cause to the sequence diagram vertical line too long issue. It is caused by this line:

https://github.com/knsv/mermaid/blob/a38a156d3b26c21b715dbe9a9f47e3ff27edb9e4/src/diagrams/sequenceDiagram/svgDraw.js#L78

 ```
.attr("y2", 2000)
```

2000 is a hard coded large value. 

Since I've already found the root cause, it should be easy to fix.

**Comment by knsv** [comment]
OK, closing. The y2 200o is no longer there. It is initially set to to 200 but updated after rendering.

**Comment by madhu72** [comment]
Hi even added htmlLabels:false, I am not seeing labels in IE 11

**Comment by madhu72** [comment]
![image](https://cloud.githubusercontent.com/assets/10324127/11733222/f15effd6-9f70-11e5-9204-4995420ea438.png)
