### ISSUE TITLE
Add download SVG link to the live editor

### ISSUE THREAD

**Issue by felipesabino** [knsv/mermaid#144]
This makes it easier to use the generated SVG file in offline documents that can not rely on the permalink

**Comment by felipesabino** [comment]
In addition (or as a work-around), tools like [svg-crowbar](http://nytimes.github.io/svg-crowbar/) could be added to the live editor

**Comment by knsv** [comment]
Good idea! @naseer, what do you think? Anything you would be interested in looking at?

**Comment by naseer** [comment]
Sure - I can look at it - any suggestion on how to save the svg along with styling? I don't know much about svg :)

**Comment by knsv** [comment]
I think the styling is in place already. The graph generation collects it.
ons 25 mar 2015 kl. 19:26 skrev Naseer Ahmed <notifications@github.com>:

**Comment by knsv** [comment]
@naseer, any progress on this one? Let me know if I can help.

**Comment by naseer** [comment]
@knsv  - Unfortunately, I haven't been able to spend any time on this yet due to work commitments.
