### ISSUE TITLE
Add option to include the syntax source in the SVG metadata

### ISSUE THREAD

**Issue by felipesabino** [knsv/mermaid#145]
Using the xml source as a feature in the SVG format can be very useful to include metadata in the generated file. 

One awesome thing [js-sequence-diagrams](https://github.com/bramp/js-sequence-diagrams) does, is including a [`<source>` tag with a `CDATA`](https://github.com/bramp/js-sequence-diagrams/pull/17) value when you download the SVG file and make it possible/easier for future editions in the generated diagram by someone else besides the author.

**Comment by knsv** [comment]
Thanks!
A good idea!

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
