### ISSUE TITLE
File Extension

### ISSUE THREAD

**Issue by streamich** [knsv/mermaid#147]
Is there a file extension `mermaid` uses for its language?

Maybe `.mm` or `.mermaid`?

**Comment by knsv** [comment]
.mermaid has been used but it has not been officially stated. Do you think that is to long?

**Comment by streamich** [comment]
I personally think `.mermaid` is too long, but it is up to you to choose.

**Comment by knsv** [comment]
Ok!

I will then pick .mmd and will push for that as the "official" extension!

**Comment by m-aciek** [comment]
For what is worth `.mmd` conflicts with Mind Map plugin format.https://www.igormaznitsa.com/netbeans-mmd-plugin/

**Comment by jzabroski** [comment]
A quick analysis reveals nobody uses .mm, and people use either mmd or mermaid extension (I like mermaid personally):

https://github.com/search?q=sequenceDiagram+extension%3Amm+extension%3Ammd+extension%3Amermaid+extension%3AmermaidDiagram&type=Code&ref=advsearch&l=&l=

Also a useful search query to see examples of other people using these diagrams!

**Comment by huyz** [comment]
Besides conflicting with https://plugins.jetbrains.com/plugin/8045-idea-mind-map , the `.mmd` extension also conflicts with https://en.wikipedia.org/wiki/MultiMarkdown

**Comment by jzabroski** [comment]
> Besides conflicting with https://plugins.jetbrains.com/plugin/8045-idea-mind-map , the `.mmd` extension also conflicts with https://en.wikipedia.org/wiki/MultiMarkdown

That might be true, but it's also why real OSes like K Desktop Environment invented [Nepomuk and Strigi](https://userbase.kde.org/Nepomuk).  Ideally, GitHub would adopt this rather than a cheap extension search.  Just my 2 cents.  To this day, Windows 11 still sucks at _semantic_ file extension searches.

**Comment by Pierstoval** [comment]
Just stumbling upon this old issue, but just to add my 2cents:

Having a "long" extension name shouldn't be an issue. We're not at the "3-characters-long maximum length for extension" era, it's been a while now 😁

**Comment by ashishjain0512** [comment]
For now we have `.mmd` as the file extension. We can think about supporting a extending version in the future.
