### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by nikolay** [knsv/mermaid#15]
Is it possible to use custom SVG icons?

**Comment by knsv** [comment]
Will add support for font-awesome. Will close this issue in favor the similar issue #49. Generic support takes more time to add and hopefully font-awesome support will cover most use cases.

Let me know if you dont agree.

**Comment by mhnsn** [comment]
Booooo. If there's enough interest in this, I'll totally write up a PR for it over the summer. I'm swamped right now, but I would absolutely love to have custom icons included in.

**Comment by dijonkitchen** [comment]
Latest issue: https://github.com/mermaid-js/mermaid/issues/1723
