### ISSUE TITLE
New(er) features unavailable in downloadable js files?

### ISSUE THREAD

**Issue by sheriferson** [knsv/mermaid#151]
(apologies if this is solved or explained somewhere, I didn't find anything after searching for a while)

It seems some of the newer features/syntax (like `-.->` for dotted lines, and `-some text here-` for text in connections) are not implemented in the js files that can be downloaded from [this page](http://knsv.github.io/mermaid/usage.html). Whenever I try to use the dotted line syntax for example, none the diagrams in the page end up rendering at all.

Is there a way to obtain the .js files that have the latest features being showcased [here](http://knsv.github.io/mermaid/flowchart.html) for use in static sites?

I am trying to use mermaid in a jekyll site, and I downloaded the mermaid .js file that includes the dependancies.

Thanks.

**Comment by knsv** [comment]
Thanks for bringing this up. Too many places to change when doing a release...

You can download the latest release from :
https://cdn.rawgit.com/knsv/mermaid/0.4.0/dist/mermaid.full.js

I think you have the css files in that folder as well.

Good luck.  

--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by sheriferson** [comment]
Thanks a lot! That answers everything I needed.
(thanks a lot for this project too)
