### ISSUE TITLE
Finite State Machine Diagram

### ISSUE THREAD

**Issue by hscells** [knsv/mermaid#152]
It is possible to create a FSM in mermaid, it can be NFA or DFA, but it looks kinda ugly.

given this example:
```
graph LR
   A((A))--0/0-->C((C))
   A((A))--1/0-->B((B))

   B((B))--0/0-->C((C))
   B((B))--1/0-->A((A))

   C((C))--0/0-->C((C))
   C((C))--1/0-->DF((DF))

   DF((DF))--0/0-->E((E))
   DF((DF))--1/0-->A((A))

   E((E))--0/0-->C((C))
   E((E))--1/1-->DF((DF))
```

It produces this output:
![mealy-min md](https://cloud.githubusercontent.com/assets/6388537/7122321/afe67e9e-e1e8-11e4-8b2e-073d8a04d06a.png)

Does anyone think it is possible to make the lines curved and with no overlap (E->C & DF->A)? It would also be nice to support things like initial state and final states. Writing the markdown for it as well is kind of tedious as well, unless I'm just doing that wrong. Thanks!

**Comment by knsv** [comment]
Tricky one. It is dagre that sets the layout of the flowchart. Maybe this should be reported there (as well).

You could change the rendering by modifying the order of the nodes but that could make the diagram less readable which sort of defeats the purpose. Like in the example below:

```
graph LR
   DF((DF))--0/0-->E((E))
   E((E))--0/0-->C((C))
   A((A))--1/0-->B((B))
   E((E))--1/1-->DF((DF))
   A((A))--0/0-->C((C))
   C((C))--0/0-->C((C))
   DF((DF))--1/0-->A((A))
   B((B))--0/0-->C((C))
   B((B))--1/0-->A((A))
   C((C))--1/0-->DF((DF))
```

**Comment by knsv** [comment]
I am going through issues am closing this one. Let me know you disagree or need further support.

**Comment by hscells** [comment]
I may take a look at the code and see if I can make it look nice, if there is enough interest. The thing is, I'm no longer in need of this in the foreseeable future.
