### ISSUE TITLE
Broken subgraph using the CLI

### ISSUE THREAD

**Issue by lra** [knsv/mermaid#153]
I run `mermaid test.mermaid` with `test.mermaid` being:
```
graph LR
    subgraph A
        B
    end
    style A fill:#f9f
```
I get this `png`:
![test mermaid](https://cloud.githubusercontent.com/assets/122286/7209605/26adfdae-e518-11e4-8d1a-3b245f795573.png)

Am I using subgraphs in a bad way?

**Comment by knsv** [comment]
Sorry for the late response. You might want to use the css optinon in the cli tool and add one of the css files inlcuded in the dist folder. I am going through the issues and there will be an overhaul of the css handling which includes setting a valid default css for the CLI.

**Comment by knsv** [comment]
In release 0.5.1 a default style for this has been added. I see this issue as resolved and will close it.- Let me know if you feel different.
