### ISSUE TITLE
UML Class diagram

### ISSUE THREAD

**Issue by bastiao** [knsv/mermaid#154]
Is there any plan to support classes in your syntax? it will be great! 

Related with #149 
Eventually related with #117

**Comment by knsv** [comment]
I think that is a good idea and I would like to see it happen. It is in the roadmap. Can promise any dates though.

So yes it is planned and I would be happy for contributions in this area as well as collaborations. It is for instance easy to split tasks between parsing and rendering. Will close this issue in a bit as it is covered by  #149 from as task persictive (as you mention).

Thanks for your interest.

**Comment by knsv** [comment]
Take a look at issue #177 . Meanwhile I will close this issue.
