### ISSUE TITLE
Links in sequence diagrams

### ISSUE THREAD

**Issue by daledude** [knsv/mermaid#159]
I see click events for flows but can this also be done for sequences?

**Comment by knsv** [comment]
Not right now. I think it should be implemented though. Will tag accordingly

**Comment by DaviUchoa** [comment]
Is anyone looking at this topic?

**Comment by mrchypark** [comment]
Is anyone looking at this topic?

**Comment by yongchaoo** [comment]
Is anyone looking at this topic?
