### ISSUE TITLE
Drop label character restrictions

### ISSUE THREAD

**Issue by gibson042** [knsv/mermaid#162]
e7cb84b1d9049c1d3674fcb31e990d6af12e3360 and then d6766de7bec9b3335589d73aae4ea7e6130ab29e dramatically expanded the range of valid label characters, but many potentially-special characters are still excluded (e.g., `{`). This is a gap with respect to Graphviz DOT (cf. #5), and an annoying one for representing certain kinds of structured data. It would be convenient to follow the lead of [CSS](http://www.w3.org/TR/css3-selectors/#attribute-selectors), expanding the syntax allowed inside of `[…]` to allow quoted strings in addition to identifiers.

**Comment by knsv** [comment]
That would be nice! I can be tricky though. I think that the grammar probably needs some refactoring it has been updated for various issues and has become a bit unruly.

The syntax makes sense. Characters within quotes should be accepted as is.

**Comment by knsv** [comment]
Added support for quoted text without restrictions on characters. This is pushed in to dev-0.5-0 branch and will be included in the next release.

**Comment by knsv** [comment]
A fix for this has been released in version 0.5.0
