### ISSUE TITLE
Create syntax cheet sheet

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#165]
One page that sums up the syntax for the different diagram types.

Perhaps available as a pdf for print.

**Comment by weralabaj** [comment]
Hi!
Is it still needed, or it was done as online doco?
Let me know if I could help, I'm interested.

**Comment by knsv** [comment]
I think that would be great! 

Much appreciated!
		_____________________________

**Comment by tylerlong** [comment]
@weralabaj 

The documentation is here: https://github.com/mermaidjs/mermaid-gitbook

Feel free to contribute. (Add missing content, fix typos, create suggestions by creating GitHub issues...etc.)

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
