### ISSUE TITLE
it can not work where graph TD contains chinese character

### ISSUE THREAD

**Issue by xhrwp** [knsv/mermaid#166]

**Comment by knsv** [comment]
Thanks for your input!

In essence this is the same issue as #162. This will be resolved in release 0.5.0 when you can put any character between quotes like this "您好". I will close this as a duplicate.

**Comment by xhrwp** [comment]
thank you！

**Comment by xhrwp** [comment]
where can i download the version 0.5.0

**Comment by xhrwp** [comment]
i found !

**Comment by xhrwp** [comment]
i found the dev-0.5.0。can you tell me where is the version release 0.5.0
