### ISSUE TITLE
How to escape characters?

### ISSUE THREAD

**Issue by vstepanyuk** [knsv/mermaid#170]
A(test(vcc)) --> B;

**Comment by knsv** [comment]
Seems there still is an issue with this. The code below should work but does not.

```
A("test(vcc)") --> B;
```

**Comment by vstepanyuk** [comment]
Yes, I tried this - doesn't work

**Comment by knsv** [comment]
Will dedicate 0.5.1 to this

**Comment by vstepanyuk** [comment]
Thx

**Comment by knsv** [comment]
A fix has been committed to the master branch and will be included in 0.5.1.

**Comment by knsv** [comment]
Fixed with release 0.5.1

**Comment by knsv** [comment]
http://knsv.github.io/mermaid/live_editor/#/graph%20LR%0AA(%22test(vcc)%22)%20--%3E%20B;

**Comment by bostevensspinakr** [comment]
That link is broken. Could someone post a new mermaid.live link with escaping @, ~, ", (, and )?

**Comment by littlepoolshark** [comment]
The answer is here: https://mermaid.js.org/syntax/flowchart.html#special-characters-that-break-syntax
