### ISSUE TITLE
Execute code after initialize

### ISSUE THREAD

**Issue by zhum** [knsv/mermaid#176]
I need to add tooltips to nodes. I want to use 'tipsy' library (like this http://bl.ocks.org/ilyabo/1373263), but it is called before real svg nodes are created. How to call my code AFTER mermaid finished?

**Comment by knsv** [comment]
Good idea!

Perhaps a callback method as an optional parameter to mermaid.init could do the trick.

**Comment by zhum** [comment]
Cool! Works well!

**Comment by pihug12** [comment]
I can't get it to work with Mermaid 7.1.0 (https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js).

    <div class="mermaid">
        graph TB
            nat_a --- nat_b
            click nat_a pouet
    </div>
    <script src="mermaid.min.js"></script>
    <script>
        mermaid.initialize({
            startOnLoad:true,
            callback:function(id) {
                console.log("test");
                console.log(id,' rendered');
            },
            logLevel:1
        });
    </script>

Is there something wrong?

**Comment by ammarcoux** [comment]
I had the same problem and after looking at the source I go it to work like this:

```
mermaid.initialize({
    startOnLoad: true,
        htmlLabels: true,
        flowchart: {
            useMaxWidth: false,
            curve: 'basis'
        },
        mermaid: {
            callback:function(id) {
                $('.mermaid').css('opacity', '');
            }
        }
});
```

**Comment by Andromelus** [comment]
Is there any doc/news from this ?
None of the above work with mermaid 10 and I can't find anything about it in the docs.

**Comment by BigBlueHat** [comment]
@Andromelus I found some content in the changelog. Looks like you can do the following in >= 10:
```html
<script type="module" async>
      import mermaid from '${src}';
      mermaid.run({
        querySelector: '.mermaid',
        postRenderCallback: (id) => {
          console.log(id);
        }
      });
</script>
```

**Comment by fnick851** [comment]
@BigBlueHat This works. Thanks for sharing.
