### ISSUE TITLE
IE9 issue 

### ISSUE THREAD

**Issue by cooljig89** [knsv/mermaid#179]
Thanks for the awesome library. 
I am trying to make it work in IE9. one issue i face is, it always works when developer tool is on. 
After looking at issue found that, mermaid slim library is using for require statement for d3. 
It would be great if we can put conditional console.log to displayed only dev mode is on. 

Look for "Exception ... but ok" under mermaid slim lib.

Thanks

**Comment by knsv** [comment]
Thanks for the input. I'll add logger and will do all output through it. If no console.log function exists it will not try to use it.

**Comment by knsv** [comment]
Fix for this issue was released in mermaid 0.5.2. Will close this now, let me know if you issues still remain.
