### ISSUE TITLE
Atom editor package

### ISSUE THREAD

**Issue by y-takey** [knsv/mermaid#183]
Thanks for the awesome library! 
I made a package that able to preview on atom editor.

https://github.com/y-takey/atom-mermaid

May i register my package to package repository(https://atom.io/packages), and publish one?

 # I'm sorry in poor English.

**Comment by knsv** [comment]
That looks great!

I have no objections to you publishing the package.

Good luck!

**Comment by y-takey** [comment]
Thank you for readily agreed with me!

I published my package. ( https://atom.io/packages/atom-mermaid ) :)
