### ISSUE TITLE
Weird bug in live editor when using words with substring `end`

### ISSUE THREAD

**Issue by sbussard** [knsv/mermaid#184]
The live editor breaks when trying to process this

```
graph LR
A --> Calendar
```

![screen shot 2015-07-09 at 9 26 11 am](https://cloud.githubusercontent.com/assets/345018/8597697/8f56acc6-261c-11e5-8bd3-7be8f9d7ce8e.png)

**Comment by sbussard** [comment]
actually this breaks
```
graph LR  

A --> end
```

**Comment by knsv** [comment]
Thanks for bringing this up. It must be because **end** is also a keyword for subgraphs. I will take a look at it.

**Comment by knsv** [comment]
Not so easy to fix I'm afraid. You **can** have keywords in text though so an easy workaround would be:

```
graph LR
A --> B[Calendar]
```

I hope this suffices, will put this issue as won't fix as there is the simple workaround.
