### ISSUE TITLE
text of mermaid div displayed on page

### ISSUE THREAD

**Issue by barttt** [knsv/mermaid#186]
THanks for producing this library-
And for your previous help.
I found that my rendering issue was the lack of a stylesheet callout for mermaid.css.
My current issue is that the text of the mermaid div is displayed above the diagram that is rendered.
Is there a way to stop this?
Thanks

**Comment by knsv** [comment]
Maybe in your context it would make sense to only use the api functions. That would mean that you call a render function with a graph definition that you fetch from your page yourself. In return you get the graph definition.

Then you have the control of whats going on on the page. A small example below that takes a graph definition renders it and prints the generated svg to the console.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="bower_components/mermaid/dist/mermaidAPI.js"></script>

    <script>
        mermaidAPI.initialize({
            startOnLoad:true
        });
        $(function(){
            var graphDefinition = 'graph TB\na-->b';
            var cb = function(svgGraph){
                console.log(svgGraph);
            }
            mermaidAPI.render('id1',graphDefinition,cb);
        });
    </script>
</head>
    <body>
         
    </body>
</html>

```  

I hope this helps.  

--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by barttt** [comment]
THanks Knut-
An excellent idea as I need to ultimately use Ajax on this page anyway.

**Comment by knsv** [comment]
Info about the render function in the mermaidAPI. Unsure how clear this is described in the docs.
```
/**
 * Function that renders an svg with a graph from a chart definition.
 * @param id - the id of the element to be rendered
 * @param txt - the graph definition
 * @param cb - callback which is called after rendering is finished with the svg code as inparam.
 * @param container - selector to element in which a div with the graph temporarily will be inserted. In one is
 * provided a hidden div will be inserted in the body of the page instead. The element will be removed when rendering is 
 * completed.
 */
```

**Comment by knsv** [comment]
Will close this one now. Let me know if you still are have problems with this.
