### ISSUE TITLE
cli: no lines and arrowheads rendered / only dotted lines

### ISSUE THREAD

**Issue by nylki** [knsv/mermaid#187]
When rendering the sample flowchart:
```
graph TD;
A-->B;
A-->C;
B-->D;
C.->D;

```

with `mermaid sample.mermaid` I get a graph without lines and arrowheads. The dotted line is rendered though:
![sample mermaid](https://cloud.githubusercontent.com/assets/1710598/8674981/a08adf0c-2a41-11e5-9b8b-97c38169be28.png)
`mermaid --version`
--> 0.5.1

**Comment by knsv** [comment]
Try adding a stylesheet using the -t option. That should do the trick. I guess better the default styles are somewhat thin... :)

**Comment by nylki** [comment]
@knsv thanks! Is there a good stylesheet you can recommend somewhere (which has visible lines :P) so I can start editing own styles.

**Comment by knsv** [comment]
Take a look at:
https://github.com/knsv/mermaid/blob/master/dist/mermaid.css
or 
https://github.com/knsv/mermaid/blob/master/dist/mermaid.forest.css

I hop this helps.

**Comment by nylki** [comment]
@knsv That does help a bit. However I don't get the consistent results I get in the [Live Editor](http://knsv.github.io/mermaid/live_editor/). Arrows still seem to be a problem. 
For testing purposes I used the [same stylesheet](http://knsv.github.io/mermaid/css/mermaid.css) used for the live editor.

This is the live editors result:
![bildschirmfoto 2015-07-15 um 14 40 49](https://cloud.githubusercontent.com/assets/1710598/8698593/c5ce1838-2aff-11e5-8b4e-1c4667158206.png)



This is the mermaid-cli's result:
![sample mermaid](https://cloud.githubusercontent.com/assets/1710598/8698595/ca008508-2aff-11e5-80ba-01c881700814.png)


Do you know what this could be the cause, although the stylesheet should be the same?

**Comment by knsv** [comment]
I see...

Your issue is now actually a duplicate of issue #181. This has been fixed but not yet released. The fix is available in the lasted build if you want to live in the edge. :)

https://github.com/knsv/mermaid/tree/master/dist

**Comment by nylki** [comment]
@knsv Ahh great, I'll try the latest build then. Thanks for your quick help! :+1:
