### ISSUE TITLE
Trying to add link using 'click' to flowchart

### ISSUE THREAD

**Issue by barttt** [knsv/mermaid#188]
I have tried everything that I can think of to get a click event to fire on a flowchart item, per the docs and the test case code, but I cannot figure out what I am doing wrong. I am using mermaid 0.5.1. Here is my code:

```
<!DOCTYPE html>
<html>
    <head>
        <title>ART Process work-flow</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
		<link href="/bower_components/mermaid/dist/mermaid.css" rel="stylesheet" type="text/css">
		<link href="/bower_components/mermaid/dist/mermaid.forest.css" rel="stylesheet" type="text/css">

        <style>

            .title 
			{
                font-size: 48px;
            }
        </style>
		<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
		<script type="text/javascript" src="/bower_components/mermaid/dist/mermaidAPI.js"></script>
		<script>
		mermaidAPI.initialize({startOnLoad:true});

		function myAction(id)
		{
			alert("click fired");
		}

		$(function()
		{
			var graphDefinition = 'graph TB\nProposal-->Contract\nContract-->Planning\nPlanning-->Design\nDesign-->Build\nBuild-->Verification\nVerification-->Delivery\nDelivery-->Support\nclick Design myAction\n';
			mermaidAPI.render('id1',graphDefinition);
		});
		</script>
		</head>
    <body>
                <div class="title">Process WorkFlow (static test)</div>
				  <div class="mermaid">
					<div class="id1"> 	</div>
				  </div>
    </body>
</html>

```

**Comment by knsv** [comment]
Sorry to hear that.

Will take a look.

**Comment by knsv** [comment]
I see the issue. With the render method you get the svg code back. The bindings done during rendering is void as the whole svg is torned out from the DOM and returned.
:(

**Comment by barttt** [comment]
Hi Knut-
Thanks for your very quick reply.

So does this mean that using the render API call will not allow a link (via javascript)?
I really hoped this would work..

**Comment by knsv** [comment]
It turns out that it is not hard to fix this so the callback for the render function not only get the svg code back but also a function that sets up the bindings. It would look something like this:

```
<!DOCTYPE html>
<html>
<head>
    <title>ART Process work-flow</title>
    <meta charset="UTF-8">
    <link href="http://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <link href="../dist/mermaid.css" rel="stylesheet" type="text/css">
    <link href="../dist/mermaid.forest.css" rel="stylesheet" type="text/css">

    <style>

        .title
        {
            font-size: 48px;
        }
    </style>
    <script src="../dist/mermaidAPI.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

    <script>
        mermaidAPI.initialize({startOnLoad:true});

        function myAction(id)
        {
            alert("click fired");
        }

        $(function()
        {
            var callback = function(code,bindEvents){
                bindEvents();
            }
            var graphDefinition = 'graph TB\nProposal-->Contract\nContract-->Planning\nPlanning-->Design\nDesign-->Build\nBuild-->Verification\nVerification-->Delivery\nDelivery-->Support\nclick Design myAction\n';
            mermaidAPI.render('id1',graphDefinition,callback);
        });
    </script>
</head>
<body>
<div class="title">Process WorkFlow (static test)</div>
    <div id="id2">
    </div>
</body>
</html>
```

**Comment by barttt** [comment]
Hmm..
Not sure what is wrong, but that doesn't work for me.
What does the bindEvents call do? 
And what is code refering to?

**Comment by knsv** [comment]
bindEvents is a function that binds the click events as per the graph definition. This must be done after the svg code is in the DOM.

If you get undefined instead of a function it means that you not have the lastest mermaid.

**Comment by knsv** [comment]
Something went wrong... Did a rebuild. 

Have this code working:
```
<!DOCTYPE html>
<html>
<head>
    <title>ART Process work-flow</title>
    <meta charset="UTF-8">
    <link href="http://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <link href="../dist/mermaid.css" rel="stylesheet" type="text/css">
    <link href="../dist/mermaid.forest.css" rel="stylesheet" type="text/css">

    <style>

        .title
        {
            font-size: 48px;
        }
    </style>
    <script src="../dist/mermaidAPI.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

    <script>
        mermaidAPI.initialize({startOnLoad:true});

        function myAction(id)
        {
            alert("click fired");
        }

        $(function()
        {
            var callback = function(code,bindEvents){
                console.log(bindEvents);
                $("#div-id1").html(code);
                bindEvents();
            }
            var graphDefinition = 'graph TB\nProposal-->Contract\nContract-->Planning\nPlanning-->Design\nDesign-->Build\nBuild-->Verification\nVerification-->Delivery\nDelivery-->Support\nclick Design myAction\n';
            mermaidAPI.render('id1',graphDefinition,callback);
        });
    </script>
</head>
<body>
<div class="title">Process WorkFlow (static test)</div>
    <div id="div-id1">
    </div>
</body>
</html>
```

**Comment by barttt** [comment]
Sorry for being a pain..
I don't see what gets passed in for code and bindEvents.
I am using firefox build 39.0 with firebug, and do not see any console log output on startup or if the flow chart elements are clicked. 
I do see 
![web](https://cloud.githubusercontent.com/assets/13264066/8758722/51c90fb2-2c9c-11e5-9a42-486598467439.png)

**Comment by barttt** [comment]
Hi Knut-
I tried this code in: 
Chrome - renders fine & alert fires
IE9 - rendering is messed up but alert fires

Looks like some browser differences are entering the picture.

Thank you for your timely replies

**Comment by barttt** [comment]
I did not catch you mention of mermaid version earlier. I just ran thru the source that I have here. It is marked 0.5.1. Perhaps there is a newer version?

**Comment by knsv** [comment]
Tested in Firefox and noticed the problem was again with the css rules.

Change the initalization call to:
```
mermaidAPI.initialize({startOnLoad:true,cloneCssStyles:false});
```

Then it works in firefox as well!

**Comment by barttt** [comment]
Thank you so much for your help!

**Comment by Daijobou** [comment]
This is like dot syntax. In dot you can add "URL" (and "tooltip") to a node. Is URL here not possible? I need each node with a URL. Click on node should open a new page. ;)

**Comment by knsv** [comment]
Yes I'll add that. Good what of breaking up a large flowchart top smaller pieces. How should the syntax for the tooltip look?

**Comment by knsv** [comment]
Will continue discussions about click/tooltip in add this in issue #34. Will close this issue, let me know any objections.
