### ISSUE TITLE
Escape "~"

### ISSUE THREAD

**Issue by sebelk** [knsv/mermaid#191]
Hi folks,

I've tried escaping character "~" as is in https://github.com/knsv/mermaid/issues/170 but it fails, for example:

```
graph TD;
   id1((Bash Login))-->id2{/etc/profile};
   id2{/etc/profile}-->id3("~/.bash_profile");
```

(I've tested doble quotes outside of parenthesis too, with no success)
any idea?

Thanks in advance

**Comment by sebelk** [comment]
I've tested using commit 3ec7c6d18b8fc6d7b4abac51076b0654b76021eb  (mermaid cli) and works well. It happened using on haroopad.

HTH

**Comment by knsv** [comment]
Hi! That you experience this using haroopad is because haroopad uses an older version of mermaid, pre fix for #170. When they upgrade mermaid version in haroopad to 0.5.1+ this should be resolved.

**Comment by knsv** [comment]
I am closing this issue. You might report this to haroopad instead if you wish. Let me know if you disagree.

**Comment by sebelk** [comment]
:+1:
