### ISSUE TITLE
Error on simple graph

### ISSUE THREAD

**Issue by zhum** [knsv/mermaid#192]
I try to render this simple graph and get this error: mermaid.min.js:28160 Uncaught TypeError: Cannot read property '0' of undefined.
What is wrong?

````
graph LR;
  head(head) --> file(file);
  file(file) --> just_link(just_link);
  file(file) ==> job_234(job_234);
  just_link(just_link) ==> joiner(joiner);
  joiner(joiner) --> csv(csv);
  job_234(job_234) --> job2_234(job2_234);

````

**Comment by knsv** [comment]
Turns out that the character v is also a keyword as in direction down which causes a syntax error in this graph. v cannot be used in ids. Will fix that.

**Comment by zhum** [comment]
Thank you! Works now!
