### ISSUE TITLE
Last word in comment boxes getting cut off by word wrap library : (

### ISSUE THREAD

**Issue by harlantwood** [knsv/mermaid#195]
[See screenshot](https://www.dropbox.com/s/6f8k013irmepb5n/Screenshot%202015-08-11%2012.30.29.png?dl=0) -- this is from the Atom preview, but same issue in Chrome/Yosemite.

I opened a PR in d3textwrap (https://github.com/vijithassar/d3textwrap/pull/8) around this.  I tested this code in a custom Mermaid build and it did fix the issue, though it messed up alignment a bit.

Another option would be to switch to d3plus, which appears to have robust text wrapping: http://d3plus.org/examples/utilities/a39f0c3fc52804ee859a/ -- Note that if you include the head version of d3plus, it now builds correctly in browserify.

**Comment by knsv** [comment]
Thanks for pointing this out and thanks for your effort with the PR. I am sure you are not the only one that has experienced this. 

I started out looking at d3plus but chose not use it as the size of it would more then double the size of mermaid. I will take a look at the PR and see what if I can incorporate it (ahead of time)!

**Comment by harlantwood** [comment]
Excellent, thanks.  And thanks for a great library, we are loving mermaid!

As a workaround, we found that adding '\n' to the end of a comment fixes the appearance in all cases, ie the last word always shows up.

Regarding d3plus, maybe it is relatively easy to extract the text wrap component?  Maybe it can/should be pulled into it's own node module and included by d3plus, mermaid, and others... Just an idle thought : )

**Comment by knsv** [comment]
Fix for this issue was released in mermaid 0.5.2. Will close this now, let me know if you issues still remain.

**Comment by harlantwood** [comment]
Excellent, thanks!
