### ISSUE TITLE
Broken CLI Graphs? (v0.5.1)

### ISSUE THREAD

**Issue by TheVulch** [knsv/mermaid#196]
Something's happened since I last used the CLI. Has the website not been updated, or is everything breaking? Even something as simple as this:
```
graph LR
    C --> D
```
or
```
graph TD
    A-->B
```
Is giving me a completely blank PNG...not even a background. Just completely transparent with nothing shown.
Also, is this (from #153 ):
```
graph LR
    subgraph A
        B
    end
    style A fill:#f9f
```
supposed to give this .png?
![t mermaid](https://cloud.githubusercontent.com/assets/5877394/9262777/6117a646-41cc-11e5-8de1-aefb25cb21eb.png)
Where is that extra `A` element coming from? I tried putting a semi-colon after the `style` line, but nothing changed.

Mermaid & PhantomJS are both updated to the newest version.

**Comment by knsv** [comment]
I think this is a result of lacking styling. I could replicate your issue and eliminating it by adding 
```-t ./dist/mermaid.css```
to the command-line

**Comment by TheVulch** [comment]
Is this the way it's supposed to work? Is there any way the css could just be included by default if no css file is given? I feel that this issue would happen to just about everyone who's starting out by reading the documentation online.

**Comment by gillesdemey** [comment]
I definitely got caught up by this, and I imagine many others will. Is there a reason why we shouldn't just use the default styles when generating a PNG file? Or is this a recent regression? 

It seems like the default behaviour, which is to generate blank PNG files, is confusing.

**Comment by knsv** [comment]
I agree! @fardog is this something you could find time for? I am unsure how the paths to the css files would be calculated in the CLI when installed globally.

**Comment by gillesdemey** [comment]
I've sent a PR to address the issue, tested it locally by using `npm link` to replace the globally installed version. I've also included a test of course :)

**Comment by fardog** [comment]
I'll review the posted PR after work and give it a +1 if it looks good
