### ISSUE TITLE
link/edge between two subgraphs

### ISSUE THREAD

**Issue by jobonaf** [knsv/mermaid#197]
Is there a way to connect two subgraphs? 
Now I'm using "phantom" nodes as labels:

```
graph TD
Wb(web-book); An(annuario); Ss[schede<br>stazioni]; Si[schede<br>indicatori]; G[grafici]; Ar[archivio]; Pr[prodotti]
subgraph;Ss;Si;G;Ar;end
subgraph;Wb;An;Pr;end
Ar ==> Pr
classDef label fill:#eef, stroke:#eef
class Ar,Pr label
```

**Comment by knsv** [comment]
I am sad to say that there are no such support. A bit tricky to fix. Th best would for the dagre library to add support for this.

**Comment by tylerlong** [comment]
Let's confirm that the upstream project https://github.com/dagrejs/dagre-d3 supports it. Then we can start working on it.

**Comment by Hviid** [comment]
@tylerlong What should dagre-d3 support in order to get this working?

**Comment by amittestkiwi** [comment]
Any update on this

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

**Comment by MikePryadko** [comment]
Is any in the World a graph description language which allow connections between subgraphs?! It's a very important thing! I need to visualize data structures, but I can't find tool for that(((
