### ISSUE TITLE
Wrap Text in Nodes of a FlowChart

### ISSUE THREAD

**Issue by vsreddy1602** [knsv/mermaid#199]
First of all, Great Library!! I have found it very useful.

To increase the usability and give more control to the user of the API, is there a way where I can customize the height and width of a node and wrap text in it?

Currently when the text is long, the node also becomes bigger. If we have a way of wrapping text in the node, the chart would look more presentable.

Please help me out here!

**Comment by pnewell** [comment]
Same here, I need a max width for nodes and then have the text autowrap.

**Comment by knsv** [comment]
Thats a good idea! I will take a look at this.

**Comment by vsreddy1602** [comment]
Please can you let us know if you have a timeline by when we can expect this feature?

**Comment by knsv** [comment]
This change might take a while as it possibly have external dependencies from the projects perspective. Meanwhile you CAN wrap text manually as in the example below:
```mermaid
graph LR
	a-->b(long long<br/>long text)
```

**Comment by locomo** [comment]
would also love to be able to specify additional node styles - width, height, text wrap etc

**Comment by cfobel** [comment]
This would be great!

**Comment by olindk** [comment]
Same here, it would be very nice to have it.

**Comment by fmatheus** [comment]
There is any better workaround for this? Like styling svg or maybe a pure html output?

**Comment by bhrutledge** [comment]
Would constraining the width of nodes be a workaround? That's been requested in #653.

**Comment by ThePenguin1140** [comment]
@bhrutledge I think that would be a good start to address this issue. Since this one is a bit more fleshed out and has an actual feature request I will close #653. We could probably add an option to the parser to accept a `nodeWidth` argument that gets applied to all nodes for now?
