### ISSUE TITLE
Generating SVG text blob for use in Node

### ISSUE THREAD

**Issue by RangerMauve** [knsv/mermaid#2]
Hey, it'd be nice if there was an API available to generate one of these graphs in node (or even at runtime in browser-side js) so that it could be either saved somewhere or sent as part of a response. If this ability already exists, could there be some docs for it?

**Comment by knsv** [comment]
@RangerMauve There is client utility for this now which is run via node. It uses phantomjs for rendering the diagrams. Hopefully that should solve your issue. I will close this but if you disagree don't hesitate to reopen it.

**Comment by RangerMauve** [comment]
That sounds good, thanks!
