### ISSUE TITLE
syntax for venn diagrams?

### ISSUE THREAD

**Issue by jasonkarns** [knsv/mermaid#200]
is there any prior art of a venn diagram syntax?

**Comment by knsv** [comment]
I am sad to say that there are no such diagram support. Maybe in the future!

**Comment by knsv** [comment]
You could add your vote in the poll for new diagram types if you wish.
https://github.com/knsv/mermaid/issues/177

**Comment by endolith** [comment]
Technically you probably want Euler diagrams, not Venn. 

![image](https://user-images.githubusercontent.com/58611/202886494-c6ad8f0c-a624-4c67-a80f-411c2e918836.png)

**Comment by brandondrew** [comment]
> Technically you probably want Euler diagrams, not Venn.
> 
> ![image](https://user-images.githubusercontent.com/58611/202886494-c6ad8f0c-a624-4c67-a80f-411c2e918836.png)

I think that all requests for Venn diagrams can reasonably be interpreted as requests for Euler diagrams unless the requester makes very clear that they really mean ***Venn*** and not ***Euler***.
