### ISSUE TITLE
Live Editor: Permalink address not being parsed

### ISSUE THREAD

**Issue by ichabodcole** [knsv/mermaid#202]
I'm expecting that clicking the permalink button in the live editor should allow me to then copy the url, paste in a new tab and see the graph I created, but I'm only seeing the default graph when doing this.

1. Go to http://knsv.github.io/mermaid/live_editor
2. Make a small change to the default diagram.
3. Click the Permalink button, copy the url, and paste into a new tab.
4. Expecting diagram to show the changes, but the default is still displayed.

Tested in chrome and safari on OSX

Seeing this errror in the console as well.

    Invalid CSS selector "[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)" DOMException: Failed to execute 'querySelectorAll' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)' is not a valid selector.(…)

**Comment by knsv** [comment]
Hmm. This used to work. 

@naseer is this something you could help us with? If so, much appreciated.

**Comment by naseer** [comment]
just tried it out - it seems to work fine, I see the link text getting updated

**Comment by spect88** [comment]
@ichabodcole Is this still a problem? With the new permalinks, there's a high chance this problem is fixed.

**Comment by orschiro** [comment]
@spect88 

Just tested the latest version. It is working great now. 

Thank you!

~ Robert
