### ISSUE TITLE
please consider port to mac osx 

### ISSUE THREAD

**Issue by pi1ot** [knsv/mermaid#203]
hoping  port to mac system, or homebrew, thanks.

**Comment by gillesdemey** [comment]
`npm install -g phantomjs && npm install -g mermaid` does the trick on OSX to install the CLI utility.

**Comment by knsv** [comment]
@pi1ot I hope this solves your issue!

**Comment by pi1ot** [comment]
it works, thanks. @knsv @gillesdemey

**Comment by knsv** [comment]
Great!
Will close this then.
