### ISSUE TITLE
Label with HTML?

### ISSUE THREAD

**Issue by Daijobou** [knsv/mermaid#206]
I need in a label subtext like:

https://raw.githubusercontent.com/carlo-colombo/grunt-angular-modules-graph/master/angular-ui-bootstrap-modules-graph.png

or

https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Huffman_(To_be_or_not_to_be).svg/220px-Huffman_(To_be_or_not_to_be).svg.png

Is this with mermaid possible? In dot you can add primitive HTML sytnax in label like TABLE. ;)

**Comment by knsv** [comment]
You can indeed. There is a setting for that:
```
    <script>
        var config = {
            startOnLoad:true,
            callback:function(id){
                console.log(id,' rendered');
            },
            flowchart:{
                    useMaxWidth:false,
                    htmlLabels:true
                }
        };
        mermaid.initialize(config);
    </script>
```

The default setting should be true though. This would 
Node text:
```
<foreignObject width="86" height="19">
     <div style="display: inline-block; white-space: nowrap;">
       Square Rect
     </div>
</foreignObject>
```
Link text:
Node text:
```
<foreignObject width="58" height="18">
      <div style="display: inline-block; white-space: nowrap;">
          <span style="background:#e8e8e8">Link text</span>
     </div>
</foreignObject>
```

Please note that graphs svgs with html in them will not work outside of the browser if expotred. If thats not an issue, go ahead. 

Good luck!

**Comment by knsv** [comment]
Just an idea. One could perhaps add the possibility to configure this. Maybe an label rendering function that mermaid can call with the text from the graph definition that returns a more complex label html.

Usage would be something like this:
```
    <script>
        var nodeFormatter = function(text){
            var title = parseTitleFromText(text);
            var title = parseBodyFromText(text);
            return '<table><tr><th>'+title</th></tr><tr><td>'+body+'</td></tr></table>'
        }
        var config = {
            startOnLoad:true,
            callback:function(id){
                console.log(id,' rendered');
            },
            flowchart:{
                    useMaxWidth:false,
                    htmlLabels:true,
                    nodeLabelRenderer:nodeFormatter
                }
        };
        mermaid.initialize(config);
    </script>
```

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

Feel free to create a new issue, if necessary.
