### ISSUE TITLE
Please add prefix for styles

### ISSUE THREAD

**Issue by Daijobou** [knsv/mermaid#208]
Like jquery ui-* you should add a prefix or a default class/id before mermaid-classes:
https://github.com/knsv/mermaid/blob/master/dist/mermaid.css

.section, .grid, .active, .node, .task is not only used in mermaid ;)

**Comment by knsv** [comment]
I see the problem. Perhaps more specific selectors for styling as
svg .label
.mermaid .label

in the stylesheet would do the trick.
