### ISSUE TITLE
node feature request

### ISSUE THREAD

**Issue by pi1ot** [knsv/mermaid#211]
such as 
<img width="339" alt="2015-09-22 18 58 07" src="https://cloud.githubusercontent.com/assets/1677644/10016761/e59a889e-615b-11e5-8655-0f12751a5c0c.png">

thanks!

**Comment by knsv** [comment]
A are you refering to subgraphs?
```
        graph TD
        subgraph A
            B
            subgraph C
                D
            end
        end
```
The definition above renders the image below.

![skarmavbild 2015-09-22 kl 20 14 00](https://cloud.githubusercontent.com/assets/5837277/10027329/a1183e5e-6166-11e5-98cb-ca60bd609061.png)

Not exactly as your image but almost.

**Comment by pi1ot** [comment]
that's it, thanks!

**Comment by knsv** [comment]
Cool, will close this issue then! :)
