### ISSUE TITLE
Brackets in a node with text?

### ISSUE THREAD

**Issue by orschiro** [knsv/mermaid#213]
Dear all,

I looked at the following example from the documentation:

> id1[This is the text in the box]

I assumed to add brackets to the text as follows:

> id1[This is the (text) in the box]

However, the Live Editor does not render the chart when using brackets. 

Are brackets in node link texts supported?

Thankfully,

Robert

**Comment by knsv** [comment]
Put the text within quotes and you will have a diagram:
```
graph LR
id1["This is the (text) in the box"]
```

Good luck!

**Comment by knsv** [comment]
Thanks for bringing this up. I added a small example in the docs for this case:
http://knsv.github.io/mermaid/#special-characters-that-break-syntax

**Comment by orschiro** [comment]
It works. Thanks @knsv!

**Comment by shatadrusaha** [comment]
I am trying to use mermaid in a RMD document. But, when I try to use bracket within quotes, it doesn't work. Although, that was the solution provided above. My code works fine, when I don't use brackets. The code is given below:

mermaid("
    graph TB;
      A[Data Extraction <br> BGL + PCD vars] --> B[WOE Binning <br/> PCD vars];

      B --> C[Data Sampling <br/> Train - 70% <br/> Test - 30%];
    ")

 This  produces the following graph:

![image](https://user-images.githubusercontent.com/18445132/59184566-4e69ea80-8b66-11e9-804c-9ff25e1a028a.png)

I am trying to have the graph look like this in the first block

Data Extraction
(BGL + PCD vars)

**Comment by csmsavage** [comment]
In an RMD document, you can still use double quotes for the node label if you surround the mermaid diagram with single quotes (the reverse doesn't seem to work).


```
library(DiagrammeR)

mermaid('
  graph TB;
  A["Data Extraction <br/> (BGL + PCD vars)"] --> B[WOE Binning <br/> PCD vars];
  B --> C[Data Sampling <br/> Train - 70% <br/> Test - 30%];
')
```
