### ISSUE TITLE
Render mermaid code on websites?

### ISSUE THREAD

**Issue by orschiro** [knsv/mermaid#215]
Dear all, 

This is a more general question. I am currently trying to switch my entire digital work to plain text (i.e. Markdown) files and syntax. Thus, I really like mermaid to use plain text syntax for generating diagrams. 

Is it somehow possible to add mermaid syntax to a markdown file and have it rendered on an online website instead of embedding a raster image? 

Thankfully,

Robert

**Comment by knsv** [comment]
That it is. One example is the documentation site. http://knsv.github.io/mermaid/

That site is generated from markdown to html. At page load the graph defintions (still as text inte the html) is rendered by mermaid.

Another way could be to do the markdown conversion in the browser as well. With this approach you could have markdown files as content that is loaded by a web app that generates html and displayed the result.

A good start could be to look at the documentation site though. The source files is in the docs folder.

**Comment by orschiro** [comment]
Dear @knsv,

Thanks for your comment!

> That site is generated from markdown to html. At page load the graph defintions (still as text inte the html) is rendered by mermaid.

I looked at the source and it is hosted on Github Pages, correct? Thus, Github Pages can render mermaid code?

~ Robert

**Comment by knsv** [comment]
Wc!

The docs pages are served from Github Pages but the rendering is not done by Github Pages. The rendering is done in the browser. This means any site can server this kind of content. The web server only sends the graph definition in a div.

When the page has loaded mermaid starts running in the browser and looks for graph definitions. The graphs found are rendered to svg which is displayed in the content by the browser.

Hope that clarifies things.

**Comment by orschiro** [comment]
> Hope that clarifies things.

Indeed it does! Thank you. Basically, one just needs to load the javascript library to render the code in the browser. Cool! ツ

~ Robert

**Comment by szrlee** [comment]
still have a question about how to render mermaid on github pages directly from jekyll markdown, etc.

**Comment by yk-liu** [comment]
Me too. I have been trying to find a way to render mermaid in markdown simply by using

     ```mermaid
     # some mermaid code
     ```

in markdown, and use javascript in the page to render it. 

I tried many solutions and faild. One of the solution I found is to use code from [here](https://stackoverflow.com/questions/53883747/how-to-make-github-pages-markdown-support-mermaid-diagram/53884027?noredirect=1#comment94616004_53884027) but that's not correct. I am wondering if the author of this awesome js can give me a solution to acheive that and add that to the documentation?

 Also I could not find the docs folder @knsv mensioned.

**Comment by asbjornu** [comment]
@szrlee, as mentioned in github/markup#533, that's a feature request you need to send to [the GitHub support team](https://github.com/contact).

**Comment by Dunning-Kruger** [comment]
This is a 16 month old closed issue. If you have any more questions or issues, please open a new one.
