### ISSUE TITLE
New documentation - need improved logo

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#216]
The documentation has been updated: http://knsv.github.io/mermaid/

During the work I could not figure out what a decent logo should look like. I found no inspiration and did a very basic one. It would be nice with a better one.

**Comment by tylerlong** [comment]
Now we have the new doc website: https://mermaidjs.github.io/

Let's close this aged issue. Feel free to create a new one if you still think we need a logo for the documentation.
