### ISSUE TITLE
Live editor offline access

### ISSUE THREAD

**Issue by orschiro** [knsv/mermaid#217]
Dear all, 

[mermaid-demo](http://danielmschmidt.github.io/mermaid-demo/) and [live_editor](http://knsv.github.io/mermaid/live_editor/) are very helpful in assisting to create diagrams. 

Is it somehow possible to make these editors available as offline web apps, e.g. for Chrome?

This could be very useful in situations without a good internet connection, e.g. traveling. 

Thankfully,

Robert

**Comment by knsv** [comment]
Cool idea. Would be nice try out the service worker concept.

**Comment by orschiro** [comment]
A good resource for further reference: https://wiki.mozilla.org/MDN/Get_involved/Events/HackOnMDN/Project:_Service_Workers

**Comment by tylerlong** [comment]
This is a long live issue and I am going to close it.

Here are some workarounds: 

https://mermaidjs.github.io/mermaid-live-editor  is a pure static website. So you can load it whenever you have network connection and keep the page open. Then you can use it offline.

You can grab the source code and run it locally: https://github.com/mermaidjs/mermaid-live-editor Then no network connection is required when you are running it.

I've added a project todo item: release a desktop client. I don't have a timeline for it though.

**Comment by AhmedThahir** [comment]
Is there a way to use it offline now?
I just get an error that it's legacy version. not supported anymore
