### ISSUE TITLE
Installing “atom-mermaid@0.1.3” failed

### ISSUE THREAD

**Issue by DSigmund** [knsv/mermaid#218]
> contextify@0.1.14 install C:\Users\sigmundd\AppData\Local\Temp\apm-install-dir-115830-34188-t8bt93\node_modules\atom-mermaid\node_modules\d3\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

C:\Users\sigmundd\AppData\Local\Temp\apm-install-dir-115830-34188-t8bt93\node_modules\atom-mermaid\node_modules\d3\node_modules\jsdom\node_modules\contextify>node "C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\sigmundd\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\sigmundd\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\sigmundd\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\sigmundd\\.atom\\.apmrc" "install" "C:\\Users\\sigmundd\\AppData\\Local\\Temp\\d-115830-34188-q00zpj\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

**Comment by knsv** [comment]
Hello!

It looks like some problem in your node environment. 

You are installing atom-mermaid 
* which in turn is requires d3 and installs it
* d3 in turn requires contextify which fails to install

```
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'
```

Maybe this issue should also be posted in the atom-mermaid instead of mermaid the project as that is the module you are trying to install. 
https://github.com/y-takey/atom-mermaid/issues

Good luck with atom-mermaid. I use it myself from time to time. Its great!

**Comment by DSigmund** [comment]
You're right about that...

Sorry to post this on the wrong place....
