### ISSUE TITLE
Double Quote as text is not working

### ISSUE THREAD

**Issue by andrew-vandenbrink** [knsv/mermaid#219]
I try to use double quote as part of the text but it is not working, escaping with &quot; also not working.

**Comment by andrew-vandenbrink** [comment]
I mean
& quot ;

**Comment by knsv** [comment]
Fix for this issue was released in mermaid 0.5.2. Will close this now, let me know if you issues still remain.

**Comment by andrew-vandenbrink** [comment]
Hi @knsv 
I just tested it with latest version,

This is working
```
<div class='mermaid'>
graph LR;
statement1["public test ()"];
if1{"string.compare('mermaid')==0"}--then-->then1["{<br/>//this is mermaid<br/>}<br/>"];
</div>
```

This is not working
```
<div class='mermaid'>
graph LR;
statement1["public test ()"];
if1{"string.compare("mermaid")==0"}--then-->then1["{<br/>//this is mermaid<br/>}<br/>"];
</div>
```

This one also not working
```
<div class='mermaid'>
graph LR;
statement1["public test ()"];
if1{"string.compare(&quot;mermaid')==0&quot;}--then-->then1["{<br/>//this is mermaid<br/>}<br/>"];
</div>
```

**Comment by knsv** [comment]
Had problems with that syntax as it was decoded when fetched from the browser.

Check more details here:
http://knsv.github.io/mermaid/#special-characters-that-break-syntax

In short, use #quote;

Good luck!

**Comment by andrew-vandenbrink** [comment]
Perfect!
It works now!
Thanks!
