### ISSUE TITLE
Please update bower's D3 version

### ISSUE THREAD

**Issue by chinakids** [knsv/mermaid#221]
3.3.8  ->  ~3.3.8 or 3.5.6

**Comment by knsv** [comment]
Good timing! :) 

Started working with updating dependencies to later versions and modernizing the build environment a couple of days ago. This turned out to be a bit bigger effort then expected though.

This will be included in the 0.5.3 release.

**Comment by knsv** [comment]
Closing issue as it's resolution is included in release 0.5.6. Let me know if you do not agree.
