### ISSUE TITLE
subgraph not rendering with change to sample

### ISSUE THREAD

**Issue by mycall** [knsv/mermaid#231]
I am having problems rendering this graph.  Am I doing something wrong?

	graph TB		
        subgraph old sys 2
            a2(new client)-->b2
            oc2(Old client)-->b2
			a3(test)-->b2
        end

        subgraph old sys 1
            a1(new client)-->b1(sys1 server)
            oc1(Old client)-->b2(test)
        end

**Comment by mycall** [comment]
error "Uncaught TypeError: Cannot set property 'label' of undefined" @ mermaid.js:10789

    if (!_.has(node, "label") && !g.children(v).length) { node.label = v; }

**Comment by knsv** [comment]
Your graph works in the editor:
http://knsv.github.io/mermaid/live_editor/#/edit/c2VxdWVuY2VEaWFncmFtCkEtPj4gQjogUXVlcnkKQi0-PiBDOiBGb3J3YXJkIHF1ZXJ5Ck5vdGUgcmlnaHQgb2YgQzogVGhpbmtpbmcuLi4KQy0-PiBCOiBSZXNwb25zZQpCLT4-IEE6IEZvcndhcmQgcmVzcG9uc2UK

What version are you running on?

Check with the graph definition:
```
info
```

**Comment by mycall** [comment]
Perhaps it is how I am using mermaid.js.  I zipped up my sample here: https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiI0ODUyZGU2ZC0zNTM1LTRlOWEtOTRhYy01YTczNjQyNTcxZjUiLCJlbWFpbCI6Im1wYWluZUBhY3RyYW5zaXQub3JnIn0=

**Comment by mycall** [comment]
any chance you can review the uploaded zip?

**Comment by knsv** [comment]
I did and found tab characters to be the problem. Replace with space and
it will work. Mermaid should handle the tabs eventually though.
fre 30 okt. 2015 kl. 18:51 skrev mycall <notifications@github.com>:

**Comment by mycall** [comment]
Thank you, that solves my problem.  I've been using tabs successfully without the subgraph feature but once I added subgraph, I was getting those errors.
