### ISSUE TITLE
When there is a Chinese symbol in the flowchart, it will crash。

### ISSUE THREAD

**Issue by Arnoldnuo** [knsv/mermaid#238]
wrong:

    graph TD
    A[a，a]

right:

    graph TD
    A[a,a]

**Comment by knsv** [comment]
Put the characters within quotes and it will work, as in:
graph TB
  A["这工作"]

Example:
http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggVEIKICBBWyLov5nlt6XkvZwiXQ

**Comment by Arnoldnuo** [comment]
@knsv thank you, I'll remenber to add quotes when I use flowchart。

**Comment by tylerlong** [comment]
Now it works even without quotes: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKICBBW-i_meW3peS9nF0

But it is a good practice to put no-ascii characters inside quotes.
