### ISSUE TITLE
Set x margin for flowchart in CLI

### ISSUE THREAD

**Issue by blahah** [knsv/mermaid#241]
The x margin on a flowchart is much larger than the y margin. The CLI provides a way to set the margins for sequence and gantt diagrams, but not for flow diagrams (as far as I can tell).

Is it possible to set the x margin for a flowchart using the current CLI?

**Comment by knsv** [comment]
Not currently. Will try to align how the various diagrams work in the CLI. Will take a w hile though as I am currently working focused on Class Diagrams. Will set this as help wanted as it would be great if someone looked at it.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

Feel free to create a new issue, if necessary.
