### ISSUE TITLE
Broken in firefox?

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#245]
Visit http://mdp.tylingsoft.com/ and scroll to the bottom.

It works in Chrome and Safari but Firefox. I haven't tested IE yet.

Frankly speaking, myself don't need other browsers support other than Chrome. This issue is just FYI.

**Comment by spect88** [comment]
The bug is in error handling when trying to access document's css rules.
Firefox throws a SecurityError, which triggers the error handler. I'll get a fix ready in a moment.
