### ISSUE TITLE
SVG arrowheads are broken in the CLI

### ISSUE THREAD

**Issue by gibson042** [knsv/mermaid#249]
[sequenceRenderer.js](https://github.com/knsv/mermaid/blob/185233c971f11765681bc605c5886f77683d4966/src/diagrams/sequenceDiagram/sequenceRenderer.js#L231-L244) and/or [mermaidAPI.js](https://github.com/knsv/mermaid/blob/eec89e04421d121e9744cddfd97f06b6b264cdb2/src/mermaidAPI.js#L436-L440) embed styles like `url(about://blank#arrowhead)` instead of the well-behaved `url(#arrowhead)`.

Relates to #225.

**Comment by knsv** [comment]
Been looking at this. Adding configuration option for when to use absolute references for arrow heads. Default is off as in your well-behaved version.

If you are using a base tag you need to have it on.

**Comment by knsv** [comment]
Closing issue as it's resolution is included in release 0.5.6. Let me know if you do not agree.

**Comment by gibson042** [comment]
Works for me. Thanks!
