### ISSUE TITLE
Allow setting a date range to display in Gantt charts

### ISSUE THREAD

**Issue by nickwynja** [knsv/mermaid#254]
I'm really enjoying the gantt charts for project road mapping. I'd like to be able to define in the config header of a chart what date range to display. I have a "rolling" timeline where I just add new projects to future dates, yet still have items in the past (say, from January). I'd like to be able to add a `startDate` and `endDate` to the chart definition so that it only shows me data from between those two dates. 

Alternately, if I only define a `startDate` it would show me all data after that date or defining `endDate` only would show me all data up until that end date.

This would allow me to maintain an accurate set of data while only displaying the range of dates that I'm interested in.

Thanks,
—Nick

**Comment by knsv** [comment]
Glad to hear that you enjoy the gantt charts!

What you propose sounds like a good idea and should be possible to implement but will have to wait a bit. I'm working with a new diagram type, classDiagrams, right now and want to finish that first.

This kind of filter could be interesting for sequenceDiagrams as well. If you have a large diagram you could pick the actors you are interested in and show a similar subset of the diagram.

**Comment by nickwynja** [comment]
Agreed! Seems to be a natural feature progression as we start to use these charts more over time. Thank for considering the feature.
