### ISSUE TITLE
Where to find line layout algorithm?

### ISSUE THREAD

**Issue by ajilius** [knsv/mermaid#258]
I've got a layout problem, highlighted in the attached diagram, with the lines between nodes.
The area circled in red is quite messy, and the line overdrawn in red has a much more simple path.
I'd like to take a look at the code to understand the problem better.
Can you point me to the code that handles this layout?

![mermaid1](https://cloud.githubusercontent.com/assets/15190128/11198669/c4473828-8d1a-11e5-8b84-39ba88231d18.png)

**Comment by knsv** [comment]
This is implemented using the dagre-d3 library. Look at https://github.com/cpettitt/dagre-d3 for more info. hope this helps. Reopen if you have more questions.
