### ISSUE TITLE
mermaid without browser

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#260]
I want to do it in pure node.js:

``` javascript
var mermaidAPI = require('mermaid').mermaidAPI;
var graphDefinition = 'graph TB\na-->b';
var graph = mermaidAPI.render(graphDefinition);
console.log(graph);
```

Currently it is not possible: https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L486

> if (typeof document === 'undefined') {
>    // Todo handle rendering serverside using phantomjs
> }

**Comment by knsv** [comment]
I agree. That would be a good function. It would impact the CLI in a positive way. It comes down to providing a document containing a DOM object which is used by d3.

I have not worked so much directly with for instance phantomJS. I'll put this as help wanted for now! Lets hope that someone are interested in coding this.

**Comment by tylerlong** [comment]
I just have an idea: https://github.com/mhart/react-server-example

React support server side DOM rendering. Can we use React as the 'browser' ?

**Comment by akuma** [comment]
+1

**Comment by popul** [comment]
It's not about the issue, but i made a webpack loader that helps to generate PNG files from mermaid diagrams.  https://github.com/popul/mermaid-loader

It can help :)

**Comment by tylerlong** [comment]
@popul, could you please explain how do you turn *.mmd into png? I checked your code but I really don't get it.

Are you using phantomjs to do the trick or something else?

**Comment by popul** [comment]
I just run [Mermaid CLI](http://knsv.github.io/mermaid/mermaidCLI.html) into the webpack loader.

https://github.com/popul/mermaid-loader/blob/master/index.js#L8
```javascript
...
var binPath = './node_modules/.bin/mermaid';
...
```
https://github.com/popul/mermaid-loader/blob/master/index.js#L87
```javascript
...
childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
...
```

I tried to generate png server side, but `dagre-d3` seems to be not compatible without a browser.

**Comment by Wreulicke** [comment]
I just remove phantomjs-prebuilt in my fork, and added [puppeteer](https://github.com/GoogleChrome/puppeteer).
How is this?

https://github.com/Wreulicke/mermaid/commit/c18c8aad8195f50ebc64c8ff56f6d552c122e097

**Comment by tylerlong** [comment]
Puppeteer is good! I like it.

I am planning to to replace Phantom with puppeteer in future official release.

**Comment by tylerlong** [comment]
Closing it, since I am the creator of this issue.

**Comment by KartikSoneji** [comment]
Hi, can this issue be reopened?
Puppeteer too launches a chrome binary in the background.
