### ISSUE TITLE
IE11 Support issue

### ISSUE THREAD

**Issue by usavic** [knsv/mermaid#261]
![image](https://cloud.githubusercontent.com/assets/15919707/11358529/4eb0e142-92ae-11e5-86b6-b139236d6581.png)

Tested on Windows 7 64 bit, IE 11.

**Comment by tylerlong** [comment]
I can reproduce the issue with IE 11 on Windows 10.

And gantt diagram doesn't render any image at all. It shows some text only.

**Comment by ivy88** [comment]
Can confirm and reproduce with IE 11 on Windows 7 - no text in flowchart.

**Comment by StevenDevooght** [comment]
We are experiencing the same issues with IE11 on Windows 10.

**Comment by tylerlong** [comment]
We've decided to give up IE due to lack of contributors. But we do want to support MS Edge browser.
