### ISSUE TITLE
label out of node 

### ISSUE THREAD

**Issue by yongrisb** [knsv/mermaid#262]
![result](https://cloud.githubusercontent.com/assets/6952621/11529325/51dafe1e-9927-11e5-99b8-161c30658f0a.png)

```
        var config = {
            startOnLoad:true,
            callback:function(id){
                console.log(id,' rendered');
            },
            flowchart:{
                    useMaxWidth:true,
                    htmlLabels:false
                }
        };
```

```
    <div class="mermaid" id="i211">
        graph TD;
        A[TESTTESTTESTTESTTEST];A-->B[testtesttesttesttest];
    </div>
```

**Comment by knsv** [comment]
Found the problem. It was a css selector issue. Committed a fix for this, it will be includedi n the next release. If you wish you can use the css files from the repository already.

Good luck.

**Comment by tylerlong** [comment]
I confirm that it has been fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQ7CiAgICAgICAgQVtURVNUVEVTVFRFU1RURVNUVEVTVF07CiAgICAgICAgQS0tPkJbdGVzdHRlc3R0ZXN0dGVzdHRlc3RdOw
