### ISSUE TITLE
sequence diagrams don't support participant aliasing

### ISSUE THREAD

**Issue by gibson042** [knsv/mermaid#263]
Per http://bramp.github.io/js-sequence-diagrams/#syntax , `participant {actor} as {alias}` should be accepted.

**Comment by xax** [comment]
*JS Sequence Diagrams* uses `participant <ID> as <ALIAS>` the other way round, compared to *mermaid*.

**JS Sequence Diagrams:**
```sequence
  participant Alice as A
  participant Bob as B
  A->>B: initialize something
```

**Mermaid:**
```mermaid
sequenceDiagram
  participant A as Alice
  participant B as Bob
  A->>B: initialize something
```
