### ISSUE TITLE
Not Able to See Labels even htmlLabels:false added

### ISSUE THREAD

**Issue by madhu72** [knsv/mermaid#268]
In IE 11:

![image](https://cloud.githubusercontent.com/assets/10324127/11733251/32c80170-9f71-11e5-8e57-6628ad991a5a.png)

I am not able to see the labels still after adding htmlLabels:false to memaid_config

**Comment by knsv** [comment]
I will take a look!

**Comment by knsv** [comment]
Does this work in another browser?

**Comment by knsv** [comment]
Can not reproduce using edge and ie11 emulation. Will look for native ie11

**Comment by knsv** [comment]
Are the html labels set at the correct level? The config needs to be in the flowchart object is in the example below:

```
    mermaid.initialize({
        flowchart:{
            htmlLabels:true
        }
    });
```

The chart looks like as if it is not set.

I hope that helps.
