### ISSUE TITLE
[Feature request] gantt diagram axis format

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#269]
We can define gantt diagram date format like following:

```
dateFormat  YYYY-MM-DD
```

What I am requesting is similar: let user define axis format like following

```
axisFormat %-m/%-d
```

Currently user defined axis format is not supported. It can only be done via js code:

``` javascript
mermaid.ganttConfig = {
  axisFormatter: [
    ["%-m/%-d", function (d) {
        return d.getDay() == 1;
    }]
  ]
};
```

**Comment by knsv** [comment]
Thats a good idea! This should be implemented.

**Comment by jackycute** [comment]
Please add this feature, thank you!

**Comment by surfingtomchen** [comment]
please add this feature, thanks!!!

**Comment by cnglen** [comment]
please add this feature, thanks!!!

**Comment by eagle0445** [comment]
please add this feature, thanks

**Comment by chaoslawful** [comment]
please add this feature, thanks!!!

**Comment by nanochap** [comment]
I need this feature too, thanks.

**Comment by tylerlong** [comment]
This feature is available in latest version.

There are two ways to specify gantt diagram xAxis format:

## Option 1

```js
mermaid.initialize({
      gantt: { axisFormat: '%m/%d/%Y' }
});
```
Then all gantt diagrams in the current web page will use `axisFormat: '%m/%d/%Y'`


## Option 2

```js
  <div class="mermaid">
gantt
dateFormat  YYYY-MM-DD
axisFormat  %m/%d/%Y
...
</div>
```
Then the current gantt diagram will use `axisFormat  %m/%d/%Y`


## Which one to use:

Option 1 is like global config while option 2 is like local config. If both are specified, option 2 overrides options 1.

**Comment by Demmonius** [comment]
Could you please put this solution in the official documentation here: https://mermaid-js.github.io/mermaid/#/gantt?id=syntax ? @tylerlong

**Comment by dhld** [comment]
How to control the date of each day on the timeline
