### ISSUE TITLE
allow user to designate node position or justification

### ISSUE THREAD

**Issue by chetanvsharma** [knsv/mermaid#270]
This graph:

graph TD
            C==>D
            D==>E
            D==>F
            E==>C
            F==>C

leads to the following plot:

![image](https://cloud.githubusercontent.com/assets/1693281/11825470/09014812-a334-11e5-9256-2a0a8f809ed8.png)

It'd be great to be able to specify that the D node in this situation should be centered, and the arrows go around it to make an upside Y shape, which would be much cleaner.

**Comment by knsv** [comment]
This might be a bit tricky. Dagre-d3 which is responsible for the layout does have support for weights fpr the relations between the nodes, perhaps that could be utilized somehow.

How do you propose the syntax should look like?

Btw: Meanwhile changing the order in the definition for changing the layout.

**Comment by chetanvsharma** [comment]
How should I change the order of the definition to get it centered? I've tried mutating the order a few times and haven't seen any different result.

For the syntax, I could see a left/right/center justification, or an explicit pixel designated position for the center of the node, with the latter preferred for flexibility. This could be designated with:

`style A justification:left` or `style A left-position:400,right-position:500` 

What do you think?

**Comment by knsv** [comment]
This renders a different layout but this is perhaps not how you wanted to illustrate this:
```
graph TD
  D==>E
  C==>D
  D==>F
  E==>C
  F==>C
```

Anyways, I will tag this as a wanted enhancement and would be happy for help with it from someone.

**Comment by n1els** [comment]
Hi, I see this is an issue that has been open for quite some time, are there any developments on this question? I have a similar problem at hand now, I want to create a (basic) network diagram where I have for example 2 core routers A & B, and 2 distribution routers C & D. I want A & B to sit on the same height, and C & D below that.

graph LR
A-->B
C-->D

Works fine, both A & B and C & D are on equal heights. But when I add the diagonal and vertical connections ( A-->C, B-->D for vertical and A-->D,B-->C for diagonal ) the layout is not what I want it to be. I would like to have a square layout with the  diagonal lines forming an X shape between the nodes.

I think that this would be accomplished already if I could force nodes A & B to have a row height of 1 and C & D to be on height 2, but I cannot find anything in the docs relating to node position.

Please let me know if I missed something.

**Comment by tylerlong** [comment]
Flowchart layout is powered by https://github.com/dagrejs/dagre-d3
Anybody who wants to help please check how upstream project supports this feature.

**Comment by BHunter2889** [comment]
Just to stress, idk, priority or something, this is a serious/blocking limitation for the system diagram I'm trying to create. Basically I have a central point that calls two bigger services which have sub services that are also called by the central service, plus several smaller independent ones called by the central point. This ends up spreading the subservices out across the entire diagram when they should really be grouped together under their non-central node parent service. Dagre seems to possibly have some features for this, but without writing my own solution in the mermaid code (I'm using the browser editor for now) this doesn't appear to be configureable through the mermaid config file.

**Comment by firedrow** [comment]
Wanted to give my support to @n1els, having a text-based diagramming system for network diagrams would be amazing.  But the auto-layout engines don't always work like we want, so we can add everything but the images are 10 times larger than we need.  I've been playing with Graphviz, but I just can't quite get things right.  I love the inline text for connections on Mermaid!

**Comment by 466023746** [comment]
hi , i found this https://466023746.github.io/face/

i have the same problem above, so i change my mind, use another way to solve this.

i use the color to distinguish each other, and without any loop.

**Comment by FrankKooij** [comment]
Similar to some layout issues experienced by other users, Mermaid code like this will result in a flowchart that gets wider and wider with the number of nodes:

````
```mermaid
graph TB
    A((START))-->B
    B(Condition1?)-->|yes|C
    C(Condition2?)-->|yes|D
    D(Condition3?)-->|yes|E
    E(Condition4?)-->|yes|X
    X[ConclusionA]-->Z((DONE))
    Y[ConclusionB]-->Z
    B-->|no|Y
    C-->|no|Y
    D-->|no|Y
    E-->|no|Y
```
````

Mermaid will output this flowchart:

![mermaid](https://user-images.githubusercontent.com/11964893/51325179-a182ba00-1a6c-11e9-9b39-3e048d546660.png)

What I would like to see, however, is something like this:

![requested](https://user-images.githubusercontent.com/11964893/51325211-afd0d600-1a6c-11e9-980d-06194d7ac6c8.png)

Any suggestions on how to do this, would be most welcome.

**Comment by vidur149** [comment]
I used subgraphs to solve this
graph TD
linkStyle default interpolate basis
subgraph 
A[gunung]-->B[NOUN]
C[Krakatau]--> D[NOUN]
E[Yang]-->F[PRON]
G[Pernah]-->H[ADV]
I[meletus] --> J[VERB]
K[mulai]-->L[VERB]
M[terbatuk-batuk] --> N[VERB]
end
subgraph 
  B --> O[FN]
  D --> O
  F --> O
  J --> O
  L --> P[FV]
  N --> P
end
subgraph 
  O --> Q[Subject]
  P --> R[Predicate]
end
subgraph 
 Q-->S[clause]
 R-->S
end

**Comment by dskarbek** [comment]
This whole area is obviously a pain point, but tricky to say what a proper solution should even look like.  Some of the examples people post above (like n1els) are probably solved well with sub-graphs to ensure that certain nodes stay grouped.  Some seem like minor complaints about the exact way to draw the graph (FrankKooij) but it seems like at that point you should just be using a hand-drawn system.  Part of the point is that the diagrams are auto-generated, right?  If you want to specify absolute pixel coordinates, you aren't really auto-generating the diagram, you're just coding it in text and that seems like a different use-case to me.  Perhaps PDF is what you are really looking for?

There's also a divide, I think, between people who drawing static graphs, like where you are hand-writing the mermaid code for some documentation; and people who are dynamically generating graphs.  For example, I'm using mermaid to render a graphical view of a user-created flow chart on a website.  In this case I'm dynamically generating the mermaid code from user content and don't know a priori what the set of nodes or their relationships are.  Where-as with the static case you do and could potentially specify some alignments.  These two cases possibly need different tools.

To my point earlier about auto-generating, I think you have to accept some non-determinism in the generated graph, but I have also seen some weird behavior in a large chart where two nodes end up far apart even though the one node is not connected to anything else except the other node.  So, there's a long path between them and a lot of empty space in the diagram where they could have been closer together without changing any of the rest of the diagram.  Clearly the graphing algorithm is not optimizing on short connectors.  This seems like something that would fit in the language scheme: have a way of indicating layout optimization priorities.  Like, "I want nodes to show up in the order that I specify them", "I want to minimize average connector length", "I want to minimize connector intersections", or maybe "i want nodes to be orthogonally aligned".  Being able to specify a layout preference like this (or even an ordered list of preferences) would, I think, address a lot of the largest problems that people are calling out here.

The other thing I would love to have, and really is needed when the graph is dynamically created, is some way for the end user (viewer) to drag the boxes around.  This allows them to re-arrange things as needed for the semantics of the graph (that only they understand), or just to help them focus on one part of the graph versus another at any given time.

**Comment by dskarbek** [comment]
BTW, here's a sample of the sort of graph I'm working with (all text has been removed).  Note that the first node (in green) is no where near the top of the chart, even though it is declared first.  Also note the yellow nodes which only connect to one other node are often far from their one connection even though there is empty space they could be in closer to their connection.
![graph](https://user-images.githubusercontent.com/3661983/57889531-e2f05f80-77e9-11e9-8e63-379fba11e655.jpg)
