### ISSUE TITLE
circle and ellipse cannot change color by classDef

### ISSUE THREAD

**Issue by ygtzf** [knsv/mermaid#271]
When I use mermaidAPI and mermaid.css, graph definiton like below:
graph LR;
    A((start))-->B(step1);
    B-->C[step2];
    C-->D{step3};
    D-->E[end];
    classDef green fill:#9f6,stroke:#333,stroke-width:1px;
    class A,B,C,D,E green;

```
But, the result is A node and D node is not green;
Please help me! Thanks!
```

**Comment by knsv** [comment]
Thanks for raising this issue. Will take a look

**Comment by knsv** [comment]
Found the issue and added those elements as well. The fix will be included in the next release.

**Comment by ygtzf** [comment]
Thanks very much.

**Comment by manor** [comment]
FWIW, this was also an issue for the nodes with the asymmetric shape, if this was not also fixed I can open the observation as a separate issue:

![asymmetric shape does not take classDef color](https://cloud.githubusercontent.com/assets/596326/12023761/bb123c2e-ad6a-11e5-9b25-cee1715def43.png)

```html
<script src="https://cdn.rawgit.com/knsv/mermaid/0.5.6/dist/mermaid.min.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/knsv/mermaid/0.5.6/dist/mermaid.css">
<script>mermaid.initialize({startOnLoad:true});</script>
<div class="mermaid">
graph TD;
    A-->B(B)
    A-->C>C]
    B-->D((D))
    C-->D
classDef eco fill:green;
class A,B,C,D eco
</div>
```

**Comment by vnijs** [comment]
It seems circles are not colored (see @manor 's example above). The same fix implemented for ellipse seems to work fine for circles as well.

+ className + '>circle, .'

![screen shot 2016-02-03 at 6 57 15 pm](https://cloud.githubusercontent.com/assets/2998956/12804354/787fc99e-caa7-11e5-92aa-87c5cd774142.png)

**Comment by tylerlong** [comment]
All fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFI7CkEoKHN0YXJ0KSktLT5CKHN0ZXAxKTsKQi0tPkNbc3RlcDJdOwpDLS0-RHtzdGVwM307CkQtLT5FW2VuZF07CmNsYXNzRGVmIGdyZWVuIGZpbGw6IzlmNixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MXB4OwpjbGFzcyBBLEIsQyxELEUgZ3JlZW47

**Comment by jsteave** [comment]
having the same issue.
