### ISSUE TITLE
Can we include customized shapes ?

### ISSUE THREAD

**Issue by jenilfuria** [knsv/mermaid#274]
Existing shapes are like square, rectangle, rhombus, circle etc....so i want to include my own customized shape.. for eg i want to include cloud shape or egg shape..

...is it possible ?
If yes then how can i integrate this .. ?

**Comment by knsv** [comment]
It should be possible as dagre-d3 allows custom shapes.

Perhaps a special function part of the initialize call that defines a shape and ties it to a key. Syntax wise it  would be easiest to tag the shapes with the custom shape in special statment in a way similar to the class definition:
 ```
customShape nodeId1,nodeId2 shapeName;
```
That breaks the concepr of the shape in the synaxt of the diagram though so open for better ideas.

Btw. Ovals are available with the following syntax:
```
graph TD
A(-this is an ellipse-)-->B
```
(This ia quite new and has not made its way into the editor or docs yet.)

**Comment by yzx226** [comment]
[An example that shows how to create and use user-defined shapes and arrows.](http://cpettitt.github.io/project/dagre-d3/latest/demo/user-defined.html)

**Comment by nickm4062** [comment]
@knsv I see the demo from @yzx226 has any of this made it in to the DSL yet?

**Comment by knsv** [comment]
Yes it is possible. This is for instance how the odd shape was implemented.

Which shape/shapes is it and how should the syntax be expanded?

Lets break this out to tasks that someone can put their teeth in!

**Comment by weralabaj** [comment]
We'd find the "database" shape very useful in our documentation.

<img width="139" alt="capture" src="https://cloud.githubusercontent.com/assets/7335079/20427199/0577deea-ad83-11e6-82a5-3b82c39e3370.PNG">

With little help, I'd be ready to take a stab at implementing it.

**Comment by knsv** [comment]
Please take a stab at it! How can I assist you?





On Fri, Nov 18, 2016 at 11:35 AM +0100, "Weronika Łabaj" <notifications@github.com> wrote:












We'd find the "database" shape very useful in our documentation.







With little help, I'd be ready to take a stab at implementing it.

**Comment by indusbull** [comment]
@weralabaj were you able to get custom shape to work? I am looking for something similar.

**Comment by nachiket** [comment]
I’m also curious — want to know if a trapezium shape is available already or needs to be added as a custom shape.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

**Comment by cs-prewittridge** [comment]
Is there documentation on this somewhere? I am building out a UML model but need "circle-cross" shapes for the "arrowheads".

**Comment by priyasingh199885** [comment]
> Is there documentation on this somewhere? I am building out a UML model but need "circle-cross" shapes for the "arrowheads".
https://github.com/mermaid-js/mermaid/issues/1500 -- this shows a blank page, any other source for custom shapes of nodes in mermaid
