### ISSUE TITLE
Mermaid + LightPaper = ❤️

### ISSUE THREAD

**Issue by ashokgelal** [knsv/mermaid#280]
We just added a new feature in [LightPaper 1.2](http://lightpaper.42squares.in?ref=mermaid) that makes it easy to add and edit Mermaid diagrams in your documents. We received a number of requests from our users [to support this awesome library](https://medium.com/hacker-daily/empowering-yours-users-so-that-they-can-fish-fbf5abb5c22b#.c9l28swsh) and worked on a way to make it easy to support it.

We've written a nice document on how to integrate Mermaid [here on GitHub](https://github.com/42Squares/LightPaper/blob/master/doc/Adding%20Mermaid%20Diagrams.md). We just wanted to let the Mermaid community know about this.

We'd really appreciate if you can add a link to LightPaper and/or to the documentation mentioned above in Mermaid's README file. Or we can also send a PR but before we do so we wanted to ask first here. We tried to find a direct way to contact @knsv but couldn't hence this ticket. Please feel free to close it.

Also, we're offering a 25% discount to all awesome Mermaid users for next few days using coupon code: **MERMAID_25**. Thanks!

**Comment by knsv** [comment]
Sounds cool! Will add links. Glad you like mermaid.
