### ISSUE TITLE
Mermaid does not work in Chrome 48

### ISSUE THREAD

**Issue by kohenkatz** [knsv/mermaid#281]
In Chrome 48, I get the following error when building Mermaid diagrams:

```
Uncaught TypeError: elem.getTransformToElement is not a function
```

Here are the [discussion](https://lists.w3.org/Archives/Public/www-svg/2015Aug/att-0009/SVGWG-F2F-minutes-20150824.html#item02) and [Chrome Change Report](https://www.chromestatus.com/feature/5736166087196672).

This appears to come from the dagre-d3 dependency - see [their issue](https://github.com/cpettitt/dagre-d3/issues/202).

It doesn't seem that dagre-d3 has released a fix yet, but I just wanted to open this so that Mermaid updates to the new dagre-js ASAP.

Thanks!

**Comment by knsv** [comment]
OK, thanks!

**Comment by FranPregernik** [comment]
I got bitten by this today :(

Seems dagre fixed their issue in https://github.com/aequologica/dagr/commit/9b9b050aac02a1440be17cf009dff1afcfeff824

**Comment by knsv** [comment]
Me to. Adding a polyfill...

**Comment by tylerlong** [comment]
Let's close it since Chrome 48 is pretty old.
