### ISSUE TITLE
Path seems to need a stroke CSS

### ISSUE THREAD

**Issue by jrgleason** [knsv/mermaid#282]
I have set up a simple plunker [here](http://plnkr.co/edit/OoqBAZ4XAb1NS5e5XyDo?p=preview)

As you can see the path does not have a stroke so it is invisible. I will try to look at creating a pull request but I wanted this here for tracking.

**Comment by knsv** [comment]
Thx, will appreviate a pull request,

**Comment by tylerlong** [comment]
Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post the link back here?

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
