### ISSUE TITLE
"No such file or directory" trying to run mermaid 0.5.7 on OS X

### ISSUE THREAD

**Issue by hairyhenderson** [knsv/mermaid#284]
```console
$ npm install -g mermaid
...
$ mermaid
env: node\r: No such file or directory
```

This is happening because the `mermaid` script is DOS-formatted (i.e. has `\r\n`/CRLF line-endings).

A simple fix to make sure this never happens again is to use a `.gitattributes` file like:

```
*.js text eol=lf
```

But the current version on npmjs.org (0.5.7) will still be broken.

A workaround could be to use `dos2unix` to fix the `mermaid` script.

**Comment by knsv** [comment]
Thx
Will release a 0.5.8 then

**Comment by knsv** [comment]
@hairyhenderson, I hope the 0.5.8 resoved your issue!

**Comment by hairyhenderson** [comment]
@knsv - Thanks! 0.5.8 fixed it :)
