### ISSUE TITLE
Live editor is broken

### ISSUE THREAD

**Issue by vasco3** [knsv/mermaid#285]
knsv.github.io/mermaid/live_editor/ is broken for **graph TD**
it reports 

> Uncaught TypeError: elem.getTransformToElement is not a function

Using Chrome v48 for OSX

**Comment by knsv** [comment]
Thanks, it needs to to be updated to v 0.5.8.

**Comment by knsv** [comment]
It should work now. Please close this issue if it works for you.

**Comment by vasco3** [comment]
Works, thanks a lot @knsv
