### ISSUE TITLE
How do I force subgraphs to be top-down

### ISSUE THREAD

**Issue by mingfang** [knsv/mermaid#287]
If I have this graph

```
graph TD
subgraph Backend
B
C
D
end

subgraph Front
A
end
```

If I link A-->B then it looks right.
http://knsv.github.io/mermaid/live_editor/#/view/Z3JhcGggVEQKc3ViZ3JhcGggQmFja2VuZApCCkMKRAplbmQKCnN1YmdyYXBoIEZyb250CkEKZW5kCgpBLS0-Qg

However if I also link C-->D then subgraphs are no longer top down.
http://knsv.github.io/mermaid/live_editor/#/view/Z3JhcGggVEQKc3ViZ3JhcGggQmFja2VuZApCCkMKRAplbmQKCnN1YmdyYXBoIEZyb250CkEKZW5kCgpBLS0-QgpDLS0-RA

If there any way to keep the subgraph top down?

**Comment by knsv** [comment]
I am afraid that Mermaid is not very expressive this way. You can play with different direction for instance RL but then the graphs in the subgraphs will also change direction.

**Comment by mingfang** [comment]
Thanks for reviewing this issue.
I've read about people hacking this in different ways
http://stackoverflow.com/questions/7777722/top-down-subragpraphs-left-right-inside-subgraphs
e.g. create invisible nodes and links to force the top down layout.

Perhaps a less "hacky" way would be to add links to subgraphs.
So in my example I can add
```Frontend-->Backend```
And this link would cause layout to follow the graph direction, e.g. TD.

**Comment by papoola** [comment]
+1

**Comment by vikram-rawat** [comment]
Can we anyhow build two different mermaid plots and merge them as one.

Like one mermaid diagram connecting to another and so on... That could solve the problem temporarily. And also it will open up a new dimension entirely.

This will solve the problem of subgraphs temporarily. But this is a must have feature because without it  Big and complex graphs can not be explained.

**Comment by tylerlong** [comment]
I believe the diagram layout is powered by [dagre-d3](https://github.com/cpettitt/dagre-d3) and [dagre](https://github.com/cpettitt/dagre). We might be able to find the answer in the upstream projects.

**Comment by lukewis** [comment]
@mingfang to clarify, linking subgraphs is not currently supported, correct?  You are suggesting this as an enhancement?

**Comment by mingfang** [comment]
I'm don't want to link subgraphs.
If you look at my example above, it's about linking nodes across subgraphs.
I think this is a bug and not an enhancement is my first example works and the second doesn't.

**Comment by lukewis** [comment]
@mingfang Sorry, I should have been more clear.  I was trying to interpret https://github.com/knsv/mermaid/issues/287#issuecomment-178153360 where you said

> Perhaps a less "hacky" way would be to add links to subgraphs.
So in my example I can add
Frontend-->Backend

I wasn't sure if this was a solution that worked for you, or a possible "enhancement/workaround" that you were suggesting **should** be supported.  When I tried linking subgraphs, the chart wouldn't render at all, so I wasn't sure if that was a currently supported scenario.

I also don't want to link subgraphs, but I haven't yet found an acceptable workaround.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

**Comment by lazarillo** [comment]
So if I write another comment, can I help to keep it alive to show that the community is interested?

My issue is more broad... I would like to be able to set *particular* subgraphs or links in an order.  My flow is fairly large, so I would like for it to, for instance, go left-right, then top-bottom, similar to how we read text from a book (but ideally snaking back and forth).

**Comment by michucz** [comment]
I would also like to keep this issue alive.
If have a couple of nodes that simply follow one another, I would like to be able to change direction, so I can start LR, than change to TB for one node, and then to RL.

**Comment by jucor** [comment]
@michucz @lazarillo That might be followed in issue #1265.

**Comment by EinfachFabi** [comment]
Hello

**Comment by jakubLangr** [comment]
Any update on this?

**Comment by jakubLangr** [comment]
Hi @IOrlandoni can we re-open I once again found many months later this thread haha.

**Comment by Ryder17z** [comment]
i also want better control over this

**Comment by mrsolarius** [comment]
It's a use case that I need maybe reopen this issue ?

**Comment by EuanMason** [comment]
This may help some people: [https://mermaid.js.org/syntax/flowchart.html#direction-in-subgraphs](https://mermaid.js.org/syntax/flowchart.html#direction-in-subgraphs)

> ### Direction in subgraphs
> With the graphtype flowcharts you can use the direction statement to set the direction which the subgraph will render like in this example.
```md
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2
```
![image](https://github.com/user-attachments/assets/ea2f239d-aa6b-4047-a5f0-3ba096482e06)

>   
> ### Limitation
> If any of a subgraph's nodes are linked to the outside, subgraph direction will be ignored. Instead the subgraph will inherit the direction of the parent graph
```md
flowchart LR
    subgraph subgraph1
        direction TB
        top1[top] --> bottom1[bottom]
    end
    subgraph subgraph2
        direction TB
        top2[top] --> bottom2[bottom]
    end
    %% ^ These subgraphs are identical, except for the links to them:

    %% Link *to* subgraph1: subgraph1 direction is maintained
    outside --> subgraph1
    %% Link *within* subgraph2:
    %% subgraph2 inherits the direction of the top-level graph (LR)
    outside ---> top2
```
> 
![image](https://github.com/user-attachments/assets/4d410428-fece-45dd-af64-d7d25bddd2da)
