### ISSUE TITLE
CSS clash

### ISSUE THREAD

**Issue by justinhunt** [knsv/mermaid#292]
I am using Mermaid with Moodle. On the Moodle course and top pages it creates and styles lists of items via a css class called "section." However Mermaid also attempts to style a css class called "section." The result is that the entire course page, or some parts of the front page are rendered with opacity 0.2 and basically become invisible.

Is it possible to be more specific when applying the mermaid CSS styles or prefix them with a mermaid identifier e.g "mermaid_section?"

![2016-02-07_17-28-35](https://cloud.githubusercontent.com/assets/1393905/12871501/b8c5f56a-cdc1-11e5-9851-35d09559458d.png)

**Comment by knsv** [comment]
Thanks for the feedback. I will take a look.

**Comment by crodriguez1a** [comment]
@knsv I'm also experience this. Let me know if you'd like me to address it.

**Comment by knsv** [comment]
@crodriguez1a You are very welcome to take a look. It would be much appreciated.

**Comment by crodriguez1a** [comment]
@knsv Sure. Not a problem. Assign.

**Comment by sclarson** [comment]
https://github.com/knsv/mermaid/pull/577 should resolve this.

**Comment by tylerlong** [comment]
It has been fixed.
