### ISSUE TITLE
Theme for dark background

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#301]
The default theme and the forest theme don't look good on a dark background web page (such as black background). Some elements are not very visible.

It is better if we can provide a new theme: `mermaid.dark.css`

**Comment by knsv** [comment]
Good idea! Lets do it.

**Comment by crodriguez1a** [comment]
:+1: I'd like to take this on if it's still open.

**Comment by knsv** [comment]
Great! 

It is yours.

**Comment by d4nyll** [comment]
This should be closed as it is already implemented with #317
