### ISSUE TITLE
Integration with remark.js - tutorial added

### ISSUE THREAD

**Issue by Hunter-Github** [knsv/mermaid#302]
Though you'd need a heads up. Your library is doing wonders inside remark.js presentations. The recipe is here: https://github.com/gnab/remark/wiki/Adding-graphs-via-Mermaid

**Comment by Hunter-Github** [comment]
I've been also trying to have multiple graphs/sequence diagrams per slideshow - so far no encouraging results (I suspect id autonaming issues).

**Comment by utdrmac** [comment]
See issues reported in #360. Do you experience similar?
