### ISSUE TITLE
Fix phantomjs2 compatibility

### ISSUE THREAD

**Issue by wingedfox** [knsv/mermaid#304]
PhantomJS2 has no `phantom.args` anymore, `System.args` should be used.

http://phantomjs.org/api/phantom/property/args.html

**Comment by knsv** [comment]
Thanks, will take a look.

**Comment by agladysh** [comment]
+1

**Comment by ssbarnea** [comment]
I think that this become a critical issue. npm complains about installing an ancient version of phantomjs and even gives an warning regarding package name change:
```
npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```
If you happen to have a newer version installed the problem becomes even bigger.

**Comment by ssbarnea** [comment]
Here is something that worked for me, but that is clearly not the desired UX
```
npm uninstall -g --force phantomjs
npm uninstall -g --force phantomjs-prebuild
npm install -g phantomjs@1.9.0-0
```
Not to say that it did take ages to build, because obviously we were not able to benefit from the prebuild versions.

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
