### ISSUE TITLE
Enhancement Request: Allow render to ascii on command line for simple graphs

### ISSUE THREAD

**Issue by paul42** [knsv/mermaid#305]
I love mermaid js, but I would love to be able to make something in ascii for easier copy/pasting to slack than a whole .svg file, especially if we could make a .mmd file and then use the command line functionality - but I don't know where i'd start for a PR - I'd be willing to help, but not certain where to begin research.

Thoughts?

**Comment by knsv** [comment]
I think it would be quite a big job. Lets ponder on this one a a bit.

Quick thoughts:

You can get coordinates from dagre. So a switch to dagre from dagre d3 would make it possible to get the layout. Then some new nifty rendering would be required.

Sequence diagrams and  charts would be more difficult.

**Comment by adrianhopebailie** [comment]
Why not write a Slackbot that replaces pasted mermaidjs input with a rendered SVG?

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

**Comment by basaran** [comment]
Hi, this would be great addition. It would make code commenting a lot more sensible. There are some perl programs written in the past decade that does this to a level, but I couldn't find any markdown integration. Someone also put an online version:

https://dot-to-ascii.ggerganov.com/

**Comment by sebolio** [comment]
any news? this is needed

**Comment by ShaddyDC** [comment]
There is a lot more discussion and alternatives in https://github.com/mermaidjs/mermaid-live-editor/issues/36
