### ISSUE TITLE
Can not get click event to fire.

### ISSUE THREAD

**Issue by eddiex** [knsv/mermaid#306]
I am having a hard time getting any click events to fire in the below simple example. Can you please have a look and advise what I am missing?

The console (chrome) is showing empty bind functions...
![screenshot_021816_102951_pm](https://cloud.githubusercontent.com/assets/1479139/13165806/2563d69e-d68f-11e5-99c1-f4fcd6154714.jpg)

The code I am running is here... (I renamed html to txt for upload)
[mermaid4.txt](https://github.com/knsv/mermaid/files/137377/mermaid4.txt)

Sincere Thanks,
Ed

**Comment by knsv** [comment]
Hello Ed!

Your example was pretty much ok but for one small omission. You need to pass the element to the bind events function. This helps when you set events for several diagrams.

~~~
bindEvents($("#div-id1")[0]);
~~~

I hope this helps.

**Comment by eddiex** [comment]
Great. Thank you very much.

**Comment by arifA9** [comment]
Thanks Alot, this really help me

**Comment by a1anw2** [comment]
It helped me a lot too ... which does highlight that many of the examples in the documentation is wrong or outdated.   Love this project.

**Comment by a1anw2** [comment]
One bug I have noticed is that the ID for a node cannot start with a numeric if you wish the click event to fire.

```
graph TB
ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1 --> 620794c281f0501b17cec8fc1e417869dcd04bce
ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1[Ocean - Wikipedia]
620794c281f0501b17cec8fc1e417869dcd04bce[New Tab]
click ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1 "https://en.m.wikipedia.org/wiki/Ocean"
click 620794c281f0501b17cec8fc1e417869dcd04bce "https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8"
```

where as, if you add a letter at the start, then this works:

```
graph TB
ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1 --> a620794c281f0501b17cec8fc1e417869dcd04bce
ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1[Ocean - Wikipedia]
a620794c281f0501b17cec8fc1e417869dcd04bce[New Tab]
click ab92aedcf2c02100b1a1690bc8aea5a1c876da3f1 "https://en.m.wikipedia.org/wiki/Ocean"
click a620794c281f0501b17cec8fc1e417869dcd04bce "https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8"
```

**Comment by tylerlong** [comment]
@a1anw2 I have confirmed the but you reported and I've fixed it.
