### ISSUE TITLE
css conflicts with boostrap's css

### ISSUE THREAD

**Issue by filomat** [knsv/mermaid#308]
I am trying to draw a flowchart and using `mermaid.forest.css` stylesheet. Flowcharts look beautiful without `bootstrap.css`:
![screenshot_6](https://cloud.githubusercontent.com/assets/11816655/13338362/f0c8270c-dc31-11e5-9d7c-91c065b9e8ca.png)

But if I include stylesheet `/bootstrap/css/bootstrap.css` text looks small and ugly, lables and edges don't show html tags:
![screenshot_7](https://cloud.githubusercontent.com/assets/11816655/13338379/131c95b8-dc32-11e5-8c3f-fc52c749c1d7.png)

Can I use mermaid along with `bootstrap 3`?

**Comment by knsv** [comment]
The only styling applied by mermaid for lables are the color. SO other styles applied by bootstrap would then kick in.

If you want other styling for the labels you can apply more specific styles for the label via css:
```
.mermaid .label {
   color:#333
  /* Other styling here */
}
``` 

I hope this helps.

**Comment by utdrmac** [comment]
bootstrap overrides/sets A LOT of defaults!

**Comment by tylerlong** [comment]
Latest version of mermaid scope all of its own CSS in chart ID. If you can still reproduce it, create a new issue. Thanks.
