### ISSUE TITLE
Styling connector lines

### ISSUE THREAD

**Issue by rorysmyth** [knsv/mermaid#31]
Firstly, great work. I've been tinkering with it the last day and I'm gonna try to build a UI on top of it to make it even easier to use. Especially at a larger scale.

One suggestion i'd make is the styling of lines

How about something like this?

A--(linkStyle)>B;

then then defining the style later
linkStyle stroke:#ff3, stroke-width:4px;

**Comment by velvia** [comment]
Something like this would be great:

`linkStyle default stroke:#ff3;`

(be able to specify a default link style)

**Comment by knsv** [comment]
Yes that makes sense. I wIll give it a go!

**Comment by knsv** [comment]
I am going through issues and am closing this one as this is implemented and released (pre 0.5.0).
Example of (part of web.html) in the test folder:
```
graph LR;
        A[Now with default style on links]--v-->B{a = '1,2'}
        B-->|v|C[v]
        B-- ... default style on links -->Z[My default thing this]
        C-->D{condition};

        linkStyle 0 stroke-width:2px,fill:none,stroke:blue;
        linkStyle default stroke-width:2px,fill:none,stroke:red;
```

**Comment by vikaskedia** [comment]
In the above example the stroke:red does not see to work. I still get black links.

See:

http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtOb3cgd2l0aCBkZWZhdWx0IHN0eWxlIG9uIGxpbmtzXS0tdi0tPkJ7YSA9ICcxLDInfQogICAgICAgIEItLT58dnxDW3ZdCiAgICAgICAgQi0tIC4uLiBkZWZhdWx0IHN0eWxlIG9uIGxpbmtzIC0tPlpbTXkgZGVmYXVsdCB0aGluZyB0aGlzXQogICAgICAgIEMtLT5Ee2NvbmRpdGlvbn07CgogICAgICAgIGxpbmtTdHlsZSAwIHN0cm9rZS13aWR0aDoycHgsZmlsbDpub25lLHN0cm9rZTpibHVlOwogICAgICAgIGxpbmtTdHlsZSBkZWZhdWx0IHN0cm9rZS13aWR0aDoycHgsZmlsbDpub25lLHN0cm9rZTpyZWQ7

**Comment by DubZyy** [comment]
Hi,
I hope I won't be bullied for my request, but am I the only person who isn't able to find this documentated or understand, how exactly this is working?
Could this example be added to the flowchart style documentation and/or give another example in this issue here? I would really appreciate that!
Thank you in advance!
BR

**Comment by seren** [comment]
The documentation now mentions it here: https://mermaid.js.org/syntax/flowchart.html#styling-links

Unfortunately, there's no way to name link-styles; you have to use the index order. From the docs:
>  As links have no ids in the same way as nodes, some other way of deciding what style the links should be attached to is required. Instead of ids, the order number of when the link was defined in the graph is used, or use default to apply to all links.

Here's an example:
```
flowchart LR
    A0-- link with index 0 -->B0;
    A1-->|link1|B1;
    A2-->|link2|B2;
    A3-->|link3|B3;
    A4-->|link4, uses default style|B4;
  

    linkStyle 0 stroke:blue;
    linkStyle 1 stroke:green,stroke-dasharray:9;
    linkStyle 2,3 stroke-width:10px,fill:none,stroke:grey;

    linkStyle default stroke-width:10px,fill:none,stroke:red;
```

```mermaid
flowchart LR
    A0-- link with index 0 -->B0;
    A1-->|link1|B1;
    A2-->|link2|B2;
    A3-->|link3|B3;
    A4-->|link4, uses default style|B4;
  
    linkStyle 0 stroke:blue;
    linkStyle 1 stroke:green,stroke-dasharray:9;
    linkStyle 2,3 stroke-width:10px,fill:none,stroke:grey;

    linkStyle default stroke-width:10px,fill:none,stroke:red;
```
