### ISSUE TITLE
Update graph

### ISSUE THREAD

**Issue by LeonardoRamos** [knsv/mermaid#311]
Hi, I have a question, I have a graph in my page that is loaded as soon the page is fully loaded. I have some menus that allow the user to add nodes and remove nodes, manipulating the graph definition that is inside a textarea, but I'm having difficulties trying to "redraw" the graph. I tried calling "init" again, I tried calling the API, but I have no success in both options. So my question is, how can I re-render the graph?

**Comment by LeonardoRamos** [comment]
Actually, it works in Firefox, it's not re-rendering the graph only in chrome (I'm using chrome 48) and I tested mermaid versions 5.7, 5.6 and 4.0, none of them worked, only a very old version worked fine (The one used in the editor folder).

**Comment by knsv** [comment]
Are you using the API for this rendering? It sounds like you should use the render function for this.

Se example in the docs:
http://knsv.github.io/mermaid/#api-usage

I hope that helps.

**Comment by radmilabord** [comment]
Render function works only ones. Did anyone found solution for this? I'm facing same problem.

**Comment by knsv** [comment]
Looking at this one.

**Comment by radmilabord** [comment]
I solved it by removing div with graph, adding it back, setting text, calling init method.
Same approach is done in "try it" demo.
However if rerender function could work, it would be great.

**Comment by knsv** [comment]
OK. Will continue with it anyway then.

**Comment by roidayan** [comment]
i know its old but wanted to say i do not delete the entire div but delete the attribute set to "data-processed". after that calling init on it again seems to work.

**Comment by radmilabord** [comment]
Thanks! That sounds like a less intrusive approach.

**Comment by dianaeneida** [comment]
roidayan, ¿could you expose the complete solution here?, please

**Comment by roidayan** [comment]
my html is:
```
<div id="mermaid"></div>
```

and in js I do this on init and each time my data in node.data.graph changes:
```
$('#mermaid').html(node.data.graph).removeAttr('data-processed');
mermaid.init(undefined, $("#mermaid"));
```

**Comment by tylerlong** [comment]
@roidayan 's solution works and I use it too.

**Comment by WeiKaiTang** [comment]
> my html is:
> 
> ```
> <div id="mermaid"></div>
> ```
> 
> and in js I do this on init and each time my data in node.data.graph changes:
> 
> ```
> $('#mermaid').html(node.data.graph).removeAttr('data-processed');
> mermaid.init(undefined, $("#mermaid"));
> ```

You solved my problem.
In addition, this method can work in mermaid 9.1.0, but not work in mermaid 9.4.3.

**Comment by eduo** [comment]
> > my html is:
> > ```
> > <div id="mermaid"></div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in js I do this on init and each time my data in node.data.graph changes:
> > ```
> > $('#mermaid').html(node.data.graph).removeAttr('data-processed');
> > mermaid.init(undefined, $("#mermaid"));
> > ```
> 
> You solved my problem. In addition, this method can work in mermaid 9.1.0, but not work in mermaid 9.4.3.

Did you find a solution? It also doesn't seem to work in mermaid 10, to which I'm trying to migrate. I can't find if it's not explicitly covered in 10.

**Comment by hikari-He** [comment]
@eduo I didn't find solution, my solution is use mermaid 9.1.0. My front-end skills are limited so I don't quite understand the reasons that why mermaid 9.1.0 can work but other version can't.
