### ISSUE TITLE
Comment in subgraph

### ISSUE THREAD

**Issue by TonyHeflin** [knsv/mermaid#319]
i checked the open issues and see anything resembling this. Putting a comment in a subgraph causes rendering to fail.

Simple example I tested with on the live editor.

```
subgraph Approval Table
  tAp(Approvals)
  tAp --- fAP_ID[ID]
  tAp --- fAP_Name[Name]
  tAp --- fAP_Desc[Description]
 %% tAp --- fAP_UserId[User ID]
  tAp --- fAP_TaskId[Task ID]
  tAp --- fAP_TaskType[Task Type]
  tAp --- fAP_Status[Status]
  tAp --- fAP_Type[Approval Type]
end
```

Thanks

**Comment by tylerlong** [comment]
Can a subgraph exist without a graph?

Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post the link back here?

**Comment by TonyHeflin** [comment]
You can close this. I vaguely remember this and I believe the subgraph I submitted was one of many in a larger graph. I did a quick test and could not reproduce the problem and I don't have any of the original material.

Thanks
