### ISSUE TITLE
unsupported reserved words, lack of escaping for nodes

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#325]
I was looking for an alternative to graphviz but I realised quickly that mermaid has some serious limitations that are not documented at all.

```
graph LR
a-->default
```

This will not render, probably because of the `default` node name. I even tried to use double quotes or single ones but with no luck. Also it seems that the online editor gives only a generic "Invalid syntax" which is obviously not helpful at all. A more verbose message, maybe even one with a hyperlink to a documentation would be really desired. Thank you.

**Comment by knsv** [comment]
I am sorry you had problems with your diagram. For me this worked well:

```
graph LR
a-->b["default"]
```

I can see that syntax error might not be so helpful. Good ide with the link to the docs.

**Comment by dzhus** [comment]
> b["default"]

This doesn't work in sequence diagrams: http://knsv.github.io/mermaid/live_editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBLT4-IEJbImItc2VydmljZSJdOiBUZXN0

**Comment by joriws** [comment]
This is not just node name "default", also affects "go_default". The keything is *WHEN* this will be fixed?

**Comment by tylerlong** [comment]
I confirm that it is still an issue: https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBLT4+IEJbImItc2VydmljZSJdOiBUZXN0/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgouLi5pYWdyYW0gICAgQS0-PiBCWyJiLXNlcnZpY2UiXTogVGVzdAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tXgpFeHBlY3RpbmcgJ05MJywgJ0FTJywgJywnLCAnU09MSURfT1BFTl9BUlJPVycsICdET1RURURfT1BFTl9BUlJPVycsICdTT0xJRF9BUlJPVycsICdET1RURURfQVJST1cnLCAnU09MSURfQ1JPU1MnLCAnRE9UVEVEX0NST1NTJywgJ1RYVCcsIGdvdCAnLSc

I will take a look when I have some time.
