### ISSUE TITLE
Include documentation for command line usage

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#326]
It seems that the current documentation does gives information only about how to install it but not on the based use case of rendering a basic graph and saving it as a file (really useful for automation purposes)

<img width="249" alt="screenshot 2016-03-20 11 24 12" src="https://cloud.githubusercontent.com/assets/102495/13904139/5058043a-ee8e-11e5-9a03-73ede9269fcc.png">

**Comment by knsv** [comment]
Great with feedback on the docs. As you write them you are not sure if anyone read the docs at all.

It is in the docs but in the mermaid CLI section:
http://knsv.github.io/mermaid/#configuration52

**Comment by jballe** [comment]
The link is not working for me, but there is nice documentation of the cli, I have successfully used that for automation too 
![image](https://cloud.githubusercontent.com/assets/1383049/14561376/24a16948-0316-11e6-917c-5fdbadd0041b.png)

**Comment by tylerlong** [comment]
Here then latest link: https://mermaidjs.github.io/mermaidCLI.html
