### ISSUE TITLE
You had errors in your syntax. Use --help for further information.

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#327]
The `You had errors in your syntax. Use --help for further information.` does not give any kind of feedback regarding what was wrong with the syntax. 

Enabling the `-v` does not help at all, nor does the recommended `--help` option.

**Comment by knsv** [comment]
The same root cause as in the editor I guess. I comes down to the feedback from the parse. Will think a bit on how this could be improved.

**Comment by StingyJack** [comment]
I get this when forgetting to double-dash long name options, like 
`-svg`
instead of 
`--svg`

**Comment by tylerlong** [comment]
Paste your code to https://mermaidjs.github.io/mermaid-live-editor/ and you can get real time information about syntax errors.
