### ISSUE TITLE
mermaid -v filename.mmd gives You must specify at least one source file.

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#328]
`mermaid -v filename.mmd` gives `You must specify at least one source file.` which is clearly against the documentation:

```
Usage: mermaid [options] <file>...
```

**Comment by knsv** [comment]
Thank this should be fixed. Any one up for it?

**Comment by tylerlong** [comment]
Ref: https://github.com/mermaidjs/mermaid.cli
