### ISSUE TITLE
npm install -g mermaid does not install phantomjs

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#329]
On OS X, if you do a `npm install -g mermaid`, it will install (0.5.8) but when you try to run it with an imput file you will get an error complaining about `Could not find phantomjs at the specified path.`

Please note that this error appears only if you give a file to process. If you do just `mermaid -v` it will return the version without the error.

**Comment by Jmuccigr** [comment]
Is it supposed to? I just used brew to install v. 1.98 of phatonjs.

**Comment by ssbarnea** [comment]
I tried the `npm install -g phantomjs@1.9.9` which seems to be a CPU killer even on i7/16GB/SSD! -- After 3h I decided to kill it! It will never finish.
<img width="659" alt="screenshot 2016-03-20 20 07 39" src="https://cloud.githubusercontent.com/assets/102495/13906802/9a150674-eed7-11e5-8977-c9431aff4459.png">

My impression was that the npm method was the official, multi-platform one.

I tried your approach too, but it fails too
```
$ brew install homebrew/versions/phantomjs198
==> Tapping homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 269, done.
remote: Compressing objects: 100% (251/251), done.
remote: Total 269 (delta 35), reused 74 (delta 18), pack-reused 0
Receiving objects: 100% (269/269), 309.45 KiB | 119.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
Checking connectivity... done.
Tapped 265 formulae (290 files, 1M)
==> Installing phantomjs198 from homebrew/versions
phantomjs198: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

**Comment by ssbarnea** [comment]
Is so hard to make it work with current versions of phantomjs? I had no problem installing the current versions, only the 1.9.x seems to be the problem.

**Comment by knsv** [comment]
I see no reason why an upgrade should be hard!

It does seem like you have som issue with your node installation though. I have never had problems with node 1.9. I personally use nvm to install node so that it is easy to upgrade to newer node versions:

https://github.com/creationix/nvm

This should be sone however.

**Comment by ssbarnea** [comment]
I should rename the bug: `npm install mermaid` fails as it fails to installed the required version of npm. This happens at least on mac with npm `3.6.0`.

**Comment by ssbarnea** [comment]
@Jmuccigr yes it is supposed to install, as any npm package, it can have dependencies, which are installed by npm whenever is needed.

**Comment by ssbarnea** [comment]
I am not able to replicate the same problem with version 6.0.0 so I am closing this ticket.
