### ISSUE TITLE
No Arrows rendered v0.5.8

### ISSUE THREAD

**Issue by mtompkins** [knsv/mermaid#330]
I've checked some of the previous `no arrow` issues before posting, however, they all seem to be resolved.
In trying to incorporate this terrific module, everything seems to render properly except no arrow heads. I've tried both Chrome (Version 49.0.2623.87) and Iceweasel (44.0.2). I've also tried the standard as well as the forest CSS files.

In visiting http://knsv.github.io/mermaid/live_editor/ arrows render properly

![screenshot from 2016-03-21 18-00-32](https://cloud.githubusercontent.com/assets/4105910/13935688/ffb9208e-ef8e-11e5-8021-94e38bc58050.png)

**Comment by knsv** [comment]
Hmm. Do you have some specific base tag settings maybe? I would be glad to help but would need some more information in order to give any insights.

**Comment by mtompkins** [comment]
Appreciate the response and offer to help.
The project that is trying to incorporate mermaid is phpMyFAQ: https://github.com/thorsten/phpMyFAQ/tree/2.9

I'll ask the main developer to tag in here to better answer questions more accurately.

**Comment by tylerlong** [comment]
Close it as lack of information for troubleshooting.

By the way, latest version is 7.1.0. We won't fix bugs for 0.5.8 any more.

Closing it.
