### ISSUE TITLE
shifted tooltips in chrome

### ISSUE THREAD

**Issue by filomat** [knsv/mermaid#332]
I am using a large graph (~15 nodes from root to the end). Everything fine but tooltips popup to the left, outside of the node.

![graph_01](https://cloud.githubusercontent.com/assets/11816655/13964221/bfad4498-f079-11e5-81b9-06b1c7791e36.jpg)

the more graph level the more distance between tooltip and the node.
Tooltips are working correct in firefox.

**Comment by knsv** [comment]
The position of the tooltip is calculated from the element.

```
            tooltipElem.html(el.attr('title'))
                .style('left', (rect.left+(rect.right-rect.left)/2) + 'px')
                .style('top', (rect.top-14+document.body.scrollTop) + 'px');
            el.classed('hover',true);
```

I wonder if these calculations are performed with the default font and the small difference betwen the default f ont and the one used is aggregating, becoming large with a large graph. That's where I would start testing.

I hope that helps.

**Comment by filomat** [comment]
Thanks for answer.

I tried to bind mousemove event for nodes and define event.clientX, but it didn't help :(

I found that error is occuring only when page is horizontally scrolled right.

**Comment by vnijs** [comment]
@ziyiwang's response to #542 seems to fix tooltip placement after zooming and scrolling. Perhaps this could also address your issue @filomat

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
