### ISSUE TITLE
Nodes in rows

### ISSUE THREAD

**Issue by eddiex** [knsv/mermaid#333]
Hi,
As you can see in the image I have a chart that is rendered very wide. Although I have added a zoom control to allow the page to be zoomed in/out, I'd prefer to have the entire chart render not so wide.

When I have many nodes coming from a single node, is there any way to get them to align such that after a certain amount, it will  go to a new vertical "row"? In other words to **stack them in groups** of (for example) 5 across?

![image](https://cloud.githubusercontent.com/assets/1479139/14045772/41c313ae-f273-11e5-9fc1-e885d03dbeb1.png)

Thank you,
Ed

**Comment by tylerlong** [comment]
flowchart layout is powered by https://github.com/dagrejs/dagre-d3. For those who want to help please check upstream project to confirm that it's doable.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
