### ISSUE TITLE
Display question: crossing lines

### ISSUE THREAD

**Issue by Jmuccigr** [knsv/mermaid#334]
Is there any way to get some kind of "bump out" when one line crosses another? For example, this code will get the B-E line crossing the F-D line:

```
graph TD;
    A-->B;
    A-->F; 
    A-->C; 
    B-->D;
    B-->E;
    C-->E; 
    F-->D;
```

I realize that if I re-order the lines, I can avoid the crossover (which was a surprise to me because I figured the drawing would be independent of order), but for complicated things, it's not always clear (to me) what will result in no crossed lines.
I'm thinking of something that looks like the semi-circular things on [this](https://en.wikipedia.org/wiki/File:CCC_Flowchart_samples_3-19-08.jpg):
![ccc_flowchart_samples_3-19-08](https://cloud.githubusercontent.com/assets/615115/14048754/9e1575f8-f286-11e5-9256-a3e0a6c9c638.jpg)

**Comment by joeblew99** [comment]
Have a look a this:
https://en.wikipedia.org/wiki/DRAKON

This is diagramming software and the KEY aspet is that lines never cross.
Its conceptually able to model anything, but in order for lines to never cross it forces a design pattern that is actually very smart.

Quote from author:
The main advantages of DRAKON are:
No line intersections. You will never find in DRAKON diagram two or more lines intersecting each other! Not seen in other diagramming systems! So you get clear algorithm and not a net like mess.
Silhouette structure. It allows to break one diagram into several logical parts. Not seen in other diagramming systems!
No slanting or curved lines. Only straight lines with right angles.
Icons are placed only on vertical lines.
Branching is done in a simple, visible and consistent way.

**Comment by Jmuccigr** [comment]
I'm thinking of other kinds of graphs (like [Harris matrices](https://en.wikipedia.org/wiki/Harris_matrix)) that often have crossing lines. For these, it seems useful to me to visually indicate the intersection.

**Comment by joeblew99** [comment]
Ok I reread that you prefer a bump out when the lines cross.

Calculating that is possible of course. I have seen it done for web diagram tools a few times. Would require a bit of googling to find the best algorithm..

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

**Comment by botteroxom** [comment]
would make more sense to add as new feature and add it to the project ...
My humble opinion

**Comment by maxnoe** [comment]
Please reconsider just closing this. This is a much needed visual aid for more complex diagrams!

**Comment by tarwich** [comment]
I think it was closed by an auto-closer. The PR was for fixing dependencies, but mentioned `#334`, which auto-closes said issue when the pr is merged.

<img width="648" alt="image" src="https://github.com/mermaid-js/mermaid/assets/334149/60a6ba73-a0e8-47bc-a68f-caaffa6e09b0">
