### ISSUE TITLE
Tabs & subgraphs cause rendering error

### ISSUE THREAD

**Issue by nayrangnu** [knsv/mermaid#336]
I spent a long time trying to figure out why my code was not rendering after I tried adding a subgraph. Eventually, I realized that using spaces instead of tabs makes it render. Perhaps something in the subgraph code?

**Comment by nienaber** [comment]
I had the same issue. 

```
graph TB
   subgraph One
      a1-->a2
   end
```

This will not compile for CLI either if there are tabs instead of spaces for the indentation. Using mermaid 6.0.0 and phantomJS 2.1.1

**Comment by tylerlong** [comment]
I confirm that it is an issue. Tabs doesn't work.

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKCXN1YmdyYXBoIE9uZQoJCWExLS0-YTIKCWVuZA

No syntax error but there is also no output chart.

**Comment by tylerlong** [comment]
It seems that this issue only happens with subgraph. There is no problem if no subgraph: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKCWExLS0-YTIK

**Comment by tylerlong** [comment]
Issue has been fixed: https://github.com/knsv/mermaid/commit/52d06050660ade81aeab1801aea34df975ac52bb

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKCXN1YmdyYXBoIE9uZQoJCWExLS0-YTIKCWVuZAo
