### ISSUE TITLE
npm test fails on osx being blocked at Can not load "PhantomJS", it is not registered!

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#337]
On current OS X 10.11, with XCode 7.3, and nvm it seems that we cannot run the tests.

```
nvm install 4.2
nvm use 4.1
npm test
```

The outcome can be read at https://gist.github.com/ssbarnea/649ab88ac9e691a28e4a

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
