### ISSUE TITLE
Question: lib/phantomscript.js - foreignObjects in SVG - related to #58

### ISSUE THREAD

**Issue by raghur** [knsv/mermaid#340]
So I've been playing around with writing a parser and adding a new diagram type. In my renderer, I added a `foreignObject` which got replaced to text/tspan. After a puzzling time, I found the following in `lib/phantomscript.js`

```
  // traverse the SVG, and replace all foreignObject elements
  // can be removed when https://github.com/knsv/mermaid/issues/58 is resolved
  allElements = traverse(oDOM)
  for (var i = 0, len = allElements.length; i < len; i++) {
    resolveForeignObjects(allElements[i])
  }
```
#58 is marked as resolved ... I commented out the call and my fo's are no longer being replaced and all seems good (cursorily though)

I don't fully understand the discussion - but wanted to ask that since the ticket is marked as resolved, then will this call to `resolveForeignObjects` can now be removed?

**Comment by knsv** [comment]
I svg markup you can insert non svg elements using a foreign object tag. Some labels in the flowcharts for instance can use this feature that simplifies text handling by using html.

That however can cause problems if you generate a svg file using the command line tool and try to open it in a svg editor. (That was the problem in issue 58)

**Comment by raghur** [comment]
I'm using foreign objects for the same purpose.. Creating labels that wrap text easily and so on. 

IMO, majority of the use case is svg being viewed in a browser... So could there be a switch for enabling disabling fo usage?

I see the 'pure' svg approach, but that makes styling and manipulation harder for the general case of viewing svg in browser

**Comment by tylerlong** [comment]
We no longer use phantomjs.
