### ISSUE TITLE
CLI: Invisible text, lines in SVG output

### ISSUE THREAD

**Issue by Billiam** [knsv/mermaid#341]
When converting a graph to SVG with the mermaid CLI tool, paths and text are added to the SVG output, but are not visible when viewing the output file in Chrome or Inkscape.

The invisible lines appear to be caused by a missing stroke color, but I can't tell what's happening with the text.

Output appears correctly in the [live editor](http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggVEQKICAgIHRlc3QtLT50ZXN0Mg), but the downloaded SVG appears to only be browser-friendly (I believe this is expected).
## Actual mermaid call

```
$ mermaid -s simple.mmd
```
## Graph input

```
graph TD
    test-->test2
```
## Test files

Input mmd file and output SVG and PNG files:
[simple.mmd.zip](https://github.com/knsv/mermaid/files/209030/simple.mmd.zip)
## PNG Output:

[simple mmd](https://cloud.githubusercontent.com/assets/242008/14363296/1d49b48c-fcc9-11e5-92b7-6993675393a6.png)
## Version info

```
$ phantomjs --version
1.9.8

$ mermaid --version
0.5.8
```

**Comment by buliaoyin** [comment]
I got the same issue with v0.5.8

**Comment by buliaoyin** [comment]
Seems like svg generated by CLI got a incorrect lowercase rule type '.edgepath' instead of '.edgePath'.
Seems the document.styleSheets in function util.cloneCssStyles() got lowercase rule types.

**Comment by Lance0312** [comment]
+1, I got `.edgepath` and `.edgelabel` instead of `.edgePath` and `.edgeLabel` in mermaid 6.0.0

**Comment by knsv** [comment]
Closed by release 7.0.0, please reopen if issues remain.

**Comment by Kochise** [comment]
d:\mermaid_test>npx mmdc -V
8.8.2-beta.8

Issue remains

```
stateDiagram-v2
[*] --> Still
Still --> [*]
Still --> Moving
Moving --> Still
Moving --> Crash
Crash --> [*] 
```
d:\mermaid_test>npx mmdc -i state.mmd -o state.svg

![state](https://user-images.githubusercontent.com/23077417/98928752-720f2e00-24da-11eb-9d41-164a2cc22f52.png)

However I got correct case, '.edgePath' and '.edgeLabel'

**Comment by Kochise** [comment]
Btw, if I export to pdf format, it is ok, but the picture doesn't fit the whole page, hence importing the pdf instead of the svg gets a bad layout.

**Comment by alexpovel** [comment]
Experienced the same issue opening the exported/downloaded SVG in InkScape. The browser (Firefox) renders it fine in a tab of its own. From that tab, I printed to PDF and opened that in InkScape, then saved as SVG after removing the cruft (select just the drawing, move away, select everything else remaining at the old location, delete, resize page to content, save as SVG).

**Comment by SudoCerb** [comment]
Can confirm that this issue persists, having exported an SVG from https://mermaid.live/edit today.
