### ISSUE TITLE
Smaller height of actor boxes

### ISSUE THREAD

**Issue by vision8tech** [knsv/mermaid#342]
Hello,

I am trying to make the actor's boxes smaller. I started setting the height on .actor class:
`.actor {
  stroke: none;
  fill: #E2ECFF;
  height: 32px;
}`

However, I could not find where to make the actor text to be centered within the box:

![2016-04-14_172408](https://cloud.githubusercontent.com/assets/14140226/14531376/c1cf69f6-0265-11e6-9c60-1933460ad224.png)

Setting `height: 32` in the `conf` object (ex: in mermaid-0.5.8.js, line 39147) did not make any difference.

Thank you!

**Comment by knsv** [comment]
Hello,

the height is managed by the rendering as it affects the sussequent coordinates in the graph.

The way to change it is by changing the conf, (as you mentioned).

This works for me:
```
    <script>
        mermaid.initialize({
                sequenceDiagram:{
                    mirrorActors:true,
                    height:35,
                    topPadding:125
                },
                logLevel:1

        });
```

Maybe the problem is how you initialize mermaid?

Sorry about the late reply and I hope this helps,
Knut

**Comment by visvadw** [comment]
Hi Knut,
Thanks for the feedback!
I'll try it.

**Comment by tylerlong** [comment]
Latest syntax has been changed to:

```js
mermaid.initialize({
      sequence:{
...
      }
})
```
