### ISSUE TITLE
C/C++ flowgraph support

### ISSUE THREAD

**Issue by fkromer** [knsv/mermaid#343]
After [reading the syntax description for flowcharts](http://knsv.github.io/mermaid/#flowcharts-basic-syntax) i am not sure if it is possible to generate flowgraphs for C/C++. (Flowgraphs do summarize process steps into process blocks in comparison with flowcharts which represent each statement as block.) The representation of the process blocks and the decision blocks itself is no problem. But the linking of the blocks and decision points with "arrows" to control structures (while loop, do while loop, for loop, if/else if/else, switch, etc.) could...

**Comment by knsv** [comment]
It might depend on how much details you try to squeeze in there. :)

**Comment by tylerlong** [comment]
What is the definition and where is the specification for C/C++ flowgraph?

**Comment by fkromer** [comment]
The general definition (which ist not specific to C/C++) can be found on the [wikipedia site "control flow graph"](https://en.m.wikipedia.org/wiki/Control_flow_graph). I think I found the best explanation and distinction between flow graphs and flow charts in "Software Testing Techniques" ISBN:0-442-20672-0.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
