### ISSUE TITLE
Documentation issue: CSS example is not visible

### ISSUE THREAD

**Issue by beerendlauwers** [knsv/mermaid#345]
See http://knsv.github.io/mermaid/index.html#sequence-diagrams :

![capture](https://cloud.githubusercontent.com/assets/3713919/14816476/672cc35e-0bb1-11e6-9cf5-3405f4fd383f.PNG)

**Comment by knsv** [comment]
That looks somewhat thin :)

Thanks for reporting.

**Comment by tylerlong** [comment]
Cannot reproduce the issue with latest documentation: https://mermaidjs.github.io/
