### ISSUE TITLE
# character broken in 0.5.8

### ISSUE THREAD

**Issue by vshesh** [knsv/mermaid#347]
I just tried the latest version of mermaid in the live editor and there is a weird bug where if "stroke:#000" (or any color with the # character) is the ONLY entity in a linkStyle declaration, the parser chokes:

```
graph TD
  A --> B
  linkStyle 0 stroke:#fee;
```

Chokes the parser.  If i make the link `linkStyle 0 stroke:#fee,fill:none;` all is well again.
Not sure why this is happening; documentation seems to suggest this should be okay.

**Comment by knsv** [comment]
Strange, this needs investigating!

**Comment by tylerlong** [comment]
Issue doesn't exist any more: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKICBBIC0tPiBCCiAgbGlua1N0eWxlIDAgc3Ryb2tlOiNmZWU7
