### ISSUE TITLE
SequenceDiagram: 3+ Alternative Paths

### ISSUE THREAD

**Issue by michaeltlombardi** [knsv/mermaid#348]
### Overview

Is it possible to have multiple alternate paths in a sequence diagram?

e.g. If A then X, else if B then Y, else if C then Z.

If not (and my tests to do so failed), is this functionality that it makes sense to add?
Example below.
### Example

``` mermaid
sequenceDiagram
Participant alpha
Participant bravo
alpha->>bravo: request resource
alt has resource
    bravo->>alpha: return resource
else does not have resource
    bravo->>charlie: request resource
else resource blacklisted
    bravo->>alpha: return error message
end
```

Edit: Initially posted the wrong example.

**Comment by knsv** [comment]
Sorry that is currently not possible

You can do single else statements though as in the example:
http://knsv.github.io/mermaid/#alt

And... Yes it would make sense to add it. I would welcome a pull request with this. 👍

**Comment by michaeltlombardi** [comment]
I've got the javascript skills of a toddler, but I will look into this in the future, time permitting.

**Comment by tylerlong** [comment]
@sechel sent a PR to add this feature!

**Comment by sassmilic** [comment]
Is this feature still available? I'm getting a syntax error when I try and make 3+ paths on both the Mermaid live editor (running v8.8.4) and locally (running v8.9.0).
