### ISSUE TITLE
Silencing CLI output

### ISSUE THREAD

**Issue by delucis** [knsv/mermaid#352]
Is there a way to silence mermaid’s output on the command line? I get [very verbose output](https://gist.github.com/delucis/355cfa6d9d5898640b73601a54baa619) (500+ lines) even without the `-v` flag.

I see the API defines a `logLevel`, might that be exposed via the command line?

**Comment by knsv** [comment]
I chatty mermaid :)

Agree this should be fixed.

**Comment by tylerlong** [comment]
Try the new CLI: https://github.com/mermaidjs/mermaid.cli
