### ISSUE TITLE
[Feature Request] ER-Diagram Support

### ISSUE THREAD

**Issue by ckdanny** [knsv/mermaid#354]
Can it support ER-Diagram? Thanks.

**Comment by joeblew99** [comment]
thats an awesome idea.

Really hoping others are interested in this 

+1

**Comment by knsv** [comment]
We have had this as an idea before. Some work was done but never completed. Se issue #117.

https://github.com/knsv/mermaid/issues/117

Commen in that one. I will close this as a duplicate. I agree that it would be cool.
