### ISSUE TITLE
'#' in the text part of a sequence diagram

### ISSUE THREAD

**Issue by Lance0312** [knsv/mermaid#355]
Just found out that '#' is considered start of a comment in the text part of a sequence diagram, and making it impossible to have '#' as plain text in text messages. Is there any trick to achieve that, or is it possible to not support inline comments?

https://github.com/knsv/mermaid/blob/2acaef67b1c2adb706c9fa609066ce82ddf3b6a6/src/diagrams/sequenceDiagram/parser/sequenceDiagram.jison#L56

**Comment by knsv** [comment]
That would be a good thing to inklude in mermaid. I think we would need to quote it some way, neatest would be support string delimters in the same way in the flowcharts.

I will rename title for this one and put help wanted on it.

The syntax for this would be to allow anything within quotes as in:
Merchant->>Customer: "foo # b"

Jison supports this, as in the code block below from the flow.jison:

```
%x string

...

["]                     this.begin("string");
<string>["]             this.popState();
<string>[^"]*           return "STR";
```

I would be happy for anyone to do this as a contribution.
