### ISSUE TITLE
Are there any documentation or examples for classDiagram and gitGraph?

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#359]
Are there any documentation or examples for classDiagram and gitGraph?

**Comment by AStupidBear** [comment]
+1

**Comment by pchaganti** [comment]
👍

**Comment by tylerlong** [comment]
I asked this question more than a year ago. And now I am one of the core collaborators of this project. It's time for me to answer my own question.  :)

classDiagram and gitGraph are unstable and buggy, there is not documentation for them yet. For now I don't recommend anybody using mermaid to generate these two types of diagrams.

Frankly speaking I don't get the point of gitGraph. I don't know when it is useful.

classDiagram is useful. And here is an example: http://mdp.tylingsoft.com/#class-diagram
But as I said classDiagram is unstable and buggy. Please stay tuned for us to optimize it.

**Comment by NaNraptor** [comment]
@tylerlong interested to hear how classDiagram has evolved and if it's worth using now?

**Comment by Dunning-Kruger** [comment]
Hey, this is a 2 year old closed issue. If the issue still exists or there's a new one, feel free to open a new issue. Thanks and sorry for the inconvenience.
