### ISSUE TITLE
software architecture diagram

### ISSUE THREAD

**Issue by danilosampaio** [knsv/mermaid#36]
hi @knsv ,

is there a way to create a architecture diagram? something like:

 ------------------------------------------------------
|                front-end libraries                     |
 ------------------------------------------------------
|                 midleware               |   others   |
 -------------------------------------------------------
|           nodejs           |    other services      |
 -------------------------------------------------------

thanks.

**Comment by knsv** [comment]
@danilosampaio How is this progressing? Tip: I have come to use flowcharts and subgraphs for similar diagrams which does it quite ok.

**Comment by danilosampaio** [comment]
hi @knsv,

it's stucked.
i'm on a steep learning curve in the jison and d3 APIs.
Because of this, i'm using other tool for 'block diagrams'.
I'm not sure if the effort is worth, due to the fact
that, apparently, no one else showed interest in this feature.

**Comment by knsv** [comment]
OK, will close this then. Thanks nevertheless!

**Comment by SamuelMarks** [comment]
3 years have passed, anyone found a good solution to this problem?

**Comment by pbhogale** [comment]
and another year has passed. this would be really nice !

**Comment by rishabh09** [comment]
one more year
