### ISSUE TITLE
mermaid-loader

### ISSUE THREAD

**Issue by questsin** [knsv/mermaid#361]
I'm building a splunk visual and trying to use mermaid for sequence diagrams. splunk uses npm, node.js, webpack.

I think the error is related due to the way mermaid is handling its markdawn like syntax. 

tried 
 "npm run build" got the below error.

ERROR in ./~/mermaid/package.json
Module parse failed: /Applications/Splunk/etc/apps/junk_app/appserver/static/visualizations/junk/node_modules/mermaid/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.

**Comment by tylerlong** [comment]
Latest version of mermaid has no problem working with webpack, please try again.

Wroking Example: https://github.com/tylingsoft/markdown-core/blob/master/webpack.config.js

Please note that, the following configurations are required:

```
externals: 'fs', // in order to make mermaid work
```

```
plugins: [
    'transform-remove-strict-mode' // in order to make mermaid work
]
```

**Comment by tylerlong** [comment]
Please also check [mermaid-webpack-demo](https://github.com/mermaidjs/mermaid-webpack-demo).

**Comment by tolbom02** [comment]
@questsin :  Where you able to do splunk visuals with mermaid? I am highly interested to do the same!
