### ISSUE TITLE
Color arrowhead

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [knsv/mermaid#362]
Hello mermaid team,

I cannot find where to set the color of the arrowhead. Can you advise?

Kind regards,
Mario

**Comment by dodoinblue** [comment]
I'm having the same issue. 
It seems that the arrowhead color is hard coded in the javascript file. See mermaid.js around line 51018, or search for code: 

```javascript
edgeData.arrowheadStyle = 'fill: #333';
```

**Comment by knsv** [comment]
Closed by release 7.0.0, please reopen if issues remain.

**Comment by dudung** [comment]
Which style I should use as `linkStyle default stroke:#8a8` for line?
