### ISSUE TITLE
Flow chart contains <foreignObject> tag, which can't be converted into image

### ISSUE THREAD

**Issue by ghosert** [knsv/mermaid#363]
This is what I could get from google, is there any way to resolve this, I'm going to convert flow chart to img, but it failed because of <foreignObject>

See the details here:
https://bugs.chromium.org/p/chromium/issues/detail?id=294129

Is there anyway to render flow chart without generating foreignObject in this case to resolve my issue ?

Thanks.

**Comment by RReverser** [comment]
Use `htmlLabels: false` if that's what you want.

**Comment by ghosert** [comment]
Thanks, it seems working, but after applying this config, some flowchart is rendering wrongly, for example this one:


         subgraph one
         a1-->a2
         end
         subgraph two
         b1-->b2
         end
         subgraph three
         c1-->c2
         end
         c1-->a2

**Comment by RReverser** [comment]
Yeah, that's a separate issue, see https://github.com/knsv/mermaid/issues/367

**Comment by ghosert** [comment]
Oh, thanks. Will this be fixed soon ?

**Comment by RReverser** [comment]
Why do you ask me? 😄 I have no idea.

**Comment by ghosert** [comment]
I thought you are the developer. :+1:

**Comment by RReverser** [comment]
No, just another user of the library.

**Comment by tylerlong** [comment]
Not sure why you cannot convert svg to image. Please check https://github.com/mermaidjs/mermaid.cli  It supports converting mermaid code to png. You can read its code and it's pretty simple

**Comment by RReverser** [comment]
@tylerlong Point is about using SVG as a standalone image, not converting it to another format (like PNG).
