### ISSUE TITLE
Add shebang support to diagrams

### ISSUE THREAD

**Issue by ssbarnea** [knsv/mermaid#365]
By adding a shebang line to the first line of the diagrams we should be able to build them by executing them.

```
#!/usr/bin/env mermad
```

The are lots of tools that allow this use case, the trick is that mermaid should be able to parse the `stdout`, nothing else.

Currently it seems that the PNG files are generated if you do this but they contain an image of the source code instead of the diagram? Quite a strange behaviour.

**Comment by tylerlong** [comment]
What is `mermad`?

The latest tool to process mermaid code is https://github.com/mermaidjs/mermaid.cli

Closing it since it's not a common requirement.
