### ISSUE TITLE
line labels are not rendered correctly in live editor

### ISSUE THREAD

**Issue by jorgheymans** [knsv/mermaid#366]
Hi,

Consider this simple example: http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFIKQS0tPnx0ZXN0fEI7 

```
graph LR
A-->|test|B;
```

in the live editor this renders like

![image](https://cloud.githubusercontent.com/assets/193792/16230767/6355413c-37c3-11e6-9726-f1ea777b5044.png)

But in the documentation all the examples i can see have a background set for the arrow labels. Am i missing a flag to enable these ? Browser versions here are FF 45.2.0 and Chrome 51

**Comment by knsv** [comment]
Thanks for the report and sorry about the late response. This is matter of configuration in the editor code and should be fixed.

**Comment by tylerlong** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/733544/29392817-b9eeb4fe-8332-11e7-8711-f634b3789799.png)

**Comment by xiaoxiao426** [comment]
How can i set the background color of lable?

**Comment by Dunning-Kruger** [comment]
@xiaoxiao426 This issue is 3 years old. Please, check the documentation or open a new issue if you need to.
