### ISSUE TITLE
Can't render subgraphs with htmlLabels: false

### ISSUE THREAD

**Issue by RReverser** [knsv/mermaid#367]
Tracked this to `addSVGLabel` which fails because for clusters, nodes are created with `labelType: "svg"` and `label: ""`, so it tries to insert `label` which is a string, using `appendNode`, hence the error.

**Comment by ghosert** [comment]
+1, will this be fixed soon. Thanks. ;)

**Comment by RReverser** [comment]
@ghosert Just another sidenote: please don't do `+1` on github issues, this is a very bad practice. Just use Github's reactions ( 👍 ) on issues, or you can even try to fix it yourself and send a PR.

**Comment by ghosert** [comment]
For example, would like to see this text rendering correctly:

     subgraph one
     a1-->a2
     end
     subgraph two
     b1-->b2
     end
     subgraph three
     c1-->c2
     end
     c1-->a2

**Comment by ghosert** [comment]
@shd101wyy I don't think we are saying the same issue, your fix may not be the solution for this issue.

**Comment by daveaglick** [comment]
Just submitted a PR for this - thanks for the starting point @RReverser, JS isn't my main language so I couldn't have figured this out without knowing where to start looking.

**Comment by knsv** [comment]
Closed by release 7.0.0, please reopen if issues remain.
