### ISSUE TITLE
mermaidAPI.render generated different svg code from mermaid.int()

### ISSUE THREAD

**Issue by shd101wyy** [knsv/mermaid#374]
Hi,

After I ran the code below ( I am using mermaid 6.0.0)

``` javascript
var text = 'graph TD\nA-->B\nA-->C\nB-->D\nD-->A\n'
var element = document.getElementById('mermaid0')
mermaidAPI.render(element.id, text, function(svgCode){ element.innerHTML = svgCode })
```

the generated graph looked like 
![screen shot 2016-07-13 at 12 57 22 pm](https://cloud.githubusercontent.com/assets/1908863/16792289/cce925b8-48f9-11e6-9922-d4bb8d1e79a0.png)

While by calling `mermaid.init()` , I got graph like 
![screen shot 2016-07-13 at 1 01 06 pm](https://cloud.githubusercontent.com/assets/1908863/16792296/e1faf67a-48f9-11e6-8abc-3e8eb5a1673a.png)

Any idea how to solve this problem?

Thanks

**Comment by shd101wyy** [comment]
I hacked the code a bit and I resolve the problem by modifying the code to 

```javascript
var text = 'graph TD\nA-->B\nA-->C\nB-->D\nD-->A\n'
var element = document.getElementById('mermaid0')
mermaidAPI.render(element.id, text, function(svgCode){ 
    element.innerHTML = svgCode 
    element.firstChild.style.height = element.getAttribute('viewbox').split(' ')[3] + 'px'
})
```

It seems that the original height of **svg** block is wrong.

**Comment by shd101wyy** [comment]
Also, **mermaidAPI.render** doesn't work properly with `sequenceDiagram` graph.

**Comment by yangxiaokun** [comment]
@shd101wyy Met this error when I use  **mermaidAPI.render** too. Thank you for your solution

**Comment by tylerlong** [comment]
I don't use the render method very often. I always just invoke the `mermaid.init` method.
