### ISSUE TITLE
feature for sequence diagrams

### ISSUE THREAD

**Issue by reggi** [knsv/mermaid#375]
I would really love a `process` box.

I realize we're strapped for space in this field. I just want a way to contain a bunch of items without them being `alt` or `opt`. Thoughts? 

![screen shot 2016-07-14 at 1 59 19 pm](https://cloud.githubusercontent.com/assets/296798/16850021/25734890-49cb-11e6-8a1f-b1b991eb0053.png)

```
proc: create customer

end
```

What about even doing a "box" clause so you can create a box with any name.

```
box=proc: create customer

end
```

I'd also just be ok with being able to wrap stuff in a box without any text like this.

![screen shot 2016-07-14 at 2 02 41 pm](https://cloud.githubusercontent.com/assets/296798/16850118/a0ada316-49cb-11e6-9fe6-1e7c54b6aa6e.png)

I'm simply looking for a way to label a bunch of things together.

Would love some help.

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866.

This is a super old issue and you are proabably not thinking about it anymore. However, this is a good idea and I will mark this as an enchancement and put it in the backlog of suitable tasks.
