### ISSUE TITLE
Finnish support for class diagrams using plantuml syntax 

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#377]
Assigned to @HustLion

**Comment by HustLion** [comment]
#379 modified the README.md and made a pull request.

I start with the README.md and then the documentation in gh-pages. Right now the README.md is finished. As for the class diagram positioning issue, still need more time to understand the code and identify the positioning issue with some examples.

**Comment by testboots** [comment]
@HustLion thank you very much for adding class support! I love plantUML and @knsv mermaid seriously rocks. thanks again.

**Comment by tylerlong** [comment]
PR has been merged and there hasn't been any activity recently. Closing.
