### ISSUE TITLE
PhantomJS crashes on a large graph

### ISSUE THREAD

**Issue by agladysh** [knsv/mermaid#380]
OS X 10.11.6
Mermaid 6.0.0
PhantomJS 2.1.1

```
$ mermaid all.mermaid
<...>
CONSOLE: [11:45:53 (716)]  Got edge twp/schedule/period/create twp/schedule/schedule (from line # in "")
CONSOLE: [11:45:53 (716)]  Got edge twp/main twp/schedule/schedule (from line # in "")
PHANTOM ERROR: TypeError: null is not an object (evaluating 'oDOM.documentElement.attributes.getNamedItem('width').value')
TRACE:
 -> phantomjs://code/phantomscript.js: 112
 -> undefined: 0 (in function forEach) 
```

Smaller files render fine on this setup.

The same large file renders fine on Ubuntu. The setup there is identical:

Ubuntu 15.10
Mermaid 6.0.0
PhantomJS 2.1.1

I can try to clean out the sensitive information from the file to show you, if this will help. I can also collect any other diagnostics for you, as needed.

**Comment by aquacash5** [comment]
Ubuntu: 16.10
Mermaid: 7.0.0
PhantomJS 2.1.1

```
$ mermaid collatz.mmd -p -w 9000

TypeError: null is not an object (evaluating 'oDOM.documentElement.attributes.getNamedItem('width').value')
```

never seems to actually finish.

I included  the file i used.
[collatz.mmd.zip](https://github.com/knsv/mermaid/files/876676/collatz.mmd.zip)

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
