### ISSUE TITLE
How to add newline in the text

### ISSUE THREAD

**Issue by coolgoose85** [knsv/mermaid#384]
I am trying to break the text in two lines on top of arrows or on notes but newline is not working anywhere

Example
 Note right of ABC: - Group all \n large and medium

OR 

abc->>cuz: How are \n you?

Am I missing some syntax?

**Comment by jboelter** [comment]
Doesn't look like this is currently supported.  The [drawNote](https://github.com/knsv/mermaid/blob/aa6e15e3acbf29e81001909e40fb2b475285f092/src/diagrams/sequenceDiagram/sequenceRenderer.js#L159) is correctly provided a multi-line input, but is putting it directly into an svg <tspan> field.  There's some commented code in [drawSvg](https://github.com/knsv/mermaid/blob/aa6e15e3acbf29e81001909e40fb2b475285f092/src/diagrams/sequenceDiagram/svgDraw.js#L35) that might be a starting point for a contribution.

**Comment by knsv** [comment]
We should support this. A good task for someone that wants to be a part of the  project.

**Comment by alanmimms** [comment]
One of the examples for sequence diagrams shows HTML `<br/>`, and it _happens_ that the sample breaks the line at that point. But if you add another `<br/>` or move the existing one the line break doesn't follow it. Apparently that is simply ignored.

**Comment by Naishy** [comment]
I found that using `<br/>` in node text gives line breaks as expected, including for multiple line breaks. Tested on Chromium 55.0.2883.87 and Firefox 51.0.1

**Comment by ufo2mstar** [comment]
Sorry, still not giving line breaks as expected for sequence diagrams (Chrome 56+ and Firefox 51+). 
I will try to work on this feature soon.

**Comment by scordature** [comment]
Line breaks work in `graph` diagrams, except not in `Subgraph` names.
They do **not** work in sequence diagrams, at all.

```
graph TD;

subgraph Line breaks <br /> don't work in <br /> Subgraphs
    inset[Line breaks <br />work in <br />Insets]
end

    inset-->A

  A(Line breaks<br />work in<br />rounded rec nodes)
  B{Line breaks <br />work in<br />decision nodes}
  C[Line breaks<br />work in<br /> rectangles]
  D((Line breaks <br />work in <br />circles))
  E>Line breaks <br />work in <br />flag nodes]


    A-->B
    B--yes-->C
    B--no-->E
    C-->D
 


style A fill:#ed6,stroke:#333,stroke-width:2px;
style B fill:#ed6,stroke:#333,stroke-width:2px;
style C fill:#ed6,stroke:#333,stroke-width:2px;
style D fill:#ed6,stroke:#333,stroke-width:2px;
style E fill:#ed6,stroke:#333,stroke-width:2px;
style inset fill:#ed6,stroke:#333,stroke-width:2px;
```

**Comment by Lucas-C** [comment]
`<br>` is not fully supported: the following graph generates an "Opening and ending tag mismatch: br line 0 and div" error, both with `mmdc` and in `mermaid-live-editor`
```
graph TD
B(B<br>b)
```

**Comment by tylerlong** [comment]
@Lucas-C It seems to work in mermaid-live-editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQihCPGJyPmIpCg

**Comment by Lucas-C** [comment]
Yeah, I wasn't clear about this one: click "Download SVG" and you'll see the error

**Comment by tylerlong** [comment]
Confirmed. Downloaded SVG doesn't work.
I am not a SVG format expert. Maybe <br> is invalid in SVG. More investigation is needed.

**Comment by alanmimms** [comment]
At least _some_ SVG implementations support newline, but not using HTML's `<br/>` tag. This sort of question [gets asked a lot](https://stackoverflow.com/questions/16701522/how-to-linebreak-an-svg-text-within-javascript).

Instead, SVG evidently supports embedding the ASCII NL character. An example [is here](https://bl.ocks.org/vicapow/cd2046770ceea172d4db).

**Comment by Lucas-C** [comment]
So a fix could be to replace every `<br>` by a `\n` ?

**Comment by alanmimms** [comment]
I suspect the fix would be to replace the `<br>` tags with `&#xA;` as described in the example I pointed to above.

**Comment by KaptainRose** [comment]
@alanmimms  @Lucas-C I'm unable to get `&#xA;` to work in `mermaid-live-editor` (I think because of the semi colon, and I haven't figured out a way to escape it out as a special character).
To continue with Lucas' code and per Alan's linked example, this is what I've input tothe editor:
```
graph TD
B(B &#xA; b)
```
Any suggestions?

**Comment by DorfilIkatu** [comment]
@KaptainRose write different lines between <p> and </p>... it worked for me

**Comment by KaptainRose** [comment]
@DorfilIkatu thank you so much, it worked!

**Comment by galaxy001** [comment]
Please make it to output `<br/>` as it is, instead of changing it to `<br>` and break Firefox XML parser.

**Comment by oisu** [comment]
I tried using <p></p>, it works but makes additional line space.
<div></div> instead works perfectly for me 🙂

**Comment by tylerlong** [comment]
@galaxy001 
> Please make it to output <br/> as it is, instead of changing it to <br> and break Firefox XML parser.
done

**Comment by jhvanderven** [comment]
Will this be supported in the sequence diagram too?

**Comment by BHunter2889** [comment]
> @galaxy001
> 
> > Please make it to output `<br/>` as it is, instead of changing it to `<br>` and break Firefox XML parser.
> 
> done
> 

This doesn't appear to be done. At least not in the Live Editor. I had to go into the svg and manually change all to be `<br/>`, which worked.

**Comment by jayagopaldaz** [comment]
i think there's still some work to be done here:

```
graph TD

Y(BEHAVIOUR OUTSIDE<br/>OF SUBGRAPHS)
Z(BEHAVIOUR OUTSIDE<br>OF SUBGRAPHS)
a-- long arrow message line 1<br>line 2 of long arrow message --> b
c-- long arrow message line 1<br/>line 2 of long arrow message --> d

subgraph BEHAVIOUR INSIDE<br>OF SUBGRAPHS
  e-- long arrow message line 1<br>line 2 of long arrow message --> f
end

subgraph BEHAVIOUR INSIDE<br/>OF SUBGRAPHS
  g-- long arrow message line 1<br/>line 2 of long arrow message --> h
end
```
https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblxuWShCRUhBVklPVVIgT1VUU0lERTxici8-T0YgU1VCR1JBUEhTKVxuWihCRUhBVklPVVIgT1VUU0lERTxicj5PRiBTVUJHUkFQSFMpXG5hLS0gbG9uZyBhcnJvdyBtZXNzYWdlIGxpbmUgMTxicj5saW5lIDIgb2YgbG9uZyBhcnJvdyBtZXNzYWdlIC0tPiBiXG5jLS0gbG9uZyBhcnJvdyBtZXNzYWdlIGxpbmUgMTxici8-bGluZSAyIG9mIGxvbmcgYXJyb3cgbWVzc2FnZSAtLT4gZFxuXG5zdWJncmFwaCBCRUhBVklPVVIgSU5TSURFPGJyPk9GIFNVQkdSQVBIU1xuICBlLS0gbG9uZyBhcnJvdyBtZXNzYWdlIGxpbmUgMTxicj5saW5lIDIgb2YgbG9uZyBhcnJvdyBtZXNzYWdlIC0tPiBmXG5lbmRcblxuc3ViZ3JhcGggQkVIQVZJT1VSIElOU0lERTxici8-T0YgU1VCR1JBUEhTXG4gIGctLSBsb25nIGFycm93IG1lc3NhZ2UgbGluZSAxPGJyLz5saW5lIDIgb2YgbG9uZyBhcnJvdyBtZXNzYWdlIC0tPiBoXG5lbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

in gitlab, none of these examples introduce newlines.

**Comment by skorokithakis** [comment]
I cannot get the live-editor to introduce newlines in any browser with any method as well. Please reopen this.

**Comment by Tinkerer-** [comment]
I tried to get a newline in  a box in Pandoc, with Mardown Preview Enhanced, and also did not manage to get a newline. Would be greatly appreciated if this could be fixed.

**Comment by rajasekaran2003** [comment]
> Sorry, still not giving line breaks as expected for sequence diagrams (Chrome 56+ and Firefox 51+).
> I will try to work on this feature soon.

any progress on this?

sequence diagrams still doesn't support multi lines for message lines,

**Comment by timcashion** [comment]
I just searched for this and it worked for me running in RStudio `&#xA;` . I tried `<br/>` and `\n` before this and neither worked. 

grViz("digraph flowchart {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']

      # edge definitions with the node IDs
      tab1 -> tab2;
      tab1 -> tab3;
      tab3 -> tab4;
      tab3 -> tab5;
      tab5 -> tab6;
      tab5 -> tab7;
      tab7 -> tab8
      }

      [1]: 'Label'
      [2]: 'Step 1: Match by Type, Group,&#xA;State, Processed, and Final Processed'
      [3]: 'Unmatched at Step 1'
      [4]: 'Step 2: Match by Type, State, &#xA;Processed, and Final Processed'
      [5]: 'Unmatched at Step 2'
      [6]: 'Step 3: Match by Type,&#xA;Processed, and Final Processed'
      [7]: 'Unmatched at Step 3'
      [8]: 'Step 4: Match by Type only'
      ")

**Comment by rajasekaran2003** [comment]
Hi,

i wanted to try this on sequence diagram and couldn't get it to work.

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5BLT4-QjogYSB2ZXJ5IHNpbXBsZSBtdWx0aSA8YnIvPiAmI3hBOyAgXFxyXFxuIGxpbmUgc2VudGVuY2UiLCJtZXJtYWlkIjp7InRoZW1lIjoibmV1dHJhbCJ9fQ


With regards,

 Raja

**Comment by gakonst** [comment]
+1, I'd like to get multiline text in a Sequence Diagram, no clear way to do this still. Can this be reopened?

**Comment by nicola** [comment]
same here!

**Comment by etimau** [comment]
When using <br> in a sequenceDiagram, when exported to SVG it is translated to </text><text> tags.
[See this example](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5BLT4-QjogYSB2ZXJ5IHNpbXBsZSBtdWx0aTxici8-bGluZSBzZW50ZW5jZSIsIm1lcm1haWQiOnsidGhlbWUiOiJuZXV0cmFsIn19)

Is it possible to have the same behavior in flowcharts?
If you try [this](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5BIC0tXCJtdWx0aTxicj5saW5lXCItLT4gQiIsIm1lcm1haWQiOnsidGhlbWUiOiJuZXV0cmFsIn19) and click on "Download SVG", the result has a parse XML error because of the <br> tag.
Idem if the <br> is inside a node.

**Comment by Dunning-Kruger** [comment]
@etimau Hey! You're commenting in an old closed issue. Feel free to create a new issue if you found a bug, need help, want to request a feature or anything!
