### ISSUE TITLE
sequence diagram config issue

### ISSUE THREAD

**Issue by michaelritsema** [knsv/mermaid#385]
sequence diagrams aren't always picking up the config: 

example config:

mermaid.sequenceConfig = {
diagramMarginX:50,
diagramMarginY:10,
boxTextMargin:5,
noteMargin:10,
messageMargin:35,
mirrorActors:true
};

more details on issue: https://github.com/tylingsoft/markdown-plus/issues/73

**Comment by kaithar** [comment]
Seconded... I've got a sequence diagram that's not registering the config:

```javascript
        mermaid.initialize({
            startOnLoad:true,
            sequenceDiagram:{
                mirrorActors:false
            }
        })
```

`mirrorActors` doesn't seem to work.

**Comment by knsv** [comment]
Very odd. I just tried this with the following example file withtout beeing able to reproduce the issue:
https://github.com/knsv/mermaid/blob/master/test/examples/seq.html

What version of mermaid are you trying this with?

**Comment by kaithar** [comment]
I'm loading https://cdn.rawgit.com/knsv/mermaid/0.5.8/dist/mermaid.min.js at the end of the page.

**Comment by kaithar** [comment]
Ok, I've just tried and it looks like the initialize call works fine if the script tag is in the head tag instead of the body, though that's somewhat inconvenient for my current use.

**Comment by tylerlong** [comment]
Latest syntax is

```js
mermaid.initialize({
            sequence:{
                ...
            }
        })
```

**Comment by fmatheus** [comment]
Still not working here, could you please disambiguate:
mirrorActor or mirrorActors? (default is still false? I'm using Mermaid Online Editor, and it seems not set it to true anywhere... but it still mirror by default).
sequence or sequenceConfig?
init or initialize?
