### ISSUE TITLE
Font Awesome support for Sequence Diagrams

### ISSUE THREAD

**Issue by Astorsoft** [knsv/mermaid#392]
Hi there,

First of all kudos for your great work on Mermaid, this tool is even better than most paid solution you can find on the Internet, which is impressive.

I was very interested in using Font awesome icons for Sequence diagrams and was surprised I was not able to use it. It looks like the feature is only there for flowcharts, would it be possible to add support to sequence diagrams? I had a quick look at the sequenceRenderer.js but I'm not good enough in javascript to figure it out myself :).

I guess that html tags are not supported altogether in the sequence diagrams right now? Could be nice to be able to usr <br/> or <strong> too.

Here is an example of diagrams I would like to be able to draw:

sequenceDiagram
Admin->> Server: Key encryption request fa:fa-key
note right of Server:  Encryption fa:fa-key
Server->>Admin: Sends the fa:fa-key
Admin->>BDD: Lookup the database
note right of BDD: Bob : <br/> A9q1XituQpj7CBPpKxB09g==
BDD->>Admin: Bob: A9q1Xit¢uQpj7CBPpKxB09g==
Admin->>Admin: Decrypt password using the fa:fa-key
note left of Admin: Bob : S3cret!

**Comment by DuncanHills** [comment]
Is there any way to reopen this issue?
