### ISSUE TITLE
Live editor does not support activate/deactivate

### ISSUE THREAD

**Issue by fabioperrella** [knsv/mermaid#394]
Hi, I tryed to use the live editor at http://knsv.github.io/mermaid/live_editor/ but the following code returns the error `Invalid syntax`:

```
sequenceDiagram
    Alice->>John: Hello John, how are you?
    activate John
    John-->>Alice: Great!
    deactivate John
```

**Comment by tylerlong** [comment]
Fixed

https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBbGljZS0-PkpvaG46IEhlbGxvIEpvaG4sIGhvdyBhcmUgeW91PwogICAgYWN0aXZhdGUgSm9obgogICAgSm9obi0tPj5BbGljZTogR3JlYXQhCiAgICBkZWFjdGl2YXRlIEpvaG4K
