### ISSUE TITLE
Edge labels should have white background in live editor

### ISSUE THREAD

**Issue by devdigital** [knsv/mermaid#396]
Edge labels have a transparent background in the live editor, and hence it's difficult to read the edge text. Could the background colour for the `edgeLabel` class be changed to white?

**Comment by toonvandeputte** [comment]
Is this also what causes text on connecting lines to be hard to read because it is rendered right on top of the line? Because that's also something that bugs me somewhat in an otherwise great tool.

**Comment by tylerlong** [comment]
Fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpCkIgLS0-IEN7TGV0IG1lIHRoaW5rfQpDIC0tPnxPbmV8IERbTGFwdG9wXQpDIC0tPnxUd298IEVbaVBob25lXQpDIC0tPnxUaHJlZXwgRltDYXJdCg
