### ISSUE TITLE
Can't Zoom the flowchart ?

### ISSUE THREAD

**Issue by buptljy** [knsv/mermaid#399]
I can't zoom the flowchart to see them clearly when the flowchart fills the screen.It's very hard to recognize them because there are too many nodes.
Any way to fix it ?

**Comment by WebSpanner** [comment]
You can change the size of the container with CSS. This will allow the browser's zoom and scrollbar functionality to work.

**Comment by buptljy** [comment]
@WebSpanner Thanks~  I've waited for a very long time. Haha.

**Comment by fayaz-issak-bbc** [comment]
> You can change the size of the container with CSS. This will allow the browser's zoom and scrollbar functionality to work.

Please can you show example how to do this?

**Comment by AndrewFeeney** [comment]
Suppose your mermaid diagram is inside a `<div>` element with an id of `mermaid` like below:

```
<div id="mermaid">
    graph myGraph
        ...
</div>
```

Then in your css file add the following:

```
#mermaid {
    /** Set this value to whatever is appropriate for your use case, or use the height property instead **/
    width: 800px; 
}
```

You could also add the above code to your `.html` file enclosed in `<style></style>` tags in either the `<head></head>` tag or the `<body></body>` tag.

I hope that helps.

**Comment by fayaz-issak-bbc** [comment]
Cant seem to get it working.. is the viewbox not going to interfere with this?

**Comment by AndrewFeeney** [comment]
I don’t know sorry. Could you share a code example on code pen or something?

**Comment by GDFaber** [comment]
I don't know if I understood correctly, perhaps the workaround mentioned in #838 (comment) can solve your problem?
