### ISSUE TITLE
Some chinese character will case Safari no responding.

### ISSUE THREAD

**Issue by abnerlee** [knsv/mermaid#405]
How to reproduce.

Open https://knsv.github.io/mermaid/live_editor/ in Safari 10.0.1 (macOS Serria)

input

```mermaid
 graph LR
		A --》 B
```

Then the browser will become unresponding. It works fine on Chrome however.

**Comment by abnerlee** [comment]
also for #238

**Comment by tylerlong** [comment]
Fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/IGdyYXBoIExSCgkJQSAtLeOAiyBC/error/TGV4aWNhbCBlcnJvciBvbiBsaW5lIDIuIFVucmVjb2duaXplZCB0ZXh0LgogZ3JhcGggTFIJCUEgLS3jgIsgQgotLS0tLS0tLS0tLS0tLS1e
