### ISSUE TITLE
Flowchart: Link text beginning with lowercase 'o' causes flowchart to break

### ISSUE THREAD

**Issue by ssurve** [knsv/mermaid#407]
E.g.: `<div class='mermaid'>graph LR\n\tstep0(step0)--next-->step1(step1)\n\tstep1--next-->step2(step2)\n\tstep2--next-->step3(step3)\n\tstep3--ok-->DONE((DONE))</div>
`
results in this output:
<img width="899" alt="flowchart display error with lowercase o in link text" src="https://cloud.githubusercontent.com/assets/12615472/20123455/0dd2abf8-a5d4-11e6-84e6-d8a2d1ea7a2b.png">

Uppercase 'O' works as expected:
code: `<div class='mermaid'>graph LR\n\tstep0(step0)--next-->step1(step1)\n\tstep1--next-->step2(step2)\n\tstep2--next-->step3(step3)\n\tstep3--Ok-->DONE((DONE))</div>`
output:
<img width="597" alt="correct flowchart display with uppercase O in link text" src="https://cloud.githubusercontent.com/assets/12615472/20123513/771339de-a5d4-11e6-8de3-445c263106b4.png">

Is this a parser rule? Not starting a link text with lowercase 'o'? If yes, are there any more such rules? Please point me to the relevant documentation.

Thanks.

**Comment by tylerlong** [comment]
I can reproduce the issue:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKc3RlcDAoc3RlcDApLS1uZXh0LS0+c3RlcDEoc3RlcDEpCnN0ZXAxLS1uZXh0LS0+c3RlcDIoc3RlcDIpCnN0ZXAyLS1uZXh0LS0+c3RlcDMoc3RlcDMpCnN0ZXAzLS1vay0tPkRPTkUoKERPTkUpKQ==/error/UGFyc2UgZXJyb3Igb24gbGluZSA1OgouLi5lcDMoc3RlcDMpc3RlcDMtLW9rLS0+RE9ORSgoRE9ORSkpCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS1eCkV4cGVjdGluZyAnU0VNSScsICdORVdMSU5FJywgJ0VPRicsIGdvdCAnQVJST1dfUE9JTlQn


This does work:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKc3RlcDAoc3RlcDApLS1uZXh0LS0+c3RlcDEoc3RlcDEpCnN0ZXAxLS1uZXh0LS0+c3RlcDIoc3RlcDIpCnN0ZXAyLS1uZXh0LS0+c3RlcDMoc3RlcDMpCnN0ZXAzLS1Pay0tPkRPTkUoKERPTkUpKQ==

**Comment by tylerlong** [comment]
I find a workaround:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKc3RlcDAoc3RlcDApLS1uZXh0LS0-c3RlcDEoc3RlcDEpCnN0ZXAxLS1uZXh0LS0-c3RlcDIoc3RlcDIpCnN0ZXAyLS1uZXh0LS0-c3RlcDMoc3RlcDMpCnN0ZXAzLS0ib2siLS0-RE9ORSgoRE9ORSkp

Put the link text inside double quotes then it can have any characters.

I still think it is a bug. I will dive into it whenever I have some time.

**Comment by tylerlong** [comment]
`--o` is a special syntax for `ARROW_CIRCLE`. I don't have any good solution for this behavior. I recommend the workaround above.

**Comment by FDiskas** [comment]
Or just use space `step3 -- ok -->DONE((DONE))`
