### ISSUE TITLE
flowchart id's with dots in them .. break links 

### ISSUE THREAD

**Issue by vikaskedia** [knsv/mermaid#408]
This works:

http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFIKICAgIGlkMShDbGljayBtZSkKCmNsaWNrIGlkMSAiaHR0cDovL3d3dy5leGFtcGxlLmNvbSIgIkNsaWNrIHRvIGdvIHRvIGV4YW1wbGUgVVJMIg

This does not work:

http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFIKICAgIGlkMS4xKENsaWNrIG1lKQoKY2xpY2sgaWQxLjEgImh0dHA6Ly93d3cuZXhhbXBsZS5jb20iICJDbGljayB0byBnbyB0byBleGFtcGxlIFVSTCI

**Comment by tylerlong** [comment]
I confirm it is an issue: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKICAgIGlkMS4xKENsaWNrIG1lKQoKY2xpY2sgaWQxLjEgImh0dHA6Ly93d3cuZXhhbXBsZS5jb20iICJDbGljayB0byBnbyB0byBleGFtcGxlIFVSTCI

**Comment by tylerlong** [comment]
It seems to be fixed. Please try again.
