### ISSUE TITLE
Dotted links .. link style does not work

### ISSUE THREAD

**Issue by vikaskedia** [knsv/mermaid#409]
This works:
http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtGaXJzdF0tLT5CW1NlY29uZF0KCiAgICAgICAgbGlua1N0eWxlIGRlZmF1bHQgc3Ryb2tlLXdpZHRoOjRweCxmaWxsOm5vbmUsc3Ryb2tlOnJlZDs

This does not work:
http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtGaXJzdF0tLi1CW1NlY29uZF0KCiAgICAgICAgbGlua1N0eWxlIGRlZmF1bHQgc3Ryb2tlLXdpZHRoOjRweCxmaWxsOm5vbmUsc3Ryb2tlOnJlZDs

**Comment by tylerlong** [comment]
I confirm that it is an issue: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtGaXJzdF0tLi1CW1NlY29uZF0KCiAgICAgICAgbGlua1N0eWxlIGRlZmF1bHQgc3Ryb2tlLXdpZHRoOjRweCxmaWxsOm5vbmUsc3Ryb2tlOnJlZDs
