### ISSUE TITLE
Linkstyle stroke does not work

### ISSUE THREAD

**Issue by vikaskedia** [knsv/mermaid#410]
In this example:

http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtTdGFydF0gLS0-IEJbRW5kXQoKICAgICAgICBsaW5rU3R5bGUgZGVmYXVsdCBzdHJva2Utd2lkdGg6MnB4LGZpbGw6bm9uZSxzdHJva2U6cmVkOw

The link color is black though I have:

stroke:red;

**Comment by knsv** [comment]
This seems to be the case in the live editor but not in mermaid itself. There is a style within the stylesheet in the editor withe !important in it that overrides the style with the diagram.

**Comment by tylerlong** [comment]
https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFI7CiAgICAgICAgQVtTdGFydF0gLS0+IEJbRW5kXQoKICAgICAgICBsaW5rU3R5bGUgZGVmYXVsdCBzdHJva2Utd2lkdGg6MnB4LGZpbGw6bm9uZSxzdHJva2U6cmVkOw

Feel free to reopen if you still have this issue.
