### ISSUE TITLE
Live editor show rendered diagram if syntax invalid

### ISSUE THREAD

**Issue by orschiro** [knsv/mermaid#415]
Dear all, 

Is it possible to let the live editor show the last version of the rendered diagram that still used valid syntax?

Let me show you an example:

![image](https://cloud.githubusercontent.com/assets/170947/20624675/87d7c1ee-b30e-11e6-80e3-d57e44185c9c.png)

**Comment by tylerlong** [comment]
The behavior has been updated. If there is a syntax error, the detailed error trace will be shown.

And you can undo (CMD-Z or CTRL-Z) to go to the last version of the diagram.

Feel free to reopen or create a new issue.
