### ISSUE TITLE
shouldn't mermaid become more like Markdown ?

### ISSUE THREAD

**Issue by g3o2** [knsv/mermaid#417]
> This is why mermaid was born, a simple markdown-like script language for generating charts from text via javascript.

A look at [Markdown](http://daringfireball.net/projects/markdown/)'s key objective:

> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible. The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.

Maybe mermaid could inspire itself from this by making its text syntax look more like the final outcome rendered via javascript. 

E.g. for graphs, a consequence could be to also allow:

```Mermaid
graph:
  A
  |
  .
  B
 / \
.   .
C   D
```

which would be visually more appealing than:

```Mermaid
graph TB;
  A-->B;
  B-->C;
  B-->D;
```

**Comment by sancarn** [comment]
As far as I am aware, the point of systems like Mermaid or Viz, isn't that the initial product should be visually appealing but that the initial product is easy for a computer to produce.

Ultimately, Viz and Mermaid are tools for automating the production of charts from data. In the end if you want something visually appealing why not just build it in a flowchart maker like draw.io?

An example use case of these graphers:
Say you have an object oriented program and you want to visualise the entire object structure to search for optimisations. It's far easier to write a program to search the code and turn it into:

```
object1-->object2
object2-->object3
object3-->object4
object3-->object5
object2-->object6
object1-->object7
```

Than it would be for the computer to produce something like:

```
                    object1
                        /  \
                        .   .
              object2  object7
                  /  \
                  .   .
       object3  object6
          /  \
          .   .
object4  object5
```

**Comment by g3o2** [comment]
I fully agree with your points. It also shows the complexity of the problem to solve. However, for those same reasons I have a hard time understanding the parallel drawn in the documentation with Markdown.

**Comment by LarryKlugerDS** [comment]
I think the docs comment re Wordpress is being interpreted too closely. The current format is good, IMHO. If @g3o2 wanted to create a converter from the format he describes to Mermaid, that would be an interesting project.

**Comment by g3o2** [comment]
`mermaid` de facto provides an easy to understand and handy coding syntax for drawing diagrams, which can be included (like any other syntax or code) into a Markdown document. 

However, the claim in the docs that `mermaid` would be _markdown-like_ is in my opinion a little far stretched. Hence, my suggestion: a) to push `mermaid` further, which I understand from your replies may not be a desirable path, or b) to remove the said claim from the docs.

**Comment by karfau** [comment]
In my opinion the `mermaid` format is _easy to write and read_ for a textual representation of a graph. 
Of course when you want to provide a visualization it is hard to do it using text, the goal is not surely not to write ASCII-art, right?

But I agree that it would make sense, to at least provide an elaboration on the relation to/ distinction from markdown.

**Comment by g3o2** [comment]
Heaven forbid manually drawn ASCII art, though `mermaid` would certainly be capable of producing such and vice versa. Maybe in a distant future version :-)

Regarding readability, `mermaid` provides a syntax for drawing a graph, but it is certainly not a _textual representation_. The latter would boil down to an interpretation à la "the graph has the shape of a diamond, represented by [x] nodes and [y] links, etc.".

**Comment by wigy-opensource-developer** [comment]
I cannot agree with the proposal. I think tools like mermaid also help people just typing out a specification of a diagram and leave the representation to be calculated based on rules. Small changes in the specification could end up producing big changes in the diagram (one arrow or adding a day to a task on a Gantt-chart).

For me it seems more natural to keep the specification under version control, see the small diff between versions and leave the formatting and rendering to the software.
