### ISSUE TITLE
Diagram without the 'flow', or link nodes at same rank?

### ISSUE THREAD

**Issue by absolutejam** [knsv/mermaid#418]
Apologies for creating an issue for this, but I wasn't sure of the best method to get in touch!

I've been toying with Graphviz, but I really what you're doing with mermaid. Is there any methods or plans to support connected nodes of the same rank?

Regards,
James.

**Comment by knsv** [comment]
No problems with the issue! 
There are no plans for this right now but if this is something that would help many people and many are interested of that could change!
Thanks for asking!Knut

Get Outlook for iOS

		_____________________________

**Comment by opengemara** [comment]
I would appreciate this. A "mother-father-child" diagram is needlessly complicated now:

http://knsv.github.io/mermaid/live_editor/#/view/Z3JhcGggVEQKCkZhdGhlci0uTWFycmllZCAuLT4gTW90aGVyCgoKRmF0aGVyIC0tIEdhdmUgQmlydGggVG8gLS0-IENoaWxkCk1vdGhlciAtLSBHYXZlIEJpcnRoIFRvIC0tPiBDaGlsZA

**Comment by tylerlong** [comment]
Could any one explain what is `connected nodes of the same rank` ?

And why do you think this is "needlessly complicated":

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKCkZhdGhlci0uTWFycmllZCAuLT4gTW90aGVyCgoKRmF0aGVyIC0tIEdhdmUgQmlydGggVG8gLS0+IENoaWxkCk1vdGhlciAtLSBHYXZlIEJpcnRoIFRvIC0tPiBDaGlsZA

How could we improve it? I am sorry but I don't have much background knowledge.

**Comment by DanielBaird** [comment]
@tylerlong usually when you're graphing family relationships, nodes in the same generation (such as husband and wife) should be alongside each other.

"Connected nodes of the same rank" would look like this, where the 'married' link doesn't force the Mother node to a lower position:

```
.--------.                  .--------.
| Father | - - married - -> | Mother |
'--------'                  '--------'
       \                      /
        \                    /
      gave birth to    gave birth to
          \                /
           \              /
            \            /
          .----------------.
          |     child      |
          '----------------'
```

For my use cases, my preferred syntax would let me say something like `sameRank Father Mother`.

**Comment by tylerlong** [comment]
I've got it. I think it is an important feature!

**Comment by guideblade** [comment]
Any update? This feature would really help in creating not ugly flowcharts!

**Comment by CAFxX** [comment]
I opened a new issue for this problem: https://github.com/mermaid-js/mermaid/issues/3723
