### ISSUE TITLE
Latex in charts?

### ISSUE THREAD

**Issue by lyndametref** [knsv/mermaid#420]
I am using mermaid with DiagrammeR in an Rmarkdown file to generate a flowchart. 

Is it possible to include latex inside the flowchart as in the rest of my markdown file?

**Comment by AStupidBear** [comment]
+1

**Comment by haohaoxiao** [comment]
+1

**Comment by aeracode** [comment]
Would be cool

**Comment by hugmanrique** [comment]
Any updates on this?

**Comment by sbussard-google** [comment]
+1
