### ISSUE TITLE
can't catch parse error Maximum call stack size exceeded on safari

### ISSUE THREAD

**Issue by kaqiling** [knsv/mermaid#421]
Hi, I'm using mermaid, but I find a problem in https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L291. When flowchart contains a Chinese symbol like '；'  or '《' ,  Chrome will catch Maximum call stack size exceeded, but Safari will call recursively and comsume memory endlessly,  and I can't do anything on Safari.

**Comment by kaqiling** [comment]
please paste code like 
```
graph LR
A--》B
```
 in http://knsv.github.io/mermaid/live_editor/

**Comment by kaqiling** [comment]
also for #405

**Comment by tylerlong** [comment]
Issue diappeared: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKQS0t44CLQg/error/TGV4aWNhbCBlcnJvciBvbiBsaW5lIDIuIFVucmVjb2duaXplZCB0ZXh0LgpncmFwaCBMUkEtLeOAi0IKLS0tLS0tLS0tLS1e
