### ISSUE TITLE
updating shapes after the flow chart rendering complete

### ISSUE THREAD

**Issue by smurugu** [knsv/mermaid#424]
Hi,

First of all thanks for putting together mermaid; i would like to see whether mermaid can support any interactivity on the shapes. Lets say we have a square box which represents a task; based on the task completion i would like update the shape with a border (green for success and red for failure). Is there a way i can do this in mermaid ?

**Comment by erdalkaraca** [comment]
You can assign a class or ID to your shapes (nodes) and style them using css.

**Comment by tylerlong** [comment]
Yes please read https://mermaidjs.github.io/flowchart.html and check "
Styling and classes" section.
