### ISSUE TITLE
Styling specific lines

### ISSUE THREAD

**Issue by radmilabord** [knsv/mermaid#431]
Is it possible to style specific lines? I can see there is general class for lines but it will apply to all. I'm trying to highlight specific path in the flow chart.

Thanks,
Radmila

**Comment by bfriedz** [comment]
You can already do that.

![screen shot 2017-01-10 at 9 13 53 pm](https://cloud.githubusercontent.com/assets/1695539/21832528/b9757900-d779-11e6-904f-3efe17458cfb.png)

```
graph LR;
        A--v-->B{B}
        B-->|v|C[C]
        B-- x -->Z[E]
        C-->D{D};

        linkStyle 0 stroke-width:2px,fill:none,stroke:blue;
        linkStyle 1 stroke-width:2px,fill:none,stroke:green;
        linkStyle 2 stroke-width:2px,fill:none,stroke:yellow;
        linkStyle 3 stroke-width:2px,fill:none,stroke:pink;
        linkStyle default stroke-width:2px,fill:none,stroke:red;
```

**Comment by 7ynk3r** [comment]
@bfriedz how to change the color of the arrow head?

**Comment by hernaneche** [comment]
Can this be done dinamically?

Related to this issue (having a name for edges) [#583](https://github.com/knsv/mermaid/issues/583)

**Comment by matkoch** [comment]
@bfriedz does this also allow to change the line to be dashed or dotted? I'm also particularly interested in changing the direction of the arrow. For class diagrams, the arrow should usually point to the _base type_, but in this case, the base type would be drawn at the bottom.

**Comment by a-r-m-i-n** [comment]
Is it possible to achieve that a click on a node, highlights all connected lines? I know there are events available, but I don't know how easy it is to identify the connected lines.

**Comment by Grenston** [comment]
the arrow head is not changing colour
i used
`linkStyle default fill:none,stroke-dth:4px,stroke:red`

**Comment by Dunning-Kruger** [comment]
> the arrow head is not changing colour
> i used
> `linkStyle default fill:none,stroke-width:4px,stroke:red`

Hey, @Grenston. Appreciate the report but you're commenting on an old closed issue. Feel free to open a new issue if necessary!
