### ISSUE TITLE
New downstream project: Mermaid Preview for VSCode

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [knsv/mermaid#442]
https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview

Documentation should be updated

**Comment by tylerlong** [comment]
Updated: https://mermaidjs.github.io/

Next time if you want to change the documentation please create an issue here: https://github.com/mermaidjs/mermaid-gitbook
