### ISSUE TITLE
Round nodes cannot be styled with CSS classes

### ISSUE THREAD

**Issue by mowijo** [knsv/mermaid#443]
Trying to style a round node with css class fails. Rectangular and rounded nodes works just fine.

    graph LR;
        A --> B(B)
        B --> C((C))
        classDef yellow fill:#ff0;
        class A,B,C yellow;

does not render A, B and C yellow. Only A and B are filled with yellow:
![image](https://cloud.githubusercontent.com/assets/804889/21425257/5c54d166-c848-11e6-819c-6276cc938a37.png)

If this is intentional, I apologize.

**Comment by RebeccaDreezer** [comment]
I just made a quick PR to fix this: https://github.com/knsv/mermaid/pull/449

**Comment by knsv** [comment]
Ok, just merged that PR!

**Comment by mowijo** [comment]
That is great! 

Thanks for the swift response and I really appreciate the work you do!

**Comment by miclay** [comment]
But it`s still not work here: 
https://knsv.github.io/mermaid/live_editor/
