### ISSUE TITLE
"animation"

### ISSUE THREAD

**Issue by whyzdev** [knsv/mermaid#446]
Some "animation" features, for lacking of better words, will allow diagrams, if defined in such a way, to draw in browser alive gradually/animatedly, by step/part/layer, with/without users control and intervention. I imagine this is useful for presentation, and think it is a major and interesting initiative. What do you think?

**Comment by anatoliykmetyuk** [comment]
This feature would have been very helpful for me.

**Comment by orasik** [comment]
This would be a great feature

**Comment by tylerlong** [comment]
The idea is exciting.

**Comment by maiermic** [comment]
According to [this](https://github.com/mermaid-js/mermaid/issues/1173#issuecomment-786267949) comment in #1173

> As to animation - this is not supported in Mermaid, and there are no plans to introduce this feature in the near future.

However, animations may be added after the diagram has been rendered by mermaid. I've implemented a first version of a [library](https://github.com/maiermic/reveal-md-mermaid-animation-example) that demonstrates how to animate diagrams in ([reveal-md]) presentations using [fragments]. The approach adds classes and data attributes to the rendered graph (SVG) elements. It may also be used in [reveal.js].

[reveal-md]: https://github.com/webpro/reveal-md
[fragments]: https://revealjs.com/fragments/
[reveal.js]: https://revealjs.com/

**Comment by panset** [comment]
For people still landing on this one: "draw gradually, by step, with or without user control, for presentation" exists as a layer on top of Mermaid now — unchanged diagram plus a `scenario` block, output is a self-contained HTML page with presenter mode. Example, a checkout told as happy path and failure path: https://panset.github.io/cinegram/examples/02-storytelling/01-payment-checkout/  (Cinegram, open source, I maintain it; the live discussions are #3029 and #7710.)
