### ISSUE TITLE
Diagonal/angled lines in message sequence diagrams

### ISSUE THREAD

**Issue by raboof** [knsv/mermaid#450]
It would be really cool to support 'diagonal' lines in message sequence diagrams. This could be useful for describing protocols where the actors communicate through messages, and those messages might 'cross each other' in transit.

This has also been discussed in https://github.com/bramp/js-sequence-diagrams/issues/129

**Comment by siddhpant** [comment]
This should be considered. Please open this.

**Comment by Gijom** [comment]
I agree this would be valuable to model distributed systems with variable delays.

**Comment by alonso-herreros** [comment]
I also would like to see this in mermaid, it could be useful to depict transmission protocols where delays must be taken into account. In my case, it doesn't really need to be very accurate, just to depict that delays exists and that actions depend on them

**Comment by maurerle** [comment]
Hello, I would like to relive this issue.
At https://sequencediagram.org/ one can write 

```
title This is a title

Alice->Bob:Click and drag to create a request or\ntype it in the source area to the left
Alice<--Bob:drag to move
note over Bob,Double click to edit text:Click Help menu for **instructions** and **examples**
Bob->(3)Double click to edit text:non-instantaneous message
```

To create this:
![image](https://github.com/user-attachments/assets/ad8765c1-2764-4780-b10a-78a3c6b04b17)


Using the `sender->(delay)receipient:` syntax would be very convenient.

**Comment by grssam** [comment]
+1 
`sender->(delay)recipient` syntax sounds intuitive and doesn't seem to clash with any other syntax for sequence diagrams either.
