### ISSUE TITLE
Can not be generated PNG pictures through CLI with Chinese

### ISSUE THREAD

**Issue by lueliu** [knsv/mermaid#451]
hello ! 
I use mermaid 6.0.0 

Can not be generated PNG pictures through CLI with Chinese.

 these is no any chinese in PNG pictures.

my mermaid file just like:
```
graph LR
%%车辆gps
redis-30[Redis<br>192.168.1.1<br>车辆gps] -- B
```
and then：
```
mermaid -p -o /tmp -w 6000 -e /opt/node-v4.4.7-linux-x64/bin/phantomjs gps.mmd
```

something wrong?

**Comment by lueliu** [comment]
I solved it.  This is my mistake. 
I've added new characters to the configuration file and installed in system.
```
copy new characters to : /usr/share/fonts/chinese/TrueType
# mkfontscale
# mkfontdir
# fc-cache  -fv

and add new characters to config file: ./node_modules/mermaid/dist/{mermaidAPI.js,mermaid.css}
just like: 
font-family: 'trebuchet ms', verdana, arial, '微软雅黑';
```
then I close this issue.

**Comment by knsv** [comment]
ok Thanks.
