### ISSUE TITLE
Related to Issue #329: Phantomjs issues.

### ISSUE THREAD

**Issue by startakovsky** [knsv/mermaid#455]
@ssbarnea thanks for your help in issue #329, I am experiencing problems on an ubuntu machine. Here are the three commands I am running:

```
apt-get install -y nodejs
npm install npm@latest -g
npm install github:knsv/mermaid -g
```

I get an error in the installation as it pertains to `phantomjs` when attempting to run `mermaid -p test.mmg.` Same thing happens after trying `npm install mermaid -g`.

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
