### ISSUE TITLE
Support for notes across multiple participants?

### ISSUE THREAD

**Issue by decentral1se** [knsv/mermaid#458]
Something like:

```
Foo --> Bar
Bar --> Baz
Baz --> Fuzz
Note over Foo, Bar, Baz: The note.
```

Currently only `Note over Foo,Bar: Note` is supported.

**Comment by tompo-andri** [comment]
By the way, why not allowing an horizontal cross-actors note like to separate the sequence diagram into two or displaying different phase of interactions?

```
Foo --> Bar
Bar --> Baz
Baz --> Fuzz
Note over *: The note.
```

**Comment by eddiewebb** [comment]
@lwm you can use 
`Note over First, Last: the note.` to span multiple actors.

**Comment by decentral1se** [comment]
Thanks :+1:

**Comment by hansu** [comment]
> @lwm you can use `Note over First, Last: the note.` to span multiple actors.

But this changes the order of the participants if not defined with `participant` .
