### ISSUE TITLE
Mermaid cli not working for subgraphs

### ISSUE THREAD

**Issue by furstenheim** [knsv/mermaid#459]
Very nice project.
I'm trying to use the mermaid cli for a subgraph but I cannot manage to get it to work

  ```
   graph TB;
      subgraph B;
      C --> D;
      C --> E;
      end;
```

Without the semicolons it works in the live [editor](http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggVEIKICAgICAgICBzdWJncmFwaCBCCiAgICAgICAgQyAtLT4gRAogICAgICAgIEMgLS0-IEUKICAgICAgICBlbmQ)

I've managed to create a simple graph with the cli, so it is correctly installed

**Comment by collingsr** [comment]
I have had this same problem. If I copy and paste the example subgraph from the documentation it works, but as soon as I try to put that subgraph code around my own graph it does not.

Example subgraph (renders correctly): 

```
graph TB
    sq[Square shape] --> ci((Circle shape))

    subgraph A subgraph
        od>Odd shape]-- Two line<br>edge comment --> ro
        di{Diamond with <br/> line break} -.-> ro(Rounded<br>square<br>shape)
        di==>ro2(Rounded square shape)
    end
```
my subgraph (does not render):
```
graph TB
    sq[Square shape] --> ci((Circle shape))
    
    subgraph En Family 
		en1[En]-->en2(Shou)
		en1-->en3[Shin]
			en3[Shin]---en4[No1]
		en1-->en4[No1]
		en1-->en5[Chota]
		en1-->en6[Fujita]
			en6[Fujita]---a7[Matsumura]
		en1-->en7[Matsumura]
		en1-->en8[Ebisu]
			en6[Fujita]---en8[Ebisu]
		en1-->en9[Turkey]
		en1-->en10[Kikurage]
	end
```

**Comment by collingsr** [comment]
The solution/problem is found under issue #231 -- it doesn't like tab characters. Use spaces instead of tabs or just align everything left and it works.

**Comment by tylerlong** [comment]
Please don't end each line with a semicolon. Semicolon is the old syntax which might not work any more.

The following works in both live editor and cliP:

```
graph TB
    subgraph B
        C --> D
        C --> E
    end
```

By the way, here is the new cli project: https://github.com/mermaidjs/mermaid.cli
