### ISSUE TITLE
Phantomjs Dependency

### ISSUE THREAD

**Issue by XiaoZYang** [knsv/mermaid#461]
I install `mermaid` with command `$ npm install mermaid -g` . When I run it with command `mermaid $ftest_ile` I got this error:
![2017-01-19 4 48 25 pm](https://cloud.githubusercontent.com/assets/8848479/22099638/227ce9da-de67-11e6-8f0a-c07682636225.png)

Then I try `npm install phantomjs` and it works.
Now, I am wondering it is a bug or wrong configuration in `package.js`(I found **"phantomjs":"^2.1.3"** in `package.js`).
THX!

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
