### ISSUE TITLE
Mermaid js increase viewbox size in css

### ISSUE THREAD

**Issue by shreyapandey** [knsv/mermaid#463]
Hi, 
how can I increase the viewbox size in the css itself? I have checked but its getting generated from the JS itself. Is there any way to fix it? I want to explicitly define the viewbox size so that my flowchart fits the screen. Please help.

**Comment by vikram-rawat** [comment]
I too want to control size of Mermaid Nodes and Boxes is there any better way to doing it. Rather than css.
