### ISSUE TITLE
Styling backwards links

### ISSUE THREAD

**Issue by JayWaWa** [knsv/mermaid#464]
Hello, 

I read in the documentation that it's somehow possible to style a link that runs backwards, but I was unable to find how to do so in the documentation or in any of the previously posted issues. How exactly does one achieve the styling of links that run backwards?

thanks!

**Comment by bradmcl** [comment]
Or could we possibly have actual backward and bidirectional links in the flowchart?  So not just --- and --> but <-- and <-> as well?  Same layout rules, just different renderings.

**Comment by tylerlong** [comment]
You can try `graph RL` but it will make all links backwards.
