### ISSUE TITLE
Adding a HTTP link to a node description breaks the graph

### ISSUE THREAD

**Issue by wsw70** [knsv/mermaid#467]
I would like, to the graph below ([also available via a JSFiddle](https://jsfiddle.net/ntwo6w88/))

    <link href="https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.0/mermaid.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.0/mermaid.js"></script>
    <div class="mermaid">
      graph TD; 
      A[hello] 
      B[an <b>important</b> link] 
      A-->B
    </div>

to add an actual link under `link` pointing to `http://google.com`.

I tried to modify the relevant node to 

    B[an <b>important</b> <a href="http://google.com">link</a>] 

but this breaks (crashes) the graph. Specifically, I noticed that what is not accepted is the `href` element.

**Is it possible to add a link in a mermaid node?**

_Note: this report was initially asked as [a question on SO](http://stackoverflow.com/questions/41960529/how-to-add-a-link-in-a-mermaid-node) but since other HTML tags are accepted it may rather be a bug._

**Comment by AidanVIII** [comment]
I identified the carrets as a breaking factor in the live editor.

You could use onclick event as per the [documentation](http://knsv.github.io/mermaid/#styling-and-classes), but this doesn't provide for accessibility or SEO.

And I see this has been root for a few other issues in the past: 
- [Support for hyperlink and tooltip](https://github.com/knsv/mermaid/issues/34)
- [Add a click style](https://github.com/knsv/mermaid/issues/426)

Since we can't escape them and  text link also don't make for a great UI anyway, how about a way to put the link around the node?

`<a href="w3.org">
	<rect></rect>
</a>`

or

`<a href="w3.org">
	<g class="node">
		<rect></rect>
	</g>
</a>`

If someone would point me toward the parts of the application that this solution would concern, I would happily help looking into it.

**Comment by tylerlong** [comment]
I can reproduce the issue. I will take a look when I finish the other tasks on hand.

**Comment by samuei** [comment]
Removing the quotes [works on the live editor](https://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggVEQ7IAogIEFbaGVsbG9dIAogIEJbYW4gPGI-aW1wb3J0YW50PC9iPiA8YSBocmVmPWh0dHA6Ly9nb29nbGUuY29tPmxpbms8L2E-XSAKICBBLS0-Qg) and for me locally. The Fiddle doesn't accept it, but that's probably a parsing mistake on their end.

**Comment by wsw70** [comment]
@samuei your hack fixes the immediate issue (the link is cliackable) but breaks the `display: grid` layout (cc: @tylerlong)

**Comment by alexrowesoap** [comment]
Hey all. I got links working.
questionA{"&lt;a href&#61;&#39;https://google.com&#39;&gt;Google link here&lt;/a&gt;"}

setup was
 mermaid.initialize({startOnLoad: true, htmlLables: true});
This doesnt work on the live editor though.

**Comment by alexrowesoap** [comment]
As an aside, it seems that brackets (), encoded or not, break the flowchart. The only solution that worked for me was to escape them to unicode brackets.

**Comment by tylerlong** [comment]
@wsw70  Could you please post a demo link using https://mermaidjs.github.io/mermaid-live-editor/? I don't quite understand the display:grid layout issue.

> @samuei your hack fixes the immediate issue (the link is cliackable) but breaks the display: grid layout (cc: @tylerlong)

**Comment by fullergalway** [comment]
This also works, (though sometimes need to respace when editing).
```
graph TD
Ready? -->|try this| B[click <a href=http://google.com>here</a>!!]
```
[Try it here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblJlYWR5PyAtLT58dHJ5IHRoaXN8IEJbY2xpY2sgPGEgaHJlZj1odHRwOi8vZ29vZ2xlLmNvbT5oZXJlPC9hPiEhXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Comment by pleabargain** [comment]
> This works (by using same http/https protocol as the page itself):
> 
> ```
> graph TD
> Ready? -->|try this|B[click <a href=//github.com/knsv/mermaid/issues/467>here</a>!!]
> ```
> 
> [See for yourself](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblJlYWR5PyAtLT58dHJ5IHRoaXN8QltjbGljayA8YSBocmVmPS8vZ2l0aHViLmNvbS9rbnN2L21lcm1haWQvaXNzdWVzLzQ2Nz5oZXJlPC9hPiEhXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

Not working 2022 May 1 on chrome Version 101.0.4951.41 (Official Build) (64-bit)

**Comment by jhaoheng** [comment]
Hi 

How to click the BTN and open another window?

**Comment by benrosen-moodys** [comment]
> but this breaks (crashes) the graph. Specifically, I noticed that what is not accepted is the `href` element.

Even more specifically, it seems to be the double-quotes that crash the graph (not the `href` element).

Using single-quotes works for me in WebStorm.

Here on GitHub, this:

```text
graph TD
B[an <b>important</b> <a href='http://google.com'>link</a>] 
```

renders like this:

```mermaid
graph TD
B[an <b>important</b> <a href='http://google.com'>link</a>] 
```
