### ISSUE TITLE
live editor: the svg file rendered from graph is not supported by browsers

### ISSUE THREAD

**Issue by jesponde** [knsv/mermaid#468]
Hi,

I noticed an issue with the live editor so here is a description of it.
When I try to render a simple graph like this:

```mermaid
graph LR
A --> B
A --> C
A --> D
```
The text is not displayed by browsers like IE or Firefox.
The rendering of the example sequence diagram works well.

Is this something specific to my computer or one have also this issue?

**Comment by MapBakery** [comment]
I have exactly the same issue on the two browsers I use (FireFox and Internet Explorer 11). The text is in the file because [svg-edit](https://github.com/SVG-Edit/svgedit) does show the text (a bit ugly).

**Comment by yudenzel** [comment]
Firefox v49.0.2 looks good.

![firefox](https://cloud.githubusercontent.com/assets/4387218/24574792/ae21643e-16ca-11e7-9974-a8da33224139.png)

**Comment by jesponde** [comment]
Hi yudenzel,
Thanks for the information! It works for me now! (Firefox 52)
But I guess this is actually solved by a renderer engine update in the server side.

**Comment by tylerlong** [comment]
We've decided to give up IE browser. We do want to support Microsoft Edge.

Feel free to reopen this issue if you still have issue view the diagram in any mainstream browsers other than IE: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKQSAtLT4gQgpBIC0tPiBDCkEgLS0-IEQ
