### ISSUE TITLE
CSS stroke-dasharray ignored by browsers but not other viewers

### ISSUE THREAD

**Issue by Alxandr** [knsv/mermaid#474]
The following diagram
```mermaid
sequenceDiagram
A--> B: 1
A-> B: 2
```

However, in the output produced, I get both styled (by css) with `stroke-dasharray`:
```
.messageLine0 {
  stroke-width: 1.5;
  stroke-dasharray: "2 2";
  marker-end: "url(#arrowhead)";
  stroke: #333;
}
```

The dasharray set to `"2 2"` is ignored by browsers however, because it's invalid:

![image](https://cloud.githubusercontent.com/assets/112334/22727208/e5bddaec-edd7-11e6-9368-be0336cf2849.png)

My problem is that inkscape is not ignoring this dasharray. Is there any reason for it being there?

**Comment by tylerlong** [comment]
The style is override by inline style:

![image](https://user-images.githubusercontent.com/733544/37556104-0c9fd4c6-2a2c-11e8-946f-194824404d67.png)

 > Is there any reason for it being there?

Because he who creates the theme put it there :) 

You can update the theme to remove it: https://github.com/knsv/mermaid/tree/master/src/themes
