### ISSUE TITLE
CSS marker-end prevents marker-end in inkscape

### ISSUE THREAD

**Issue by Alxandr** [knsv/mermaid#475]
The css property `marker-end` stops the `line` property `marker-end` from working in inkscape.

**Comment by tylerlong** [comment]
I don't quite understand the issue. Is it because the SVG produced by mermaid is non-standard or is it an inkscape issue?

**Comment by Alxandr** [comment]
It's been over a year since I looked at this (because I got it working). But what I did to get it working was remove `marker-end` and `stroke-dasharray` from the generated SVG before piping it to `inkscape`. You can see the source here: https://github.com/Alxandr/pandoc-mermaid/blob/master/src/Text/Pandoc/Mermaid/Run.hs#L82

I no longer remember why though. I've not used it in a year.
