### ISSUE TITLE
How to display "-" in sequence participant

### ISSUE THREAD

**Issue by zjiemain** [knsv/mermaid#476]
sequenceDiagram
  participant I-CSCF
  participant SLF
  participant HSS

[Mermaid]Lexical error on line 2. Unrecognized text.
...agram  participant I-CSCF  participant
----------------------^

**Comment by tristan-lescut** [comment]
I just had the same issue, you can use aliases for that:
sequenceDiagram
participant ICSCF as I-CSCF
ICSCF ->> OtherParticipant: Hello
