### ISSUE TITLE
Mermaid resets some of the page CSS styles

### ISSUE THREAD

**Issue by anatoliykmetyuk** [knsv/mermaid#482]
```html
<head>
  <!-- ... -->
  <link rel="stylesheet" href="/assets/css/all.css">
  <link rel="stylesheet" href="https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.css">
  <script src="https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.min.js"></script>
  <script>mermaid.initialize({startOnLoad: true;});</script>
</head>
<body>
<div class="mermaid">
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</div>
<h1>Foo</h1>
```

The page is deployed on a local Jekyll server. The `h1` styling set by `all.css` is displayed correctly up until the point when the graph is rendered. The behavior is hard to reproduce: I was not able to reproduce it outside of my own [blog](https://github.com/anatoliykmetyuk/anatoliykmetyuk.github.io) served locally via Jekyll. Given this, can you please suggest a quick fix that would guarantee that mermaid will have absolutely no effect beyond a tag I have specified? I do not want it to influence anything else but the contents of the tag I am trying to render.

**Comment by anatoliykmetyuk** [comment]
I have created a [repository](https://github.com/anatoliykmetyuk/mermaid-482-reproduction) that reproduces this bug.

Steps to reproduce:

1. `clone https://github.com/anatoliykmetyuk/mermaid-482-reproduction.git`
2. `cd mermaid-482-reproduction`
3. `bundle exec jekyll serve`
4. Navigate to `localhost:4000`
5. Look closely at the large "Foo" text below the graph. Before the graph is rendered, it is displayed in large font, after - in small.
6. Remove [this](https://github.com/anatoliykmetyuk/mermaid-482-reproduction/blob/master/_layouts/default.html#L26) div. Reload the page. Notice how "Foo" displayed in large text.

Relevant lines of code: [3 lines here](https://github.com/anatoliykmetyuk/mermaid-482-reproduction/blob/master/_layouts/default.html#L21), [2 lines here](https://github.com/anatoliykmetyuk/mermaid-482-reproduction/blob/master/_layouts/default.html#L26).

Also: if you remove [this](https://github.com/anatoliykmetyuk/mermaid-482-reproduction/blob/master/_layouts/default.html#L20) line that requests CSS and reload the page, the page will not be styled, but the graph will not change the styling on load.

Any ideas why this happens and how to fix?

**Comment by anatoliykmetyuk** [comment]
Removing `body, div, span` from [this](https://github.com/anatoliykmetyuk/mermaid-482-reproduction/blob/master/_includes/css/base.css#L28) line seems to have solved the issue. Strange.

**Comment by knsv** [comment]
Glad to hear that it now works for you. I can't say that I see any obvious reason for why it failed without digging deeper.

Get Outlook for iOS




On Thu, Feb 23, 2017 at 8:58 PM +0100, "Anatolii Kmetiuk" <notifications@github.com> wrote:












Removing body, div, span from this line seems to have solved the issue. Strange.

**Comment by itamarst** [comment]
Passing in option `cloneCssStyles: false` in the configure object passed to `mermaid.initialize()` fixes a similar problem for me.

**Comment by StingyJack** [comment]
I had a different element style collision with bootstrap - bootstrap was overriding the styles used by the rendered svg. I ended up commenting out the bootstrap.less styles that I didnt need and run a gulp-less on that.

**Comment by tylerlong** [comment]
The issue has been fixed.  Now all mermaid CSS are scoped within its own ID so it won't pollute global CSS.
