### ISSUE TITLE
Menu and layout bugs in docs

### ISSUE THREAD

**Issue by cnanney** [knsv/mermaid#484]
https://knsv.github.io/mermaid/

Erratic menu behavior, using Chrome 56:

![merm](https://cloud.githubusercontent.com/assets/195134/23527922/79c8b19e-ff5d-11e6-8295-d6fb1c0ae038.gif)

Body text also gets partially covered by menu.

**Comment by saveman71** [comment]
I'm pretty sure it's been introduced by fb70b9742a22f8673cdd3a8d74fcbbc6ea03b432 (at least the overflow problem), since the page is good until the section of usage.md that was modified in this commit 
(cc @knsv)

**Comment by tylerlong** [comment]
Docs has been moved to https://github.com/mermaidjs/mermaid-gitbook
