### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by cuiweiqiang** [knsv/mermaid#485]
In Node REPL when I type `const mermaid = require('mermaid');` it tell me     
> ReferenceError:
 window is not defined
    at new Log (/[my project]/node_modules/mermaid/src/logger.js:87:18)
    at Object.<anonymous> (/[my project]/node_modules/mermaid/src/mermaid.js:8:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:17

And I try to install it with these ways: 
    `npm install mermaid` 
    `npm install git+https://github.com/knsv/mermaid.git`
but it still not work. 

My Node version is `v7.7.1`, 
 and npm version is `4.1.2`

**Comment by szaliszali** [comment]
You should not require('mermaid') in a node environment. It requires a web browser (or a headless browser like PhantomJS).

Depending on your goal, you may or may not succeed by using its subcomponents as a library (see https://knsv.github.io/mermaid/#development11).
Alternatively, you can use the bundled CLI tool as an external process.

**Comment by tylerlong** [comment]
Version 7.1.0 allows you to use mermaid in node directly.(but you still need a browser environment in order to render).

Example: https://github.com/mermaidjs/mermaid-live-editor/blob/fe51c26ecf77027fd882af0c6034b1c99c555601/src/components/Preview.js#L6

**Comment by Schachte** [comment]
@tylerlong Why did this lose support in the v8 release?

**Comment by elgunhuseynli** [comment]
@tylerlong  Still cannot use in NodeJS :(

**Comment by Schachte** [comment]
:(

**Comment by davibe** [comment]
I wanted to use mermaid JS while transpiling markdown to html+js+css. During transpilation I do not have a browser environment available (normally).
