### ISSUE TITLE
Gant PNG margin 

### ISSUE THREAD

**Issue by 7ynk3r** [knsv/mermaid#486]
Hi there!

I'm using the following markdown 
```
gantt
    dateFormat  YYYY-MM-DD
    title Interactions & Actions

    section Responses
    init       :a1, 2010-01-01, 5ss
    request data       :a2, after a1, 10ss
    render     :a3, after a2, 3ss

    section Dashboards
    init       :d1, 2010-01-01, 2ss
    request data1       :d2, after d1, 7ss
    request data2       :d3, after d1, 9ss
    render     :d4, after d3, 4ss
    sumit     :d5, after d4, 1ss

    section Zaraza
    init       :d1, 2010-01-01, 2ss
    request data1       :d2, after d1, 7ss
    request data2       :d3, after d1, 9ss
    render     :d4, after d3, 4ss
    sumit     :d5, after d4, 1ss
```

and generating a PNG using (nothing special)
```
mermaid ./assets/*.mmd -p -o ./assets
```

The result is the following
![arc_instrumentation_interactions_actions mmd](https://cloud.githubusercontent.com/assets/6763798/23718417/3df3393a-03ec-11e7-9503-9101c898f04a.png)

You can notice a lot of white space in the sides.

Am I missing some configuration? Is there any workaround?

BTW, I love mermaid!

Thanks!
JM

**Comment by LasseJacobs** [comment]
I have the same issue, very annoying. I can find a solution anywhere...

**Comment by tylerlong** [comment]
Try the latest command line tool https://github.com/mermaidjs/mermaid.cli

And create a new issue if it doesn't work.
