### ISSUE TITLE
Very different styles when rendering as png vs. svg

### ISSUE THREAD

**Issue by StingyJack** [knsv/mermaid#489]
I get very different looking results when using the on-page render as svg vs. calling the cli for the same graph text.  Is there a way to get these more consistent looking (more like the svg if possible but either way is better than current)?

Diffs
-  transparent svg background
- node color
- subgraph background color
- subgraph text color (also text and line collision, but thats different)

As CLI rendered image
![image](https://cloud.githubusercontent.com/assets/15381181/23796161/87ffe790-0567-11e7-9e49-f137b9832488.png)

As on page svg...
![image](https://cloud.githubusercontent.com/assets/15381181/23796198/acd08dae-0567-11e7-9d91-2fa77a5a87d5.png)

**Comment by yudenzel** [comment]
It looks like these two images were rendered with different theme, default and forest.

To change theme applied to svg output on web, just introduce the css file you want, options available under `dist/mermaid.*.css`.

I don't know how to change/apply theme for CLI output.

**Comment by tylerlong** [comment]
Yes, the are two different themes. You can change the theme with the new CLI: https://github.com/mermaidjs/mermaid.cli
