### ISSUE TITLE
Any plans for adding a typescript definition file?

### ISSUE THREAD

**Issue by StingyJack** [knsv/mermaid#495]
I think I kind of need one, and I'd like to avoid duplicating work if there is already one available (even partially) anywhere.

**Comment by tylerlong** [comment]
Nope, it seems that nobody is working on it.

But mermaid's API is crazy simple. I only use these two:

- `mermaid.initialize`
- `mermaid.init`

You can go ahead and create TS definition for them.

**Comment by hydrosquall** [comment]
There's now an community maintained TS file: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mermaid/index.d.ts

**Comment by nkuehn** [comment]
PS on closed issue: The developer experience  of creating custom themes would profit a lot from an officially maintained type declaration for the config.  The community maintained file is unfortunately far from complete or correct in the Config object. 

The top level API is "dead simple", sure.  The full nesting of the configuration and theming variables is everything but dead simple.
