### ISSUE TITLE
Export to pdf on website

### ISSUE THREAD

**Issue by thorst** [knsv/mermaid#496]
I'm trying to take the diagram and put it in a pdf. Any direction would be helpful.

I think it may be easier to generate a png or jpg on the website in mermaid, is that possible? I've tried to add the svg to the pdf and haven't been successful. I've also tried to take the long route and convert the svg to canvas and then to png and that hasn't gone well.

Ive been playing with pdfKit and jsPdf. I have the basic generation of the pdf fine it just that I cant get the mermaid diagram on the pdf.

**Comment by sooraj771989** [comment]
Did You Get the solution for this ? Please help me out

**Comment by thorst** [comment]
I'll post more details in a bit but basically I used pdfkit and then used
svg-to-pdfkit and that worked.

I would still like to know how to get a png out.

What are you trying to do?

**Comment by tylerlong** [comment]
There is a **manual** way: display mermaid charts in Chrome browser, then print the page, select destination as "save as PDF".

![image](https://cloud.githubusercontent.com/assets/733544/25159007/30a60e56-24df-11e7-9a25-d85be3ea22cc.png)

**Comment by thorst** [comment]
Using https://github.com/alafr/SVG-to-PDFKit and https://mozilla.github.io/pdf.js/

Semi-pseudo code
```
    <script src="~/Scripts/lib/SVG-to-PDFKit/pdfkit.js"></script>
    <script src="~/Scripts/lib/SVG-to-PDFKit/blobstream.js"></script>
    <script src="~/Scripts/lib/SVG-to-PDFKit/source.js"></script>

blobToBase64= function (blob, callback) {
        // Borrowed
        var reader = new FileReader();
        reader.onload = function () {
            var dataUrl = reader.result;
            var base64 = dataUrl.split(',')[1];
            callback(base64);
        };
        reader.readAsDataURL(blob);
    };
    Base64toArrayBuffer= function (base64_string) {
        // Borrowed
        var raw = window.atob(base64_string);
        var rawLength = raw.length;
        var array = new Uint8Array(new ArrayBuffer(rawLength));

        for (var i = 0; i < rawLength; i++) {
            array[i] = raw.charCodeAt(i);
        }
        return array;
    };

let doc = new PDFDocument({ compress: true });

let hiddenDiv = $("#hidden-div").html('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">' + app.mermaid.html + '</svg>');
            SVGtoPDF(doc, hiddenDiv[0].firstChild, doc.x, doc.y, { useCSS: true });
            doc.y = doc.y + (parseFloat($("#mermaidId0").attr("height")) * 72 / 96) // Best solution provided by developer

// Works on blob
        let stream = doc.pipe(blobStream());
        // Events are: "finish", "Data", "end"
        stream.on('finish', function () {

            // Convertintg blob to base64
            let blob = stream.toBlob('application/pdf');
            app.documentation.blobToBase64(blob, function (d) {

                // Put in global
                app.documentation.base64 = d;

                // Display in viewer
                var raw = app.documentation.Base64toArrayBuffer(app.documentation.base64);
                PDFViewerApplication.open(raw);

                // Overwrite filename for saving
                PDFViewerApplication.url = app.interface.current.name + ".pdf";
            });
        });

        // Close pdf document
        doc.end();
```

 app.mermaid.html is a variable that contains the html of the mermaid. Basically i get the base64 pdf and save that off to a database for a revision history, I also render it using pdf.js (PDFViewerApplication).
