### ISSUE TITLE
Graphviz DOT syntax

### ISSUE THREAD

**Issue by timdp** [knsv/mermaid#5]
It looks like Mermaid is in many ways similar to Graphviz's [DOT language](http://www.graphviz.org/Documentation/dotguide.pdf). I just came across [Viz.js](https://github.com/mdaines/viz.js/), which attempts to bring that to the Web. Any reason you're not adopting DOT syntax? It seems like it would be more useful to collaborate on this.

**Comment by greacen** [comment]
:+1: for DOT support. Even if this is an add-on. Seems like there's some similarities with the relationship notation you've done for mermaid. Though I agree with the sentiment of most of these comments, I still think there's room for a new (more web-centric?) approach to making these kind of graph notations clear, useful, and interconnected with more data.

**Comment by tylerlong** [comment]
Close it. Since it is a question and there hasn't been active activity here for almost 3 years.

**Comment by Utopiah** [comment]
Naive question as I'm just discovered the project but mermaid depends on `graphlib` and graphli` does have a [DOT parser](https://github.com/dagrejs/graphlib-dot) so I'm wondering if it's now being support and if not, what's blocking?

**Comment by ooker777** [comment]
> "Although in Science they have seen further by standing on the shoulders of giants; in computing, we mostly stand on each other's feet." -- Richard Wesley Hamming

FWIW [I'm unable to confirm if this quote was actually said by him](https://www.google.com/search?client=firefox-b-d&q=%22Although+in+Science+they+have+seen+further+by+standing+on+the+shoulders+of+giants%3B+in+computing%2C+we+mostly+stand+on+each+other%27s+feet.%22+--+Richard+We). Nevertheless [he did say this](https://en.wikiquote.org/wiki/Richard_Hamming#One_Man's_View_of_Computer_Science_(1969)):
> Indeed, one of my major complaints about the computer field is that whereas Newton could say, "If I have seen a little farther than others, it is because I have stood on the shoulders of giants," I am forced to say, "Today we stand on each other's feet." Perhaps the central problem we face in all of computer science is how we are to get to the situation where we build on top of the work of others rather than redoing so much of it in a trivially different way. Science is supposed to be cumulative, not almost endless duplication of the same kind of things.

**Comment by ooker777** [comment]
Anyway, I wonder why there isn't a tool to convert mermaid and dot formats online?

**Comment by timdp** [comment]
There's at least one: https://kroki.io/

**Comment by jasonm23** [comment]
I mean there's github. 👍🏻
