### ISSUE TITLE
Styling label texts

### ISSUE THREAD

**Issue by szilardhuber** [knsv/mermaid#50]
If I am right styling label text is not quite possible right now. For me replacing `<span style="background:#e8e8e8">` in main.js to `<span class="mermaid-label">` solves the problem but in this case to stay compatible with the current output a default .css file should be added to the project.

Am I using it wrong or a PR like that would be welcome?

**Comment by knsv** [comment]
@bjowes: Any news for this one?

**Comment by bjowes** [comment]
No significant progress yet due to lack of time. I am still planning to complete it eventually, but if someone else is interested in contributing, I would happily share my thoughts on how we can achieve this.

**Comment by knsv** [comment]
@bjowes any progress on this one?

**Comment by Daijobou** [comment]
Same question here. :)

I want give labels the same color-style of lines between nodes.

**Comment by knsv** [comment]
There is a variable for this in the themes, edgeLabelBackground. This is for the text labels. I am closing this overdue issue. I am trying to cleanup the issues. If there still is an issue, repoen it or create a new on for the specific issue. Thnks
