### ISSUE TITLE
How do I get the log for a render or parse attempt?

### ISSUE THREAD

**Issue by StingyJack** [knsv/mermaid#500]
I want to capture and display errors/diagnostics to users.

Most of the library/API uses a Logger that eventually binds to window.console.debug. I've tried a few things to intercept this in-browser and cant get it to work. If I perform the request server-side, I can call the CLI and capture stdout (there isn't a stderr for errors), just not in the browser.

Is there a recommended way to get this info from the API?

**Comment by tylerlong** [comment]
If want you want is the errors, you can take the live editor as an example: https://mermaidjs.github.io/mermaid-live-editor/

It shows you live error report when you make a syntax mistake: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVApBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZykKQiAtLT4gQ3tMZXQgbWUgdGhpbmt9CkMgLS0-fE9uZXwgRFtMYXB0b3BdCkMgLS0-fFR3b3wgRVtpUGhvbmVdCkMgLS0-fFRocmVlfCBGW0Nhcl0K/error/UGFyc2UgZXJyb3Igb24gbGluZSAxOgpncmFwaCBUQVtDaHJpc3RtYXNdIC0tPnxHCi0tLS0tLV4KRXhwZWN0aW5nICdESVInLCAnVEFHRU5EJywgJ1RBR1NUQVJUJywgJ1VQJywgJ0RPV04nLCBnb3QgJ0FMUEhBJw

You can simply try catch to get the error message: https://github.com/mermaidjs/mermaid-live-editor/blob/fe51c26ecf77027fd882af0c6034b1c99c555601/src/components/Preview.js#L28-L34
