### ISSUE TITLE
logLevel's option doesnt work at 7.0.0

### ISSUE THREAD

**Issue by suziwen** [knsv/mermaid#501]
mermaid's version 7.0.0

devTool always print debug info, no matter how logLevel is set
``` javascript
 mermaid.initialize({
    logLevel: 4
})
```

![image](https://cloud.githubusercontent.com/assets/57370/24535374/4846012e-1599-11e7-84dc-ba7bcfcbc45a.png)

**Comment by knsv** [comment]
I see the problem and will fix it.

**Comment by tylerlong** [comment]
Issue had been fixed.
