### ISSUE TITLE
Problem showing graph with php on localhost

### ISSUE THREAD

**Issue by fmerciergh1** [knsv/mermaid#502]
Hello,

I have a local XAMP host used for development. I did a test.html (very simple test) with a very basic Mermaid graph, and it works well. However, when I copy the **exact** content of that file into a php file (test.php), the graph is not showing (it shows the content of the div... as if the javascripts where not there or no good). Links to file are good hence they don't change between .html and .php. Other content of the php shows well, php code run well, etc).

Tried with many browsers, cleared cache. Same problem.

Here you can see the content of the files (both files works on remote server... the problem is only when trying to run on my local xamp installation...) 

http://akua.ca/test/test.html
http://akua.ca/test/test.php

Any clue? Txk.

**Comment by yudenzel** [comment]
It looks both links show the same content.

**Comment by fmerciergh1** [comment]
Yes, as specified, it works well on remote server, but on my local xamp installation, I don't see the graph at all with php file, only html file works.

With php, I see the DIV content only (textualy, as if not javascipt was enable, but javascript is enebled in all my browsers).

**Comment by tylerlong** [comment]
I am afraid that we are unable to help since it seems to be your local xamp env issue.
