### ISSUE TITLE
layout of docs page looks broken

### ISSUE THREAD

**Issue by yudenzel** [knsv/mermaid#504]
Seems that the layout was broken by some code from section `Labels out of bounds`

http://knsv.github.io/mermaid/#simple-usage-on-a-web-page

![image](https://cloud.githubusercontent.com/assets/4387218/24675914/802c8694-19b3-11e7-8edc-470d6a9d29f2.png)

**Comment by yudenzel** [comment]
Hi @knsv ,

How should we convert the md files in `docs/content` into html pages?

**Comment by tylerlong** [comment]
Doc has been moved to https://github.com/mermaidjs/mermaid-gitbook
