### ISSUE TITLE
add function rendering mermaid syntax to html string without replacing html objects

### ISSUE THREAD

**Issue by iansowinski** [knsv/mermaid#506]
I think a lot of people could possibly benefit from mermaidAPI.render() function having more flexibility when it comes to rendering options. Last two days I had to hack mermaidAPI.render() to get just rendered string (to use it with Vue.js). Here what I discovered:

- The first time it renders correctly, each next time it raises error:
```js
mermaidAPI.render(NaN, string, function(graph){console.log(graph)})
```
- Raises error every time:
```js
mermaidAPI.render(null, string, function(graph){console.log(graph)})
```
- Sometimes raises error, sometimes not (not sure how it works):
```js
mermaidAPI.render(undefined, string, function(graph){console.log(graph)})
```
- Renders for the first call, after it raises error, that it cant find "#string" (without #string in html):
```js
mermaidAPI.render("string", string, function(graph){console.log(graph)})
```
- Raises error only if first letter of generated string is digit:
```js
var hack = Math.random().toString(36).substring(7)
mermaidAPI.render(hack, string, function(graph){console.log(graph)})
```
- We use this solution, and it's working well so far:
```js
var hack = Math.random().toString(36).substring(7).replace(/\d/, "a")
mermaidAPI.render(hack, string, function(graph){console.log(graph)})
```

Our problem: we need onclick refreshing string witch communicates well with vue.js (we pass output in callback function to vue data object. There is no mermaidAPI function for that so we had to hack render function, but it occurs it acts very unpredictable  depending on what JS object is passed to the first variable.

The best possible solution would be function witch just renders the graph, without trying to replace div with given id every time called.

**Comment by yudenzel** [comment]
The first argument of `mermaidAPI.render()` of 5th and 6th code blocks should be `hack`?

**Comment by iansowinski** [comment]
@yudenzel yeah, sorry I corrected it :)

**Comment by iansowinski** [comment]
Oh, it's not working anymore in mermaid 7.1. Not sure what changed, because of lack of changelog :/

**Comment by tylerlong** [comment]
mermaid was not designed as a node library. So it is closely coupled to browser and DOM. The ultimate solution would be like this:

```js
const svgString = mermaid.render('Your graph code here...')
```

And it should also work in a pure node env without browser.

Recently I've been thinking about it.

**Comment by iansowinski** [comment]
It could be great tip for modern front-end frameworks based on virtual-dom (like React or Vue).

**Comment by futurist** [comment]
I'm also struggled with this API, which seems buggy, as below demo:

https://stackblitz.com/edit/react-ocgzkn?file=index.js

1. After first time rendering, change text, the result become empty.

2. Then after that, change text, result ok

I think it's due to some issue related to mermaid?

**Comment by strangedev** [comment]
Why is this closed? This would be a very handy function to have, as it is very complicated at the moment to get mermaid to work correctly in React.
