### ISSUE TITLE
issue when using sphinxcontrib-mermaid extension for sphinx

### ISSUE THREAD

**Issue by thjensuit** [knsv/mermaid#507]
Hi everyone,

I have installed sphinxcontrib-mermaid extension as the following guide: https://github.com/mgaitan/sphinxcontrib-mermaid

in a "mermaid-template.rst" file I made a code such below
```
Mermaid Template
#################

.. mermaid::

    graph LR
    A[Hard edge] -->B(Round edge)
        B --> C{Decision}
        C -->|One| D[Result one]
        C -->|Two| E[Result two]

```

When running sphinx that threw a warning such below and the flowchart was not generated: 

> warning: command 'mermaid' cannot be run (needed for mermaid output), check the mermaid_cmd setting.

After that I still installed `mermaid-cli` as the following guide: https://knsv.github.io/mermaid/#mermaid-cli8

But the warning was still exists and was not generated the flowchart.
May anyone help me in this case?

P.S: 
+ OS: window 8.1
+ Sphinx: 1.4.8
+ PhantomJS: 2.1.1
+ Mermaid setup success with command such as `mermaid template.mmd` or `mermaid --help`

Thank you for your watching,
Best Regards

**Comment by mgaitan** [comment]
hey @thjensuit, please open this issue in the sphinx-mermaid's tracker, https://github.com/mgaitan/sphinxcontrib-mermaid/issues

meanwhile, could you find the absolute path of mermaid command, and set this as the `mermaid_cmd` variable in your project's `conf.py`?

**Comment by thjensuit** [comment]
Moved to https://github.com/mgaitan/sphinxcontrib-mermaid/issues/4

**Comment by tylerlong** [comment]
mermaid command line has been moved to https://github.com/mermaidjs/mermaid.cli. 

Please let me know if you have problem making it work.
