### ISSUE TITLE
phantomjs renamed to phantomjs-prebuilt

### ISSUE THREAD

**Issue by yudenzel** [knsv/mermaid#508]
Following npm warning was reported while executing `npm install`.
```
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```

Is it necessary/needed to update the package.json?

**Comment by tylerlong** [comment]
We do not use PhantomJS any more. Ref: https://github.com/mermaidjs/mermaid.cli
