### ISSUE TITLE
CDN is not working

### ISSUE THREAD

**Issue by iansowinski** [knsv/mermaid#511]
as for now both https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.min.js and https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.css are not working

**Comment by tylerlong** [comment]
It works for me at the moment.

CDN service is provide by rawgit for free. If you still have issues, please create an issue here: https://github.com/rgrove/rawgit
