### ISSUE TITLE
Conflict while using mermaid along with core-js

### ISSUE THREAD

**Issue by jibesh** [knsv/mermaid#512]
Hi,
I am trying to use mermaid with core-js https://github.com/zloirock/core-js and is facing some interference. When using core-js alone, the identifier _ refers to an Object. If I also include mermaid (v7.0.0) along with core-js, the identifier gets overwritten by a Function. The order of inclusion for mermaid does not matter.
The following code snippets depict what I mean.

Only using core-js
```javascript 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.min.js"></script>
typeof _; // "object"
```
Using mermaid and core-js
```javascript 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.0/mermaid.min.js"></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.min.js"></script> 
typeof _; // "function"

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.min.js"></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.0/mermaid.min.js"></script> 
typeof _; // "function"
```

**Comment by tylerlong** [comment]
I am going to migrate mermaid to ES6 + webpack. By then there will be simple solution to this problem. Please hold off.

**Comment by tylerlong** [comment]
I confirm I can reproduce the issue.

**Comment by tylerlong** [comment]
The `_` from mermaid is lodash:

![image](https://cloud.githubusercontent.com/assets/733544/26758247/2f5e3ac8-490b-11e7-8f5c-8c0853ee91c5.png)

**Comment by tylerlong** [comment]
Fixed.

Try latest version: https://unpkg.com/mermaid@7.0.3/dist/mermaid.min.js
