### ISSUE TITLE
Interactivity for elements in a sequence diagram  ..

### ISSUE THREAD

**Issue by maxMidius** [knsv/mermaid#513]
Is there any way we can add links to boxes within sequence diagrams - similar to the support you have for nodes  (graph).   Thanks a lot

**Comment by tylerlong** [comment]
Could you please create a simple chart to demonstrate what you want? I don't quite get the idea.

**Comment by phillip-walker** [comment]
I believe the ask is to create the equivalent of "click" so that an element in a sequence graph could link out to another window or otherwise call Javascript. That would be very helpful in my case, too.
