### ISSUE TITLE
Good example of interactivity with mermaidAPI

### ISSUE THREAD

**Issue by maxMidius** [knsv/mermaid#514]
The documentation which describes how to create links + tooltips  is not a complete example.
Furthermore if mermaidAPI is the preferred approach going forward - then it makes sense to provide a concise yet complete working example without any extra clutter.

**Comment by maxMidius** [comment]
I would like to add that - I have gone through the  dist/test/examples and there is only one example with interactivity but that one is using the deprecated  mermaid.js.   Where as the mermaid markup code is Ok - the javascript functions for rendering svg and attaching callbacks (bindings) is confusing. For example what is the complete signature of  mermaidAPI.render( "graphDiv", graphDef, insertSvg, element)  - this needs proper explanation - for example is element derivable from "graphDiv" ??

**Comment by tylerlong** [comment]
> Furthermore if mermaidAPI is the preferred approach going forward

Where do you get this information?

I am doing some investigation. I think mermaidAPI.js is for Node.js while mermaid.js is for browser. With the help of webpack, you can also use mermaidAPI.js for browser of course.

I am going to submit a huge PR soon. I have migrated the mermaid projectd to use webpack.

**Comment by tylerlong** [comment]
Here is an example using mermaidAPI: https://github.com/knsv/mermaid/blob/master/dist/demo/index.js

It's not "good" since it's simple. But it gives you an starting point to continue your work.

Closing it for now. Feel free to reopen or create a new issue.
