### ISSUE TITLE
Strange syntax error - when importing mermaid.js

### ISSUE THREAD

**Issue by maxMidius** [knsv/mermaid#515]
I am getting this error 
mermaid.js:1264 Uncaught SyntaxError: Invalid or unexpected token
when I download the  mermaid package and  refer to it from my downloaded version.

Strangely this error disappears  if I refer to it from your github site
<script src="https://knsv.github.io/mermaid/javascripts/lib/mermaid.js"/> </script>

Please help - this is very very weird

**Comment by tylerlong** [comment]
Could you please try the CDN version? http://www.jsdelivr.com/projects/mermaid
It's a good idea to referenrence files hosted by CDN

**Comment by maxMidius** [comment]
yes - it worked from CDN - thank you
