### ISSUE TITLE
clicking links works from inset in subgraph but not from nodes

### ISSUE THREAD

**Issue by scordature** [knsv/mermaid#516]
This test page shows that a link from an inset in a subgraph works fine, but the same link from a node has no effect, although the tooltip works.

Tested on Firefox 51.0.1 (64-bit), and Chrome Version 57.0.2987.133 (64-bit), on OS X Sierra.

This example was done following the mermaid docs ... am I doing something wrong?

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <!-- Downloaded as per http://knsv.github.io/mermaid/#installation -->
  <!-- Stored in the same directory as html file                     -->
  <link rel="stylesheet" href="mermaid.css">

  <!-- Optional to use fontawesome                                   -->
  <!-- Downloaded as per http://fontawesome.io/get-started/          -->
  <!-- Stored in the same directory as html file                     -->
  <!-- <script src="https://use.fontawesome.com/7065416dc9.js"></script> -->

</head>
<body>

  <!-- Include mermaid on your web page:                             -->
  <script src="mermaid.min.js"></script>
  <script>mermaid.initialize({startOnLoad:true});</script>

  <div class="mermaid">

        graph TD;

        subgraph Happy Subgraph
            inset[This inset is linked and it works]
        end

            click inset "http://www.voanews.com/" "VOA"
            click A "http://www.voanews.com/" "VOA"
            click B "http://www.voanews.com/" "VOA"

        subgraph Sad Subgraph
            A[This node is linked and the tooltip works but the link does not]
        end

          B>This node is linked and the tooltip works but the link does not]

            inset-->A
            A-->B

        style A fill:#ed6,stroke:#333,stroke-width:2px;
        style B fill:#ed6,stroke:#333,stroke-width:2px;
        style inset fill:#ed6,stroke:#333,stroke-width:2px;

  </div>

</body>
</html>
```

**Comment by tylerlong** [comment]
I think you just need to move the `click` statements down to the bottom.

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQ7CgogICAgICAgIHN1YmdyYXBoIEhhcHB5IFN1YmdyYXBoCiAgICAgICAgICAgIGluc2V0W1RoaXMgaW5zZXQgaXMgbGlua2VkIGFuZCBpdCB3b3Jrc10KICAgICAgICBlbmQKCiAgICAgICAgICAgIGNsaWNrIGluc2V0ICJodHRwOi8vd3d3LnZvYW5ld3MuY29tLyIgIlZPQSIKCgogICAgICAgIHN1YmdyYXBoIFNhZCBTdWJncmFwaAogICAgICAgICAgICBBW1RoaXMgbm9kZSBpcyBsaW5rZWQgYW5kIHRoZSB0b29sdGlwIHdvcmtzIGJ1dCB0aGUgbGluayBkb2VzIG5vdF0KICAgICAgICBlbmQKCiAgICAgICAgICBCPlRoaXMgbm9kZSBpcyBsaW5rZWQgYW5kIHRoZSB0b29sdGlwIHdvcmtzIGJ1dCB0aGUgbGluayBkb2VzIG5vdF0KCiAgICAgICAgICAgIGluc2V0LS0-QQogICAgICAgICAgICBBLS0-QgoKICAgICAgICBzdHlsZSBBIGZpbGw6I2VkNixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4OwogICAgICAgIHN0eWxlIEIgZmlsbDojZWQ2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHg7CiAgICAgICAgc3R5bGUgaW5zZXQgZmlsbDojZWQ2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHg7CgogICAgICAgICAgICBjbGljayBBICJodHRwOi8vd3d3LnZvYW5ld3MuY29tLyIgIlZPQSIKICAgICAgICAgICAgY2xpY2sgQiAiaHR0cDovL3d3dy52b2FuZXdzLmNvbS8iICJWT0Ei
