### ISSUE TITLE
 FlowChart's linkStyle contain some problems in IE 11 or IE Edge.

### ISSUE THREAD

**Issue by sdlddr** [knsv/mermaid#517]
Hi,Recently I found some problems in FlowChart's linkStyle, it was rendered different effect on browsers.

my code is below:
`linkStyle 3 stroke:#F60,stroke-width:2px;`

The result is below:
![qq 20170414111402](https://cloud.githubusercontent.com/assets/4285162/25032235/0317ccc8-2105-11e7-84c7-a9b384024e6d.png)
It's in Chrome or Firefox

![qq 20170414111702](https://cloud.githubusercontent.com/assets/4285162/25032236/031965c4-2105-11e7-9c39-35edf588efa6.png)
It's in IE Edge

![qq 20170414111737](https://cloud.githubusercontent.com/assets/4285162/25032237/0319ec38-2105-11e7-84bf-64258972762c.png)
It's in IE 11

The perfect style is in chrome or Firefox.
Do you have any suggestion to make sure FlowChart's linkStyle renders like in chrome when it's in IE 11 and IE Edge?
Or may you fixed and update your mermaid project to solve these problems?
Thanks.

**Comment by havenqi** [comment]
seems you don't have problem with the diagram size in IE. My problem is that the diagram is shrunk into a very small one when it's opened in IE11. It works well in Edge and all the others. How do you config your IE11 to have the right display?

**Comment by tylerlong** [comment]
Could you please create a sample in https://mermaidjs.github.io/mermaid-live-editor/ and post a link here? @sdlddr
