### ISSUE TITLE
Draw marmaid flowchart from JSON

### ISSUE THREAD

**Issue by tscislo-lingaro** [knsv/mermaid#518]
Hello,

This is more a question then an issue.
We would like to have some sort of json representation of a mermaid flowchart that we can download from a server. Is there any parser form JSON -> mermaid mardown? Maybe people do this differently?

Thanks!

**Comment by tylerlong** [comment]
> We would like to have some sort of json representation of a mermaid flowchart that we can download from a server.

Does it have to be JSON? Can you download plain text which is mermaid markdown?

**Comment by tscislo** [comment]
@tylerlong 
Yes I could download mermaid markdown from the server. However editing mermaid markdown string either on the server or on client is problematic (it has to be regexp based), it would be much easier to have a json representation which is easy to edit on both sides and then transform it to mermaid markdown. Any tools to do that?

**Comment by tylerlong** [comment]
I am not aware of such a tool. 

Why do you think JSON is easier to edit than markdown? Because JSON has linter? 

You can check the syntax of mermaid markdown like this on client side: https://github.com/tylingsoft/markdown-it-mermaid/blob/master/src/index.js#L5-L14  So you can give user live feedback if he/she makes a mistake.

Not a direct solution. Just my 2 cents for your reference.

**Comment by tscislo** [comment]
Thanks @tylerlong !

I'm NOT trying to create a parser for marmaid markdown. My aim is to have multiple flowcharts on a page and the user should be able to edit ONLY the names of particular elements. For example in such flowchart:
`
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[Car]
`
I'd like to easily change the name of C which is currently 'Let me think' and send it to the server. It will be done in a UI by a modal with a text box. In markdown it can be done only via string regexp find and replace which is not optimal. Any better way for this?

**Comment by tylerlong** [comment]
I've got your point. What you said is like "reverse editing". User could edit part of the rendered chart to update mermaid code.  It is true that markdown is not friendly to end users (compared to a model with a text box).

I don't think there is any solution at the moment. I am not the creator of mermaid. I am just a collaborator. Recently I have been thinking: mermaid's syntax is very concise and short. But it's not as expressive as json and xml. For example if I use xml to define a chart, I can add as many information as I want to the XML node attributes. I could add an ID, so when user update the text, I can update the xml tag by ID

Just some random thoughts. If we want to make this happen. It might lead to a new product other than mermaid.

**Comment by rafaduka** [comment]
My use with mermaid is to build diagrams for web systems. Today, I had give up it because does not have support parse from json format. I'm looking for a way to build flowchart reading by json, this way I can put it [ids, edges, label, etc]. Although I think mermaid is awesome project.

**Comment by fasteddys** [comment]
@rafaduka @tscislo were you able to get to JSON and updates, maybe we can collectively come up with something

**Comment by NewToStuff** [comment]
@rafaduka @tscislo @fasteddys 
Hi,
This one is marked as stale so probably need to start something new. I have a similar use case where I would like to determine valid next steps from each point in the flowchart. I was thinking that it would be possible by running through each line of the markdown and creating a JSON entry. Maybe it could work bi-directional as well.

I am a bit surprised that nobody has had the need so I am looking for alternatives. Failing that I may see if I can write something.

Thanks

**Comment by aadamsx** [comment]
This library has so much potential.  I see so many good ideas just go down the memory hole with no one to work on it.  This project needs to be spun off into a for profit business.

**Comment by ScalaWilliam** [comment]
@NewToStuff  @aadamsx Mermaid uses GraphLib behind the scenes, which has serialization.

See: https://github.com/dagrejs/graphlib/wiki/API-Reference#json-write

I was also looking at visualising programatically.

**Comment by Ogglas** [comment]
@ScalaWilliam `Dagre` and `graphlib` has been removed now:

https://github.com/mermaid-js/mermaid/pull/3861

https://github.com/mermaid-js/mermaid/blob/develop/package.json
