### ISSUE TITLE
input activate/deactivate cause safari unresponding

### ISSUE THREAD

**Issue by kaqiling** [knsv/mermaid#521]
How to reproduce.

Open https://knsv.github.io/mermaid/live_editor/ in Safari

input
```
sequenceDiagram
Alice->>John: Hello John, how are you?
activate
```
Then the browser will become unresponding. It works fine on Chrome however.

**Comment by tylerlong** [comment]
I can reproduce this issue

**Comment by tylerlong** [comment]
Fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCkFsaWNlLT4-Sm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_CmFjdGl2YXRl/error/UGFyc2UgZXJyb3Igb24gbGluZSAzOgouLi5vdyBhcmUgeW91P2FjdGl2YXRlCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS1eCkV4cGVjdGluZyAnQUNUT1InLCBnb3QgJzEn
