### ISSUE TITLE
Flowchart Line/Path Kinks

### ISSUE THREAD

**Issue by JohnLBevan** [knsv/mermaid#522]
**Request**
As you can see from the attached screenshot, one of the paths goes off to the right for no reason, then swings back on itself to the left to connect to the node beneath it.
Is there any way to improve the intelligence of the path layout, or if that's too complex, to simply force all paths to be straight-lines?

![cmdb](https://cloud.githubusercontent.com/assets/1840140/25242845/f97eeb18-25f2-11e7-956d-7c4a057e0c74.png)

**Thanks & Background Info**
Thanks for producing such an amazing & simple to use solution; really like it & very impressed.
I've used it to automate my documentation, by having discovery scripts build a detailed, low level CMDB, then using the dependency data from that to generate graphs in Mermaid.

I added the following CSS to allow me to hover over a path & have it display more clearly; i.e. so I can see at a glance which nodes are connected.  Hopefully that makes the issue reported above stand out more:
```
path:hover {
	stroke-width:4px;
}
/* more complex option to color edger red too:
.edgePath:hover * {
	stroke:red;
	stroke-width:4px;
	fill: red;
}
*/

```

**Comment by tylerlong** [comment]
Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post back a link here?

The layout is powered by https://github.com/dagrejs/dagre-d3 and it could be an upstream issue too.

**Comment by JohnLBevan** [comment]
No worries, I've anonymised the original data; thankfully the issue still shows: [Example](https://mermaidjs.github.io/mermaid-live-editor/#/view/Z3JhcGggVEQKCTllMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY3JlYXRpdmUtY29tbW9ucyBNeSBTeXN0ZW0gfCBUZXN0IEVudmlyb25tZW50IikKCTgyMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY29ncyBTaGFyZWQgQnVzaW5lc3MgTG9naWMgU2VydmVyOlNlcnZpY2UgMSIpCglkYjA1MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWNvZ3MgU2hhcmVkIEJ1c2luZXNzIExvZ2ljIFNlcnZlcjpTZXJ2aWNlIDIiKQoJNGUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyKCJmYTpmYS1jb2dzIFNoYXJlZCBSZXBvcnQgU2VydmVyOlNlcnZpY2UgMSIpCgkzMDEyMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWNvZ3MgU2hhcmVkIFJlcG9ydCBTZXJ2ZXI6U2VydmljZSAyIikKCTVlMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY29ncyBEZWRpY2F0ZWQgVGVzdCBCdXNpbmVzcyBMb2dpYyBTZXJ2ZXI6U2VydmljZSAxIikKCWMxMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY29ncyBEZWRpY2F0ZWQgVGVzdCBCdXNpbmVzcyBMb2dpYyBTZXJ2ZXI6U2VydmljZSAyIikKCWI3MDQyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY2lyY2xlIFtEQlNlcnZlclxTaGFyZWREYkluc3RhbmNlXS5bU3VwcG9ydERiXSIpCgk4ZjEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWNpcmNsZSBbREJTZXJ2ZXJcU2hhcmVkRGJJbnN0YW5jZV0uW0RldmVsb3BtZW50RGJdIikKCTBlMTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY2lyY2xlIFtEQlNlcnZlclxTaGFyZWREYkluc3RhbmNlXS5bVGVzdERiXSIpCgkwNzEzMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWNpcmNsZSBbREJTZXJ2ZXJcU2hhcmVkRGJJbnN0YW5jZV0uW1NoYXJlZFJlcG9ydGluZ0RiXSIpCgljNzA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLXNlcnZlciBTaGFyZWQgQnVzaW5lc3MgTG9naWMgU2VydmVyIikKCWNhMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtc2VydmVyIFNoYXJlZCBSZXBvcnQgU2VydmVyIikKCTY4MTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtc2VydmVyIERlZGljYXRlZCBUZXN0IEJ1c2luZXNzIExvZ2ljIFNlcnZlciIpCglmNDExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWRhdGFiYXNlIFtEQlNlcnZlclxTaGFyZWREYkluc3RhbmNlXSIpCglkNjA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLXNlcnZlciBEQlNlcnZlciIpCgk3MTA4MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLWNvZ3MgREJTZXJ2ZXJcOk1TU1FMU0VSVkVSIikKCWMwMTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtY29ncyBEQlNlcnZlclw6U1FMQWdlbnQiKQoJOWEwNzIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyKCJmYTpmYS1jb2dzIERCU2VydmVyXDpTUUxCcm93c2VyIikKCTFkMGEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMigiZmE6ZmEtc2VydmVyIFZtSG9zdDEiKQoJMjAwYTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyKCJmYTpmYS1zZXJ2ZXIgVm1Ib3N0MiIpCgkxYzBhMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIoImZhOmZhLXNlcnZlciBWbUhvc3QzIikKCTllMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjgyMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJOWUxMjIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-ZGIwNTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk5ZTEyMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT40ZTExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTllMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjMwMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJOWUxMjIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-NWUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk5ZTEyMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5jMTExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTgyMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmI3MDQyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJODIwNzIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-OGYxMDIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk4MjA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT4wZTEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTgyMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmM3MDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJZGIwNTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-YzcwNzIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCglkYjA1MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT44MjA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTRlMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmI3MDQyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJNGUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-OGYxMDIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk0ZTExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT4wZTEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTRlMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjA3MTMyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJNGUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-Y2ExMjIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgkzMDEyMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5jYTEyMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTMwMTIyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjRlMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJNWUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-OGYxMDIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk1ZTExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT42ODEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCWMxMTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjY4MTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJYzExMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-NWUxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgliNzA0MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5mNDExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCThmMTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmY0MTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJMGUxMDIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-ZjQxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgkwNzEzMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5mNDExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCWM3MDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjFkMGEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJY2ExMjIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-MjAwYTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk2ODEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT4xYzBhMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCWY0MTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmQ2MDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJZjQxMTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-NzEwODIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCglmNDExMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5jMDEwMjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCWY0MTEyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjlhMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJZDYwNzIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-MWMwYTIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk3MTA4MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5kNjA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCWMwMTAyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPmQ2MDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgoJYzAxMDIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyLS0-NzEwODIyOTBfMWVjM19lNzExXzhjNWFfMDA1MDU2YWQwMDAyCgk5YTA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDItLT5kNjA3MjI5MF8xZWMzX2U3MTFfOGM1YV8wMDUwNTZhZDAwMDIKCTlhMDcyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMi0tPjcxMDgyMjkwXzFlYzNfZTcxMV84YzVhXzAwNTA1NmFkMDAwMgo)

There are a few examples of the issue; one is the link between `Shared Business Logic Server:Service 2` and `Shared Business Logic Server:Service 1` (i.e. leftmost items in the second and third "rows" of the graph).

Thank-you for picking this up / looking into it.

**Comment by tylerlong** [comment]
@JohnLBevan  Last night I did a change which might mitigate the issue: https://github.com/knsv/mermaid/issues/580#issuecomment-373929046

**Comment by JohnLBevan** [comment]
Nice one @tylerlong ; agree that this does look better.
The kink does still exist (i.e. the example line between "Shared Business Logic Server:Service 2" and "...1" still goes right first then left / crosses over the link from "...2" to "Shared Business Logic Server" unnecessarily; but it's definitely an improvement.   Thank-you.
