### ISSUE TITLE
Is there any way I can influece placement of boxes in flowchart?

### ISSUE THREAD

**Issue by tscislo** [knsv/mermaid#525]
For example when I have multiple subgraphs with left to right orientation I'd like all elements in those subgraphs to be left aligned. There are connections between those subgraphs. Is that possible?

Thanks!

**Comment by tylerlong** [comment]
You can create each unconnected subgraph as a standalone graph. Then all of them are left aligned. Does it make sense?

**Comment by vikram-rawat** [comment]
I have the same problem too... 

As the graph becomes more complex I want to get subgraphs in different directions.

**Comment by tylerlong** [comment]
For those who wants to help please check the upstream project https://github.com/dagrejs/dagre-d3. Is this feature supported by it? We might be able to implement it as soon as we get more information.
