### ISSUE TITLE
mermaid wrong editor in chrome

### ISSUE THREAD

**Issue by nacardozo** [knsv/mermaid#529]
I have been looking for and I find that this issue appear because it only works with the 4 version or less of chrome and firefox, what can I do to solve this issue?
In the 6.0 mermaid version says that they fixed this bugs but I make the test but is the same, that happens too with the 7.0 version, any solution

> Uncaught TypeError: elem.getTransformToElement is not a function
>     at getCoords (http://xxx.xxx.xxx.xxx/mermaid/editor/build.js:28:4651)

**Comment by tylerlong** [comment]
Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post back ad link here?
