### ISSUE TITLE
Make link text look like it is on the line

### ISSUE THREAD

**Issue by chrisalley** [knsv/mermaid#53]
Could the alternative (or replacement) link text syntax be added?

`A-->|Link text|B` becomes `A--Link Text-->B`

And similarly:

`A---|Link text|B` becomes `A--Link Text--B`

The reason being that the suggested syntax looks more like it is sitting on the line.

**Comment by badbye** [comment]
Seems that A-->|Link text|B generate a line instead of a arrow?
Then how to generate a arrow with a link text?

**Comment by knsv** [comment]
Hello!

The code below, should generate an arrow:
```
A-->|Link text|B
```
This code should generate a line:
```
A---|Link text|B
```

When I test this I see the expected behaviour. Can you help me reproduce your problem?

**Comment by knsv** [comment]
Released in 0.3.1
