### ISSUE TITLE
Hexagon shape in mermaid flowchart?

### ISSUE THREAD

**Issue by pi314** [knsv/mermaid#530]
According to the document, there are 6 shapes available (one found from the issues):
`[box]`
`(rounded box)`
`((circle))`
`>flag-like box]`
`{rhombus or diamond}`
`(-oval-)`

Is that possible to draw a hexagon in flowchart?

Normally, a flowchart uses diamond shape to represent a condition, but when the description text grows, the diamond becomes very very large. So I always use hexagons instead.

**Comment by dotancohen** [comment]
+1
This is a very valid request and I hope to see it implemented. As is, Mermaid currently makes poor use of space in general but the huge rhombi make the conditional statements very difficult to use.

I've also used hexagons in the past and they are understood by anybody familiar with conventional flowchart shape syntax.

**Comment by fzzylogic** [comment]
[Drakon](http://drakon-editor.sourceforge.net/) flattened the rhombus got to space with that.

**Comment by airbj31** [comment]
It would be wonderful if we can use various shapes.
e.g. https://www.conceptdraw.com/How-To-Guide/flowchart-design

**Comment by fzzylogic** [comment]
@stale, flattened hexagons rule.

**Comment by dotancohen** [comment]
@Stale, flattened hexagons rule.

**Comment by knsv** [comment]
This should be fairly easy to implement. How so you think the syntax should be for the hexagon?

**Comment by mearns** [comment]
Making some pretty quick progress on this, should have a completed PR in a few days.

**Comment by Dunning-Kruger** [comment]
Resolved on #970
