### ISSUE TITLE
live editor make browser(safari on macOS&iOS) not longer respond

### ISSUE THREAD

**Issue by liyang-bsy** [knsv/mermaid#531]
https://knsv.github.io/mermaid/live_editor/
if I input these:
```
graph TD
A（[xx]
```

**Comment by tylerlong** [comment]
Fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQe-8iFt4eF0K/error/TGV4aWNhbCBlcnJvciBvbiBsaW5lIDIuIFVucmVjb2duaXplZCB0ZXh0LgpncmFwaCBUREHvvIhbeHhdCi0tLS0tLS0tLV4

**Comment by liyang-bsy** [comment]
maybe you should reopen this issue, regard '（、，' as simple text. so that I can write like this:
A[something(with explanation)]
A[something（with explanation）]

**Comment by tylerlong** [comment]
Yes you can. Just surround the text with double quotes:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQVsic29tZXRoaW5nKHdpdGggZXhwbGFuYXRpb24pIl0KQlsic29tZXRoaW5n77yId2l0aCBleHBsYW5hdGlvbu-8iSJdCg

Let me know if you still want to reopen this issue.
