### ISSUE TITLE
how to change mermaid text color or line text block color？

### ISSUE THREAD

**Issue by zyyedi** [knsv/mermaid#534]
I am using Typora, and the user are allowed to use .css file to set up the style of mermaid graphs. I am wondering how to set up the text color or line text block filled-color by .css file? Because Typora's author are somehow setting the text color as the same color as my code fence, which is white, the text seems totally invisible in my flowchart. Hope there is a way can figure that out.

**Comment by tylerlong** [comment]
Since you can use .css file. You can simply override the color. Here the css(less) code for mermaid: https://github.com/knsv/mermaid/tree/master/src/less

**Comment by gilbertchenzhe** [comment]
@tylerlong 
你好，我最近在使用美人鱼，需求是想要改变某条流程线的颜色，而不是修改整体的CSS去改变所有流程线，目前的API中能实现吗？

Hello, I recently used mermaid, the demand is to change the color of a process line, rather than modify the overall CSS to change all the process lines, the current API can be achieved?

**Comment by gilbertchenzhe** [comment]
@tylerlong 好吧，我们更改了需求，不再要求修改流程线的颜色，用API的方法修改流程线的样式为实线、虚线。

Ok, we changed the demand, no longer ask to modify the color of the process line, with the API method to modify the flow line style is solid line, dotted line.

**Comment by tylerlong** [comment]
Please read https://mermaidjs.github.io/faq.html  **How to specify custom CSS file?**

**Comment by skunk007** [comment]
> @tylerlong 好吧，我们更改了需求，不再要求修改流程线的颜色，用API的方法修改流程线的样式为实线、虚线。
> 
> Ok, we changed the demand, no longer ask to modify the color of the process line, with the API method to modify the flow line style is solid line, dotted line.

使用 html 语言可以直接在 typora mermaid 编辑内容上改变字体颜色，不知道是否能满足你的需要。
比如 --> <font color='red'>tst</font>
