### ISSUE TITLE
the documentation website is down

### ISSUE THREAD

**Issue by AStupidBear** [knsv/mermaid#539]
cannot launch http://knsv.github.io/mermaid/

**Comment by tylerlong** [comment]
I can visit it without problem.

![image](https://cloud.githubusercontent.com/assets/733544/26753527/18451dcc-489b-11e7-80d9-47c7ba8e6907.png)

Please post the error message or even better screenshot.

**Comment by AStupidBear** [comment]
After refreshing the website for many times now I can visit it. I think it's a DNS issue. Sorry for the interruption.
