### ISSUE TITLE
No Edge Boxes if useHtmlLabels=false

### ISSUE THREAD

**Issue by renierr** [knsv/mermaid#541]
The Background Boxes are not rendered correct if html Labels are false.
Only the first one is shown, all other have no rect on edge labels.

**Comment by renierr** [comment]
The error is in:
var label = labels[i];

should be:
var label = labels[k];

**Comment by renierr** [comment]
can not reproduce, its a long time ago.

in file flowRenderer.js Line 459
ther is the wrong index var of the for loop

**Comment by tylerlong** [comment]
`flowchart.htmlLabels` by default is `false`. So mermaid live editor is also using a `false` value.

It is better if you can reproduce.

But I **do** see the code you pointed out, that code is very likely wrong. Nice catch.

**Comment by tylerlong** [comment]
Confirmed, the bug was introduced in https://github.com/knsv/mermaid/commit/ab398c64a826120b37adcd6be974211dda1683c5#diff-2d1e5c0548ca8417cc597b345f914aa2L513

Thanks!
