### ISSUE TITLE
Tooltip Position is wrong if useMaxWidth = false and you scroll

### ISSUE THREAD

**Issue by renierr** [knsv/mermaid#542]
if you set useMaxWidth to false and render a large graph where you able to scoll.
The Tooltip position is wronmg if you scroll left/right or up/down

I solved this by setting the CSS style for tooltip to 'fixed' and changed the added scroll top position in JS

from:
tooltipElem.html(el.attr('title')).style('left', rect.left + (rect.right - rect.left) / 2 + 'px').style('top', rect.top - 14 + document.body.scrollTop + 'px');

to:
tooltipElem.html(el.attr('title')).style('left', rect.left + (rect.right - rect.left) / 2 + 'px').style('top', rect.top - 14 + 'px');

**Comment by ziyiwang** [comment]
Hi
the above didnt work for me

changing to this worked

tooltipElem.html(el.attr('title')).style('left', rect.left + (rect.right - rect.left) / 2 + 'px').style('top', rect.top - 14 + document.scrollingElement.scrollTop + 'px');

**Comment by minheeDitto** [comment]
In the flowChart subgraph add the local image,the node can not adjust,such as B[<img src="logo.png">the product unit],how to fix it
