### ISSUE TITLE
q: heard of the cosmogol standard?

### ISSUE THREAD

**Issue by andreineculau** [knsv/mermaid#545]
https://tools.ietf.org/html/draft-bortzmeyer-language-state-machines-01

would be great to have support for it e.g. I would switch to mermain from a custom solution for the SVG drawing at http://for-get.github.io/http-decision-diagram/httpdd.fsm.html (part of https://github.com/for-GET/http-decision-diagram )

**Comment by tylerlong** [comment]
I am definitely not an expert on FSM. I don't think it is support by mermaid. Or do you mean use flowchart to draw FSM?

**Comment by andreineculau** [comment]
Like I wrote above, I was interested in using mermaid to read my cosmogol dumps.
What I was hoping is to hear at least is that the creators/maintainers of mermaid (initial commit in 2014) have at least heard of a standard from 2006. It has nothing to do with being an expert, nor with saying that everyone needs to understand the IETF spec.

Few read the IETF spec, but that doesn't stop many to use/like/love HTTP/REST. Thanks anyway
