### ISSUE TITLE
font awesome in link text?

### ISSUE THREAD

**Issue by niksfirefly** [knsv/mermaid#546]
Is there any way to use font awesome in link text?
A-->|"fa:fa-envelope"| B
not working

**Comment by ndeixonne** [comment]
Me too, it seems to be broken now

**Comment by trichetriche** [comment]
Or you can make custom CSS directly into your node and use usual HTML for that. 

Currently not only I can use font awesome with that technique, but also embed images and even Angular 2 code into the nodes

**Comment by Chandu** [comment]
@trichetriche Would it be possible to share how are dealing with inserting Angular 2 code into the nodes?
I am currently stuck with using click callback handlers assigned to the node in the markup and am not quite sure how to proceed.

**Comment by trichetriche** [comment]
Personally I created window functions and deleted them on component destruction. Works like a charm for me !

**Comment by tylerlong** [comment]
Pleas read https://mermaidjs.github.io/breakingChanges.html now you don't need mermaid CSS file any more.

Please read https://mermaidjs.github.io/faq.html **How to specify custom CSS file?**

**Comment by woahdae** [comment]
Is this supposed to work? [OP's example in the live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgQS0tPnxcImZhOmZhLWVudmVsb3BlXCJ8IEJcblx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ) doesn't:

```
graph LR
  A-->|"fa:fa-envelope"| B
```

![mermaid-diagram-20200708113253](https://user-images.githubusercontent.com/25282/86956930-c6f6fe00-c10e-11ea-90eb-720ddc8b13e8.png)

**Comment by Shawak** [comment]
Having the same problem.
