### ISSUE TITLE
Link issue with cursor not displaying a pointer

### ISSUE THREAD

**Issue by joannaz** [knsv/mermaid#547]
Similar Issue to #516 

Highlighting links does not change the cursor to a pointer if the pointer is directly on the text. It only changes to a pointer when the pointer is hovering over the edge of the box.

Is it also possible to change the colour of links so they are more noticeable?

**Comment by tylerlong** [comment]
Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post back a link here?
