### ISSUE TITLE
add shapes

### ISSUE THREAD

**Issue by vikram-rawat** [knsv/mermaid#549]
Can You Please add shapes like

parrellogram --> / /
Pointed Box -->  [>
semicircle Box --> [ )
Data Box --> [))

can You anyhow add them at a future version...

**Comment by jdayton3** [comment]
It would be awesome if there were support for these symbols: 

![image](https://user-images.githubusercontent.com/16820980/40247418-8661d5f6-5a89-11e8-88ab-23bef4a162d0.png)

([image source](https://study.com/academy/lesson/flowchart-symbols-in-programming-definition-functions-examples.html))

**Comment by pyBlob** [comment]
A while ago, I've created a fork containing some of the pointy-boxes. Will prepare it and merge-request it one of the next days.

**Comment by pyBlob** [comment]
With all the different kinds boxes, I think it would be a nice idea to separate the parsing and rendering of the left and right side, so you can combine any left side with any right side.

**Comment by moshemalawach** [comment]
Any news on that? :)
