### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by vikram-rawat** [knsv/mermaid#550]
Should Be able to control the direction of the flowchart..

Like
Say My main graph is going Left to Right ---------->>>>>>>>

but I want the subgraphs and decision graph to go from top to bottom

I am unable to do it....

It should be tidy enough to read and understand thus we need control for elements direction in simple arrows 

A--TD-->B
A--BT-->B etc...

**Comment by vikram-rawat** [comment]
Thanks for such a nice initiative. I really appreciate it. And if everything goes well we would never ever have to switch to visio or excel again.

I am more of a functional analyst and define process flow very often.

In mermaid you can not control the flow of sub graphs. It follows the same flow till the end.

But originally if the you want to define a sub process it should have a different direction so that it doesn't create noise on the graph

Like if main is TB
Sub should be LR or RL

If main is LR
Sub should be TB of BT

So on...

I read the documentation of mermaid it doesn't help us with that. Can you anyhow give us the ability to control the flow may be by joining two different graph.

Is there anything you can do please.

**Comment by vikram-rawat** [comment]
Can we anyhow build two different mermaid plots and merge them as one.

Like one mermaid diagram connecting to another and so on... That could solve the problem temporarily. And also it will open up a new dimension entirely.

This will solve the problem of subgraphs temporarily. But this is a must have feature because without it  Big and complex graphs can not be explained.

**Comment by tylerlong** [comment]
I am reviewing all the issues for mermaid and several people have the same requirements. 

Layout is powered by https://github.com/dagrejs/dagre-d3. mermaid could support it as long as upstream project supports it.

**Comment by vikram-rawat** [comment]
Is it implemented now. Trust me it's basics and very crucial if you actually want to draw a flow chart

**Comment by bifeng** [comment]
"Like if main is TB
Sub should be LR or RL

If main is LR
Sub should be TB of BT"

This kinds of subgraph seems not implemented, is that right?
