### ISSUE TITLE
classdiagram not works in mermaid live_editor 

### ISSUE THREAD

**Issue by houyf** [knsv/mermaid#553]
**I sorry if the question is  stupid but it does make me confused.**

==========     Problem Description    ========== 

**I copyed  your demo about  the classdiagram to the [mermaid live editor](https://knsv.github.io/mermaid/live_editor/),  but it happen to failed with promotion " Invalid syntax".**  
![image](https://user-images.githubusercontent.com/8338346/28495848-3648d39e-6f8e-11e7-8ec2-63d80484ae60.png)

**I also found that the live editor docs lack the usage introduction about classdiagram.** 

![image](https://user-images.githubusercontent.com/8338346/28495869-d5f86fe4-6f8e-11e7-9fdd-100ff24defb4.png)

**Does the live editor not support  classdiagram ?  Is there any other way to  make the code work  ?**

**Comment by vikram-rawat** [comment]
I am trying to access the same via R programming DiagrammeR but it is not working for me too....

What should We do please document.

**Comment by tylerlong** [comment]
Class diagram is experimental feature and it is not officially announced.

**Comment by tylerlong** [comment]
Now it support class diagram: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Y2xhc3NEaWFncmFtCkNsYXNzMDEgPHwtLSBBdmVyeUxvbmdDbGFzcyA6IENvb2wKQ2xhc3MwMyAqLS0gQ2xhc3MwNApDbGFzczA1IG8tLSBDbGFzczA2CkNsYXNzMDcgLi4gQ2xhc3MwOApDbGFzczA5IC0tPiBDMiA6IFdoZXJlIGFtIGk_CkNsYXNzMDkgLS0qIEMzCkNsYXNzMDkgLS18PiBDbGFzczA3CkNsYXNzMDcgOiBlcXVhbHMoKQpDbGFzczA3IDogT2JqZWN0W10gZWxlbWVudERhdGEKQ2xhc3MwMSA6IHNpemUoKQpDbGFzczAxIDogaW50IGNoaW1wCkNsYXNzMDEgOiBpbnQgZ29yaWxsYQpDbGFzczA4IDwtLT4gQzI6IENvb2wgbGFiZWw

But it is still an experimental feature and there are known bugs.
