### ISSUE TITLE
Japanese text appears garbled

### ISSUE THREAD

**Issue by JGJP** [knsv/mermaid#554]
![screenshot 2017-07-25 12 45 54](https://user-images.githubusercontent.com/3692190/28554930-6c34a8c0-7137-11e7-8ed2-b8199d8afb48.png)

Possible to add support for non-latin characters? It actually seems that functions besides the text rendering work fine though.

**Comment by tylerlong** [comment]
Please list the steps to reproduce the issue. It seems to work in live editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQS0tPkJb44GT44KT44Gr44Gh44GvIV0K

![image](https://user-images.githubusercontent.com/733544/29394158-23a1d02c-833b-11e7-87d2-1a8a2a29cdf3.png)
