### ISSUE TITLE
Arrows are not shown in Flag Shape Boxes

### ISSUE THREAD

**Issue by vikram-rawat** [knsv/mermaid#555]
graph LR

Qc      -->     Rej>Rejected]

try the Code you will understand What I mean... Please change it.

**Comment by tylerlong** [comment]
I can reproduce it https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKClFjIC0tPiBSZWo-UmVqZWN0ZWRd
