### ISSUE TITLE
Simple full example in online documentation is broken

### ISSUE THREAD

**Issue by Lucas-C** [knsv/mermaid#558]
http://knsv.github.io/mermaid/#simple-full-example-

<img width="770" alt="2017-08-16 14_14_21-mermaid - generation of diagrams and flowcharts from text in a similar manner as" src="https://user-images.githubusercontent.com/925560/29362700-4305d2fa-828d-11e7-90a8-7ae510675bed.png">

I'm using Chrome version 60.0.3112.78

**Comment by tylerlong** [comment]
We are working on a new documentation website and soon we will make it official.

Here it is: https://mermaidjs.github.io/

**Comment by Lucas-C** [comment]
Thank you very much !
