### ISSUE TITLE
Syntax suggestions

### ISSUE THREAD

**Issue by snarlynarwhal** [knsv/mermaid#564]
I think mermaid could look a bit sleeker by borrowing these from graphviz dot:
```
graph mygraph
  a -> b -> c
  d -> {e f}
```

If you're open to these changes and would like help implementing them, I can try and help out if you point me in the right direction.

**Comment by tylerlong** [comment]
It seems cool.

What's the equivalent in mermaid for ` d -> {e f}` ?

**Comment by snarlynarwhal** [comment]
It's been awhile, but I believe it's:

```
graph TD;
    D-->E;
    D-->F;
```

**Comment by snarlynarwhal** [comment]
Large graphs start to get very verbose without these shortcuts. I personally switched to graphviz/dot because of this.
