### ISSUE TITLE
Arrows should Come out in upward and Downward direction from decision Node

### ISSUE THREAD

**Issue by vikram-rawat** [knsv/mermaid#566]
graph LR
    A[Hard edge] -->|Link text| B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]

**Comment by tylerlong** [comment]
If there are LOTS of decisions, it's impractical to have all of them upward / downward: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKQVtIYXJkIGVkZ2VdIC0tPnxMaW5rIHRleHR8IEIoUm91bmQgZWRnZSkKQiAtLT4gQ3tEZWNpc2lvbn0KQyAtLT58T25lfCBEW1Jlc3VsdCBvbmVdCkMgLS0-fFR3b3wgRVtSZXN1bHQgdHdvXQpDIC0tPnxUaHJlZXwgRltSZXN1bHQgdGhyZWVdCkMgLS0-fEZvdXJ8IEdbUmVzdWx0IGZvdXJd

![image](https://user-images.githubusercontent.com/733544/37550610-11b2bfb6-29cb-11e8-97b0-7983ce264f0b.png)
