### ISSUE TITLE
Nodes aren't aligned properly (just need an explanation)

### ISSUE THREAD

**Issue by trichetriche** [knsv/mermaid#568]
Hi ! first of all thank you for this amazing library. I've decided to use it in one of my project. I needed to build a process tree and your library suits that perfectly. 

Today, while testing, we found a strange error : some nodes aren't aligned properly. I think that I should just show it to you : 

![mermaid_error](https://user-images.githubusercontent.com/7789922/29971059-34946b5e-8f27-11e7-9bbc-729ec1b0bc9b.PNG)

As you can see in the last row, on the right side of the perfect middle, some nodes aren't aligned properly (the arrow goes farer than expected). 

My boss asked me to find why it does that, and I legit tried to read each file of the source, but after a couple of hours, I gave up. 

All I need to know is **why** it does that, and not to correct it (for now at least). I thought that it was a symmetry issue since the arrow next door is behaving as silly as this one. But why would it put the symmetry line not in the middle ? 

Thank you in advance for any help on that !

**Comment by tylerlong** [comment]
Sorry for the late reply but flowchart layout is powered by https://github.com/dagrejs/dagre and https://github.com/dagrejs/dagre-d3. Maybe you can find an answer there.
