### ISSUE TITLE
The documentation for CLI seems outdated.

### ISSUE THREAD

**Issue by zhanzhenzhen** [knsv/mermaid#572]
I just found that the CLI caused errors when upgrading to 7.0.18 yesterday. It said the bin file contains the `import` keyword which can't be parsed by Node.js. Today I even saw the 7.1.0 version removed the CLI. But the documentation is not yet updated.

Also, I have a question: Is using CLI+PhantomJS the only method to generate PNG images on a server?

**Comment by tylerlong** [comment]
CLI has been moved: https://github.com/mermaidjs/mermaid.cli
