### ISSUE TITLE
Subgraph title label overflow

### ISSUE THREAD

**Issue by larsw** [knsv/mermaid#579]
Hi,

Is the title/label overflow as expected, is it a bug, or can I resolve it with additional markup?

![image](https://user-images.githubusercontent.com/63235/30962894-cc303860-a44b-11e7-9f67-3b9b129466c3.png)
https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKICAgIGMxLS0-YTIKICAgIHN1YmdyYXBoIE9uZSBTZXJ2aWNlIEdvZXMgaGVyZQogICAgYTEtLT5hMgogICAgZW5kCiAgICBzdWJncmFwaCBPdGhlciBPbmUgR29lcyBIZXJlCiAgICBiMS0tPmIyCiAgICBlbmQKICAgIHN1YmdyYXBoIFRoaXJkIE9uZSBPdmVyIEhlcmUKICAgIGMxLS0-YzIKICAgIGVuZA

**Comment by Ozmoica** [comment]
+1. I have the same problem. Also if the titles are very long then overlap itselfs..

**Comment by cmur2** [comment]
I also encounter that problem with something I'm working on and the example given by the original poster.
