### ISSUE TITLE
Rounded connections

### ISSUE THREAD

**Issue by eduo** [knsv/mermaid#580]
Hello.

Have you considered adding the possibility of making the connectors in flowcharts rounded when not exactly vertical or horizontal?

Currently a straight line is drawn, unless it overlaps with another one in which case both are angled. This is a good solution but visually it looks a bit weird. Especially for roundtrips.

Smoothing out those angles into curves (and nothing else) would immediately improve visibility.

I'm not saying improve collision detection or smart paths for complex diagrams. Although this would be nice it's also orders of magnitude more complex.

**Comment by liyawang** [comment]
Second this. I actually see very sharp angles as attached.
<img width="295" alt="screen shot 2017-11-10 at 8 44 40 pm" src="https://user-images.githubusercontent.com/1692806/32685039-20d08cd4-c658-11e7-8358-0ec59c9e60d6.png">

**Comment by tylerlong** [comment]
I believe there is a feature in D3 called `interpolate`. I've seen some code about it in mermaid but not sure it works.

**Comment by tylerlong** [comment]
I've added an new option to mermaid:

```js
mermaid.initialize({
  flowchart: { 
    curve: 'basis' 
  }
});
```
`flowchart.curve` by default is `linear` and you think it is not rounded enough. Change it to `basis` will be much better.

## `curve === 'linear'`

![image](https://user-images.githubusercontent.com/733544/37557177-aaf7a766-2a3b-11e8-93e1-8dcadcda6b0c.png)


## `curve === 'basis'`

![image](https://user-images.githubusercontent.com/733544/37557173-9e5e1e18-2a3b-11e8-9bd0-828b4f2fb89e.png)

**Comment by kitsu** [comment]
To enable this for a flow chart without access to the Mermaid object (i.e. in a markdown document) use `linkStyle default interpolate basis`.

``` mermaid
graph TD
  %% Set edges to be curved (try monotoneX for a nice alternative)
  linkStyle default interpolate basis
  A[Christmas] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[fa:fa-car Car]
```

Your Jison grammar is a little hard to read, but it is a good reference!

**Comment by legoming** [comment]
Can I use the same method to change the curve line of sequenceDiagram -- the loop line point to self?
