### ISSUE TITLE
Add unique IDs to flowchart edges

### ISSUE THREAD

**Issue by SSchwaiger** [knsv/mermaid#583]
I'd like to attach a onClick event handler to every edge to display context information. But (different from the nodes), the edge don't get a unique ID.

My suggestion for this ID is a concatenation of the node's IDs they connect.

Regards

Sebastian

**Comment by crankycyclops** [comment]
I would also love to see this feature.

**Comment by crankycyclops** [comment]
It looks like the lack of an ID on the edges is an issue with the dagre-d3 library that mermaid depends on, and isn't something the author of mermaid can do anything about (at least it doesn't seem so at first glance.) I have a very messy workaround that requires you to edit this library after running "yarn install" on a copy of the current repo. Just in case it helps you in your particular use case, I'm posting it here.

cd mermaid
yarn install
vim node_modules/dagre-d3-renderer/dist/dagre-d3.core.js (or use your other favorite text editor)

Then, in your editor:

1. search for the line "function createEdgePaths(selection, g, arrows) {"
2. Scroll through that function until you find the line "if (edge.id) {"
3. Right before that line, add the following extra line of code: "edge.id = _util2.default.edgeToId(e);"

Exit your editor.

cd back to mermaid
yarn build
copy the resulting mermaid.js to your webroot. Now, each edge will have an id that includes the ids of the start and end nodes. Very helpful.

I'm sure this is a terrible solution, but for now, I'm not sure what else to do. At least it works for me ;)

**Comment by crankycyclops** [comment]
Alternatively, you can build mermaid, then edit the resulting mermaid.js afterward.

**Comment by crankycyclops** [comment]
More digging, and I discovered the proper fix for this, and one that could easily be integrated into the mermaid library, where it belongs.

Edit src/diagrams/flowchart/flowRenderer.js and add this line just before the call to g.setEdge:

`edgeData.id = edge.start + '_' + edge.end;`

This change is trivial to make and will, I believe, help other people, so I'm going to open a separate issue with a proposed patch.

**Comment by crankycyclops** [comment]
I've just posted a patch in #701. I hope the maintainers will consider adding it to Mermaid, as it's simple and I think it would help some people out :)

**Comment by Heiko-san** [comment]
Just as a besides note:
Actually you can do the following in mermaid, resulting in 2 connectors being drawn from A to B:
```
A-->B
A-->B
```
This may not be a commonly used case, but it is valid and would definitely result in an ID conflict using:
```
edgeData.id = edge.start + '_' + edge.end;
```
