### ISSUE TITLE
sequenceDiagram -> notetext css font is hardcoded

### ISSUE THREAD

**Issue by agusmba** [knsv/mermaid#587]
See https://github.com/knsv/mermaid/blob/7c74107f360dee4bceb197a2802bfd89a2a8dc64/src/less/default/sequenceDiagram.less#L73

I think this is preventing me from modifying the font of notes.

I don't know if there is a good reason for this or could this be removed?

**Comment by tylerlong** [comment]
Please refer to https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785
