### ISSUE TITLE
Golang based editor

### ISSUE THREAD

**Issue by joeblew99** [knsv/mermaid#588]
Anyone know of a golang one ?
Outputting svg with golang is very easy as well as pdf.
It's just a matter of finding a parser to parse the mermaid markdown.

Ultimately I want to use this to allow developer to describe orchestration workflows and then codegen the Js code that executes the workflow.

The Js runs inside a JavaScript VM that is build with golang.

I know this is a Js based project but I figured it's worth asking.

**Comment by tylerlong** [comment]
Check this project: https://github.com/mermaidjs/mermaid.cli
