### ISSUE TITLE
Remove status code

### ISSUE THREAD

**Issue by gmdutra** [knsv/mermaid#589]
Hello guys. How do you remove the status code? I'm sending print screen
[https://i.imgur.com/TAw4CrP.png](url)

**Comment by erikh2000** [comment]
Your link goes to a 404. It's hard to understand what the status code is that you are describing.

**Comment by gmdutra** [comment]
I'm sorry. [https://i.imgur.com/nqPLjH9.png](url)

**Comment by gmdutra** [comment]
![captura de tela de 2017-10-31 08-59-45](https://user-images.githubusercontent.com/19363862/32220802-3d2a13fa-be1a-11e7-9fd6-4678d5eccc25.png)

How to remove these one??

**Comment by erikh2000** [comment]
By status code, you mean the little number at the bottom of the 2 boxes?

Maybe post your graph markup in case there is an easy way to fix it by editing the graph.
