### ISSUE TITLE
Async arrows in sequence diagram.

### ISSUE THREAD

**Issue by erikh2000** [knsv/mermaid#590]
I am uncertain about how to express an asynchronous message with the sequence diagram. In most UML I've seen, either an open arrow (stick arrow) or a half arrow is used to indicate an async message. Mermaid offers "-X" and "--X" (lines with X at the end) and describes them as "(async)". But I haven't found any non-Mermaid documentation that show this convention being used. I did find one that said those icons could be used to indicate *synchronous* messages, which would be the opposite of what the Mermaid docs say. What is a generally accepted way to indicate async messages using Mermaid? Maybe there is some variant of UML documented someplace that Mermaid is based on?

Much thanks to Knut, Tyler, and other contributors. It may sound like I'm complaining above, but I'm a fan of Mermaid. It is much better than what I've used in the past.

**Comment by tylerlong** [comment]
I have the feeling that the flowchart/sequenceDiagram/ganttDiagram DSL are not very expressive. If there many different cases, it's hard to cover all of them.

I have been thinking about it recently.

**Comment by winterer** [comment]
This is still an issue. "-X" (or "--X") produces no valid asnychronous message arrows.

**Comment by hankyusa** [comment]
Duplicate of #1528
