### ISSUE TITLE
How to use mermaid on node.js restful api?

### ISSUE THREAD

**Issue by robertrita** [knsv/mermaid#593]
I'm not an expert with javascript. Below is how I did it.
expected output: .svg or .png file that I can show on the response as full path.
Please help. thanks.

---------------------------
const express = require('express');
const mermaidAPI = require('mermaid');

app.get('/chart', (req, res) => {
	mermaidAPI.initialize({
	    startOnLoad: true
	})
	const graphDefinition = 'graph TB\na-->b'
	const cb = function(svgGraph) {
	   console.log(svgGraph)
	}
	mermaidAPI.render('id1',graphDefinition,cb)

	res.status(200).json('.svg or .png file path here!');
})
---------------------------

**Comment by aimed** [comment]
You can use the mermaid.cli to create the image serverside, then serve it.
If you don't want to use the cli, look at how it uses a headless browser (puppeteer) to generate the files.

**Comment by tylerlong** [comment]
@aimed  is correct. Please refer to https://github.com/mermaidjs/mermaid.cli
