### ISSUE TITLE
stylesheet crashed with other library like abcjs

### ISSUE THREAD

**Issue by cyrusn** [knsv/mermaid#596]
<img width="983" alt="screen shot 2017-12-01 at 10 58 47" src="https://user-images.githubusercontent.com/5738511/33466112-d7e1b5ae-d686-11e7-87b2-a3813d7fb603.png">

The mermaid inserted style affect other `svg` tag generated by other library like `abcjs`. As the mermaid inserted style may not all nested in .mermaid class, so that coloyr of the stem in the score changed. Should it nest all mermaid style in .mermaid class?

Thank you.

**Comment by cyrusn** [comment]
#577 

Oh, I just found that the pull request should fix this problem.

**Comment by tylerlong** [comment]
Yes, it should have been fixed in the latest version.
