### ISSUE TITLE
Just saying thanks!

### ISSUE THREAD

**Issue by jdbranham** [knsv/mermaid#597]
Thanks @knsv and everyone that contributes to mermaid.
I'm leveraging it for a Grafana plugin that is turning out to be quite popular. 

https://github.com/jdbranham/grafana-diagram/

**Comment by tylerlong** [comment]
You can add your project to "downstream projects" section of https://mermaidjs.github.io/ by creating an PR to https://github.com/mermaidjs/mermaid-gitbook
