### ISSUE TITLE
Encoding creates a left offset

### ISSUE THREAD

**Issue by ciarans** [knsv/mermaid#599]
When I encode the following in the live editor on https://mermaidjs.github.io/mermaid-live-editor/#/ and my app 

```
graph TD
cb134ad3-2f8f-ba8f-41db-59bd060ef112(("fa:fa-play Start"))-->|"Send Call In #quot;Sales#quot; Queue"|da2eb2ff-4548-f80f-db09-e5cdb64ed05f(("Queue"))
da2eb2ff-4548-f80f-db09-e5cdb64ed05f(("fa:fa-stack-overflow Queue"))-.->|"Dial a team member"|da2eb2ff-4548-f80f-db09-e5cdb64ed05f-dial-0{"Send Call In #quot;Sales#quot; Queue"}
```

I get a left offset - anyone else experienced this?

Here is a link

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKY2IxMzRhZDMtMmY4Zi1iYThmLTQxZGItNTliZDA2MGVmMTEyKCgiZmE6ZmEtcGxheSBTdGFydCIpKS0tPnwiU2VuZCBDYWxsIEluICNxdW90O1NhbGVzI3F1b3Q7IFF1ZXVlInxkYTJlYjJmZi00NTQ4LWY4MGYtZGIwOS1lNWNkYjY0ZWQwNWYoKCJRdWV1ZSIpKQpkYTJlYjJmZi00NTQ4LWY4MGYtZGIwOS1lNWNkYjY0ZWQwNWYoKCJmYTpmYS1zdGFjay1vdmVyZmxvdyBRdWV1ZSIpKS0uLT58IkRpYWwgYSB0ZWFtIG1lbWJlciJ8ZGEyZWIyZmYtNDU0OC1mODBmLWRiMDktZTVjZGI2NGVkMDVmLWRpYWwtMCgoIlNlbmQgQ2FsbCBJbiAjcXVvdDtTYWxlcyNxdW90OyBRdWV1ZSIpKQ

**Comment by tylerlong** [comment]
Confirmed.  Interesting problem.

I think it is because you encode the text so mermaid failed to calculate the correct width of the whole text. `#quote;` is much longer than `"`.

**Comment by ciarans** [comment]
@tylerlong I never got this working and simply changed `#quot;` to `''` (Two single quotes)
