### ISSUE TITLE
classDiagram cardinality not showing

### ISSUE THREAD

**Issue by ruizmarc** [knsv/mermaid#602]
Hi,

I'm using  mermaid 7.0.17 in a classDiagram and I'm trying to show cardinality following the example in the specs. However cardinality is not being showed. I know it is an experimental feature, but I think it is worth to mention the problem to take it into consideration.

This is an example of how I'm using cardinality:  

` User "1" *-- "many" Session `

EDIT: Also tested with 7.1

**Comment by Vrixyz** [comment]
As main maintainer is  not available to fix that for the moment, I suggest delving into details here, so it helps him or whoever has time to fix it.

I'll post my findings in this issue, and eventually I might look into submit a Merge Request.

# Technical understanding

## Parser

From my understanding of [classDiagram parser](https://github.com/knsv/mermaid/blob/master/src/diagrams/class/parser/classDiagram.jison#L165) : the parsing of cardinality looks like it's done within `STR`, then transformed into properties `relationTitle1` and `relationTitle2`, so my guess is we don't have to improve on `classDiagram.jison` :tada: 

## Renderer initialization

[For each relations](https://github.com/knsv/mermaid/blob/3e9215b27d23a92dc02766a0ee5b37c25179298d/src/diagrams/class/classRenderer.js#L343), the whole relation object we saw in the parser is passed to the "edge" within the [graphlib](https://github.com/dagrejs/graphlib/wiki) graph. So we don't have to worry about how to pass our information to multiple layers of functions :tada: 

## Renderer last run

Next let's check the [drawEdge function](https://github.com/knsv/mermaid/blob/3e9215b27d23a92dc02766a0ee5b37c25179298d/src/diagrams/class/classRenderer.js#L123)

We notice there is a [title attached to a relation](https://github.com/knsv/mermaid/blob/3e9215b27d23a92dc02766a0ee5b37c25179298d/src/diagrams/class/classRenderer.js#L181), its origin is not relevant but [here it is](https://github.com/knsv/mermaid/blob/master/src/diagrams/class/parser/classDiagram.jison#L141)

[Here](https://github.com/knsv/mermaid/blob/3e9215b27d23a92dc02766a0ee5b37c25179298d/src/diagrams/class/classRenderer.js#L169) begins some maths, somewhere from there there is magical code to put the title at half the length of the edge/path/relation.


I'll continue if/when I have time, maths without comments scared me out :rabbit2: .

**Comment by NMarkgraf** [comment]
It is 2025 and still not working! --- Bad job! ;-)
