### ISSUE TITLE
Why does this code's flowchart lines get cut-off on screen?

### ISSUE THREAD

**Issue by mpaine-act** [knsv/mermaid#604]

**Comment by mpaine-act** [comment]
[Workflow.txt](https://github.com/knsv/mermaid/files/1543879/Workflow.txt)

**Comment by tylerlong** [comment]
It is an known issue. Currently a workaround is to change `graph TD` to `graph LR`

https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFI7IAogICAgICAgICAgICAgICAgQW55b25lWzx1PkFueW9uZTwvdT46PGJyPkJ1cyBTdG9wIFJlcGFpcl0gCgogICAgICAgICAgICAgICAgV1JOZXdbPHU-V1IgTmV3PC91Pl0KICAgICAgICAgICAgICAgIFdSQXBwcm92ZWRbPHU-V1IgQXBwcm92ZWQ8L3U-XQogICAgICAgICAgICAgICAgV1JSZWplY3RlZFs8dT5XUiBSZWplY3RlZDwvdT5dCiAgICAgICAgICAgICAgICBXUlN0YXJ0ZWRbPHU-V1IgU3RhcnRlZDwvdT5dCiAgICAgICAgICAgICAgICBXUkNvbXBsZXRlZFs8dT5XUiBDb21wbGV0ZWQ8L3U-XQogICAgICAgICAgICAgICAgV1JDbG9zZWRbPHU-V1IgQ2xvc2VkPC91Pl0KICAgICAgICAgICAgICAgIFdSUmVkaXJlY3RlZFs8dT5XUiBSZWRpcmVjdGVkPC91Pl0KICAgICAgICAgICAgICAgIFdPU3RhcnRbPHU-V29yayBPcmRlcjogQ1JFQVRFRDwvdT5dCiAgICAgICAgICAgICAgICBXT0Nsb3NlWzx1PldvcmsgT3JkZXI6IENMT1NFRDwvdT5dCgogICAgICAgICAgICAgICAgQW55b25lLS0-V1JOZXdOb3RpZnkKICAgICAgICAgICAgICAgIFdSTmV3LS0-V1JBcHByb3ZlZAogICAgICAgICAgICAgICAgV1JOZXctLT5XUlJlamVjdGVkTm90aWZ5CiAgICAgICAgICAgICAgICBXUk5ldy0tPldSQ2xvc2VkCiAgICAgICAgICAgICAgICBXUk5ldy0tPldSUmVkaXJlY3RlZAogICAgICAgICAgICAgICAgV1JSZWRpcmVjdGVkLS0-V1JSZWRpcmVjdGVkCiAgICAgICAgICAgICAgICBXUlJlZGlyZWN0ZWQtLT5XUkFwcHJvdmVkCiAgICAgICAgICAgICAgICBXUlJlZGlyZWN0ZWQtLT5XUlJlamVjdGVkTm90aWZ5CiAgICAgICAgICAgICAgICBXUkFwcHJvdmVkLS0-V1JTdGFydGVkCiAgICAgICAgICAgICAgICBXUlN0YXJ0ZWQtLi0-V09TdGFydAogICAgICAgICAgICAgICAgV1JDb21wbGV0ZWQtLT5XUkNsb3NlZAogICAgICAgICAgICAgICAgV1JSZWplY3RlZC0tPldSQ2xvc2VkCiAgICAgICAgICAgICAgICBXT1N0YXJ0LS0gUG9sZSBDcmV3IC0tPldPQ2xvc2UKICAgICAgICAgICAgICAgIFdPQ2xvc2UtLi0-V1JDb21wbGV0ZWROb3RpZnkKCiAgICAgICAgICAgICAgICBXUk5ld05vdGlmeVs8dT5XUiBOZXc6IE5PVElGWTwvdT48YnI-QlNQQyBNYW5hZ2VyXQogICAgICAgICAgICAgICAgV1JSZWplY3RlZE5vdGlmeVs8dT5XUiBSZWplY3RlZDogTk9USUZZPC91Pjxicj5CU1BDIE1hbmFnZXJdCiAgICAgICAgICAgICAgICBXUlN0YXR1c0NoYW5nZVsxLiA8dT5BbnkgV1IgU3RhdHVzIENoYW5nZTogTk9USUZZPC91Pjo8YnI-Q3JlYXRvciwgQ29udHJpYnV0b3JdCiAgICAgICAgICAgICAgICBXUkNvbXBsZXRlZE5vdGlmeVs8dT5XUiBDb21wbGV0ZWQ6IE5PVElGWTwvdT48YnI-QlNQQyBNYW5hZ2VyXQogICAgICAgICAgICAgICAgc3R5bGUgV1JTdGF0dXNDaGFuZ2UgZmlsbDojY2NmCiAgICAgICAgICAgICAgICBzdHlsZSBXT1N0YXJ0IGZpbGw6IzlmOQogICAgICAgICAgICAgICAgc3R5bGUgV09DbG9zZSBmaWxsOiM5ZjkKCiAgICAgICAgICAgICAgICBXUk5ld05vdGlmeS0tPldSTmV3CiAgICAgICAgICAgICAgICBXUlJlamVjdGVkTm90aWZ5LS0-V1JSZWplY3RlZAogICAgICAgICAgICAgICAgV1JDb21wbGV0ZWROb3RpZnktLT5XUkNvbXBsZXRlZA

**Comment by mpaine-act** [comment]
Changing from TD to LR didn't help, it is still cut off.   Any tips where in mermaid source is the problem, I can review it.  I love this project btw.

**Comment by tylerlong** [comment]
Code for flowchart is here: https://github.com/knsv/mermaid/tree/master/src/diagrams/flowchart

Let me know if you find anything. I would like to fix it too.

And by the way, flowchart is powered by https://github.com/dagrejs/dagre-d3/wiki

**Comment by tylerlong** [comment]
Fixed. https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7IFxuICAgICAgICAgICAgICAgIEFueW9uZVs8dT5BbnlvbmU8L3U-Ojxicj5CdXMgU3RvcCBSZXBhaXJdIFxuXG4gICAgICAgICAgICAgICAgV1JOZXdbPHU-V1IgTmV3PC91Pl1cbiAgICAgICAgICAgICAgICBXUkFwcHJvdmVkWzx1PldSIEFwcHJvdmVkPC91Pl1cbiAgICAgICAgICAgICAgICBXUlJlamVjdGVkWzx1PldSIFJlamVjdGVkPC91Pl1cbiAgICAgICAgICAgICAgICBXUlN0YXJ0ZWRbPHU-V1IgU3RhcnRlZDwvdT5dXG4gICAgICAgICAgICAgICAgV1JDb21wbGV0ZWRbPHU-V1IgQ29tcGxldGVkPC91Pl1cbiAgICAgICAgICAgICAgICBXUkNsb3NlZFs8dT5XUiBDbG9zZWQ8L3U-XVxuICAgICAgICAgICAgICAgIFdSUmVkaXJlY3RlZFs8dT5XUiBSZWRpcmVjdGVkPC91Pl1cbiAgICAgICAgICAgICAgICBXT1N0YXJ0Wzx1PldvcmsgT3JkZXI6IENSRUFURUQ8L3U-XVxuICAgICAgICAgICAgICAgIFdPQ2xvc2VbPHU-V29yayBPcmRlcjogQ0xPU0VEPC91Pl1cblxuICAgICAgICAgICAgICAgIEFueW9uZS0tPldSTmV3Tm90aWZ5XG4gICAgICAgICAgICAgICAgV1JOZXctLT5XUkFwcHJvdmVkXG4gICAgICAgICAgICAgICAgV1JOZXctLT5XUlJlamVjdGVkTm90aWZ5XG4gICAgICAgICAgICAgICAgV1JOZXctLT5XUkNsb3NlZFxuICAgICAgICAgICAgICAgIFdSTmV3LS0-V1JSZWRpcmVjdGVkXG4gICAgICAgICAgICAgICAgV1JSZWRpcmVjdGVkLS0-V1JSZWRpcmVjdGVkXG4gICAgICAgICAgICAgICAgV1JSZWRpcmVjdGVkLS0-V1JBcHByb3ZlZFxuICAgICAgICAgICAgICAgIFdSUmVkaXJlY3RlZC0tPldSUmVqZWN0ZWROb3RpZnlcbiAgICAgICAgICAgICAgICBXUkFwcHJvdmVkLS0-V1JTdGFydGVkXG4gICAgICAgICAgICAgICAgV1JTdGFydGVkLS4tPldPU3RhcnRcbiAgICAgICAgICAgICAgICBXUkNvbXBsZXRlZC0tPldSQ2xvc2VkXG4gICAgICAgICAgICAgICAgV1JSZWplY3RlZC0tPldSQ2xvc2VkXG4gICAgICAgICAgICAgICAgV09TdGFydC0tIFBvbGUgQ3JldyAtLT5XT0Nsb3NlXG4gICAgICAgICAgICAgICAgV09DbG9zZS0uLT5XUkNvbXBsZXRlZE5vdGlmeVxuXG4gICAgICAgICAgICAgICAgV1JOZXdOb3RpZnlbPHU-V1IgTmV3OiBOT1RJRlk8L3U-PGJyPkJTUEMgTWFuYWdlcl1cbiAgICAgICAgICAgICAgICBXUlJlamVjdGVkTm90aWZ5Wzx1PldSIFJlamVjdGVkOiBOT1RJRlk8L3U-PGJyPkJTUEMgTWFuYWdlcl1cbiAgICAgICAgICAgICAgICBXUlN0YXR1c0NoYW5nZVsxLiA8dT5BbnkgV1IgU3RhdHVzIENoYW5nZTogTk9USUZZPC91Pjo8YnI-Q3JlYXRvciwgQ29udHJpYnV0b3JdXG4gICAgICAgICAgICAgICAgV1JDb21wbGV0ZWROb3RpZnlbPHU-V1IgQ29tcGxldGVkOiBOT1RJRlk8L3U-PGJyPkJTUEMgTWFuYWdlcl1cbiAgICAgICAgICAgICAgICBzdHlsZSBXUlN0YXR1c0NoYW5nZSBmaWxsOiNjY2ZcbiAgICAgICAgICAgICAgICBzdHlsZSBXT1N0YXJ0IGZpbGw6IzlmOVxuICAgICAgICAgICAgICAgIHN0eWxlIFdPQ2xvc2UgZmlsbDojOWY5XG5cbiAgICAgICAgICAgICAgICBXUk5ld05vdGlmeS0tPldSTmV3XG4gICAgICAgICAgICAgICAgV1JSZWplY3RlZE5vdGlmeS0tPldSUmVqZWN0ZWRcbiAgICAgICAgICAgICAgICBXUkNvbXBsZXRlZE5vdGlmeS0tPldSQ29tcGxldGVkIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by lijuld** [comment]
How did you fix it?
