### ISSUE TITLE
classDiagram feature request : Unnassociated classes

### ISSUE THREAD

**Issue by M0dM** [knsv/mermaid#609]
Hi again,

Like in my previous issue (#608) I propose to add a new feature to mermaid class diagram generation.
-> Allow unnassociated classes.

One good example of this class is a class used for converting money between two currencies.
Most of the time this type of classes will not be linked with any other classes in the model.
It is just usefull when you need to convert a money to another, and because money value change frequently, we want to store the value in database and refresh them periodically.

I am still open to spend some time on this if I have a some help to start.

**Comment by vikram-rawat** [comment]
I have my fingers crossed for Class diagram because I can use it to create a database diagram in a much better way. But it is still experimental since like 10 months or so.... Please at least offer an intial state.

**Comment by tylerlong** [comment]
Currently I seem to be the only active contributor to this project. And class diagram was created by the original author and he hasn't came back to this project for quite a while.

And the top priority currently is to release mermaid 8.0 which supports D3 V4 and fix bugs in the three most popular diagrams: flowchart, sequence diagram and gantt diagram.

**Comment by blackTay** [comment]
Any updates on this feature request? Unassociated classes would be very useful and don't seem to be much work to code.
