### ISSUE TITLE
Inconsistency in rendering HTML labels in diagrams

### ISSUE THREAD

**Issue by aral** [knsv/mermaid#611]
Reference: https://github.com/vjeantet/hugo-theme-docdock/issues/112

It looks like Mermaid is rendering a `foreignObject` tag correctly for flowcharts but it’s not doing so for a sequence diagram. This breaks the search term highlighting in Hugo Learn Theme and its fork, Hugo DocDock Theme (see issue referenced above).

Flowchart:

<img width="509" alt="screen shot 2017-12-26 at 12 16 34" src="https://user-images.githubusercontent.com/41798/34355731-fd216976-ea37-11e7-8fe0-52214bec4a78.png">

Sequence diagram:

<img width="922" alt="screen shot 2017-12-26 at 12 34 04" src="https://user-images.githubusercontent.com/41798/34355904-432aa6c0-ea39-11e7-9868-d3aeda124075.png">

(Both DOM fragments shown after the Hugo theme has marked up the text as a search match. The effect on the sequence diagram is to make the text disappear.)

CC @matcornic @vjeantet

**Comment by tylerlong** [comment]
Thank you for reporting this.

I am by no means a SVG standard expert. I want to ask: when is `foreignObject` required? Should  all `text` tags be enclosed in `foreignObject` tags?
