### ISSUE TITLE
The new online editor does not support previously generated links

### ISSUE THREAD

**Issue by marceloogeda** [knsv/mermaid#613]
![image](https://user-images.githubusercontent.com/3205036/34387457-73cd13a8-eb15-11e7-8ae4-ac299dc7cad2.png)

**Comment by cabralj** [comment]
Was sbout to report the same thing...  support for Gantt no longer working.

**Comment by cabralj** [comment]
as of 2018-01-10 gantt charts now appear to be working.

**Comment by tylerlong** [comment]
Great. Feel free to reopen if you still have this issue.
