### ISSUE TITLE
Example export to SVG generates error

### ISSUE THREAD

**Issue by marceloboeira** [knsv/mermaid#614]
The page's example: Larger flowchart with some styling
```
graph TB
    sq[Square shape] --> ci((Circle shape))

    subgraph A subgraph
        od>Odd shape]-- Two line<br/>edge comment --> ro
        di{Diamond with <br/> line break} -.-> ro(Rounded<br>square<br>shape)
        di==>ro2(Rounded square shape)
    end

    %% Notice that no text in shape are added here instead that is appended further down
    e --> od3>Really long text with linebreak<br>in an Odd shape]

    %% Comments after double percent signs
    e((Inner / circle<br>and some odd <br>special characters)) --> f(,.?!+-*ز)

    cyr[Cyrillic]-->cyr2((Circle shape Начало));

     classDef green fill:#9f6,stroke:#333,stroke-width:2px;
     classDef orange fill:#f96,stroke:#333,stroke-width:4px;
     class sq,e green
     class di orange
```

If exported to SVG,  it returns this as an error:

```
This page contains the following errors:
error on line 7 at column 4440: Opening and ending tag mismatch: br line 0 and div
Below is a rendering of the page up to the first error.
```

**Comment by tylerlong** [comment]
I have updated https://mermaidjs.github.io/mermaid-live-editor/. So if you download a SVG file there, `<br>`s are already replace with `<br/>`s.

**Comment by tylerlong** [comment]
I also updated the mermaid file so it will auto convert `<br>` to `<br/>`.

**Comment by marceloboeira** [comment]
@tylerlong thanks!

**Comment by cdrfun** [comment]
@tylerlong  I'm still getting the error and using <br/> wont't help. Here's the example from @marceloboeira 

- [Original](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgICBzcVtTcXVhcmUgc2hhcGVdIC0tPiBjaSgoQ2lyY2xlIHNoYXBlKSlcblxuICAgIHN1YmdyYXBoIEEgc3ViZ3JhcGhcbiAgICAgICAgb2Q-T2RkIHNoYXBlXS0tIFR3byBsaW5lPGJyLz5lZGdlIGNvbW1lbnQgLS0-IHJvXG4gICAgICAgIGRpe0RpYW1vbmQgd2l0aCA8YnIvPiBsaW5lIGJyZWFrfSAtLi0-IHJvKFJvdW5kZWQ8YnI-c3F1YXJlPGJyPnNoYXBlKVxuICAgICAgICBkaT09PnJvMihSb3VuZGVkIHNxdWFyZSBzaGFwZSlcbiAgICBlbmRcblxuICAgICUlIE5vdGljZSB0aGF0IG5vIHRleHQgaW4gc2hhcGUgYXJlIGFkZGVkIGhlcmUgaW5zdGVhZCB0aGF0IGlzIGFwcGVuZGVkIGZ1cnRoZXIgZG93blxuICAgIGUgLS0-IG9kMz5SZWFsbHkgbG9uZyB0ZXh0IHdpdGggbGluZWJyZWFrPGJyPmluIGFuIE9kZCBzaGFwZV1cblxuICAgICUlIENvbW1lbnRzIGFmdGVyIGRvdWJsZSBwZXJjZW50IHNpZ25zXG4gICAgZSgoSW5uZXIgLyBjaXJjbGU8YnI-YW5kIHNvbWUgb2RkIDxicj5zcGVjaWFsIGNoYXJhY3RlcnMpKSAtLT4gZigsLj8hKy0q2LIpXG5cbiAgICBjeXJbQ3lyaWxsaWNdLS0-Y3lyMigoQ2lyY2xlIHNoYXBlINCd0LDRh9Cw0LvQvikpO1xuXG4gICAgIGNsYXNzRGVmIGdyZWVuIGZpbGw6IzlmNixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4O1xuICAgICBjbGFzc0RlZiBvcmFuZ2UgZmlsbDojZjk2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHg7XG4gICAgIGNsYXNzIHNxLGUgZ3JlZW5cbiAgICAgY2xhc3MgZGkgb3JhbmdlIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)
- [`<br/>` Correction ](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgICBzcVtTcXVhcmUgc2hhcGVdIC0tPiBjaSgoQ2lyY2xlIHNoYXBlKSlcblxuICAgIHN1YmdyYXBoIEEgc3ViZ3JhcGhcbiAgICAgICAgb2Q-T2RkIHNoYXBlXS0tIFR3byBsaW5lPGJyLz5lZGdlIGNvbW1lbnQgLS0-IHJvXG4gICAgICAgIGRpe0RpYW1vbmQgd2l0aCA8YnIvPiBsaW5lIGJyZWFrfSAtLi0-IHJvKFJvdW5kZWQ8YnIvPnNxdWFyZTxici8-c2hhcGUpXG4gICAgICAgIGRpPT0-cm8yKFJvdW5kZWQgc3F1YXJlIHNoYXBlKVxuICAgIGVuZFxuXG4gICAgJSUgTm90aWNlIHRoYXQgbm8gdGV4dCBpbiBzaGFwZSBhcmUgYWRkZWQgaGVyZSBpbnN0ZWFkIHRoYXQgaXMgYXBwZW5kZWQgZnVydGhlciBkb3duXG4gICAgZSAtLT4gb2QzPlJlYWxseSBsb25nIHRleHQgd2l0aCBsaW5lYnJlYWs8YnIvPmluIGFuIE9kZCBzaGFwZV1cblxuICAgICUlIENvbW1lbnRzIGFmdGVyIGRvdWJsZSBwZXJjZW50IHNpZ25zXG4gICAgZSgoSW5uZXIgLyBjaXJjbGU8YnIvPmFuZCBzb21lIG9kZCA8YnIvPnNwZWNpYWwgY2hhcmFjdGVycykpIC0tPiBmKCwuPyErLSrYsilcblxuICAgIGN5cltDeXJpbGxpY10tLT5jeXIyKChDaXJjbGUgc2hhcGUg0J3QsNGH0LDQu9C-KSk7XG5cbiAgICAgY2xhc3NEZWYgZ3JlZW4gZmlsbDojOWY2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHg7XG4gICAgIGNsYXNzRGVmIG9yYW5nZSBmaWxsOiNmOTYsc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjRweDtcbiAgICAgY2xhc3Mgc3EsZSBncmVlblxuICAgICBjbGFzcyBkaSBvcmFuZ2UiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

Error when opening the svg with current Chrome: `error on line 352 at column 4922: Opening and ending tag mismatch: br line 0 and span`

**Comment by Vidyut** [comment]
I have mismatched tags br, line and div.

**Comment by Aneurin** [comment]
> @tylerlong I'm still getting the error and using `<br/>` wont't help. Here's the example from @marceloboeira
> 
> * [Original](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgICBzcVtTcXVhcmUgc2hhcGVdIC0tPiBjaSgoQ2lyY2xlIHNoYXBlKSlcblxuICAgIHN1YmdyYXBoIEEgc3ViZ3JhcGhcbiAgICAgICAgb2Q-T2RkIHNoYXBlXS0tIFR3byBsaW5lPGJyLz5lZGdlIGNvbW1lbnQgLS0-IHJvXG4gICAgICAgIGRpe0RpYW1vbmQgd2l0aCA8YnIvPiBsaW5lIGJyZWFrfSAtLi0-IHJvKFJvdW5kZWQ8YnI-c3F1YXJlPGJyPnNoYXBlKVxuICAgICAgICBkaT09PnJvMihSb3VuZGVkIHNxdWFyZSBzaGFwZSlcbiAgICBlbmRcblxuICAgICUlIE5vdGljZSB0aGF0IG5vIHRleHQgaW4gc2hhcGUgYXJlIGFkZGVkIGhlcmUgaW5zdGVhZCB0aGF0IGlzIGFwcGVuZGVkIGZ1cnRoZXIgZG93blxuICAgIGUgLS0-IG9kMz5SZWFsbHkgbG9uZyB0ZXh0IHdpdGggbGluZWJyZWFrPGJyPmluIGFuIE9kZCBzaGFwZV1cblxuICAgICUlIENvbW1lbnRzIGFmdGVyIGRvdWJsZSBwZXJjZW50IHNpZ25zXG4gICAgZSgoSW5uZXIgLyBjaXJjbGU8YnI-YW5kIHNvbWUgb2RkIDxicj5zcGVjaWFsIGNoYXJhY3RlcnMpKSAtLT4gZigsLj8hKy0q2LIpXG5cbiAgICBjeXJbQ3lyaWxsaWNdLS0-Y3lyMigoQ2lyY2xlIHNoYXBlINCd0LDRh9Cw0LvQvikpO1xuXG4gICAgIGNsYXNzRGVmIGdyZWVuIGZpbGw6IzlmNixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4O1xuICAgICBjbGFzc0RlZiBvcmFuZ2UgZmlsbDojZjk2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHg7XG4gICAgIGNsYXNzIHNxLGUgZ3JlZW5cbiAgICAgY2xhc3MgZGkgb3JhbmdlIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)
> * [`<br/>` Correction ](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgICBzcVtTcXVhcmUgc2hhcGVdIC0tPiBjaSgoQ2lyY2xlIHNoYXBlKSlcblxuICAgIHN1YmdyYXBoIEEgc3ViZ3JhcGhcbiAgICAgICAgb2Q-T2RkIHNoYXBlXS0tIFR3byBsaW5lPGJyLz5lZGdlIGNvbW1lbnQgLS0-IHJvXG4gICAgICAgIGRpe0RpYW1vbmQgd2l0aCA8YnIvPiBsaW5lIGJyZWFrfSAtLi0-IHJvKFJvdW5kZWQ8YnIvPnNxdWFyZTxici8-c2hhcGUpXG4gICAgICAgIGRpPT0-cm8yKFJvdW5kZWQgc3F1YXJlIHNoYXBlKVxuICAgIGVuZFxuXG4gICAgJSUgTm90aWNlIHRoYXQgbm8gdGV4dCBpbiBzaGFwZSBhcmUgYWRkZWQgaGVyZSBpbnN0ZWFkIHRoYXQgaXMgYXBwZW5kZWQgZnVydGhlciBkb3duXG4gICAgZSAtLT4gb2QzPlJlYWxseSBsb25nIHRleHQgd2l0aCBsaW5lYnJlYWs8YnIvPmluIGFuIE9kZCBzaGFwZV1cblxuICAgICUlIENvbW1lbnRzIGFmdGVyIGRvdWJsZSBwZXJjZW50IHNpZ25zXG4gICAgZSgoSW5uZXIgLyBjaXJjbGU8YnIvPmFuZCBzb21lIG9kZCA8YnIvPnNwZWNpYWwgY2hhcmFjdGVycykpIC0tPiBmKCwuPyErLSrYsilcblxuICAgIGN5cltDeXJpbGxpY10tLT5jeXIyKChDaXJjbGUgc2hhcGUg0J3QsNGH0LDQu9C-KSk7XG5cbiAgICAgY2xhc3NEZWYgZ3JlZW4gZmlsbDojOWY2LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHg7XG4gICAgIGNsYXNzRGVmIG9yYW5nZSBmaWxsOiNmOTYsc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjRweDtcbiAgICAgY2xhc3Mgc3EsZSBncmVlblxuICAgICBjbGFzcyBkaSBvcmFuZ2UiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)
> 
> Error when opening the svg with current Chrome: `error on line 352 at column 4922: Opening and ending tag mismatch: br line 0 and span`

Or [see here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkEgLS0yPGJyLz5MaW5lcy0tPkIiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) for a minimal example. The "Download SVG" option always seems to convert `<br/>` to `<br>` so I guess something's regressed here. Opening the downloaded SVG in a text editor and manually converting back to `<br/>` fixes it as expected.
