### ISSUE TITLE
how to get mermaidAPI?

### ISSUE THREAD

**Issue by lth946965333** [knsv/mermaid#617]
i use  <script src="mermaidAPI.js"></script>  ,and i have this file ,but when  i open the html , it tell me    ReferenceError: mermaidAPI is not defined  
this is  my code 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="mermaid.min.css">
</head>
<body>
  <div class="mermaid">
  graph LR
      id1(行号) --> id2(指令名称)
      id2(指令名称) --> id3(加载)
      id3(加载) --> id4(就绪)
      id4(就绪) --> id5(发送)
      id5(发送) --> id6(发送时间);
  </div>
  <script src="mermaidAPI.js"></script>
  
  
<script>

    mermaidAPI.initialize({
        startOnLoad:false
    });
    $(function(){
        // Example of using the API
        var element = document.querySelector("#graphDiv");

        var svgCode = "style id1 fill:#fff,stroke:#333,stroke-width:4px"

        var insertSvg = function(svgCode, bindFunctions){
            element.innerHTML = svgCode;
        };

        var graphDefinition = 'graph TB\na-->b';
        var graph = mermaidAPI.render('graphDiv', graphDefinition, insertSvg);
    });
</script>
</body>
</html>

**Comment by lth946965333** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="mermaid.min.css">
</head>
<body>
  <div class="mermaid">
  graph LR
      id1(行号) --> id2(指令名称)
      id2(指令名称) --> id3(加载)
      id3(加载) --> id4(就绪)
      id4(就绪) --> id5(发送)
      id5(发送) --> id6(发送时间);
  </div>
  <script src="mermaidAPI.js"></script>
  
  
<script>

    mermaidAPI.initialize({
        startOnLoad:false
    });
    $(function(){
        // Example of using the API
        var element = document.querySelector("#graphDiv");

        var svgCode = "style id1 fill:#fff,stroke:#333,stroke-width:4px"

        var insertSvg = function(svgCode, bindFunctions){
            element.innerHTML = svgCode;
        };

        var graphDefinition = 'graph TB\na-->b';
        var graph = mermaidAPI.render('graphDiv', graphDefinition, insertSvg);
    });
</script>
</body>
</html>

**Comment by tylerlong** [comment]
Please take this file as example for how to use mermaid in a static HTML page: https://github.com/knsv/mermaid/blob/master/dist/index.html

**Comment by zxzzxxzx** [comment]
So the usage of mermaidAPI is deprecated? Everything should be done through regular mermaid,js file? After executing 

yarn build:watch

mermaidAPI.js is not generated in dist folder

**Comment by apavlyut** [comment]
> So the usage of mermaidAPI is deprecated? Everything should be done through regular mermaid,js file? After executing
> 
> yarn build:watch
> 
> mermaidAPI.js is not generated in dist folder

call 

mermaid.mermaidAPI
