### ISSUE TITLE
Missing tags and releases for newer versions

### ISSUE THREAD

**Issue by hlfcoding** [knsv/mermaid#623]
I don't see tags or releases for 7.1.0, 7.1.1, 7.1.2. Releases with change notes would be ideal.

**Comment by tylerlong** [comment]
Yes. they are missing.

Due to lack of man power, we use npm.org as the main publish channel. 

I promise I will create tags and release notes for the upcoming version 8.0

**Comment by kghbln** [comment]
@tylerlong A quick and dirty 8.0.0 tag will be very much appreciated. Cheers.
