### ISSUE TITLE
Uncaught TypeError: _.constant is not a function (mermaid.js) 

### ISSUE THREAD

**Issue by SunilPetkar** [knsv/mermaid#626]
When i am trying to load mermaid.js in my angularjs directive it give me error Uncaught TypeError: _.constant is not a function
    at Object.<anonymous> (:3001/assets/lib/mermaid/mermaid.js:51354)

**Comment by tylerlong** [comment]
I have no experience with angularjs. But mermaid works with HTML without problem: https://github.com/knsv/mermaid/blob/f62736c7496cccb486b93a155da038baeba700e8/dist/index.html#L106

Where did you get the mermaid.js file and how did you try to load it?
