### ISSUE TITLE
Flowchart labels appear "cutoff" 

### ISSUE THREAD

**Issue by gregglind** [knsv/mermaid#628]
Example:

http://docs-origin.telemetry.mozilla.org/concepts/data_pipeline.html
```
<g transform="translate(-24.808334350585938,-11.900001525878906)" class="label"><foreignObject width="49.616668701171875" height="23.800003051757812">
<div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; white-space: nowrap;">
<span class="edgeLabel">parquet</span>
</div>
</foreignObject>
</g>
```

Here, the foreignObject 'witdh' is too small, and it cuts off the label.

**Comment by gregglind** [comment]
(Apparently it was the 'fontsettings' plugin to blame: "-fontsettings" in book.json fixes it.

**Comment by tylerlong** [comment]
We have rewritten the CSS part with mermaid 8.0.

Feel free to report a new issue if you can reproduce this issue with the new version.
