### ISSUE TITLE
Making HTTP API communication easier in sequenceDiagram

### ISSUE THREAD

**Issue by reggi** [knsv/mermaid#629]
I'd love to add features to Mermaid that make it easier to specify HTTP requests. 

An HTTP request can have a `method`, `body`, `headers`, `url`. It's kind of messy to put all this data in a `note`. 

![screen shot 2018-02-23 at 3 36 48 pm](https://user-images.githubusercontent.com/296798/36615783-7179c246-18af-11e8-860a-4b8422f88f9f.png)

I'd love a way to be able to create a legend at the bottom of the document, with pointers for specific arrows. Or some way to add a JSON object into the note and print out key value pairs in a nice way.

Any thoughts of how we could either make this better? Or ideas for a quick hack to make this more legible? Am I using these `sequenceDiagram` incorrectly?

**Comment by reggi** [comment]
It would also be nice if you could concat two diagrams and it render one diagram with both.

```
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by baverman** [comment]
@reggi sequence diagram doesn't need to be crowded with implementation details. However it will be nice to have ability to add a link to details (i.e. endpoint docs) in a message.
