### ISSUE TITLE
Graph TD line out of the picture (left side)

### ISSUE THREAD

**Issue by 0xbaadf00d** [knsv/mermaid#630]
They are an issue with the graph TD, picture is not draw on the left side

```
graph TD
            A-->B
            A-->C
            A-->Z
            A-->Y
            B-->Y
            Z-->Y
            Y-->A
```

![image](https://user-images.githubusercontent.com/1005086/36642093-76502756-1a3a-11e8-9f7b-589197c9f02e.png)

**Comment by tylerlong** [comment]
Confirmed. I can reproduce it.

**Comment by tylerlong** [comment]
Fixed. https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICAgICAgICAgIEEtLT5CXG4gICAgICAgICAgICBBLS0-Q1xuICAgICAgICAgICAgQS0tPlpcbiAgICAgICAgICAgIEEtLT5ZXG4gICAgICAgICAgICBCLS0-WVxuICAgICAgICAgICAgWi0tPllcbiAgICAgICAgICAgIFktLT5BIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0
