### ISSUE TITLE
Actor line cuts through other elements

### ISSUE THREAD

**Issue by pierrebonbon** [knsv/mermaid#633]
The actor line extents or cuts through other elements when fill is set to none. I wonder if there any way for the actor line to go behind or, even better, cut where the borders of other elements begin.

Here's a couple of example snapshots:

![screenshot_2](https://user-images.githubusercontent.com/11869768/36937791-9bf4fb8c-1f10-11e8-87aa-f6d126c48920.jpg)

![screenshot_1](https://user-images.githubusercontent.com/11869768/36937793-a94190ac-1f10-11e8-95bd-3366431aa7df.jpg)

![screenshot_4](https://user-images.githubusercontent.com/11869768/36937795-af38ec3a-1f10-11e8-8c31-0eb8c4f8dd55.jpg)

**Comment by tylerlong** [comment]
What is your environment? Are you running an old version of IE?

We have decided to drop IE support. If you can reproduce the issue with Microsoft Edge browser, we can take a look.

![image](https://user-images.githubusercontent.com/733544/37341464-7201bc22-26fc-11e8-831b-6dd5c4a14e03.png)
