### ISSUE TITLE
How to "auto ajust space" between two participants ?

### ISSUE THREAD

**Issue by Azef1** [knsv/mermaid#635]
Hi, 

I using "sequence diagram" function. I like SVG export file. 
Currently the problem is: If i write a long text, the text exceed participant limit.
See [URL or image below](https://mermaidjs.github.io/mermaid-live-editor/#/view/c2VxdWVuY2VEaWFncmFtCiAgICBBbGljZSAtPj4gQm9iOiBIZWxsbyBCb2IsIGhvdyBhcmUgeW91PwogICAgQm9iLS0-PkpvaG46IEhvdyBhYm91dCB5b3UgSm9obiB0ZXN0IHRlc3QgdGVzdCB0ZXN0IHRlc3QgdGVydCA_CiAgICBCb2ItLXggQWxpY2U6IEkgYW0gZ29vZCB0aGFua3MhCiAgICBCb2IteCBKb2huOiBJIGFtIGdvb2QgdGhhbmtzIQogICAgTm90ZSByaWdodCBvZiBKb2huOiBCb2IgdGhpbmtzIGEgbG9uZzxici8-bG9uZyB0aW1lLCBzbyBsb25nPGJyLz50aGF0IHRoZSB0ZXh0IGRvZXM8YnIvPm5vdCBmaXQgb24gYSByb3cuCgogICAgQm9iLS0-QWxpY2U6IENoZWNraW5nIHdpdGggSm9obi4uLgogICAgQWxpY2UtPkpvaG46IFllcy4uLiBKb2huLCBob3cgYXJlIHlvdT8)
![image](https://user-images.githubusercontent.com/15362041/37112547-0cb4854c-2243-11e8-84a0-420118f968b0.png)

I would like more spacing between participants (auto-ajust), like that (i using https://www.websequencediagrams.com/)
![image](https://user-images.githubusercontent.com/15362041/37112626-41a33bb8-2243-11e8-9f91-26f2e9127e88.png)

Do you know if it's possible to add this improvement ?

**Comment by tylerlong** [comment]
There is currently no way to auto adjust. But you can change the margin between actors:

```js
mermaid.initialize({ theme: 'forest', sequence: { actorMargin: 300 } });
```

![image](https://user-images.githubusercontent.com/733544/37341230-a0867fca-26fb-11e8-87a2-77af4bdf281b.png)

**Comment by harveyslash** [comment]
This issue can be somewhat mitigated if its possible to add newlines in the texts. Is there a reliable way to do so for sequence diagrams ?

**Comment by tylerlong** [comment]
I am unaware of a way to add line breaks to sequence diagram.

**Comment by rajasekaran2003** [comment]
Since there isn't a way to add line breaks to sequence diagram, it would help if there is auto adjust for the line width
