### ISSUE TITLE
The live editor cant show seq diagram with notes for 8.0.0-alpha.3

### ISSUE THREAD

**Issue by davojta** [knsv/mermaid#638]
see the issue in live - editor https://github.com/mermaidjs/mermaid-live-editor/issues/21

**Comment by davojta** [comment]
https://github.com/mermaidjs/mermaid-live-editor/issues/21

**Comment by tylerlong** [comment]
It has been fixed. Sample sequence diagram:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCkFsaWNlIC0-PiBCb2I6IEhlbGxvIEJvYiwgaG93IGFyZSB5b3U_CkJvYi0tPj5Kb2huOiBIb3cgYWJvdXQgeW91IEpvaG4_CkJvYi0teCBBbGljZTogSSBhbSBnb29kIHRoYW5rcyEKQm9iLXggSm9objogSSBhbSBnb29kIHRoYW5rcyEKTm90ZSByaWdodCBvZiBKb2huOiBCb2IgdGhpbmtzIGEgbG9uZzxici8-bG9uZyB0aW1lLCBzbyBsb25nPGJyLz50aGF0IHRoZSB0ZXh0IGRvZXM8YnIvPm5vdCBmaXQgb24gYSByb3cuCkJvYi0tPkFsaWNlOiBDaGVja2luZyB3aXRoIEpvaG4uLi4KQWxpY2UtPkpvaG46IFllcy4uLiBKb2huLCBob3cgYXJlIHlvdT8
