### ISSUE TITLE
How to pass styling 

### ISSUE THREAD

**Issue by harveyslash** [knsv/mermaid#639]
I am using mermaid api like this :

```
 mermaid.mermaidAPI.initialize({
                                theme: 'forest',
                                startOnLoad:true,
                                sequence: {
                                        diagramMarginX:5,
                                        diagramMarginY:1,
                                },
                        });
```
then i call render : 
```mermaid.mermaidAPI.render('__graph'+i,graphDefinition,cb)```

The theme correctly changes from default to green , but the styles passed in sequence dont seem to have any effect. 

I would like to make the actor boxes in sequence diagram smaller in comparison to the text.

**Comment by tylerlong** [comment]
> I would like to make the actor boxes in sequence diagram smaller in comparison to the text.

```js
mermaid.initialize({
      sequence: {
        width: 100,
        height: 50
      }
});
```

Actually those are not controlled by CSS. It's controlled by D3.

**Comment by harveyslash** [comment]
```
mermaid.mermaidAPI.initialize({
                                theme: 'forest',                                                                                                        startOnLoad:true,
                                sequence: {                                                                                                                     width:50,
                                },
                        });
```

Had no effect on the diagram. 
I am using this on a static page , with this version: 
https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

**Comment by tylerlong** [comment]
Please test the latest version.

For that version you probably need to replace `sequence:` with `sequenceDiagram:`
