### ISSUE TITLE
How to get started with this project ?

### ISSUE THREAD

**Issue by bismoy2013** [knsv/mermaid#64]
Please provide the steps on how to execute this project after doing : bower install .

**Comment by Grahack** [comment]
Also you can just open `test/web.html` in a browser and hack it in a text editor.

**Comment by knsv** [comment]
@bismoy2013: Was your question answered here? If not we should give it another go.

**Comment by knsv** [comment]
I am closing issues and see this one as closed. Let me know if you feel differently!

**Comment by bismoy2013** [comment]
No it's okay, it was solved already. Sorry for delaying my response to this thread :)
