### ISSUE TITLE
Is it possible to use custom CSS with the Gantt chart?

### ISSUE THREAD

**Issue by mehertz** [knsv/mermaid#643]
Hi,

I can't work out how to use custom CSS with the Gantt chart. Let's say I want to define a CSS class for a block type just like "done", or "active", how would I do that? Simply creating one ("cancelled") and referencing it by name (":cancelled, ...") doesn't seem to work.

Any ideas?

Thanks

**Comment by tylerlong** [comment]
You can find the answer here: https://mermaidjs.github.io/faq.html

**Comment by mehertz** [comment]
But I want to *add* a class. Looking at the Gantt chart, the classes for the boxes are hard coded:

https://github.com/knsv/mermaid/blob/master/src/diagrams/gantt/ganttRenderer.js#L151

If they are hard coded, how is this possible?

**Comment by gerardbosch** [comment]
Hi @tylerlong , how do you make to override a CSS class for a diagram? I've tried this to decrease font size in notes, but does not seem to take effect. I'm using the Atom plugin to render the diagram:

    <style>
      .noteText {
        fill:black;
        stroke:none;
        font-family: 'trebuchet ms', verdana, arial;
        font-size:8px;
      }
    </style>
    
    ```mermaid
    sequenceDiagram
    ...
    ```

Thanks!

**Comment by asifm** [comment]
> You can find the answer here: https://mermaidjs.github.io/faq.html

The faq link has changed to this: https://mermaid-js.github.io/mermaid/#/faq
