### ISSUE TITLE
"Cannot activate" in sequenceDiagram

### ISSUE THREAD

**Issue by chenwq3** [knsv/mermaid#647]
Thank for your software that help me a lot!

Some times ago, I noticed that I can't "activate" an object, it show "transparent wide vertical line". 

![cannot activate](https://user-images.githubusercontent.com/25943138/38653778-e56cea02-3e3e-11e8-8278-7f54dd39a452.png)

**Comment by chenwq3** [comment]
I found that I need to use "deactivate" to make it pair to draw that "activate status vertical line"...

**Comment by djsipe** [comment]
> I found that I need to use "deactivate" to make it pair to draw that "activate status vertical line"...

Thanks for following up with the solution.  Ran into this same issue.
