### ISSUE TITLE
Fixed width of nodes

### ISSUE THREAD

**Issue by Apachez-** [knsv/mermaid#653]
I failed to figure out how to define a fixed width for nodes being used in a flowchart - is this possible and if not can this feature be added?

That is either one specify a specific width like 300px (or some other metric) or have an option that mermaid will autoadjust all widths to the widest node within the graph?

**Comment by bhrutledge** [comment]
[`<rect>` elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect) have a `width` attribute, but [apparently](https://stackoverflow.com/questions/22088987/how-to-change-the-width-of-an-svg-rect-with-css) it can't be styled via CSS. This implies to me that there'd have to be an additional bit of syntax or configuration.

**Comment by ThePenguin1140** [comment]
We can take a look at this as part of #199
