### ISSUE TITLE
Force direction within a subgraph

### ISSUE THREAD

**Issue by Apachez-** [knsv/mermaid#654]
Today one can define the direction of rendering in the global graph definition like so (top to bottom in the example below):

graph TB
A --- B
A --- C

This would place A at top with B and C below.

However when one create a subgraph there doesnt seem to be a way to force a direction within the subgraph.

For example like so:

graph TB
A --- B
A --- C
subgraph LR somename
D --- E
E --- F
F --- G
end
C --- E

As a feature request it would be nice if direction within a subgraph could be specified.

**Comment by creeperyang** [comment]
A nice and useful feature. And any progress？

**Comment by benelgiac** [comment]
Definitely needed, I started looking at this 5 minutes after starting using Mermaid. Let us know if you plan to do introduce it.

**Comment by yk-liu** [comment]
Definitely needed

**Comment by ztxc** [comment]
A nice and useful feature. And any progress？

**Comment by Dunning-Kruger** [comment]
Duplicate of #561.

**Comment by jucor** [comment]
Currently tracked at #1265

**Comment by koly23** [comment]
Definitely needed
