### ISSUE TITLE
mermaid.render() returns incorrect SVG, possible d3 error

### ISSUE THREAD

**Issue by blizzardengle** [knsv/mermaid#665]
**Background**
I am using the latest mermaid (8.0.0-rc.8) packed with Webpack for the web. My project dynamically adds diagrams to the page that need to be parsed when they are created. If I call `mermaid.init()` everything works 100% as expected; I just have to keep calling `mermaid.init()` which I know isn't right and doesn't allow me to catch errors.

**What I Was Trying To Do**
What I would like to do is fail gracefully and display a message in place of any diagram that fails parsing. To do this I switched to using `mermaid.render()` and was planning to catch errors in my callback function.

**The Bug / Error**
`mermaid.render()` runs as it should and passes the SVG to my callback however 2 errors/ bugs happen:
 
1. The render passes but only shows the diagram shapes, no text ~or connections~ of any kind.
2. If an error is triggered mermaid crashes and all unprocessed diagrams are left unprocessed.

**Change Of Plans, Another Bug / Error**
I then switched to using `mermaid.parse()` which would theoretically solve my problem because I could either place the SVG in the document if it passed or catch the error by overwriting `mermaid.parseError` with my own function; I could also run the `mermaid.parse()` in a try-catch but either way the following errors happen:

1. Again, partial rendering of a correct diagram caused I believe by the following:
2. An error is thrown every time. The error simply says: NO INTERSECTION FOUND, RETURN NODE CENTER. I belive this is being caused by dagre-d3.
3. `parseError` is never called, I have no way of catching any errors.
4. If an error is triggered mermaid crashes and all unprocessed diagrams are left unprocessed.

**Comment by brookhong** [comment]
> parseError is never called, I have no way of catching any errors.

Confirmed this.
