### ISSUE TITLE
Label's css conflict with boostrap's .label

### ISSUE THREAD

**Issue by RexKang** [knsv/mermaid#67]
There is a .label in bootstrap 3, when using bootstrap and mermaid together, the color of mermaid's .label will changed to white, like http://jsbin.com/hegoqelogo/1/.

So I suggest change .label to .mermaid-label to avoid the conflict.

**Comment by fanix** [comment]
add ".mermaid .label {}" to your css file will be ok.

**Comment by knsv** [comment]
Thanks for the suggestions @fanix. As of release 0.4.0 a mermaid.css stylesheet is included in the distribution, this stylesheet plays nice with bootstrap. Closing this issue, reopen if this still causes problems.
