### ISSUE TITLE
mermaidAPI latest with link and click

### ISSUE THREAD

**Issue by virendavelogicode** [knsv/mermaid#676]
How i can get mermaidAPI i see in recent version dist didnt produce mermaidapi.js and how i can use link i try in my way with 6.0.0 but click not working

**Comment by virendavelogicode** [comment]
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Flowchart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/mermaid@6.0.0/dist/mermaid.css" />
    <script src="https://unpkg.com/mermaid@6.0.0/dist/mermaidAPI.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

    <script>
        mermaidAPI.initialize({
            startOnLoad: true,
            cloneCssStyles: false,
            flowchart: {
                useMaxWidth: true,
                htmlLabels: true
            }
        });

        function myAction(id) {
            alert("click fired");
        }

        $(function () {
            var graphDefinition =
                'graph TB\nProposal-->Contract\nContract-->Planning\nPlanning-->Design\nDesign-->Build\nBuild-->Verification\nVerification-->Delivery\nDelivery-->Support\nclick Design myAction\n';
            var callback = function (code, bindEvents) {
                console.log(bindEvents);
                $("#div-id1").html(code);
                bindEvents();
            }
            mermaidAPI.render('id1', graphDefinition, callback);
        });
    </script>
</head>

<body>
    
    <div class="title">Process WorkFlow (static test)</div>
    <div id="div-id1">
    </div>

</body>

</html>

**Comment by Didjeeh** [comment]
Use a more recent version of mermaid. Works perfectly with https://unpkg.com/mermaid@7.0.10/dist/mermaid.min.js

Personally I do not use bindEvents. I / my users do not want to type a  *click \<Id> \<callback>* for each node.
If you like you can always do some post processing (dirty hack) like so. The timeout is to make sure the graph div and childs exist.

     setTimeout(function () {

....

     $("#div-id1 .nodes .node").click(function () {
            var nodeHelp = jsonHelp[$(this).attr("id")];
            var help = "<h2>" + $(this)[0].textContent + "</h2>";
            if (nodeHelp) {
                nodeHelp = nodeHelp.replace(/[\n]/g, "<br \\>");
                help += "<div>" + nodeHelp + "</div>";
            }
            $("#some-other-div").html(help);
        });

...
        }, 500);
