### ISSUE TITLE
How can I escape - character in sequenceDiagram?

### ISSUE THREAD

**Issue by harobed** [knsv/mermaid#679]
How can I escape `-` in `foo-bar` here:

```
sequenceDiagram
foo-bar->foo: foo
```

**Comment by gvlx** [comment]
It seems there are no escape characters in TEXT elements on this graph type.

Maybe the text processing function from the flowchart diagram could be reused here?

**Comment by zeerd** [comment]
use #8211; instead

**Comment by masch712** [comment]
@zeerd  the UTF-8 character codes work in `participant` declarations, but they don't appear to work in the actual sequence part of the diagram (sorry if my jargon is off here).
Example:
![image](https://user-images.githubusercontent.com/17676379/127323050-35bde9d5-3f8a-42e1-b01e-968ff1470956.png)
![image](https://user-images.githubusercontent.com/17676379/127323116-7ad3f968-1169-459f-8478-c74d601b6ae3.png)

the mermaid code:
```
sequenceDiagram
    participant leftOfColon#58;rightOfColon
    participant leftOfColon2#58;rightOfColon2
    leftOfColon#58;rightOfColon->>leftOfColon2#58;rightOfColon2: hello
```

**Comment by zeerd** [comment]
use 'as' might help.

```
sequenceDiagram
    participant a as leftOfColon#58;rightOfColon
    participant b as leftOfColon2#58;rightOfColon2
    a->>b: hello
```
