### ISSUE TITLE
Mix horizontal and vertical graph

### ISSUE THREAD

**Issue by raymestalez** [knsv/mermaid#68]
Hi!
I am tying to make a graph like this:
![linreg-graph](https://cloud.githubusercontent.com/assets/4761235/5515236/475e85d6-8830-11e4-9e36-0edd1cc486b1.png)
Is it possible?
And if not - is there some alternative way to do that?

P.S.
Thank you very much for a fantastic project!!

**Comment by andrewfhart** [comment]
I am new to this project, and so haven't looked at the code in detail yet, but I was interested in doing something similar, and wondered if it might be possible to extend layout support (TD,LR, etc.) to subgraphs. If that could be done, then the above could be represented as:

```
graph TD
  ts(Training Set) --> lr(Learning Algorithm)
  subgraph hypothesis LR
  sh(Size Of House) --> h(Hypothesis) --> ep(Estimated Price)
  end
  lr --> h
```

The "LR" in the subgraph defininition would specify a horizontal left-to-right layout for subgraph elements, creating the inverted T structure desired above. Is this feasible to implement in the current architecture?

**Comment by knsv** [comment]
Hello Andrew!  

Subgraphs are actually supported with very similar syntax to the one you proposed.

The only difference is that in the current implementation the subgraphs inherit the layout from the main chart.

Chains are however not supported:
h(Size Of House) --> h(Hypothesis) --> ep(Estimated Price)

would take two rows:

h(Size Of House) --> h(Hypothesis)  
h(Hypothesis) --> ep(Estimated Price)


so correct syntax for the subgraph would be:
subgraph hypothesis
sh(Size Of House) --> h(Hypothesis)
h(Hypothesis) --> ep(Estimated Price)
end

I hope this help!
/Knut

**Comment by knsv** [comment]
I am going through issues and see this one as closed. Let me know if you feel differently.

**Comment by ranjitc** [comment]
hi @knsv fantastic project! (sorry just had to say that) ... i believe subgraphs still cannot have their own topology and inherit it from the parent. is this feature planned to be added? will add great flexibility to mermaid.
