### ISSUE TITLE
sequenceDiagram width too small

### ISSUE THREAD

**Issue by harobed** [knsv/mermaid#680]
sequenceDiagram width too small [Link view](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgZm9vYmFyMS0-PmZvb2JhcjI6IE15TG9uZ01ldGhvZChwYXJhbTE9XCJmb29iYXJcIiwgcGFyYW0yPVwiZm9vYmFyXCIsIHBhcmFtMz1cImZvb2JhclwiLCBwYXJhbTQ9XCJmb29iYXJcIilcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19):

```
sequenceDiagram
    foobar1->>foobar2: MyLongMethod(param1="foobar", param2="foobar", param3="foobar", param4="foobar")
```

result:

<img width="539" alt="capture d ecran 2018-06-29 a 13 27 11" src="https://user-images.githubusercontent.com/230143/42090070-287af1a6-7ba0-11e8-9ce2-ac95c81dc71b.png">

How can I fix that?

**Comment by jjeejj** [comment]
Same problem， How to solve it？
