### ISSUE TITLE
Tooltip link in Flowchart docs not working

### ISSUE THREAD

**Issue by simondorfman** [knsv/mermaid#682]
Given I'm on this page:
https://mermaidjs.github.io/flowchart.html#interaction
...and I've scrolled down to the Interaction section,
When I click on the "A" box in the example diagram,
Then I expect to see some sort of tooltip text appear, but I don't see any.

Looks like something isn't working to me. Or perhaps more javascript code is required to make some tooltip text appear? Or maybe it used to work and was accidentally broken is a prior release?

Thanks for any help.

Screenshot:
![tooltip](https://user-images.githubusercontent.com/106923/42407375-bdf24690-8180-11e8-970b-cf476616c9b0.png)

**Comment by larryq** [comment]
I'm having the same issue.  The message I see in my console is:

Uncaught TypeError: window[e] is not a function
    at SVGGElement.<anonymous> (lodash.js:2873)
    at SVGGElement.<anonymous> (index.js:355)

That's happened on several different flowcharts I've tried.  Here's an example of one that demonstrates the problem:
https://bit.ly/2JqlVep

**Comment by tarnelope** [comment]
Based on docs and testing, as of right now, one has to define the `callback` function on the page where the graph is displaying. You can name the function whatever you want.

```
   click A functionName "Text that currently doesn't do anything"

   # Somewhere in the scripts of your page
   var functionName = function(node_id) {
       # what ever you want here
       alert('For example you can display an alert!');
   }
```

This doesn't seem ideal so I'll dig into it and see if the current behavior is the result of a bug and if not, I'll see what I can do to make the callback feature more intuitive.

**Comment by larryq** [comment]
Thanks @tarnelope, it'd be a nice to have for sure if the tooltips were working again.

**Comment by tarnelope** [comment]
@larryq Yea! For now, they seem to work but require additional styling steps which I documented here: https://github.com/mermaidjs/mermaid-gitbook/pull/25

**Comment by RoyiAvital** [comment]
Is there a way to have *ToolTip* when mouse is hovering without any action when clicking?

**Comment by sb2059** [comment]
I've found that using the unminified version located [here ](https://cdnjs.com/libraries/mermaid) results in expected tooltips and clicking behavior.

**Comment by GDFaber** [comment]
Possibly related to #901?
