### ISSUE TITLE
How to achieve Multi-line text in a Gantt chart boc

### ISSUE THREAD

**Issue by tsrinivas2406** [knsv/mermaid#683]
I wish to have multi-line text in the gantt chart to show the name and mobile number in a new line : 
I have tried <br> , </br> , /n but could wasn't able to achieve it. Any help on this will be greatly appreciated. 

Folllowing is my code : 

`gantt
	dateFormat  YYYY-MM-DD HH:mm
	title Support Schedule
	        
section APAC
		. : E1 , 2018-07-11,1m
      	John <br> Mobile-9963792226 : E1, 2018-07-11 08:00, 9h
       
section INDIA
	Robert : done,E2, 2018-07-11 11:00,7h
	Mike : active,E3, 2018-07-11 14:00,9h
	Srinivas : crit,E4, 2018-07-11 11:00,9h
	
section EURO
	Zoran: E5, 2018-07-11 13:00,9h`

![image](https://user-images.githubusercontent.com/24503203/42417135-e4d441cc-829e-11e8-9f81-f010876587af.png)

**Comment by gvlx** [comment]
Even suggestion https://github.com/knsv/mermaid/issues/199#issuecomment-135757612 does not work on this type of chart. :(
