### ISSUE TITLE
Adding axisFormat to docs?

### ISSUE THREAD

**Issue by Jmuccigr** [knsv/mermaid#686]
Any objection to adding `axisFormat` to the example in the docs? I had to search to figure out how to use the scale information

**Comment by imma90** [comment]
This pull request is about axisFormat in the Gantt: [(https://github.com/mermaidjs/mermaid-gitbook/pull/19)]. In other words: pull request #19 in mermaidjs/mermaid-gitbook

Or is this axisFormat also relevant for other types of diagrams, so that it should be described elsewhere?
