### ISSUE TITLE
Support Chinese punctuation

### ISSUE THREAD

**Issue by yearliny** [knsv/mermaid#687]
First of all, thank you for your excellent work,and forgive me for my bad English.

I can't generate a graph when I type Chinese punctuation,such as 、：，。

Do you have plans to fix this problem?

**Comment by elliemhwu** [comment]
For future ones who also needs this.  I found it works when you type your mermaid code like: `A("blah blah...，blah blah。")`.  It works for me to show Chinese punctuation properly!
