### ISSUE TITLE
SquenceDiagram does not support actors with a dash

### ISSUE THREAD

**Issue by kreuzerk** [knsv/mermaid#691]
I try to create a sequencediagram with an actor that includes a dash. It does not work because the dash is also included in the line definition. I just wanted to ask if it is already possible to add actors with dasehs or if we could add this feature.

I tried the following diagram on the mermaid online editor:
````
sequenceDiagram
foo-test->>+bar:test
````

Output
````
Parse error on line 2:
sequenceDiagramfoo-test->>+bar:test
------------------^
Expecting 'NL', 'AS', ',', 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', 'TXT', got '-'

````

**Comment by zeerd** [comment]
maybe you want:

>sequenceDiagram
>foo#8211;test->>+bar:test
