### ISSUE TITLE
Multiple notes should fit in a single row.

### ISSUE THREAD

**Issue by eddiewebb** [knsv/mermaid#698]
This is specifically used for the "over" notes where you might introduce actors.

Currently each note steps down another row leaving lots of unusued space.

![screen shot 2018-07-20 at 8 57 13 am](https://user-images.githubusercontent.com/5262154/43003579-f0ad97a4-8bfa-11e8-9969-adee035411ac.png)

**Comment by samuelfvlcastro** [comment]
Have you managed to fix this? it's very annoying 😞
