### ISSUE TITLE
Graph edges appear to render outside of the canvas

### ISSUE THREAD

**Issue by it0a** [knsv/mermaid#70]
[jsbin here](http://jsbin.com/puduyobeya/1/edit?html,js,output)
The following graph appears to render the A-->D edge outside of the canvas:
```
graph TD;
    A-->B;
    A-->C;
    A-->D;
    B-->D;
```

Rearranging the order to the following will render correctly:
```
graph TD;
    B-->D;
    A-->B;
    A-->C;
    A-->D;
```

**Comment by knsv** [comment]
Closing after release
