### ISSUE TITLE
Here's a patch to add unique IDs to flowchart edges (just one line of code)

### ISSUE THREAD

**Issue by crankycyclops** [knsv/mermaid#701]
After some digging into the mermaid source, I've discovered that it would be trivial to add IDs to the flowchart edges, which would help not just myself, but others as well (see: #583)

Here's my proposed patch: [https://gist.github.com/crankycyclops/ecfe70d6e6546db1345ebe77596f0e39](https://gist.github.com/crankycyclops/ecfe70d6e6546db1345ebe77596f0e39)

**Comment by crankycyclops** [comment]
@eduo, yeah. The nodes in the graph already had ids (identical to the names given in the flowchart definition.) Some people (including myself) wanted to be able to attach click events to the edges as well as the nodes, but doing so doesn't really accomplish much if you have no way to uniquely identify them. So this small patch adds an id to each edge which is a composite of both nodes' ids.

**Comment by eduo** [comment]
Ah. You're right. I was using the dist from the CDN and I wasn't seeing this. I even opened a ticket for it. Thanks!

**Comment by samevans** [comment]
Attempting to bump this so this will get added

**Comment by Heiko-san** [comment]
The IDs from that patch are NOT UNIQUE, see my comment at https://github.com/knsv/mermaid/issues/583
