### ISSUE TITLE
css IDs for elements

### ISSUE THREAD

**Issue by eduo** [knsv/mermaid#708]
Hi.

I may be missing something obvious but I can't find a way to add an ID to all element in a flowchart.

I want to add some interactivity and to be able to call individual nodes and to detect their click events, but I need a way to identify what's being clicked.

**Comment by ChiragSSinghal** [comment]
The css IDs of individual elements are saved from the object name that you use to create the elements.
E.g. Using
`A-->B`
or
`A[Start]-->B[Process 1]`
will assign the objects with css ID 'A' and 'B'. you can then use the JS or jQuery functions to access the individual functions.
`document.querySelector("#A").addEventListener("click", fun);`

I hope this helps you.
