### ISSUE TITLE
Re-render graph

### ISSUE THREAD

**Issue by mstrop** [knsv/mermaid#709]
I need to change graph definition based on a user action. My initial sequence follows the documentation:

```
        <div id="schema_cont" class="mermaid">
            graph TD;
            entry((Entry));
            click entry nodeClick;
        </div>
....

        mermaid.initialize({ startOnLoad: true });
```
It works fine. Later on I need to change the graph ( add / remove node etc. ). I tried to implement an example form the documentation using render function:

```
    var cb = function (svgGraph) {
        $("#schema_cont").html(svgGraph);
    }

    $("#schema_cont").html("");

    mermaid.render("id1", "graph TD;\nentry((New entry));\nclick entry nodeClick;", cb);

```

Doing it this way the graph is reloaded with the new definition, but the click callback is never called. Am I doing anything wrong?

**Comment by sudhakar-sekar** [comment]
Hi @mstrop,

I am also trying same, have you found any solutions for the rendering issue based on user action?
If you found the solution and resolved, will you please tell me that.

Thanks,
Sudhakar.

**Comment by GDFaber** [comment]
I think this is what you are looking for:
https://github.com/knsv/mermaid/issues/311#issuecomment-332557344

I am using this solution with mermaid 8.2.1 and it still does the trick.
