### ISSUE TITLE
opt/alt/loop with long describing text

### ISSUE THREAD

**Issue by zeerd** [knsv/mermaid#710]
At some early version , the opt/alt/loop and the describing text were putting into two lines, so a long describing text could be shown well. 

But at the current version, the two were putting into a same line, and if the describing text is too long , it will be mixed with alt/opt/loop.

Is there any way to avoid this situation? 

```mermaid
sequenceDiagram
A ->> B : abc
opt there is a very very long describing text
A ->> B : mixd
end
```

**Comment by abnerlee** [comment]
And also when node contains long text:
```
sequenceDiagram
Aaaaaaaaaaaaaaaaaaaaaaa ->> B : abc
opt 
A ->> B : mixd
end
```
