### ISSUE TITLE
Support of interactions (click) for gantt charts

### ISSUE THREAD

**Issue by felixboehm** [knsv/mermaid#715]
to be able to link to the details of a task.

Syntax for flowchart can be also used for gantt, https://mermaidjs.github.io/flowchart.html#interaction

This would allow to render gantt charts based on backend data of other tools (github issues?) and link to the detailed infos.

**Comment by fadeevda** [comment]
Indeed, there is not enough interactive in the gantt chart.

**Comment by abzicht** [comment]
Hello there, check out my [pull request #804 (Clickable Gantt Tasks)](/knsv/mermaid/pull/804)!
It adds exactly that support of interactions for gantt charts you requested. As the request is not yet accepted, you can pull it from my [fork](/abzicht/mermaid).
