### ISSUE TITLE
Subgraph title characters are too restricted

### ISSUE THREAD

**Issue by uuf6429** [knsv/mermaid#719]
Things I tried* with the subgraph title that didn't work:
- `subgraph new<br>line` - prints `subgraph new<br/>line`
- `subgraph some (text)` - syntax error
- `subgraph "some (text)"` - syntax error
- `subgraph some &#40;text&#41;` - syntax error
- `subgraph "some &#40;text&#41;"` - syntax error

\* mermaid live editor 8.0.0-rc.8

I also couldn't find much documentation about subgraphs other than the few examples.

**Comment by GDFaber** [comment]
The examples with quotes work now (try 
`subgraph "some (text)"`
`subgraph "some #40;text#41;"` (I removed the ampersands as they are not needed in mermaid's DSL and will be shown as characters in the label)

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbnN1YmdyYXBoIFwic29tZSAjNDA7dGV4dCM0MTtcIlxuQS0tPkNcbmVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19
