### ISSUE TITLE
change default node style

### ISSUE THREAD

**Issue by eadmaster** [knsv/mermaid#724]
is it possible to change the default node style in graphs with a single line (without using classes)?
e.g.:
```
	graph TD
		A --> B
		B --> C  
		A --> C
                nodeStyle default stroke-width:2px,fill:none,stroke:red;
```

**Comment by bhrutledge** [comment]
It looks like this can be accomplished via the `node` and `edgePath` classes that are already applied:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;

classDef node stroke-width:2px,fill:none,stroke:red
classDef edgePath stroke-width:2px,stroke-dasharray: 5, 5
```
<img width="154" alt="Screen Shot 2019-07-06 at 7 03 27 AM" src="https://user-images.githubusercontent.com/1326704/60755331-339b6200-9fbc-11e9-908e-bbeda114a4f7.png">

See also #684.
