### ISSUE TITLE
Bug: <br> being rendered as text in node

### ISSUE THREAD

**Issue by sudodoki** [knsv/mermaid#73]
Using sample code from readme
```
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
```
I get following diagram 
![sample2 txt](https://cloud.githubusercontent.com/assets/1506905/5562762/e29d6c3a-8e05-11e4-8703-cab18dcc67a0.png)
As you can see, `<br/>` is being part of text content in the node.
`phantomjs -v` outputs `1.9.8`
`mermaid --version` outputs `0.3.0`

**Comment by knsv** [comment]
Released in 0.3.1
