### ISSUE TITLE
Click keyword does not fire my callback (Vue.Js) 

### ISSUE THREAD

**Issue by seansabour** [knsv/mermaid#731]
I'm hitting an issue where mermaid is not firing my callback 
```
<template>
  <div class="panel-body points demo flow_chart mermaid" id="points" >
    graph LR
      id1((Start))
      click id1 test "wooo"
      id1-->id2
  </div>
</template>

<script>

  import mermaid from "mermaid"

  export default {
    name: 'Workflows',
    methods: {
      test() {
        alert("I was clicked")
      }
    },
    mounted() {
      mermaid.initialize({startOnLoad:true});
    }
  }
</script>

<style>

</style>
```
I've also tried to change test to this.test with no luck.

**Comment by anasameur** [comment]
test callback have to be declared on the windows object something like this 
<script>

  import mermaid from "mermaid"

  export default {
    name: 'Workflows',
    methods: {
    },
    mounted() {
      mermaid.initialize({startOnLoad:true});
      windows.test = () => {
              alert("I was clicked")
        }
    }
  }
</script>
