### ISSUE TITLE
Yarn build does not add mermaid.min.css to dist

### ISSUE THREAD

**Issue by finseth** [knsv/mermaid#732]
The documentation on web usage is unclear.
https://mermaidjs.github.io/usage.html

The "simple full example" uses mermaid.min.css, but cloning the repository and running yarn build/release does not produce the minified css. As far as I can tell from the documentation the css is required. If that is the case then it would be logical to have yarn build/release produce the minified css and have it included in dist/ together with the minified js.

**Comment by laurent22** [comment]
Did you ever found out how to get or build mermaid.min.css? It puzzles me that this apparently essential file is not built, and not present anywhere in the repo or CDNs. I'm assuming I'm missing something obvious but don't know what.
