### ISSUE TITLE
Use mermaid with angular 5

### ISSUE THREAD

**Issue by Xen3r0** [knsv/mermaid#734]
Hi,

I have a problem with mermaid in Angular5, i didn't see the graph : https://stackblitz.com/edit/angular-ddccjh

I have try with mermaid.init and mermaidAPI.render directly, but it's not working.

Any idea ?

Thanks so much.

**Comment by BowWow-Studio** [comment]
Please include the snippet of your code

**Comment by juaalta** [comment]
The problem is in the `styles.less` file.
I have commented the line `@import '~mermaid/src/less/dark/mermaid';` and it has worked for me.
From the environment I told him to update the dependencies.
