### ISSUE TITLE
Is there any API to render a template into class?

### ISSUE THREAD

**Issue by ghk829** [knsv/mermaid#735]
I,m using mermaid API to render a template from markdown to svg.
But, the documents of gitbook only has an example, the result is "id", not "class".
So, is there any class based API for rendering?

**Comment by brunobarretofreitas** [comment]
All you need to do is create a div with a class named "mermaid", the mermaidAPI searches the whole HTML document for this.

`` <div class="mermaid"></div> ``

And then, You'll need to insert the mermaid markdown code in the div before calling the mermaid API.

`` 
var element = document.querySelector(".mermaid");

element.nativeElement.innerHTML = 'graph TB\na-->b';
``

And then, you call the initializing function of mermaid

`` 
var element = document.querySelector(".mermaid");

element.nativeElement.innerHTML = 'graph TB\na-->b';

mermaid.init();
``

Doing that, mermaid will insert the svg code inside the div and will place an attribute in the div ``data-processed=true``. If you want something dynamic, you need to remove the data-processed attribute from the div element and the redo the whole process.
