### ISSUE TITLE
mermaid theme have a error

### ISSUE THREAD

**Issue by daidai21** [knsv/mermaid#736]
```mermaid 
graph TB;
5 --> 6;
5 --> 8;
```

color is block.
It is unsightly.

**Comment by louagej** [comment]
Indeed, I have the same problem:
```mermaid
graph LR
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
```

![image](https://user-images.githubusercontent.com/7229592/46146826-0e770780-c264-11e8-801f-e48fb17a8d48.png)

**Comment by k1ng440** [comment]
same problem

**Comment by k1ng440** [comment]
https://codesandbox.io/s/zl5z7o2ml4

**Comment by daidai21** [comment]
This is user configuration problem.

This is my settings of vscode .
```
    "markdown-preview-enhanced.mermaidTheme": "forest",
```

**Comment by louagej** [comment]
I used Markdown Enhanced Preview in VSCode.
I solved i by going to the user settings and changed the 'mermaidTheme' back too default.

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/149

**Comment by daidai21** [comment]
> I used Markdown Enhanced Preview in VSCode.
> I solved i by going to the user settings and changed the 'mermaidTheme' back too default.
> 
> [shd101wyy/vscode-markdown-preview-enhanced#149](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/149)

nice
