### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by AlbanMinassian** [knsv/mermaid#737]
``end`` node throw an error !

try [https://mermaidjs.github.io/mermaid-live-editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5zdGFydC0tPmVuZDtcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgpncmFwaCBURDtzdGFydC0tPmVuZDsKLS0tLS0tLS0tLS0tLS0tLS1eCkV4cGVjdGluZyAnRElSJywgJ0RPV04nLCAnTUlOVVMnLCAnVEVTVFNUUicsICdQSVBFJywgJ05VTScsICdDT01NQScsICdBTFBIQScsICdDT0xPTicsICdCUktUJywgJ0RPVCcsICdQVU5DVFVBVElPTicsICdVTklDT0RFX1RFWFQnLCAnUExVUycsICdFUVVBTFMnLCAnTVVMVCcsIGdvdCAnZW5kJw)
```mermaid
graph TD;
start-->end;
```

if i rename "end" to ``_end`` same error
if i rename "end" to ``__end`` same error
if i rename "end" to ``end_`` , ok (curious !)
if i rename "end" to ``edn`` , ok

Thank
ami44

**Comment by GDFaber** [comment]
`end` is a reserved word for defining subgraphs, like so:

`graph TD`
`subgraph g`
`A-->B`
`end`

If you want "end" to be the node's title, you can do that by specifying the label text:

`graph TD`
`start-->A["end"]`
