### ISSUE TITLE
Gantt diagram with days of the week instead of specific dates

### ISSUE THREAD

**Issue by simondorfman** [knsv/mermaid#740]
I want to create a Gantt diagram to illustrate a bi-weekly process. So instead of specific dates showing along the bottom. I want to show generic days of the week (Sunday - Saturday) for two weeks. Is it possible to do that right now?

Looking at the docs here:
https://mermaidjs.github.io/gantt.html
...and it doesn't look like it.

**Comment by chuyuanlinzi** [comment]
I have the same question.

**Comment by PhilippeVay** [comment]
You can use the [axisFormat](https://github.com/knsv/mermaid/issues/269#issuecomment-373229136) keyword and the many parameter values are those of [scale](https://mermaidjs.github.io/gantt.html#scale) in documentation.

**Comment by tim-elmer** [comment]
This issue does not seem to have been answered. While [documentation of the axis output format](https://mermaid.js.org/syntax/gantt.html#output-date-format-on-the-axis) makes it fairly clear how to only output weekdays and week numbers (e.g. `%A %W` -> `Tuesday 2`), it isn't clear how to input data in this level of detail. Reading the documentation, especially for [Day.js formatting](https://day.js.org/docs/en/parse/string-format/), I am skeptical that this is even possible.

If I understand @simondorfman's question correctly, they want to be able to describe two hypothetical weeks and events on days within those weeks. As Day.js appears to not support abstract dates (dates missing parameters are assumed to be relative to "now"; e.g. the first of April is interpreted as the first of April, this year), I don't think Mermaid.js is capable of handling schedules in this fashion.

As a workaround, one could pick a specific year/month (September 2024 lines up conveniently, with the 1st being a Sunday) and use dates within it (e.g. 09/02/24 is Monday), but this isn't ideal - especially from a code legibility standpoint.
