### ISSUE TITLE
gantt: sections can't have a colon

### ISSUE THREAD

**Issue by rhz** [knsv/mermaid#742]
Something like
```
gantt
  ...
  section First goal: Build a greenhouse
  ...
```
produces the following error when rendered using [mermaid.cli](https://github.com/mermaidjs/mermaid.cli)
```
(node:23207) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 5:
...  section First goal: Build a greenhouse
-----------------------^
Expecting 'EOF', 'SPACE', 'NL', 'dateFormat', 'axisFormat', 'title', 'section', 'taskTxt', got 'taskData'
```

**Comment by mikeblume** [comment]
Try using the HTML encoded character without the ampersand; e.g., `#58;` or `#colon;`

**Comment by rhz** [comment]
Thanks for the suggestion @mikeblume! It works!

I've been using my own modified copy of the code as described in #743, so I don't know if it works on the last version from this repo. I'll nevertheless close the issue and if anyone still has the problem we can re-open it.
