### ISSUE TITLE
Rendering argument maps

### ISSUE THREAD

**Issue by dsanson** [knsv/mermaid#747]
I'm interested in rendering argument maps using mermaid. The key feature that they require, and that does not seem to be possible using the existing diagram types, are clusters of nodes grouped together, with a single edge attaching them to another node. These are used to represent distinct premises that together constitute a single reason in support of, or against, a claim, as in this example, generated using [Mindmup's argument visualization mode](https://www.mindmup.com/tutorials/argument-visualization.html):

![Sample argument map](https://user-images.githubusercontent.com/14331/47167094-50272b00-d2c3-11e8-91d6-780bd67e2e52.png)

Am I right to think that it should be reasonably straightforward to create a new diagram type that achieves this? If so, I'll take a crack at it. I am imagining that the syntax might look something like this,

```
argumentMap BT
A["It is okay for humans to eat meat"]
pro -- A
B["Other animals eat meat."]
C["It is okay for humans to do things if other animals do them"]
end
con -- A
D["The production of meat causes animal suffering."]
E["It is not okay to do things that cause animal suffering."]
end
```

**Comment by eyssette** [comment]
@dsanson : i've created a template to create argument maps with Mermaid.
You can change `TB` and `direction TB`to `BT`and `direction BT` if you prefer to have the conclusion on the top of the map.
I'm planning to add examples of reconstructed arguments there : [https://github.com/eyssette/arguments](https://github.com/eyssette/arguments)


```mermaid
%%{init:{"theme":"base","themeCSS": "#Argument rect{stroke:transparent; fill:#e5e5e5} #Argument span {color:transparent} .edgeLabel{color:#888; font-size:0.9em; margin-right:3px} .edge-pattern-dotted{stroke:crimson} .edge-pattern-solid{stroke:green} #flowchart-pointEnd{fill:green}  g[id*=\"O\"] *{stroke:crimson!important; font-size:0.95em} circle+g span{color:white; } circle{fill:green!important} g[id*=\"C\"] * {fill:black;color:white;font-weight:bold}","themeVariables":{"secondaryColor":"transparent","primaryColor":"white","primaryBorderColor":"black"},"flowchart":{"htmlLabels":true,"padding":20,"rankSpacing":20}} }%%
flowchart TB
    %%accTitle: Titre
    %%accDescr: Description
    subgraph Argument
    direction TB
    %% 1("Prémisse")
    %% Pour utiliser les guillemets dans une prémisse : #quot;
    %% 1 -->|Par conséquent|2
    %% 1 & 2 --- PL1((&))
    %% C(["Conclusion"])
    1("Prémisse")
    1 -->|Par conséquent|C
    C(["Conclusion"])
    end
    %% OBJECTIONS
    %% O1["Objection"]
    %% O1-.-|objection !|3
```
