### ISSUE TITLE
FlowChart - large space between text and the image

### ISSUE THREAD

**Issue by hmf** [knsv/mermaid#754]
I am using [sbt microsite](https://47deg.github.io/sbt-microsites/) to generate the documentation of an open source project in GitLab. Gitlab uses [Jekyll](https://jekyllrb.com/) with the mermaid plugin,  so I am trying to use that too. However I cannot add the mermaid plugin to my install and so use it directly via the JS iibrary.   

I have the following code in my markdown (page has other elements):

``` 
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="mermaid.min.css">
</head>
<script>mermaid.initialize(
   {
     startOnLoad:true,
     flowchart:{ useMaxHeight:false, }     
    });</script>

Text here.

<div class="mermaid">
graph LR;
  A --> B;
  A --> C;
  B --> D;
  C --> D;
</div>

And text here. 

```

The page however ends up with large blank space between the graph and the surrounding text. 
Unfortunately my knowledge is limited in this area so I don't know if this is a mermaid or HTML issue.   
Can anyone point me to the right direction?

Here is the [example](https://cese.gitlab.io/adw/docs/pipes.html)

TIA

**Comment by bryandamon** [comment]
No idea where is came from, but inspecting (using developer tools in Chrome `Ctrl-Shift-I`) the page you linked shows the following wrapper.  The **height="100%"** is the part that is generating the white space.  You can edit it (again using Chrome developer tools) to remove it and see the result.

`<svg id="mermaidChart0" xmlns="http://www.w3.org/2000/svg" height="100%" viewBox="0 0 335.71875 219.375" style="max-width:335.71875px;">`

**Comment by lloyd094** [comment]
I have the same issue, and I can't figure out what's causing it. For me, I'm using mermaid through Typora (markdown editor), and then export the project to PDF. Unfortunately currently, this leaves me with several blank pages.

**Comment by hmf** [comment]
@bryandamon Appreciate the feedback. I can confirm the culprit is the `height`attribute. 

Like @lloyd094 I am using mermaid via another tool ([sbt microsite](https://47deg.github.io/sbt-microsites/)), which in turn uses [Kramdown](https://kramdown.gettalong.org/). So I don't know what's happening, however I am a bit skeptical that either micro-sites or the Kramdown plugin generate the HTML <svg> tag. 

Is their any way I can find out who is inserting the misbehaving attribute? 

TIA

**Comment by hmf** [comment]
A small update with a **hack**. 

I looked at the code and in fact in [src/diagrams/flowchart/flowRenderer.js](https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/diagrams/flowchart/flowRenderer.js#L411) we see that only the width is set to 100%. This would in principle solve my problem. I am using version [7.1.2](https://unpkg.com/mermaid@7.1.2/dist/) so I cannot confirm if this was changed recently. 

If however you are using 7.1.2 you can use the parent container to *scale* the SVG so that no space is seen. Here is the final HTML snippet:

```HTML
<div class="mermaid" style="height: 30%" data-processed="true">
<svg id="mermaidChart0" xmlns="http://www.w3.org/2000/svg" height="100%" viewBox="0 0 304 210.3333282470703" style="max-width:304px;">
...
</svg></div>
```
For those using Kramdown here is the source:

```Kramdown
<div class="mermaid" style="height: 30%">
graph LR;
  title[<u>Pipe Example 1</u>]
  A --> B;
  A --> C;
  B --> D;
  C --> D;
</div>
```

Note that use of Kramdown style or [attribute overwriting ](https://about.gitlab.com/2016/07/19/markdown-kramdown-tips-and-tricks/) was not possible for the Mermaid HTML class because it is generated by JS after the page HTML has been generated. 
 
HTHs

**Comment by hmf** [comment]
Small update. 

Version 8.0.0.rc.8 generates a width="100%" and works correctly.

**Comment by lloyd094** [comment]
@hmf - Thanks for the info, just submitted a request to update Mermaid to the Release Candidate for Typora to solve this issue over there.

**Comment by hmf** [comment]
Ok. I am going to close this seeing as it works in the latest version.
