### ISSUE TITLE
Sequencediagram signal texts with <br/> not working but works with note

### ISSUE THREAD

**Issue by coolgoose85** [knsv/mermaid#755]
I have seen multiple posts here with <br/> but I have come to realize in 
```
sequenceDiagram
a->>b: test is <br/>done.   => Doesn't work
```
```
sequenceDiagram
a->>b: test is done.   
Note right of b: This line will <br/> break.  ===> Works
```

Please let me know if there is any work around for now?

**Comment by Dunning-Kruger** [comment]
A first version of this feature was completed on https://github.com/knsv/mermaid/pull/764

**Comment by knsv** [comment]
The issue #764 dealt with br in actor names. This one deals with br tags ion the signal descriptions. @edumicse is working with this in an active branch. Based on description I see how this can be confusing. Will reopen and update description.
