### ISSUE TITLE
How can I use a dotted line with my custom color?

### ISSUE THREAD

**Issue by hexawing** [knsv/mermaid#760]
when I use
`linkStyle 8 stroke:#f33,stroke-width:1px;`
the line I set in `A -.- B` will be overridden.

Can I use them both without extra .CSS file?( because I am using a plugin in TiddlyWiki)

And further question is, when I use style define of edge, the label of it will move to the right side of the line instead of over the line.

**Comment by RudeySH** [comment]
Yeah I wonder this too.

**Comment by GDFaber** [comment]
I've come across this too (mermaid 8.2.1), but you can reapply the dotted pattern in your style definition:
`linkStyle 8 stroke:#f33,stroke-width:1px,stroke-dasharray:3;` (or whatever value suits you best)
