### ISSUE TITLE
Render mermaid on github pages with simple code 

### ISSUE THREAD

**Issue by yk-liu** [knsv/mermaid#772]
I have been trying to find a way to render mermaid in markdown simply by using

     ```mermaid
     # some mermaid code
     ```
in markdown, and use javascript in the page to render it.

I tried many solutions and faild. One of the solution I found is to use code from here but that's not correct. I am wondering if the author of this awesome js can give me a solution to acheive that and add that to the documentation?

Also I could not find the docs folder @knsv mensioned in #215.

**Comment by tewarid** [comment]
I have a similar request related to GitHub Pages. The HTML rendered by Jekyll, when it encounters a code block such as the above, looks like

```html
<code class="language-mermaid">
# some mermaid code
</code>
```

Would it be possible for mermaid to replace such a code tag with a diagram?

**Comment by yk-liu** [comment]
> I have a similar request related to GitHub Pages. The HTML rendered by Jekyll, when it encounters a code block such as the above, looks like
> 
> ```
> <code class="language-mermaid">
> # some mermaid code
> </code>
> ```
> 
> Would it be possible for mermaid to replace such a code tag with a diagram?

I think the html will be 
```html
<pre><code class="language-mermaid">graph LR
A  --&gt; B
<code></pre>
```

**Comment by yk-liu** [comment]
I found the solution.
```html
<!DOCTYPE html>
<html lang="en">
   <head>
 

	 <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js"></script>
	

    </head>
	 
<body>
 <pre><code class="language-mermaid">graph LR
A--&gt;B
</code></pre>

<div class="mermaid">graph LR
A--&gt;B
</div>
	
</body>
<script>
var config = {
    startOnLoad:true,
    theme: 'forest',
    flowchart:{
            useMaxWidth:false,
            htmlLabels:true
        }
};
mermaid.initialize(config);
window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));
</script>

</html>
```

it works great on my site.

**Comment by fulldecent** [comment]
Please update broken link.

That approach can be improved so that JS is injected only if that page actually has Mermaid code in it.

---

The `<code class="language-mermaid">` approach is preferred because it is compatible with Typora.

**Comment by fulldecent** [comment]
Here is the best I've got so far.

```html
{%- if content contains 'mermaid' -%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js"></script>
<script>
const config = {
    startOnLoad:true,
    theme: 'forest',
    flowchart: {
        useMaxWidth:false,
        htmlLabels:true
        }
};
mermaid.initialize(config);
window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));
</script>
{% endif %}
```

This could be a little better if 'mermaid' could include the code fence part ```. But I'm not sure how to escape that into the Liquid string literal above.

**Comment by b00nw33** [comment]
> Here is the best I've got so far.
> 
> ```
> {%- if content contains 'mermaid' -%}
> <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js"></script>
> <script>
> const config = {
>     startOnLoad:true,
>     theme: 'forest',
>     flowchart: {
>         useMaxWidth:false,
>         htmlLabels:true
>         }
> };
> mermaid.initialize(config);
> window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));
> </script>
> {% endif %}
> ```
> 
> This could be a little better if 'mermaid' could include the code fence part ```. But I'm not sure how to escape that into the Liquid string literal above.


@fulldecent , where should this code be inserted?

**Comment by fulldecent** [comment]
> @fulldecent , where should this code be inserted?

Probably into your _layouts/post.html or an include if that uses an include.

**Comment by norahvii** [comment]
@fullbright @fulldecent I wasn't able to get Mermaid to work in `_layouts/post.html` or `_includes/scripts.html` or `_includes/head.html` My LaTeX works because of code under `head.html` I learned recently that `post.html` was not necessary in my case to render LaTeX - my repo: https://github.com/norahvii/norahvii.github.io/tree/master/_includes
