### ISSUE TITLE
how to use render API

### ISSUE THREAD

**Issue by sebcagnon** [knsv/mermaid#779]
I looked at the doc and couldn't understand how to use the mermaid.render function. here is my code and my current use. (in my real vue app, I use `import mermaid from 'mermaid'` of course)

index.html

```html
<body>

  <div id="myDiagram" class="mermaid2">

  </div>

  <button onclick="init()">init</button>
  <script src="node_modules/mermaid/dist/mermaid.js"></script>
  <script src="index.js"></script>
</body>
```

index.js

```js
mermaid.initialize({theme: "neutral"});

init = function () {
  var graph = `graph LR
A --> B`
  el = document.getElementById("myDiagram")
  el.innerHTML = ""
  el.textContent = graph;
  el.removeAttribute("data-processed")
  mermaid.init(undefined, ".mermaid2")
}
```

Note: I want to be able to load the graph on click event, and update the graph when the user clicks again. My method works, but is both deprecated (init) and hackish (removeAttribute!).

I tried the following line solution:

```js
mermaid.initialize({theme: "neutral"});

init = function () {
  var graph = `graph LR
A --> B`
  el = document.getElementById("myDiagram")
  mermaid.render("myDiagram", graph, function () {console.log("finished")},  undefined)
}
```

it does not work (finished displayed in logs, nothing happens on webpage).

**Comment by xifenghuyang** [comment]
it should be note in the document of mermaidAPI. for i saw not a api called init and the render doesn,t work.
when can fix the render function?
