### ISSUE TITLE
mermaid@8.0.0: render method produces <div>'s on body when syntax errors occur

### ISSUE THREAD

**Issue by simpltek** [knsv/mermaid#786]
I'm having a hard time re-rendering a flowchart when it's been live edited after it's initial render. Every time a syntax error occurs (if you type and backspace the "8" at the end of the graph definition in the textarea, for example) mermaid creates an empty graph svg element inside a div and appends it to the body of the page:

![image](https://user-images.githubusercontent.com/38133930/51751787-c76b1880-2083-11e9-934e-f1524750f396.png)

Here's the code I'm working with:

    <style>* {margin:0;padding:0;} #chart {flex:2;height:90vh;width:100vw;max-width:100% !important;text-align:center;} main {display:flex;} pre {white-space:pre-line;text-align:left;} #editor {flex:2;}</style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js"></script>
    {% framework %}
    <script>
        mermaid.initialize({
            startOnLoad: true,
            flowchart: {
                curve: 'basis'
            }
        });
        function Render(data) {
            var def = 'graph TD\n'+data,
                ver = 'ver' + (Math.floor(Math.random() * 10000)).toString();
            
            var cb = function(graph) {
                $('#chart').html(graph);
            }
            try {
                mermaid.render(ver,def,cb);
            } catch(e) {
                $('#chart').html('<pre>'+e+'</pre>');
            }
        }
        function Edit(e) {
            Render(e.value);
        }
    </script>
    <main>
        <div class='mermaid' id='chart'>
    graph TD
    1["Introduction (Stage 1)"] -- "Yes #quot;Thank You#quot;" --> 3["PurposeOfCall.asp (Stage 3)"]
    1 -- Answering Machine --> 2["AMC.asp (Stage 2)"]
    3 -- Prayed Answered --> 4["AnsweredPrayer.asp (Stage 4)"]
    3 -- Still Praying --> 5["StillPraying.asp (Stage 5)"]
    
    4 --> b{No To Prayer}
    
    4 --> a{Yes To Prayer}
    
    5 --> b
    b --> 7["CloseForm3.asp (Stage 7)"]
    
    5 --> a
    a --> 6["Prayer.asp (Stage 6)"]
    
    6 --> 7
    
    7 --> 8["OutboundFinishCall.asp (Stage 8)"]
    2 --> 8
        </div>
        <textarea id='editor' oninput='Edit(this)'>1["Introduction (Stage 1)"] -- "Yes #quot;Thank You#quot;" --> 3["PurposeOfCall.asp (Stage 3)"]
    1 -- Answering Machine --> 2["AMC.asp (Stage 2)"]
    3 -- Prayed Answered --> 4["AnsweredPrayer.asp (Stage 4)"]
    3 -- Still Praying --> 5["StillPraying.asp (Stage 5)"]
    
    4 --> b{No To Prayer}
    
    4 --> a{Yes To Prayer}
    
    5 --> b
    b --> 7["CloseForm3.asp (Stage 7)"]
    
    5 --> a
    a --> 6["Prayer.asp (Stage 6)"]
    
    6 --> 7
    
    7 --> 8["OutboundFinishCall.asp (Stage 8)"]
    2 --> 8</textarea>
    </main>

I'm not sure what I'm doing wrong, as I pulled most of the code from your docs :/ And there's this global confusion about "mermaidAPI.js" between Github and your docs site, so not sure if that's what's missing either; some say you need it, some say you don't, the Unpkg dist directory doesn't have one for 8.0.0, etc.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.

Feel free to create a new issue, if necessary.

**Comment by JSv4** [comment]
@IOrlandoni, I am seeing the same behavior. 

At the bottom of my component, I'm seeing some random divs:

![image](https://github.com/mermaid-js/mermaid/assets/5049984/405d5f1b-99ce-44c9-8a30-b33bfb769e12)

I can see I'm also getting unexpected dicvs with the letter d appended to the id:

![image](https://github.com/mermaid-js/mermaid/assets/5049984/aa8256c6-abd7-4911-ac2c-291027bb6e08)
