### ISSUE TITLE
scaling of fonts

### ISSUE THREAD

**Issue by Dimouse** [knsv/mermaid#787]
In Google Chrome if browser scaling is 100% than everything is perfect. But when I zoom out (about 75%), the size of rectangles becomes too small to fit text inside.
What can I do?
![image](https://user-images.githubusercontent.com/7388561/51766981-19945400-20ed-11e9-9ce3-8075ee78d5a8.png)

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
