### ISSUE TITLE
How can i use this awesome library in Angular 6 ?

### ISSUE THREAD

**Issue by Vbboi24** [knsv/mermaid#789]
Hello, This library looks cool, Can anyone suggest how to use this in Angular ?

**Comment by brunobarretofreitas** [comment]
Hello Vbboi24, all You need to do is install this library in your project, via npm for example, and import the library in your angular.json file at the scripts property :
`
"scripts": [
    ...
    "node_modules/mermaid/dist/mermaid.min.js"
]
`
Then, in your component.ts file where You will use the library, You'll import mermaidjs like this:
`declare const mermaid;`

That's it, now You only need to create a <div class="mermaid"> with the mermaidjs code inside of it, and call mermaid.init();

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
