### ISSUE TITLE
The mermaid sequence diagrams issue

### ISSUE THREAD

**Issue by capvor** [knsv/mermaid#796]
![image](https://user-images.githubusercontent.com/16610170/52704883-8ef09780-2fbc-11e9-8fe9-dee2bbfe56c1.png)
**Drawing sequence diagrams using mermaid is not adjust when the text is too long.
The sequence syntax is better.**

Next is the source code
![image](https://user-images.githubusercontent.com/16610170/52705000-d0814280-2fbc-11e9-97b9-57c876d1f2f0.png)

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
