### ISSUE TITLE
Why the use of code blocks?

### ISSUE THREAD

**Issue by BenjaminHoegh** [knsv/mermaid#799]
Why do mermaid use markdown ``` code blocks as open close syntax?

**Comment by knsv** [comment]
The reasoning for this was convenience. Many markdown converters that generate html from markdown have suitable callbaks fore cxode blocks.

**Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed.
