### ISSUE TITLE
Re-render shrinks diagram making text unreadable

### ISSUE THREAD

**Issue by ErikSteNL** [knsv/mermaid#800]
Hello,

When rendering the same flowchart multiple time using the mermaid.render() function it seems to shrink. I do not suppose this is expected behavior. 
I switch between different width flowcharts and this seems to affect it.
When a large graph is loaded for the first time it renders fine. Second one (in the same div) is smaller, also fine. But when the larger one is re-rendered it takes the size of the smaller graph.

Example:
Graph 1
```
graph LR
0(Example 1 TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest)
```

Graph 2
```
graph LR
0(Example 1 Test)
```

when switching between these two graphs the problem occurs.

I'm on the latest version.
I hope I have given enough information, if not please ask.
Thanks!

**Comment by GDFaber** [comment]
I don't know if I understood correctly, perhaps this can solve the problem for you? https://github.com/knsv/mermaid/issues/838#issuecomment-514594935
