### ISSUE TITLE
UOEProcessShow

### ISSUE THREAD

**Issue by Mashiane** [knsv/mermaid#801]
Hi everyone...

Been working on a flowchart app using MaterializeCSS and Mermaid, check it out now, https://youtu.be/m-EeHAabSUU

Ta!

**Comment by Mashiane** [comment]
This is now available for use from github, check it out now, https://github.com/Mashiane/UOEProcess.Show and enjoy creating your flowcharts. More is coming..

**Comment by Mashiane** [comment]
This other demo shows how I have been able to do a code execution analysis for my app using UOEProcess.Show, check it out now, https://youtu.be/s7WXKI-K1cs

**Comment by knsv** [comment]
Wow, that looks quite impressive!

**Also, sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed.
