### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by sunt05** [knsv/mermaid#802]
It would be good to add comments for this option as well:
https://github.com/knsv/mermaid/blob/7d3578b31aeea3bc9bbc618dcda57d82574eaffb/src/mermaidAPI.js#L98

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866.

**Comment by ezeed** [comment]
Hi! I was looking this [commit](https://github.com/knsv/mermaid/commit/f1d280859443e4d1f4f15d8b38a6486172666969).
It seems like that missing documentation was related to this [documentation](https://github.com/d3/d3-shape#curves) of D3. 
Regrettably a lot of `curves` listed had complement function like `curveCardinal.tension`.
If you are agree i can list all the options with no complement functions, just let me know. :+1:

**Comment by knsv** [comment]
This has been fixed, see http://knsv.github.io/mermaid/#/mermaidAPI?id=flowchart

I will close this one. Please reopen if your verification fails
