### ISSUE TITLE
[bug] incorrect height 

### ISSUE THREAD

**Issue by yk-liu** [knsv/mermaid#803]
When I try to make the boxes' height smaller, the arrows are rendered incorrectly, see 
```mermaid
graph TD
    A[Start] --> B[Stop]
class A,B className;
classDef className height:2em 
```
https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW1N0YXJ0XSAtLT4gQltTdG9wXVxuY2xhc3MgQSxCIGNsYXNzTmFtZTtcbmNsYXNzRGVmIGNsYXNzTmFtZSBoZWlnaHQ6MmVtICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
