### ISSUE TITLE
how can I start a newLine in FlowChart

### ISSUE THREAD

**Issue by liuzhebaba** [knsv/mermaid#805]
like this 

![image](https://user-images.githubusercontent.com/22785707/54345816-c8312b80-467e-11e9-97ee-9d219420f0b9.png)

<br> doesn't work also <br/>,\n,<p></p>

**Comment by jakubLangr** [comment]
Did anyone figure out a solution to this?

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed. 

Is this still a problem? If so please reopen it.
