### ISSUE TITLE
Force-directed graph Layout Style

### ISSUE THREAD

**Issue by jgroom33** [knsv/mermaid#806]
The existing layout scheme is strictly hierarchical (TD, LR).
An [organic layout](https://live.yworks.com/demos/layout/layoutstyles/index.html) should also be supported.
The organic layout above uses a predefined [force-directed graph layout](https://en.wikipedia.org/wiki/Force-directed_graph_drawing)

The Class UML layout appears to operate in this manner, however, the class UML use case is currently limited to class diagrams because of the rendered box (with variable placeholders)

This issue will provide the following implementation:

graph Hierarchical TD
...
end

graph Organic
....
end

To address scenarios with subgraphs, the following approach could be used

graph Organic
  subgraph Hierarchical TD
  ...
  end
  subgraph Hierarchical LR
  ...
  end
end

**Comment by knsv** [comment]
Thanks for your input. I think you have a good point here in a general sense. Currently the layout mechanism is using a dagre algorithm. It would be powerfull to add the possibility to specify which layout algoritm to use.  #867 

I will close this one but link to it from #867. I will modify the syntax a bit. Default layout would for instance be current behavior. I dont want to breake a bunch of diagrams out there.

**Comment by jgroom33** [comment]
Thanks. I appreciate the review

**Comment by mjaggard** [comment]
@knsv But now both #867 and this issue got closed.
