### ISSUE TITLE
uml Class as shape type

### ISSUE THREAD

**Issue by jgroom33** [knsv/mermaid#807]
The following are implementations for various shapes using the TD/LR layout:

() - rounded corners
(()) - circle
{} - diamond

This feature is designed to treat a class UML object in the same manner a shape is used.  Consequently #806 can define the layout of the graph.

Proposal for Class UML shape:

graph TD
 class0{{class0|int foo|str bar}}
end

**Comment by ntmls** [comment]
I would also like to see this feature. I use yUML for class diagrams. Additional arrow types would also be nice. It seems like it wouldn’t be too difficult to extend the language support some similar features to yUML here https://yuml.me/diagram/scruffy/class/samples

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

Perhaps the diagram type classDiagram would be suited for you needs?
![image](https://user-images.githubusercontent.com/5837277/60393525-188da580-9b17-11e9-847a-24edb9764e47.png)

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed.

**Comment by jgroom33** [comment]
Yes. I was just trying to document some ideas for how to make the implementations a bit more scalable. This feature could potentially deprecate the uml drawing type and and more capable to a generic layout type.
