### ISSUE TITLE
no triming  participant name and the name following spaces is as another actor in sequence

### ISSUE THREAD

**Issue by guide2it** [knsv/mermaid#809]
sequenceDiagram
participant A
participant A 
participant A  
participant B
A->>B:Who are these guys between us？
![MermaidBug](https://user-images.githubusercontent.com/48471295/54484981-df089580-48ab-11e9-8d06-1baf9fba17f9.png)

**Comment by IOrlandoni** [comment]
I'd be happy to work on this.

Would the solutionbe as simple as not treating the whitespace as part of the actor name in the participant declaration without a description?

**Comment by ThePenguin1140** [comment]
Yea that sounds right.
I think this can be fixed by adding a `+` to the SPACE definition in the parser. I was rooting through that the other day but I didn't commit anything yet.

**Comment by IOrlandoni** [comment]
Merged to master on #882
