### ISSUE TITLE
[Feature Request] Electrical circuit diagrams

### ISSUE THREAD

**Issue by lsonnino** [knsv/mermaid#811]
Would it be possible to add a new diagram type to design simple circuits such as this one:
<img width="541" alt="Screenshot 2019-03-25 at 12 32 11" src="https://user-images.githubusercontent.com/30297828/54916534-0558b180-4efa-11e9-8263-789559ec3a9e.png">
It could be really useful.
Thanks in advance
Lorenzo

**Comment by konsumer** [comment]
I actually started doing this in a flowchart, thinking I could maybe generate a netlist, and in turn generate other stuff with already-made tools.

I really like the idea of "describe the relationship between the parts and the software will work out the layout".

As an example, I made a diagram of a separated high-voltage power-supply controlled by an arduino-nano (nano can read voltage and turn on/off the power via a relay.)

![circuit][https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblxuUjFbMU1dXG5SMlsxMEtdXG5VMVtBcmR1aW5vIE5hbm9dXG5VMltGMEQ0MjBdXG5cbjUwMFYtLS1SMVxuUjEgLS0tIFIyXG5SMS0tIEEwIC0tLSBVMVxuUjIgLS0tIEdORDFcbjUwMFYgLS0gNiAtLS0gVTJcblUyIC0tIDQgLS0tVk9VVFxuVTItLTEtRDItLS1VMVxuVTItLTItR05ELS0tVTEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ]

```mermaid
graph TD

R1[1M]
R2[10K]
U1[Arduino Nano]
U2[F0D420]

500V---R1
R1 --- R2
R1-- A0 --- U1
R2 --- GND1
500V -- 6 --- U2
U2 -- 4 ---VOUT
U2--1-D2---U1
U2--2-GND---U1
```
It illustrates the idea that, like `graph TD`, you can specify the parts in a header, or inline. It hooks them all up correctly, albeit in a very "bug" way.

The only limitation I saw was for things that have multiple pins (`U1` or `U2`) there was only one text label for a connection, so I would do it in `A--APIN-BPIN---B` format.

It seems like it would be easier (and maybe good for regular graphs too) if I could specify a whole circuit-path & have labels on both sides of the connection:

```mermaid
500V --- R1 --- R2
U2 -- (2 -- GND) --- U1 # or similar
```

**Comment by konsumer** [comment]
I find that in general mermaid helps me visualize graphs better. Like I describe the things, and then the connections, and other people get a nice graph of that.  When I build circuits I often do the same in reverse (write down all the parts so I can buy them, then list all the connections to wire, so I don't miss any) so weirdly, I bet mermaid would be really good for me to design circuits, even though it's really not what it's for.

[this](https://sourceforge.net/projects/netlistviewer/) might give us some inspiration to generate a schematic from just a list of parts & connections.
