### ISSUE TITLE
How to set the spacing between the text of the flowchart node and the border?

### ISSUE THREAD

**Issue by yuzhujiutian** [knsv/mermaid#812]
my markdown flowchart code is  as follows:

\`\`\`flow
story_approval( 需求立项 )
story_zgh-ing( 转规划ing )
story_zsx-ing( 转实现ing )

story_compound( 需求复盘 )
style story_compound fill:#F0F,stroke:#F00,stroke-width:1px;

classDef cssName fill:#FF0,stroke:#F00,stroke-width:1px;
class story_zsx-ing,story_zys-ing,story_zcs-ing cssName;

story_approval --> | 产品设计 | story_zgh-ing

story_approval .-> | 开发编码 | story_zsx-ing
story_zgh-ing --> | 开发评审OK | story_zsx-ing
story_zsx-ing --> story_compound
\`\`\`

The output flowchart is as follows:
![image](https://user-images.githubusercontent.com/386347/54999344-fc0b3a00-500a-11e9-8ecd-20bfc6e32b8d.png)

When I clicked the flowchart, I found that some text could not be displayed properly.
![image](https://user-images.githubusercontent.com/386347/54999432-2e1c9c00-500b-11e9-83a4-921239ceadb6.png)

How to set the spacing between the text of the flowchart node and the border?

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866.
I think this is a dupilcate of #790
