### ISSUE TITLE
How load mermaidApi notejs electron 

### ISSUE THREAD

**Issue by Pedro2219** [knsv/mermaid#813]
When loading mermaid api on html (se code below) the error "unexpected token *" is displayed on line 14 inside marmaidAPI.js file

How should I load the module 

Code:
<script>src=".. /note_modules/mermaid/src/mermaidAPI" </script>

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed. 

Is this still a problem? If so please reopen it.
