### ISSUE TITLE
Overlap, Overflow and cut titles in flowchart

### ISSUE THREAD

**Issue by Ozmoica** [knsv/mermaid#814]
Hello all,

I'm working in a angularjs project and I discover this powerfull API for charts and I very happy to start learning how it works.

I'm having some problems with the rendering of the svg because the titles are sometimes are quite long so it produce an overflow and overlap between them. 

I'm using the mermaid.min.js and mermaidAPI.js 8.0-rc to render the graph. I don't know either if i have to add some other files or to change same flowchart propertiees / CSS.

` mermaidAPI.initialize({
            startOnLoad:false,
            cloneCssStyles:false,
            flowchart:{
                useMaxWidth:false,
                htmlLabels:false,
                width: '100%',
                curve:'basis',
            },
            theme: 'forest',  
        });`

![imagen](https://user-images.githubusercontent.com/15928769/55225272-912c4f80-5212-11e9-87a6-9f7e96ab6d04.png)

![imagen](https://user-images.githubusercontent.com/15928769/55225365-bb7e0d00-5212-11e9-8e7d-4530072e498c.png)

Thanks!!!

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed. 

Is this still a problem? If so please reopen it.
