### ISSUE TITLE
TOO LARGE mermaid node size on mobile Chrome

### ISSUE THREAD

**Issue by zq1997** [knsv/mermaid#816]
Is there any suggestion for the node size on Android chrome browser? I found it is too large, and this problem disappear on PC or firefox browser.

code example:
```
graph LR
c-m1(( ))-->c-m2(( ))
c-m2(( ))-->c-m3(( ))
c-m3(( ))-->c-m4(( ))
c-m4(( ))-->c-m5(( ))
c-m5-->m(master)
c-m5-->c-merge1[ ]
c-m3-->c-b1[ ]
c-b1-->b(blog)
c-b1-->c-merge1
c-merge1-->ub(* updated-blog)
```

### Expected behavior 
> Screenshot on Android firefox

![Screenshot_2019-04-01-10-20-12-004_org mozilla fi](https://user-images.githubusercontent.com/17429111/55300277-507a4380-5469-11e9-9841-69e3ca799f8f.png)

### Actual behavior 
> Screenshot on Android chrome

![chrome](https://user-images.githubusercontent.com/17429111/55300292-58d27e80-5469-11e9-98f8-a5049912829f.png)

**Comment by novneetnov** [comment]
Any update on this so far? I am still facing this issue in android-chrome.

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The project has got good traction but it also means that it is very hard to manage all issues on your spare time.

How would you propose this to be solved?
