### ISSUE TITLE
preprocessing of HTML page without deploying mermaid.js

### ISSUE THREAD

**Issue by boennhoff** [knsv/mermaid#817]
Hi devs,
i am using Markdig within a standalone C# tool to convert technical Markdown documents to good looking (self-contained) HTML outputs. Markdig supports mermaid by translating ~~~mermaid to a mermaid DIV.

I included mermaid.min.js in the final output of the HTML and got wonderful diagrams, but i am shocked by the increase in size of the output file. It's like delivering a Markdown Parser/Processor together with the Markdown document instead of its output: So that is a no-go!

My idea is to preprocess the HTML from Markdig to replace all mermaid DIVs with SVGs, without deploying the mermaid.js itself. How should this be done? I see most problems in the Javascript nature of mermaid and my code being C#. Any ideas? A valid answer might even be to use a completely different tool, i am just not aware of any, yet.

NB: a local node.js instance is also a no-go, self-contained is the keyword. there won't be any things preinstalled on the target computers that run my tool beside the .NET framework.

**Comment by knsv** [comment]
Hi! Are you still working with this? Maybe you could use the mermaid cli to generate the diagrams and incorporate the result.

**Comment by boennhoff** [comment]
Hi, thank you for our answer. That is exactly what I was thinking about in the first place, but I totally dislike the idea, because I would add a reference to a locally installed application (nodejs) that also need to be configured correctly, compared to the single .NET framework reference as of today -- see the above NB about "self-contained".
I potentially could deliver a whole nodejs installation including needed references, but that would increase my tool from a few kilobytes to a few hundred megabytes and thousands of files... ridiculous, imho. Especially if the minified mermaid.js is able to do the processing with something over 1 MiB in size (okay, and a running browser)...
But maybe i am just doing it wrongly and I should try another approach I haven't yet thought of!?

**Comment by boennhoff** [comment]
Well, _github-actions_ is true, nothing to say anymore, and a solution is not around the corner... so let's close this as _"won't fix, look for something else"_... thanks for your answer @knsv
