### ISSUE TITLE
[sequenceDiagram] How can I change the self-self loop line from curved to linear style?

### ISSUE THREAD

**Issue by legoming** [knsv/mermaid#819]
How can I change the loop line from curved line to linear line?

![](https://camo.githubusercontent.com/552e9d4f58eac852994f8109b96326673e7ba3cf/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f373834302f34373536383932313639315f383665373037656466655f7a5f642e6a7067)

**Comment by knsv** [comment]
Sorry, that cant be done. You want it to be square? I am not sure I understand what you mean.

**Comment by legoming** [comment]
Yes, I like the square style, something like 1.1.1 in below diagram

![](https://cdn.visual-paradigm.com/guide/uml/what-is-sequence-diagram/01-sequence-diagram-example.png)
