### ISSUE TITLE
Assymetric shapes not documented

### ISSUE THREAD

**Issue by Grahack** [knsv/mermaid#82]
Hi,
At http://knsv.github.io/mermaid/flowchart.html we learn that it is possible to use:

    id1>This is the text in the box]

I tried other shapes like:

    id1[This is the text in the box<

don't work. Would it be possible to list available shapes, or say that `>...]` is the only available, or maybe even implement other shapes ;) ?

Thanks.

**Comment by knsv** [comment]
Will take look at the docs. And why not implement the reversed assymetric shape as well. What do you think @bjowes ?

**Comment by bjowes** [comment]
I found that the assymetric shape is now already documented, excellent! Adding the reverse assymetric shape is fairly easy, I will look into it.

**Comment by bjowes** [comment]
@knsv: I added the reversed asymmetric shape in my last pull request, but could not work out the jison to handle the syntax. The attempt is included in the pull request as a commented out section in the jison. Apparently [ .. > conflicts with text elements. Can you see a way around it?

**Comment by knsv** [comment]
I will close this issue and add a new one regarding adding a reversed assymetric shape.
