### ISSUE TITLE
Customize flowchart shapes

### ISSUE THREAD

**Issue by iCirconflexe** [knsv/mermaid#820]
hi,

Is it possible to customize a shape in the flowchart diagram ?

I would like to do something like a table with several cells, something like that :
|--------------|------|
|   blabla        |  bla  |
|--------------|------|
|    bla bla                |
|-----------|----------|
|   bla bla  |    bla      |
|-----------|----------|

Is that a way to do it ?

**Comment by knsv** [comment]
Sorry, no such functionality in place.
