### ISSUE TITLE
DRAKON: soviet flowchart

### ISSUE THREAD

**Issue by mdtrooper** [knsv/mermaid#822]
I am https://en.wikipedia.org/wiki/DRAKON fan. it is a soviet version of flowcharts, there are a lot of rules but it is ok.

Some time ago (maybe one year) I tryed to code Drakon into PlantUML but it was hard work.

Well, I add this issue as "enhancement"....cold war "towarish"....

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
