### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by gmanriqueUy** [knsv/mermaid#826]
I just want to know if this project is still maintained or if someone have plans to continue with it?

**Comment by gaui** [comment]
Not sure but something is happening [here](https://github.com/mermaidjs). Also interested in knowing this.

**Comment by FranklinYu** [comment]
I see that @tylerlong updated https://github.com/mermaidjs/mermaid-gitbook so it should be somewhat maintained. There are several Pull Requests waiting for review though.

**Comment by knsv** [comment]
Yes the project is still maintained. Works goes in cycles though.

**Comment by knsv** [comment]
Closing this one now but want to flag #866. Things would be easier if there were more of us.
