### ISSUE TITLE
too many curves makes it ugly

### ISSUE THREAD

**Issue by ferdiozturk** [knsv/mermaid#827]
When using many (I mean massive count of) curves in the flowchart, many of them overlap and the reader can't see at all which source(s) and target(s) are connected... it's just a mess

We need a solution for this please. d3 offers "Links", a.k.a. Bezier curves, in d3.link or alternatively we need to be able to customize the curves ourselves in markdown. Perhaps this is already possible and I missed it?

THXs

**Comment by FiyaFly** [comment]
[This Comment](https://github.com/knsv/mermaid/issues/580#issuecomment-373929046) on an older issue may help you accomplish what you're looking for.

**Comment by Dunning-Kruger** [comment]
Given how long ago this issue's activity died out, I'm closing it.
This allows us to maintain a fresh list of issues the community is interested in.
