### ISSUE TITLE
Docs for integration with wiki.js?

### ISSUE THREAD

**Issue by sindhus** [knsv/mermaid#829]
Hi! I am asking a pretty basic developer question here. Which documentation should I be reading in order to integrate mermaid.js with wiki.js? Is it the [Mermaid API docs](https://mermaidjs.github.io/mermaidAPI.html)? I am not sure because I haven't done anything like this before.

Wiki.js is a simple markdown powered wiki. It is a node application.

**Comment by knsv** [comment]
Hi!

Take a look here for a good start:
https://mermaidjs.github.io/usage.html

**Comment by resu-cireneg** [comment]
page gone... https://github.com/mermaid-js/mermaid

> Hi!
> 
> Take a look here for a good start: https://mermaidjs.github.io/usage.html
