### ISSUE TITLE
Missing fontawesome icon support

### ISSUE THREAD

**Issue by adriandarian** [knsv/mermaid#830]
fa:fa-satellite-dish does not work
![image](https://user-images.githubusercontent.com/23567187/57187292-10abdf00-6ea1-11e9-8214-7e6dd594e230.png)
![image](https://user-images.githubusercontent.com/23567187/57187294-14d7fc80-6ea1-11e9-8779-aac6a32dbf33.png)

**Comment by YFFcloud** [comment]
+1,Have you solved the problem now?

**Comment by YFFcloud** [comment]
This problem requires the introduction of font-asome files to add to your page
like this
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">

**Comment by knsv** [comment]
Closing this one. I shope it worked out.

**Comment by JoNilsson** [comment]
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
```mermaid
GRAPH TD
a-->b
b-->c
c-->d
```

**Comment by LKSeng** [comment]
> where would one need to add this to get Font-Awesome icons to display in MERMAID that is going to live on GitHub? simply adding `<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">` to the source does not seem to solve the issue.
> 
> 
> <img alt="image" width="579" src="https://user-images.githubusercontent.com/54599325/158282720-4ce0687e-c9ea-482f-8b9e-e020285e6e00.png">

I think it's because Github strips it. See: https://github.com/community/community/discussions/11940
