### ISSUE TITLE
First node isn't at the top

### ISSUE THREAD

**Issue by dskarbek** [knsv/mermaid#833]
Even though I specify my start node first in a top-down flowchart, it doesn't end up at the top of the chart.  In a more complex diagram, this can leave people hunting for where it is.  Is there a way to force it to be at the top?  Seems like it simply always should be by default.

https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVEJcbnN0YXJ0KChzdGFydCkpXG41M1tcIk1haW4gSHViXCJdXG40NFtcIkZvcm1zIFN0ZXAgMVwiXVxuNThbXCJGb3JtcyBTdGVwIDJcIl1cbjU0W1wiVHJhbnNpdGlvbiBUaW1lT3V0IFRlc3RcIl1cbjU1W1wiRGlzcGxheSBEYXRhXCJdXG41N1tcIkdlbmVyYXRlIERvY3VtZW50XCJdXG41NltcIlNob3cgRG9jdW1lbnRcIl1cbjQ1KChcIkVuZCBTdGVwXCIpKVxuNTMtLT58Rm9ybXN8NDRcbjUzLS0-fFRyYW5zaXRpb24gVGVzdHw1NFxuNTMtLT58VmlldyBEYXRhfDU1XG41My0tPnxNYWtlIERvY3VtZW50fDU3XG41My0tPnxDbG9zZSBDYXNlfDQ1XG40NS0tPnxJbXBvc3NpYmxlIFJlc3RhcnR8NTNcbjQ0LS0-fE5leHR8NThcbjQ0LS0-fEJhY2t8NTNcbjU4LS0-fEJhY2t8NDRcbjU4LS0-fERvbmV8NTNcbjU4LS0-fENvcnJlY3Rpb24gTmVlZGVkIG9uIFN0ZXAgMXw0NFxuNTQtLT58Q29tZSBCYWNrIEltbWVkaWF0ZWx5fDUzXG41NC0tPnxDb21lIEJhY2sgQWZ0ZXIgMWhyfDUzXG41NC0tPnxDb21lIEJhY2sgU29tZXRpbWUgQWZ0ZXIgMmhyfDUzXG41NC0tPnxDb21lIEJhY2sgYSBEYXkgTGF0ZXJ8NTNcbjU0LS0-fENvbWUgQmFjayBMYXRlfDUzXG41NS0tPnxEb25lfDUzXG41Ny0tPnxEb2N1bWVudCBHZW5lcmF0ZWR8NTZcbjU2LS0-fEJhY2sgdG8gSHVifDUzXG5zdGFydC0tPiA1M1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by Dunning-Kruger** [comment]
The live editor link no longer reproduces the issue. Has it been fixed or do we need a new sample?
