### ISSUE TITLE
Non ASCII chars in labels

### ISSUE THREAD

**Issue by Grahack** [knsv/mermaid#84]
Hi,
See this error message:

    Error: Lexical error on line 2. Unrecognized text.
    ...        id>nom de l’algo]
    ----------------------^

I'd like to use this special apostrophe: `’` instead of this good old one: `'`.
I guess the problem is the same with other chars but I didn't test any.

EDIT: tested with `é` and it works well. Strange.

**Comment by knsv** [comment]
Will take a look. Will need to add it as a valid character

**Comment by knsv** [comment]
A fix is committed but not released yet.

**Comment by Grahack** [comment]
Wha! This is quite a big commit!
Big thanks then.
