### ISSUE TITLE
"undefined is not an object (evaluating 'n.starty')" when deactivating a participant that hasn't been activated

### ISSUE THREAD

**Issue by chucker** [knsv/mermaid#840]
With Mermaid 8.0.0, using the `deactivate` keyword on a participant will show an inscrutable error message if that participant hadn't previously been explicitly `activate`d. The message at first confused me and could probably be a bit nicer.

**Comment by IOrlandoni** [comment]
Still happening on 8.1.0. 
Repro on the live editor [here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgTGVubm94LT4-Sm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgZGVhY3RpdmF0ZSBMZW5ub3giLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/Q2Fubm90IHJlYWQgcHJvcGVydHkgJ3N0YXJ0eScgb2YgdW5kZWZpbmVk).
