### ISSUE TITLE
Changing the links’ behaviour

### ISSUE THREAD

**Issue by NicolasMatiasWW** [knsv/mermaid#842]
Hello,

I would like to know if is it possible to modify the direction of the links in the diagrams because I think they are not always logical or even optimal.
For example, when two items are at the same height, the links are not going straight but turns left or right before going into the next item.

please check the screenshots  1.png and 2.png ( the second one is the result that I want to have )

Thanks 

<img width="664" alt="1" src="https://user-images.githubusercontent.com/26058079/57938921-7ba9dc80-78c9-11e9-8ed7-1e17768a9daa.png">
<img width="644" alt="2" src="https://user-images.githubusercontent.com/26058079/57938922-7c427300-78c9-11e9-9469-27214763e94e.png">

**Comment by GDFaber** [comment]
I suppose you went with the flowchart setting `curve: 'step'` in your configuration.
Perhaps 'stepBegin' or 'stepEnd' would be worth a try, but that's just me guessing right now.
