### ISSUE TITLE
Smaller bundles

### ISSUE THREAD

**Issue by fabiospampinato** [knsv/mermaid#843]
When installed mermaid is pretty heavy on disk, requiring about 39MB of stuff to be downloaded. I see pre-bundled versions of the library are provided under the `dist` directory, but I think there are still some simple ways to make the bundles significantly smaller, I propose to make the following changes:

- Replace `moment` with with [`dayjs`](https://github.com/iamkun/dayjs). `moment` is a notoriously heavy library, and we are only using it for formatting some dates. Even if we are not using all other `moment`'s many features or provided localizations we are still paying for them in the bundle.
- Slim down `lodash`. The whole of `lodash` is currently included in the bundle, even though out of the 330+ provided methods only the following ones are being used: `each`, `extend`, `find`, `isArray`, `isString`, `map`, `maxBy`, `orderBy`, `uniqBy`.  I propose to replace some of these with plain JS (`each`, `map`, `isString`, `isArray`, `find`, maybe also `extend`), unless very old browsers are supposed to be supported, and require the specific modules for the others (`lodash.maxBy`, `lodash.orderBy` and `lodash.uniqBy`).
- Avoiding publishing the `src` directory to NPM. [Here](https://github.com/knsv/mermaid/blob/7d3578b31aeea3bc9bbc618dcda57d82574eaffb/package.json#L75) we are including it in the published package, I don't see why that'd be useful to the end user, so I propose to avoid publishing that folder.

I'd like to submit PRs implementing these suggestions, would those PRs be welcome? @knsv @tylerlong

Thanks!

**Comment by fabiospampinato** [comment]
Btw I've just published [`mermaid-bundled`](https://www.npmjs.com/package/mermaid-bundled), which is simply the file found under `dist/mermaid.js`, but on its own module.

Just importing this instead of the regular `mermaid` shaved ~15MB off my app.

Also `dist/mermaid.min.js` for some reason doesn't for me, I get an error, perhaps the minification has performed some unsafe operations.

**Comment by knsv** [comment]
Good suggestions we shuold do this.

**Comment by fabiospampinato** [comment]
@knsv do you want me to submit a PR for this?

**Comment by knsv** [comment]
Yes please. That would be much appreciated

**Comment by fabiospampinato** [comment]
Awesome! I'll try to fix the file under `dist/mermaid.min.js` too while I'm at it (it throws an error for me).
