### ISSUE TITLE
pseudo c style syntax ?

### ISSUE THREAD

**Issue by ltpyt** [knsv/mermaid#846]
Are there any way or ports that have done  a similar syntax as ex code2flow ?

Where you can write something like this :
label1:
if (file exists) 
{
 read file
}
else
{
 file doesnt exist
}

so it can generate code by a c pseudo style syntax ? it would be really useful

**Comment by knsv** [comment]
Interesting idea. The rendering could be done by compiling to the same graph object that mermaid syntax is compiles to. I wonder about copyright stuff though. I noticed that code2flow is commercial product. I would not want to be sued for breaking copyright of their syntax...
