### ISSUE TITLE
Insecure Randomness - Issue

### ISSUE THREAD

**Issue by karthikdav** [knsv/mermaid#848]
When scanned with Fortify scanner, it reported Insercure Randomness for function Math.random() since it was generating cryptographically weak random numbers.

**Comment by NicolaiSoeborg** [comment]
It's used in `src/diagrams/git/gitGraphAst.js` to generate a random id.
That function does not have to be securely random, so this isn't a problem.

If anything, then I think the random seed should be fixed to some constant to avoid hard-to-debug problems.

**Comment by knsv** [comment]
Thanks, that should be easy enoght to fix. Waiting for some comments on this proposal before ding anything though.

**Comment by Dunning-Kruger** [comment]
If it's cheap to fix, we might as well do it so it does not show up on scans.

**Comment by mearns** [comment]
I'll take a look and send in a PR. Sounds as simple as replacing the call to `Math.random()` with a cryptographically secure PRNG, am I missing anything else?
