### ISSUE TITLE
how to draw a line from a box to the line between two boxes?

### ISSUE THREAD

**Issue by Kailasa** [knsv/mermaid#849]
Is it possible to draw a line in mermaid like the red line in the screenshot?

<img width="246" alt="line" src="https://user-images.githubusercontent.com/7901720/58603722-53a47b00-82c4-11e9-9731-5c9c7e72aaa1.png">

**Comment by leematos** [comment]
don't think so, but you could probably make an element there, style it to be "invisible" and then have that rendering, but it wouldn't be easy. (new to mermaid tho)
