### ISSUE TITLE
Apply styling from css when using the CLI utility

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#85]
It is possible to apply styles to diagrams via css classes.

It would be cool if styling could be applied this way also when using the client utility.

This could perhaps be achieved via an option for giving a path to a css file which is then included in the rendering of the diagram. 

@fardog, what do you think of this idea?

**Comment by fardog** [comment]
Injecting CSS into the page is fairly trivial; I'm assuming this is the only requirement? I'd probably add the following option:

```
  -c --includeCSS    Specify a path to a CSS file to be included when rendering each diagram
```

…then, that CSS file would be included in each file that you specified to be rendered. However, I'd also add the following caveats:

- The CSS won't affect SVG output, and a warning would be printed to that effect when trying to render SVG (of course, SVG is still experimental until #58 is closed out)
- Any styling that plays with the margins could be problematic; basically it'll be somewhat easy to shoot yourself in the foot.

As to the margins; Phantom doesn't have a "take a screenshot of this region" function, so the way I accomplish this is by removing all margins, inspecting the width/height of the SVG element after it's rendered, and then set Phantom's viewport to that size. If someone were to mess with anything that moved it around on the page, this code would fail, and the image would be offset.

If these seem like reasonable caveats, I'll implement as above. I should have time to take a look at it this week.

**Comment by zdrummond** [comment]
That would be great!

**Comment by naseer** [comment]
+1  - I wanted to use this on the command line primarily - I had to scaffold a webapp to get around it for now :)

**Comment by knsv** [comment]
@fardog, is this issue still active?

**Comment by fardog** [comment]
sorry for the delay on this! just submitted #116 which should resolve this issue.
