### ISSUE TITLE
Gantt and sequence diagram do not render

### ISSUE THREAD

**Issue by renanlecaro** [knsv/mermaid#853]
Thank your for making this awesome library ! I'm working on a google docs integration. I've encountered some difficulties along the way so i'll report them in separate issues.

I cannot render gantt charts and sequence diagrams, while the same code works for flow charts. Here's a test case reproducing the problem :  https://codepen.io/renanlecaro/pen/VJZZge

Am i pulling a version of mermaid that does not have those capabilities ? What am i doing wrong ? 

Cheers

**Comment by renanlecaro** [comment]
Turns out using mermaid.init instead of mermaid.render solved this, so i guess we can close it

**Comment by knsv** [comment]
Great, good luck!
