### ISSUE TITLE
Vertical line overflows into actor boxes

### ISSUE THREAD

**Issue by rajasekaran2003** [knsv/mermaid#855]
![image](https://user-images.githubusercontent.com/1349525/59310222-8e11fe80-8c5a-11e9-94ca-b8c028d7ea76.png)

The vertical lines overflows into the actor boxes.

**Comment by rajasekaran2003** [comment]
.messageLine0 {
                                stroke-width:1.5;
                                stroke-dasharray:"2 2";
                                marker-end:"url(#arrowhead)";
                                stroke:black; }
                            .messageLine1 {
                                stroke-width:1.5;
                                stroke-dasharray:"2 2";
                                stroke:black; }
                            .actor-line { stroke:black; } 
                            .loopLine {
                                stroke-width:1.5; 
                                stroke-dasharray:"2 2";
                                marker-end:"url(#arrowhead)";
                                stroke:black; }
                            .messageText {
                                fill:black;
                                stroke:none;
                                font-family:'trebuchet ms', verdana, arial;
                                font-size:14px;}
                            text.actor {
                                fill:black;
                                stroke:none;
                                font-family: Helvetica;}
                            .labelBox {
                                stroke: none;
                                fill: black;}
                            .note {
                                stroke: black;
                                fill: none;}
                            .actor {
                                stroke: black;
                                fill: none;}
                            #arrowhead {
                                fill:black;}

This is the css that I used

**Comment by knsv** [comment]
Could you make the background of the actor boxes white?

**Comment by rajasekaran2003** [comment]
That does help. Thanks.
