### ISSUE TITLE
new line for message sequence diagram

### ISSUE THREAD

**Issue by rajasekaran2003** [knsv/mermaid#857]
There doesn't seem to be any support for having multi line messages in sequence diagrams.

while notes have multi line support, message lines don't seem to.

**Comment by rajasekaran2003** [comment]
This ticket was added to "TODO" feature list. would be very useful to have this.

**Comment by Dunning-Kruger** [comment]
The "To do" lists do not represent a commitment and are more of an encouragement for the community to work on the issues. 

I'm sure the team would be happy to review a PR for this feature but if no one is willing to do it then it might just fall through the cracks.
