### ISSUE TITLE
#748: Class diagram not working with StackEdit

### ISSUE THREAD

**Issue by rafaelbenavent** [knsv/mermaid#859]
This is related to #748 which I see has been closed and marked as resolved.
However, I just tried StackEdit and the class diagram did not work with it. I'm guessing the issue is more on the Stack Edit side though.

**Comment by DanShai** [comment]
@rafaelbenavent  I think its stackEdit problem in parsing the string
I just tried clas diagram on liveedit and its working:
[live edit](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5DbGFzczAxIDx8LS0gQXZlcnlMb25nQ2xhc3MgOiBDb29sXG5DbGFzczAzICotLSBDbGFzczA0XG5DbGFzczA1IG8tLSBDbGFzczA2XG5DbGFzczA3IC4uIENsYXNzMDhcbkNsYXNzMDkgLS0-IEMyIDogV2hlcmUgYW0gaT9cbkNsYXNzMDkgLS0qIEMzXG5DbGFzczA5IC0tfD4gQ2xhc3MwN1xuQ2xhc3MwNyA6IGVxdWFscygpXG5DbGFzczA3IDogT2JqZWN0W10gZWxlbWVudERhdGFcbkNsYXNzMDEgOiBzaXplKClcbkNsYXNzMDEgOiBpbnQgY2hpbXBcbkNsYXNzMDEgOiBpbnQgZ29yaWxsYVxuQ2xhc3MwOCA8LS0-IEMyOiBDb29sIGxhYmVsIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0l)

in stackedit, try not to leave any new line or space between the 3 quote marks(```) and the text like in here :  #794

**Comment by ThePenguin1140** [comment]
Please add a graph that will reproduce this as well as the version of mermaid you are currently using
