### ISSUE TITLE
CHANGELOG missing updates for all versions since 0.4.0

### ISSUE THREAD

**Issue by gene1wood** [knsv/mermaid#865]
The [CHANGELOG](https://github.com/knsv/mermaid/blob/4bb0da0ce6db97b1c55510fd7d8402d95d17a0f4/CHANGELOG.md) hasn't been updated since version `0.4.0` back in 2015.

I suspect all that need be done here is to look at the diffs for the git tags and write up what was added in each version.

**Comment by knsv** [comment]
✔️
