### ISSUE TITLE
Make Gantt chart date inclusive

### ISSUE THREAD

**Issue by FranklinYu** [knsv/mermaid#868]
This is a feature request.

It would be cool if we can configure our Gantt chart so that the dates are inclusive. For example if there is a task from June 1st to June 3rd I can write `2019-06-01, 2019-06-03`. Currently the ending date is exclusive, so I have to write `2019-06-01, 2019-06-04` which is counter-intuitive.

It can be either a switch in JavaScript API, or some command in the diagram definition (similar to `dateFormat` and `title`).

**Comment by IOrlandoni** [comment]
Hey, @ThePenguin1140. This is done and we can close it, right?

**Comment by FranklinYu** [comment]
Verified with `./dist/index.html`. Looking forward to next release!
