### ISSUE TITLE
Tidy breaks mermaid (linebreaks in <div>)

### ISSUE THREAD

**Issue by StefanKrauth** [knsv/mermaid#87]
Hello,

I'm running my site through tidy. Tidy is breaking mermaid, because it does not respect line breaks in `<div>` elements.

So this code:
```
<div class="mermaid">
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
</div>
```

Gets compressed into this code:

```
<div class="mermaid">sequenceDiagram participant Alice participant Bob Alice->John: Hello John, how are you? loop Healthcheck John->John: Fight against hypochondria end Note right of John: Rational thoughts <br/>prevail... John-->Alice: Great! John->Bob: How about you? Bob-->John: Jolly good!</div>
```

I tried to configure tidy to ignore the class "mermaid" div without success. My second thought was: What about changing mermaid to use semicolons as line separators (or anything else)?

Best Regards,
Stefan

**Comment by knsv** [comment]
An optional ; as a line breaker is possible. Looking at a working prototype. A pity that this missed the recent release though :)

**Comment by StefanKrauth** [comment]
Oh, that's very cool! Thanks. I'll check the next release then.
