### ISSUE TITLE
Angular wrapper for Mermaid. (ng-mermaid)

### ISSUE THREAD

**Issue by rdandnayak** [knsv/mermaid#892]
**Is your feature request related to a problem? Please describe.**
For flowChart. I faced a problem while attaching click event listener inside Angular. I have to provide a function which has a global scope. And that function in turn has to call Angular method. Which is not possible. So i had to abandon using it midway

**Describe the solution you'd like**
You should be able to simply pass data structure as an input & It outputs a graph you need

**Describe alternatives you've considered**
No other way. I had to abandon.

**Additional context**
I had to move to https://github.com/dagrejs/graphlib

**Comment by rdandnayak** [comment]
I am open to contribute in case needed.

**Comment by sagea** [comment]
Have you tried posting a ticket in the ng-mermaid issues board? You might find more luck there.
https://github.com/MSakamaki/ng-mermaid/issues

**Comment by jrvjrv** [comment]
> For flowChart. I faced a problem while attaching click event listener inside Angular. I have to provide a function which has a global scope. And that function in turn has to call Angular method. Which is not possible.

It is possible to wire up a mermaid click event to call into Angular. I created a [demo app](https://github.com/jrvjrv/mac) that has an embedded mermaid graph. The Angular component sets up the function to call. In the demo, clicks on the two nodes in the graph update counters of clicks that are displayed on the page as "moustache" variables.

**Comment by rdandnayak** [comment]
@sagea ng-mermaid works on angular v1.x not on 2.0 onwards

**Comment by rdandnayak** [comment]
@jrvjrv . thanks for workaround. couldnt there be an easy way without polluting global scope. 
Anyways this works perfectly for me. so closing the issue.
