### ISSUE TITLE
Flowchart parsing issue with CRLF

### ISSUE THREAD

**Issue by irqbank** [knsv/mermaid#894]
**Describe the bug**
Mermaid sometimes fails to parse valid flowchart input if new lines are encoded as CRLF instead of LF. This causes unexpected behaviour when using subgraphs, and potentially in other situations too. This may occur when static content served by Windows systems is fed to Mermaid. 

**Potential root cause**
This might be caused by [flow.jison](https://github.com/knsv/mermaid/blob/master/src/diagrams/flowchart/parser/flow.jison#L167) defining `NEWLINE` as `\n` instead of the more platform independent regex `\r?\n`. 

**Workarounds**
* Convert CRLF to LF, either programmatically or on the file system
* Migrate away from Windows

**To Reproduce**
See [codepen](https://codepen.io/anon/pen/jgMjqb?editors=0010) and snippet below. The last statement results in a parsing error in the console.

```
const dotest = (test, input) => {
  try {
    mermaid.render(test, input, () => {}); 
  } catch (err) { 
    console.error("Error in %s:\n\n%s", test, err);
  }
};
mermaid.initialize({startOnLoad: false});
dotest("Test1", "graph LR\nsubgraph\nA --> B\nend");
dotest("Test2", "graph LR\r\nsubgraph\r\nA --> B\r\nend");
```

**Expected behavior**
No errors are written to the console.

**Desktop (please complete the following information):**
 - Mermaid: 8.2.3
 - OS: Windows 7
 - Browser: Google Chrome
 - Version: 75.0.3770.142

**Comment by GDFaber** [comment]
This seems to me like a good start for someone who is new to the project. I'd like to give it a try if that's ok for you.

**Comment by GDFaber** [comment]
My PR is at #957.

**Comment by nothingismagick** [comment]
Seems to me that some test cases would be good to validate that it really
works.

But otherwise: nice!

💯

**Comment by GDFaber** [comment]
Ah, found the specs file. So I can put the tests in there to be executed automatically, right? Should they be removed from dist/index.html afterwards?

**Comment by Dunning-Kruger** [comment]
Thank you everyone for your contributions!

**Comment by Dunning-Kruger** [comment]
Thank you everyone for your contributions!
