### ISSUE TITLE
Missing tags: 8.0.0, 8.2.2, 8.2.3

### ISSUE THREAD

**Issue by stanhu** [knsv/mermaid#896]
Would you mind pushing up tags so we can have the right history? It's hard to bisect changes (e.g. https://github.com/knsv/mermaid/issues/895).

**Comment by knsv** [comment]
8.2.2 and 8.2.3 is pushed. 8.0.0 is not and I do not think it was not tagged.

**Comment by stanhu** [comment]
Thank you!
