### ISSUE TITLE
Subgraph Title Positioning

### ISSUE THREAD

**Issue by spbert29** [knsv/mermaid#899]
Hello,

My Process has got a lot of Subprocess - when i draw the subprocess the title of the subgraph gets randomly positioned into the subgraph frame (centered or top)

![image](https://user-images.githubusercontent.com/42182294/62195866-2c7a3080-b37d-11e9-9644-b595370d8d6e.png)

The best thing in my case would be to get it above the subgraph. How to do this?

Thanks

Edit: I'm using Version 8.2.3

**Comment by GDFaber** [comment]
I tried to reproduce this out of some kind of minimal example in the live editor, but had no luck. Can you provide the script for your flowchart or some minimal example which shows the problem?

**Comment by spbert29** [comment]
Actually the [example ](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbjE3MDAwKFByb3plc3M6IDE3MDAgLSBNb25hdHNhYnNjaGx1c3MgQ29udHJvbGxpbmcgZmE6ZmEtY2hlY2sgKS0tPjE3MDAxNzAxMChLb250cm9sbGUgUmVjaG51bmdzYWJzY2hsdXNzKVxuMTcwMDE3MDEwKDE3MDEwIC0gS29udHJvbGxlIFJlY2hudW5nc2Fic2NobHVzcyktLT4xNzAwMTcwMjBcbjE3MDAxNzAyMFsxNzAyMCAtIEtvbnRyb2xsZSBhYmdlc2NobG9zc2VuZSBQQSdzXS0tPjE3MDAxNzAzMFxuMTcwMDE3MDMwWzE3MDMwIC0gQWJzY2hsdXNzIE1BV0ldLS0-MTcwMDE3MDQwXG4xNzAwMTcwNDBbMTcwNDAgLSBBYnNjaGx1c3MgUmVjaG51bmdzZWluZ2FuZ10tLT4xNzAwMTcwNTBcbjE3MDAxNzA1MCgxNzA1MCAtIFN0YW5kYXJka29zdGVua2Fsa3VsYXRpb24gQ08pLS0-MTcwMDE3MDYwXG4xNzAwMTcwNjB7MTcwNjAgLSBTdGFydCBQcsO8ZnVuZ2VuIER1cmNoc2Nobml0dHNwcmVpc2V9LS0-MTcwMDE3MDYxXG4xNzAwMTcwNjFbMTcwNjEgLSBQcsO8ZnVuZ2VuIER1cmNoc2Nobml0dHNwcmVpc2VdLS0-ZWRiMTcyNDQ1YzE3MTEwW05hY2hrYWxrdWxhdGlvbiBDT11cbnN1YmdyYXBoIDlkNDczOTQzMzVlYzBkMTFhMGRhMzY3NGYxZjg4YzU4W1wiU3ViUHJvemVzczoxNzAxIC0gTW9uYXRzYWJzY2hsdXNzIFRlaWxwcm96ZXNzIERQLUJpbGR1bmdcIl1cbmVkYjE3MjQ0NWMxNzExMCgxNzExMCAtIE5hY2hrYWxrdWxhdGlvbiBDTyktLT5lZGIxNzI0NDVjMTcxMjBcbmVkYjE3MjQ0NWMxNzEyMCgxNzEyMCAtIEtvbnRyb2xsZSBEdXJjaHNjaG5pdHRzcHJlaXNlKVxuZW5kXG5jbGFzcyAxNzAwMTcwNjEsZWRiMTcyNDQ1YzE3MTEwLGVkYjE3MjQ0NWMxNzEyMCwgYWxsXG5lZGIxNzI0NDVjMTcxMjAtLT4xNzAwMTcwNjIoMTcwNjIgLSBFbmRlIFByw7xmdW5nZW4gU3RhcnQgUHLDvGZ1bmdlbiBEdXJjaHNjaG5pdHRzcHJlaXNlKVxuMTcwMDE3MDYyWzE3MDYyIC0gRW5kZSBQcsO8ZnVuZ2VuIFN0YXJ0IFByw7xmdW5nZW4gRHVyY2hzY2huaXR0c3ByZWlzZV0tLT4xNzAwMTcwODBcbjE3MDAxNzA4MFsxNzA4MCAtIFZlcnNvcmd1bmcgQmV0cmllYnNidWNoaGFsdHVuZ10tLT4xNzAwMTcwOTBcbjE3MDAxNzA5MFsxNzA5MCAtIFVlYmVyZ2FiZSBCZXRyaWVic2J1Y2hoYWx0dW5nXS0tPjE3MDAxNzA5OVxuMTcwMDE3MDk5WzE3MDk5IC0gQXJjaGl2aWVydW5nIFdvcmtmbG93XVxuY2xhc3NEZWYgYWxsIHN0cm9rZS13aWR0aDozcHhcbmNsYXNzRGVmIHByb2Nlc3NIZWFkIGZpbGw6Izg4ODg4OCxjb2xvcjp3aGl0ZSxmb250LXdlaWdodDpib2xkLHN0cm9rZS13aWR0aDozcHgsc3Ryb2tlOiMwMDFmM2ZcbmNsYXNzRGVmIHdmbXN0YXR1czAgc3Ryb2tlOiMyRUNDNDAsZmlsbDojRkZGRkZGLHdmbXN0YXR1czAgZmlsbC1vcGFjaXR5OjAuNSxzdHJva2Utb3BhY2l0eTowLjVcbmNsYXNzRGVmIHdmbXN0YXR1czEgc3Ryb2tlOiMyRUNDNDAsZmlsbDojRkZGRkZGLHN0cm9rZS1kYXNoYXJyYXk6NSw1LGFuaW1hdGlvbjogZGFzaCAxODAwcyBsaW5lYXJcbmNsYXNzRGVmIHdmbXN0YXR1czIgc3Ryb2tlOiNGRjg1MUIsZmlsbDojRkY4NTFCLHN0cm9rZS13aWR0aDozcHgsZmlsbC1vcGFjaXR5OjAuNFxuY2xhc3NEZWYgd2Ztc3RhdHVzMyBzdHJva2U6IzAwNzREOSxmaWxsOiMwMDc0RDksc3Ryb2tlLXdpZHRoOjNweCxmaWxsLW9wYWNpdHk6MC40XG5jbGFzc0RlZiB3Zm1zdGF0dXM4IHN0cm9rZTojRkY0MTM2LGZpbGw6I0ZGNDEzNixzdHJva2Utd2lkdGg6M3B4LGZpbGwtb3BhY2l0eTowLjRcbmNsYXNzRGVmIHdmbXN0YXR1czkgZmlsbDojMkVDQzQwLGZpbGwtb3BhY2l0eTowLjMsc3Ryb2tlOiMyRUNDNDAsc3Ryb2tlLXdpZHRoOjNweFxuY2xhc3MgMTcwMDAgcHJvY2Vzc0hlYWRcbmNsYXNzIDE3MDAxNzAxMCwxNzAwMTcwMjAsMTcwMDE3MDMwLDE3MDAxNzA0MCwxNzAwMTcwNTAsMTcwMDE3MDYwLGVkYjE3MjQ0NWMxNzEyMCwxNzAwMTcwNjIsMTcwMDE3MDgwLDE3MDAxNzA5MCwxNzAwMTcwOTkgYWxsIiwibWVybWFpZCI6eyJ0aGVtZSI6ImZvcmVzdCJ9fQ/error/RmFpbGVkIHRvIGV4ZWN1dGUgJ3F1ZXJ5U2VsZWN0b3JBbGwnIG9uICdEb2N1bWVudCc6ICcjbWVybWFpZC0xNTY0NTY5NzQzNDUzICM5ZDQ3Mzk0MzM1ZWMwZDExYTBkYTM2NzRmMWY4OGM1OCByZWN0JyBpcyBub3QgYSB2YWxpZCBzZWxlY3Rvci4)is not rendering in the Live Editor - on my dev Environment its no problem

**Comment by Dunning-Kruger** [comment]
Hey, note that we still have not been able to reproduce the issue. 
If you can, please provide a live editor sample that shows the issue.

**Comment by spbert29** [comment]
As i wrote - in my case the ID naming of the subgraph resolved that issue.

I cannot reproduce it in the live editor - feel free to close this issue.
