### ISSUE TITLE
subgraph fails to render when subgraph ID starts with a number

### ISSUE THREAD

**Issue by spbert29** [knsv/mermaid#900]
**Describe the bug**
A subgraph id cannot start with a Number[0-9] - it needs to start with a letter [a-z][A-Z]

**To Reproduce**
[Working](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5zdWJncmFwaCB0ZXN0XG5BXG5lbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)
[Not Working](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5zdWJncmFwaCAxdGVzdFxuQVxuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/RmFpbGVkIHRvIGV4ZWN1dGUgJ3F1ZXJ5U2VsZWN0b3JBbGwnIG9uICdEb2N1bWVudCc6ICcjbWVybWFpZC0xNTY0NTcxNDMyMzE1ICMxdGVzdCByZWN0JyBpcyBub3QgYSB2YWxpZCBzZWxlY3Rvci4)
[Working Workaround](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5zdWJncmFwaCBcIjF0ZXN0XCJcbkFcbmVuZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)
[Not Working Workaround](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5zdWJncmFwaCBcIjF0ZXN0XCJbaGVsbG9dXG5BXG5lbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19/error/UGFyc2UgZXJyb3Igb24gbGluZSA3OgouLi5hcl1zdWJncmFwaCAiMXRlc3QiW2hlbGxvXUFlbmQKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLV4KRXhwZWN0aW5nICdTRU1JJywgJ05FV0xJTkUnLCAnRU9GJywgZ290ICdTUVMn)

**Expected behavior**
subgraph 1test
A-->B
end

should render

**Desktop (please complete the following information):**
 - Version 8.2.3

**Additional context**

**Comment by GDFaber** [comment]
It works if you set the subgraph title  in quotes:

`subgraph "1test"`
`A-->B`
`end`

**Comment by spbert29** [comment]
If i quote it and want to add another text it fails:
subgraph "1test"[hello]
A-->B
end

**Comment by GDFaber** [comment]
Ah sorry, when I read it I missed that you want an ID to be named that way, so it's not about the title.
