### ISSUE TITLE
chore: Split flow.spec.js into several files

### ISSUE THREAD

**Issue by knsv** [knsv/mermaid#906]
The file has grown to large and needs to be split into several files

**Comment by PatrickRoumanoff** [comment]
There are 156 test in the spec file, would splitting the files according to those categories be a good fit?


|category|count|
|-----|---|
arrow | 22|
comment | 9
edge | 32
flow (default) | 10
interaction | 4
line | 12
singlenode | 13
style | 19
subgraph | 8
text | 27
total | 156

**Comment by christopherkade** [comment]
Hi @knsv, if this issue is still up for grabs, I'd love to help out, I could use Patrick's input to divide the file.
