### ISSUE TITLE
Node text getting clipped

### ISSUE THREAD

**Issue by rpagliuca** [knsv/mermaid#907]
**Describe the bug**
When I open the "homepage" of the Mermaid Live Editor, two of the nodes of the demo flowchart have their contents clipped.

**To Reproduce**
1. Go to https://mermaidjs.github.io/mermaid-live-editor
2. Look for the decision node "Let me think" inside the "Preview" panel
3. You should see that the final letter "k" is clipped
4. Look for the node "Car" inside the "Preview" panel
5. You should see that the final letter "r" is clipped

**Expected behavior**
The whole content (all the letters of the phrase "Let me think" and "Car") of the nodes should be visible

**Screenshots**
![2019-08-12-102555_1876x915_scrot](https://user-images.githubusercontent.com/963751/62868268-9c78a700-bceb-11e9-81ff-66621c7abdc0.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 9
 - Browser: Google Chrome 
 - Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by knsv** [comment]
Thank for taking your time to point that out... It's a font thing. The font used to render the graph as a svg needs to match the font used when the graph is presented on the page.

**Comment by knsv** [comment]
This was really an issue with the editor. Fixed it there and closing this one.
