### ISSUE TITLE
disable auto render

### ISSUE THREAD

**Issue by timelyportfolio** [knsv/mermaid#91]
I see in these [lines of code](https://github.com/knsv/mermaid/blob/master/src/main.js#L98-L109) where auto render can be disabled.  Would it be possible to handle this within the `mermaid` namespace as a config rather than `global`?

By the way, extremely well done, so well that we are attempting to wrap it in `R` as a [`htmlwidget`](http://htmlwidgets.org).  Hope to have more input and at least tests as we work through the process.

Thanks again.

**Comment by knsv** [comment]
Hello!

Thanks for the kind words!

It is possible to turn off auto rendering. To do  so, create a config object named mermaid_config with the property startOnLoad set to false.

Ex:
```
var mermaid_config = {
   startOnLoad: false
};
```
If I understand you correctly you want this to be with in the mermaid namespace something like:
```
mermaid.startOnLoad = false;
```
That makes sense. Think the config came to be before the mermaid namespace and was never moved.

**Comment by knsv** [comment]
Cool with the widget! Hope this helps.

Added the option to disable auto rendering via the mermaid namespace as below. This is in master but not released yet.
```
mermaid.startOnLoad = false;
```

**Comment by timelyportfolio** [comment]
Your interpretation is correct, and I hesitated to file issue since the `startOnLoad` looked temporary.  The code is a little whacky with the widget binding/infrastructure, but here are the applicable lines for which the `startOnLoad` is important for me.  This is to make the `SVG` quasi-"responsive" to fit the parent container, since widgets load in multiple contexts.

- disable auto render [lines](https://github.com/rich-iannone/DiagrammeR/blob/master/inst/htmlwidgets/DiagrammeR.js#L15-L23)
- make responsive [lines](https://github.com/rich-iannone/DiagrammeR/blob/master/inst/htmlwidgets/DiagrammeR.js#L52-L59)


While I was typing, just noticed your response and change, thanks so much.  Please let me know if I can help on any way with development or testing.
