### ISSUE TITLE
version number on npm does not match github release number

### ISSUE THREAD

**Issue by jrvjrv** [knsv/mermaid#913]
**Describe the bug**
Version on npm is 8.2.5. github release is 8.2.4

**To Reproduce**
Add mermaid package using npm install mermaid
View version in package.json

**Expected behavior**
It's not exactly harmful, but it would be nice if the versions matched.

**Comment by knsv** [comment]
Added the release in github. Will make sure 8.2.6 will match versions between github and npm 😃
