### ISSUE TITLE
Styling with Classes is Broken when id of node starts with a digit

### ISSUE THREAD

**Issue by spbert29** [knsv/mermaid#914]
**Describe the bug**
Styling with Classes is Broken

**To Reproduce**
[Look Here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbjc0MDkwW1RFU1RdXG5jbGFzc0RlZiBwcm9jZXNzSGVhZCBmaWxsOiM4ODg4ODgsY29sb3I6d2hpdGUsZm9udC13ZWlnaHQ6Ym9sZCxzdHJva2Utd2lkdGg6M3B4LHN0cm9rZTojMDAxZjNmXG5jbGFzcyA3NDA5MCBwcm9jZXNzSGVhZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

**Screenshots**
Should Look Like This
![image](https://user-images.githubusercontent.com/42182294/63749931-c06fe700-c8ac-11e9-9fc5-bb50774d61b6.png)

**Additional context**
Broken Since 8.2.4 and isnt working in 8.2.5 either 
Last working Version 8.2.3

**Comment by knsv** [comment]
This has to do with that the node is starting with a number.

**Comment by spbert29** [comment]
Indeed - i will work around with adding a letter.

**Comment by knsv** [comment]
Released in 8.2.6
