### ISSUE TITLE
labels in subgraphs cannot be numbers anymore in 8.2.5

### ISSUE THREAD

**Issue by rajasekaran2003** [knsv/mermaid#918]
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbnN1YmdyYXBoIG9uZVxuMS0tPiAyXG5lbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/Q2Fubm90IHNldCBwcm9wZXJ0eSAnbGFiZWwnIG9mIHVuZGVmaW5lZA

this used to work in 8.2.3 but is broken in the latest version.

**Comment by knsv** [comment]
I seems to be connected to subgraphs as ```graph TB;1-->2``` works just fine.

**Comment by knsv** [comment]
Released in 8.2.6

**Comment by rajasekaran2003** [comment]
Thanks !!
