### ISSUE TITLE
Callback JS Function doesnt Trigger when NodeID starts with number

### ISSUE THREAD

**Issue by spbert29** [knsv/mermaid#922]
**Describe the bug**
Callback JS Function doesnt Trigger when NodeID starts with number

**To Reproduce**
This doesnt work. The Node is klickable but it does nothing
![image](https://user-images.githubusercontent.com/42182294/64117557-c4f93b80-cd95-11e9-9994-e618149b1176.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/42182294/64117663-0b4e9a80-cd96-11e9-9ac3-c85f29ea32ee.png)

This works as it should

**Additional context**
8.2.6

**Comment by knsv** [comment]
Thanks for reporting. Will take a look.

**Comment by knsv** [comment]
This will be included in v8.2.7
