### ISSUE TITLE
Style font color only working in classes not in style Tag

### ISSUE THREAD

**Issue by spbert29** [knsv/mermaid#926]
**Describe the bug**
Style font color only working in classes not in style Tag

**To Reproduce**
Look The font color here:
[Link](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5zdHlsZSBCIGZpbGw6cmVkLGNvbG9yOndoaXRlXG5jbGFzc0RlZiB0ZXN0IGZpbGw6bGlnaHRibHVlLGNvbG9yOmdyZWVuLHN0cm9rZTojRkY5RTJDLGZvbnQtd2VpZ2h0OmJvbGRcbmNsYXNzIEEgdGVzdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

The class is working as expected the style tag is not

**Expected behavior**
Should work in both ways 

**Screenshots**
![image](https://user-images.githubusercontent.com/42182294/64232904-31d61800-cef3-11e9-975f-a711296e5fbd.png)

**Additional context**
I'm not sure but this was working in <8.2.3 in a Version i cannot remember

**Comment by knsv** [comment]
Good finding and thanks for reporting.

**Comment by knsv** [comment]
This will be released on 8.2.7
