### ISSUE TITLE
Possible to change the style of the axis dates in Gantt charts?

### ISSUE THREAD

**Issue by slmingol** [knsv/mermaid#934]
I saw that it was possible to change the axis date format via `axisFormat %m/%d` but is there any way to change the font details? Specifically the color?

I find it hard too read these faint colors:

![image](https://user-images.githubusercontent.com/15072/64915465-6e94e100-d735-11e9-94f3-da1950ec891f.png)

**Comment by Dunning-Kruger** [comment]
Now tracked on #995
