### ISSUE TITLE
Flowchart parse error

### ISSUE THREAD

**Issue by maniuf** [knsv/mermaid#937]
**Describe the bug**
Marmaid  fails to parse the node with name _node0TB_ in flowchart.
It seems that the error occurs then the node identifier ends with a character sequence being defined as a keyword in parser grammar (e.g. direction LR, RL, BT, TB or class, style, end) proceeded by a non-letter character (e.g. a digit or an underscore).

**To Reproduce**
Create simple graph containing node named _node1TB_.
`graph LR;
  node1TB`
See in [Marmaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG4gIG5vZGUxVEIiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgpncmFwaCBURDsgIG5vZGUxVEIKLS0tLS0tLS0tLS0tLS0tLV4KRXhwZWN0aW5nICdTRU1JJywgJ05FV0xJTkUnLCAnU1BBQ0UnLCAnRU9GJywgJ1RBR0VORCcsICdET1dOJywgJ1NRUycsICdTVFlMRV9TRVBBUkFUT1InLCAnUFMnLCAnKC0nLCAnRElBTU9ORF9TVEFSVCcsICdUUkFQU1RBUlQnLCAnSU5WVFJBUFNUQVJUJywgJy0tJywgJ0FSUk9XX1BPSU5UJywgJ1NUQVJUX0RPVUJMRV9BUlJPV19QT0lOVCcsICdBUlJPV19DSVJDTEUnLCAnU1RBUlRfRE9VQkxFX0FSUk9XX0NJUkNMRScsICdBUlJPV19DUk9TUycsICdTVEFSVF9ET1VCTEVfQVJST1dfQ1JPU1MnLCAnQVJST1dfT1BFTicsICctLicsICdET1RURURfQVJST1dfUE9JTlQnLCAnU1RBUlRfRE9VQkxFX0RPVFRFRF9BUlJPV19QT0lOVCcsICdET1RURURfQVJST1dfQ0lSQ0xFJywgJ1NUQVJUX0RPVUJMRV9ET1RURURfQVJST1dfQ0lSQ0xFJywgJ0RPVFRFRF9BUlJPV19DUk9TUycsICdTVEFSVF9ET1VCTEVfRE9UVEVEX0FSUk9XX0NST1NTJywgJ0RPVFRFRF9BUlJPV19PUEVOJywgJz09JywgJ1RISUNLX0FSUk9XX1BPSU5UJywgJ1NUQVJUX0RPVUJMRV9USElDS19BUlJPV19QT0lOVCcsICdUSElDS19BUlJPV19DSVJDTEUnLCAnU1RBUlRfRE9VQkxFX1RISUNLX0FSUk9XX0NJUkNMRScsICdUSElDS19BUlJPV19DUk9TUycsICdTVEFSVF9ET1VCTEVfVEhJQ0tfQVJST1dfQ1JPU1MnLCAnVEhJQ0tfQVJST1dfT1BFTicsICdET1VCTEVfQVJST1dfUE9JTlQnLCAnRE9VQkxFX0FSUk9XX0NJUkNMRScsICdET1VCTEVfQVJST1dfQ1JPU1MnLCAnRE9VQkxFX0RPVFRFRF9BUlJPV19QT0lOVCcsICdET1VCTEVfRE9UVEVEX0FSUk9XX0NJUkNMRScsICdET1VCTEVfRE9UVEVEX0FSUk9XX0NST1NTJywgJ0RPVUJMRV9USElDS19BUlJPV19QT0lOVCcsICdET1VCTEVfVEhJQ0tfQVJST1dfQ0lSQ0xFJywgJ0RPVUJMRV9USElDS19BUlJPV19DUk9TUycsICdOVU0nLCAnQ09NTUEnLCAnQUxQSEEnLCAnQ09MT04nLCAnTUlOVVMnLCAnQlJLVCcsICdET1QnLCAnUFVOQ1RVQVRJT04nLCAnVU5JQ09ERV9URVhUJywgJ1BMVVMnLCAnRVFVQUxTJywgJ01VTFQnLCAnVU5ERVJTQ09SRScsIGdvdCAnRElSJw)

**Expected behavior**
Should render single node graph.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/7712426/65148726-130e7000-da21-11e9-9d4a-8ef11eb107d6.png)

**Additional context**
Affected version v8.2.6. Not tested with older releases.

**Comment by knsv** [comment]
This should be fixed with 8.3.1. Please reopen if you cant verify this.
