### ISSUE TITLE
graph LR makes TD

### ISSUE THREAD

**Issue by nothingismagick** [knsv/mermaid#941]
**Describe the bug**
`graph LR` making TD...

**To Reproduce**
1. Go to https://knsv.github.io/mermaid/#/flowchart

**Expected behavior**
should be horizontal

**Screenshots**
![Screen Shot 2019-09-19 at 21 51 46](https://user-images.githubusercontent.com/35242872/65276314-bd70bb00-db27-11e9-9962-cb74e1df42d1.png)

**Desktop (please complete the following information):**
Also noticed in latest 8.3.0 on brave and chrome (MacOS)

**Additional context**
Seems just plain wrong.

**Comment by knsv** [comment]
Ha ha, right you are. Thanks for reporting.

**Comment by nothingismagick** [comment]
Can confirm that this seems resolved in 8.3.1
