### ISSUE TITLE
Unable to use # in sequence diagram

### ISSUE THREAD

**Issue by Wh1terat** [knsv/mermaid#947]
**Describe the bug**
I'm trying to draw a sequence diagram in which the # character is a regular occurrence - however mermaid strips the hash and the following text.   

**To Reproduce**
```
sequenceDiagram
Alice->Bob: Hey bob, you #suck
Bob->Alice: Huh? I what?
```

**Expected behavior**
I would expect the whole message including the # to be visible in the output

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by GDFaber** [comment]
Hi, it works if you use #35; instead of just # in your text:
```
sequenceDiagram
Alice->Bob: Hey bob, you #35;suck
Bob->Alice: Huh? I what?
```

**Comment by Wh1terat** [comment]
Perfect, thank you @GDFaber
