### ISSUE TITLE
Class diagram: Add support for cardinalities

### ISSUE THREAD

**Issue by chris579** [knsv/mermaid#949]
In UML diagrams the cardinalities are written next to the class they belong to.

![](https://upload.wikimedia.org/wikipedia/commons/d/d0/Aggregation-Composition3.png)

This is not possible in mermaid currently. A workaround for this would be to write the cardinalities in the label of arrow. 

```mermaid
classDiagram
Class01 *-- AveryLongClass : 1 : 1..n
```
![image](https://user-images.githubusercontent.com/6552521/65393463-2737d180-dd81-11e9-8ab3-81b0525d326b.png)

However, this workaround is ambiguous as you need to define which part belongs to which class. This makes reading the cardinalities in a fast way impossible. 

Given the fact that it's possible to use aggregations and compositions arrows there should be support to define the cardinalities. The syntax for this could look like this, where the seperator is another colon

```mermaid
Class01 *-- AveryLongClass : 1 : 1..n
```

or with any other seperator char, like a pipe

```mermaid
Class01 *-- AveryLongClass : 1 | 1..n
```

If there is no seperator char it should be placed as an ordinary label.

**Comment by Dunning-Kruger** [comment]
This was released in 8.4.0
