### ISSUE TITLE
Error with >9 linkStyles

### ISSUE THREAD

**Issue by vurted** [knsv/mermaid#95]
Error in the parser if try to define a linkStyle with an index of > 9.

e.g 
linkStyle 10 stroke-width:1px

 Uncaught Error: Parse error on line 51:
...#00728F;linkStyle 11 stroke:#00728F;str
----------------------^
Expecting 'SPACE', got 'NUM'
mermaid.full.js:14528 parseError
mermaid.full.js:14593 
parsemermaid.full.js:13230 
exports.getClassesmermaid.full.js:16455 
initmermaid.full.js:16517 
global.mermaid.initmain.js:139

**Comment by knsv** [comment]
Thanks for reporting this!

I can replicate the problem and will work on a fix.

**Comment by knsv** [comment]
Fixed with release 0.3.2

**Comment by vurted** [comment]
Thanks! Now working :)
