### ISSUE TITLE
mermaid.parse API doesn't return anything. Is this intentional?

### ISSUE THREAD

**Issue by volkanunsal** [knsv/mermaid#955]
I'm trying to use the markup generated by Mermaid in Webpack, but I discovered that `parse` function doesn't return anything. Is this intentional? 

```js
> mermaid.parse(definition)
undefined
```

**Comment by nothingismagick** [comment]
what framework are you using? I found for example in Vue, that I had to use this.$nextTick for my API injection - and since API usage is an append action, I had to null out the data object that it was supposed to inject into BEFORE I injected

**Comment by volkanunsal** [comment]
I'm just using the library API. I want to get the markup generated for a source definition and return it in the Webpack loader.

**Comment by volkanunsal** [comment]
Here is the issue:

https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L354

**Comment by Dunning-Kruger** [comment]
Have you considered using the "render" function which gives you the svg result?
These and some other basic usage examples can be found [here](http://knsv.github.io/mermaid/#/usage).

**Comment by nothingismagick** [comment]
Yeah, render is where its at.
```
this.graph = this.$mermaid.render('mermaid', pattern)
```

**Comment by nothingismagick** [comment]
That example is really just the tip of the iceberg, there's a bunch of configuration stuff you have to have and I haven't shown any of my state or real display pipeline. But the renderAPI is really powerful. Having a dynamic mermaid renderer really saved my project.

**Comment by nothingismagick** [comment]
BUT one little tip: IF you are using webpack, that means you probably are setting the <base> value in the head of your html. Then you definitely want to set this (or it won't even render in MacOS / iOS):

```
mermaid.initialize({
  arrowMarkerAbsolute: true
})
```

**Comment by volkanunsal** [comment]
Aha, very cool. Thanks for the insight.
