### ISSUE TITLE
Class diagram: Add support for annotations

### ISSUE THREAD

**Issue by chris579** [knsv/mermaid#963]
In UML diagrams, types are often decorated with annotations. 

![](https://www.uml-diagrams.org/class-diagrams/class-interface-compartments.png)
![](https://www.ibm.com/support/knowledgecenter/SS4JE2_7.5.5/com.ibm.xtools.modeler.doc/images/enumeration.gif)

Same goes for all kinds of annotations. It makes easy to understand the purpose of the described type. This is not possible atm. Having annotations support would make the class diagram a lot more useful and could make it a replacement for other diagram tools.

**Comment by gaui** [comment]
Yes this would be very appreciated, so it's possible to mark an entity as an interface.

**Comment by chris579** [comment]
I would give this issue a try and try to implement it. PR coming soon™

**Comment by Dunning-Kruger** [comment]
@chris579 Don't forget to drop by [our slack](https://join.slack.com/t/mermaid-talk/shared_invite/enQtNzc4NDIyNzk4OTAyLWVhYjQxOTI2OTg4YmE1ZmJkY2Y4MTU3ODliYmIwOTY3NDJlYjA0YjIyZTdkMDMyZTUwOGI0NjEzYmEwODcwOTE) if you need any help!

**Comment by knsv** [comment]
Looking forward to the PR @chris579. A heads up, @ashishjain0512 is also working with class diagrams. You two might want to sync up to avoid merging conflicts.

**Comment by chris579** [comment]
Regarding the syntax I came up with some ideas. What would you prefer?

In front of class definitions. Not my favorite solution because when using multiple ones (which should be possible) the line will get very long.
```
class <<interface>> <<injected>> MyInterface
class <<interface>> <<injected>> MyInterface {
}
```

Only for bracket syntax
```
class MyInterface {
<<interface>>
<<injected>>
}
```


As a separate statement that allows separate definitions to make things look cleaner.
```
class MyInterface
<<interface>> MyInterface
<<injected>> MyInterface
```
I would favor for the last solution. Looks straight forward for me.
