### ISSUE TITLE
Clipping in documentation

### ISSUE THREAD

**Issue by bjowes** [knsv/mermaid#97]
When looking at the flowchart page of the documentation
http://knsv.github.io/mermaid/flowchart.html
in Firefox 34.0.5, I notice that the generated charts are clipped in the right hand side. For some it looks like a few pixels, but for the asymmetric shape, it looks wrong since it looses too much on the right hand side of the shape.
Some issue with the margins perhaps?

**Comment by knsv** [comment]
Thanks for pointing this out. As od v 0.3.3 the clipping has been eliminated.
