### ISSUE TITLE
Not able to use mermaid properly in Angular 7 along with ngx-markdown

### ISSUE THREAD

**Issue by arora-kushal** [knsv/mermaid#979]
**Describe the bug**
Issue 1: Not able to use this library properly with Angular. As you can see in the stackblitz, correct HTML is getting formed but diagram 1 is not generated.
Issue 2: Diagram 2 is getting generated but incorrect (see screenshot below)

**To Reproduce**
This is not reproducable in stackblitz. Clone this project and run this on your local computer.

1. https://stackblitz.com/edit/angular-markdown-mermaid

**Expected behavior**
Diagrams should be visible but only mermaid text is visible.

**Screenshots**
Expected Diagram: 
https://mermaidjs.github.io/#/sequenceDiagram
Output Diagram:
![image](https://user-images.githubusercontent.com/8510977/66318750-85e07c00-e939-11e9-8925-8eecbef983f8.png)

**Additional context**
I have also tried to write
`import * as mermaid from 'mermaid';`
instead of
`import mermaid from 'mermaid';`
but this is not working as well. 

Please suggest.

**Comment by knsv** [comment]
Add mermaid.init(); below initialize to get the rendering going. Then it should work fine.

**Comment by Dunning-Kruger** [comment]
Sample [here](https://stackblitz.com/edit/angular-markdown-mermaid-7jfvvh?file=src/app/app.component.ts).
