### ISSUE TITLE
Issue with mermaid along with ngx-markdown

### ISSUE THREAD

**Issue by arora-kushal** [knsv/mermaid#980]
This is related to bug: https://github.com/knsv/mermaid/issues/979

Issue #1: Its not working in Firefox.

![image](https://user-images.githubusercontent.com/8510977/66333242-204db900-e954-11e9-98fc-44b789e7fb55.png)

Issue #2: Please see the output of chrome. Why these 2 diagrams are different given the same sequence code.

![image](https://user-images.githubusercontent.com/8510977/66333085-cfd65b80-e953-11e9-8d5a-a47b682ed710.png)

**Comment by Dunning-Kruger** [comment]
Hey, apologies if I closed your other issue prematurely. 

For your second issue, by removing the call to `mermaid.initi()`, I noted that you're not generating the same sequence code. 
![image](https://user-images.githubusercontent.com/1564825/66336065-5cf4c280-e90a-11e9-8cee-687f3729f406.png)

**Comment by Dunning-Kruger** [comment]
As for your first issue, I suspect the markup is being included in the page after mermaid has already run. In which case, you should be able to fix it by changing the event you're using to initialize mermaid.

As I have no experience with angular I could not say which are the other options.

**Comment by arora-kushal** [comment]
Thanks @Dunning-Kruger for your help.. I have fixed this after reading your suggestions.

The solution: 
Instead of using markdown like this
`<markdown [src]="'path/to/file.md'"></markdown>`
I have used this like
`<div markdown [src]="'path/to/file.md'" (load)="onLoad($event)" ></div>`

and in TS file

```
onLoad(event) {
    mermaid.init();
    mermaid.initialize({
      securityLevel: 'loose'
    });
  }

```
