### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by mike-ward** [knsv/mermaid#99]
<AshamedForAsking>

Doesn't work in Internet Explorer. Any chance this will happen?

</AshamedForAsking>

**Comment by knsv** [comment]
I have tested a bit and sequenceDiagrams works but not the flowchart. Will investigate further.

**Comment by mike-ward** [comment]
That's good to hear. I started with the flowcharts and then quit. I'm no fan of IE. I use the web control in some desktop applications, which is why I'm interested in IE.

**Comment by mike-ward** [comment]
Update?

**Comment by knsv** [comment]
Yes! Sorry about the delay. I have had some issues to find an internet explorer to test. Who could have believed that a couple of years ago....

Anyways now with an Internet Explorer in place I found the underlying issue. It was a bug in dagre-d3 that the project had already resolved. I will include the new version in next mermaid release which will resolve this issue!

**Comment by mike-ward** [comment]
Awesome cool!

**Comment by knsv** [comment]
With release 0.3.5 the graph renders!

I have some styling issues remaining with html labels. If you run into that set htmlLabels to false in the mermaid config. Will close now, reopen if the problem lingers... :)

**Comment by mike-ward** [comment]
When I go to: http://knsv.github.io/mermaid/demos.html

using IE 11 I still don't see any charts.

**Comment by knsv** [comment]
Just got around to update the docs. Try now.

/Knut
sön 15 feb 2015 kl. 19:49 skrev Mike Ward <notifications@github.com (mailto:notifications@github.com)>:

**Comment by mike-ward** [comment]
Much better now. I'm seeing empty labels however. Is that the styling issue you mentioned?

**Comment by knsv** [comment]
Try adding something like this:
var mermaid_config = {
startOnLoad:true,
htmlLabels:false
}  

--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by gerritgriebel** [comment]
With IE 11 (11.0.9600.18349) http://knsv.github.io/mermaid/#flowcharts-basic-syntax shows only empty boxes. No labels on boxes and edges. http://knsv.github.io/mermaid/#sequence-diagrams look fine, though. Above htmlLabels:false didn't work for me either.

**Comment by derberg** [comment]
I have exactly the same issue in IE 11 as @gerritgriebel

**Comment by jaseeey** [comment]
I am able to replicate this issue in IE11. Setting _htmlLabels_ to _false_ does result in the flowchart displaying correctly, however, this is an issue because I am using HTML in the labels. Is there any further information to what might be causing this in IE?

**Comment by fengzhihaostar** [comment]
你们的问题解决了吗？  我也出现了这种情况，  加这个“htmlLabels:false”  也没用，代码已是最新代码

**Comment by fengzhihaostar** [comment]
这个问题解决了吗？  我现在也出现了这个情况。  用IE打开这个http://knsv.github.io/mermaid/demos.html#demos地址，流程里面的文字没有显示出来。
